### ISSUE TITLE
Request: expose the state.d3ForceLayout 

### ISSUE THREAD

**Issue by morandd** [vasturiano/3d-force-graph#1]
First, thanks for this great contribution. 

If you have a moment, could you expose the state.d3ForceLayout object in the Graph(), so users can adjust the forces without having to edit and recompile this module?

**Comment by vasturiano** [comment]
@morandd sorry for the delay in answering. I think this can definitely be valuable as an escape hatch to externally modify the behavior of the forces, thanks for requesting it. I exposed the d3 forceSimulation object via `Graph().d3ForceLayout`. Available on `v1.8.0`. 
It's an experimental feature for now, but it serves well as an escape hatch for modifying the forces directly.
