### ISSUE TITLE
WarmupTicks promise/callback/event

### ISSUE THREAD

**Issue by rkalidhindi-tanium** [vasturiano/3d-force-graph#100]
Hi @vasturiano,
Would it be possible to get a promise, callback, or something to let us know when `warmupTicks` and `cooldownTicks` are done?

I am able to get a sample graph with 10,000 points to look nice and not freeze up if I let it run for 250 ticks with 
`Graph.d3VelocityDecay(0.1)
    .d3Force('charge').strength(-100);

  Graph.d3AlphaDecay(0.0)`

But at the moment I have no good way to know when those ticks are done so I can change `d3AlphaDecay` back to the default, turn off a loading screen, etc. 
I'd rather not use cooldownTime and a setTimeout because a certain amount of time may be enough for some computers and not others.

I can't think of any way to solve this issue without the ability to call a function when the ticks have finished. It would be super helpful in my use case (and probably with most giant graphs). 

Thank you!

**Comment by vasturiano** [comment]
@rkalidhindi-tanium as mentioned in #53 there are two additional methods now: `.onEngineTick()` and `onEngineStop()`. They are called at every tick and when the layout freezes, respectively.

Let me know if that works for your case.

**Comment by rkalidhindi-tanium** [comment]
Perfect, thank you!
