### ISSUE TITLE
Forced to npm install in 3d-force-graph

### ISSUE THREAD

**Issue by rkalidhindi-tanium** [vasturiano/3d-force-graph#102]
Hi @vasturiano, 

Ever since I installed version 1.35.1 I have had to manually go to the 3d-force-graph folder in node-modules and run npm install there to get everything working. Before I updated I used to just run npm install in workbench and that was enough. I don't know if this started with 1.35.1, but that's the first version I downloaded that had that issue. Could it go back to installing it's dependencies when it itself gets installed?

Thank you!

**Comment by vasturiano** [comment]
@rkalidhindi-tanium there doesn't seem to be any particular changes on `v1.35.1` in terms of the module build. Have you tried cleaning up the node_modules dir and reinstalling everything from scratch?

**Comment by rkalidhindi-tanium** [comment]
@vasturiano It might have occurred before that as I'm sure I skipped several versions. I have reinstalled node_modules several times, but keep getting that packages are missing until I install in 3d-force-graph.

**Comment by vasturiano** [comment]
@rkalidhindi-tanium can you tell me which packages are reported as missing until you run install on the `3d-force-graph` folder? Is it any of these in the `devDependencies` section:
https://github.com/vasturiano/3d-force-graph/blob/master/package.json#L43

**Comment by rkalidhindi-tanium** [comment]
@vasturiano My bad, it seems I messed up something in my dev environment because grunt was looking for those until I did a full restart. Afterwards a normal npm install in workbench was enough. Thank you for helping me figure it out!
