### ISSUE TITLE
Some control over when to render?

### ISSUE THREAD

**Issue by msbit** [vasturiano/3d-force-graph#104]
I've got a project that is generally static (once the force engine has settled) and only really needs for the scene to be rendered on camera rotation or node selection. Currently rendering every animation frame results in fairly high CPU usage on some machines.

I was wondering if there is a way to selectively pause rendering until necessary, similar to https://github.com/mrdoob/three.js/blob/a1daef37e5a6b80d0173af54edd000202b95fca5/examples/misc_controls_trackball.html#L75.

Thanks!

**Comment by vasturiano** [comment]
@msbit there is no way to currently halt the rerendering of the scene at every animation frame. 

However, generally what consumes the CPU the most is the computation of the force engine.
Have you tried shortening the cool down times (using `.cooldownTime(<ms>)`)? I'm curious as to whether the issue is still noticeable after the simulation engine completely freezes.

**Comment by msbit** [comment]
@vasturiano thanks for the response!

I still get high CPU usage after the simulation has frozen, just waiting the default 15 seconds. It's enough to keep my older (2012) laptop running its fan, and for Safari to pop up its warning about the page possibly causing performance issues. The latter is my primary motivation, to be honest :)

I think the main issue is having a custom `THREE.Group` being returned for each node, which overrides `updateMatrixWorld` to constantly keep facing the camera:

```
import * as THREE from 'three';

function CameraFacingGroup (camera) {
  THREE.Group.call(this);

  this.camera = camera;
};

CameraFacingGroup.prototype = Object.assign(Object.create(THREE.Group.prototype), {
  constructor: CameraFacingGroup,

  updateMatrixWorld: function (force) {
    THREE.Group.prototype.updateMatrixWorld.call(this, force);

    if (!this.quaternion.equals(this.camera.quaternion)) {
      this.quaternion.copy(this.camera.quaternion);
    }   
  }
});

export default CameraFacingGroup;
```

This was motivated by wanting to have a text element with an accurate hit-box (so a `THREE.PlaneGeometry` with `THREE.MeshBasicMaterial` / `THREE.CanvasTexture`) instead of using a `THREE.Sprite` which always has a square hit-box for simplicity.

What I have done is added in both the `3d-force-graph` and `three-render-objects` libraries, with the following diff:

```
--- a/src/3d-force-graph/3d-force-graph.js
+++ b/src/3d-force-graph/3d-force-graph.js
@@ -73,7 +73,8 @@ const linkedRenderObjsProps = Object.assign(...[
   'height',
   'backgroundColor',
   'showNavInfo',
-  'enablePointerInteraction'
+  'enablePointerInteraction',
+  'shouldRender'
 ].map(p => ({ [p]: bindRenderObjs.linkProp(p)})));
 const linkedRenderObjsMethods = Object.assign(...[
   'cameraPosition'

```

```
--- a/src/three-render-objects/three-render-objects.js
+++ b/src/three-render-objects/three-render-objects.js
@@ -61,14 +61,18 @@ export default Kapsule({
     hoverOrderComparator: { default: () => -1, triggerUpdate: false }, // keep existing order by default
     tooltipContent: { triggerUpdate: false },
     onHover: { default: () => {}, triggerUpdate: false },
-    onClick: { default: () => {}, triggerUpdate: false }
+    onClick: { default: () => {}, triggerUpdate: false },
+    shouldRender: { default: true }
   },
 
   methods: {
     tick: function(state) {
       if (state.initialised) {
         state.tbControls.update();
-        state.renderer.render(state.scene, state.camera);
+        if (state.shouldRender) {
+          state.renderer.render(state.scene, state.camera);
+          state.shouldRender = false;
+        }
 
         if (state.enablePointerInteraction) {
           // Update tooltip and trigger onHover events
```

so I can call `graph.shouldRender(true)` whenever my state is dirty and in `graph.onEngineTick`.

All of this isn't likely to be acceptable for a PR as it changes the behaviour significantly :)

**Comment by artyomtrityak** [comment]
@msbit did you consider using `stopAnimation()` for freezing rendering state.
@vasturiano What would you say about PR with `startAnimation()` to un-freeze scene?

**Comment by msbit** [comment]
@artyomtrityak I did consider it, but as you’d noted I’d need something like `startAnimation` to restart it. Additionally, I’d need the drag controls to continue to respond to know when to do so; from what I saw both render and interaction were frozen when calling `stopAnimation`.
