### ISSUE TITLE
linkCurvature does not work

### ISSUE THREAD

**Issue by nisace** [vasturiano/3d-force-graph#107]
Hi,

I'm trying to use linkCurvature option but I get the following error
`three-forcegraph.module.js?1efb:417 Uncaught TypeError: line.geometry.setFromPoints is not a function` which seems to come from [this line](https://github.com/vasturiano/three-forcegraph/blob/95f45ee22aa3a2acb38b98164fd78bbd188cb523/src/forcegraph-kapsule.js#L275).

I am using `v1.39.0`. I also tried to run the [Curved lines and self links](https://github.com/vasturiano/3d-force-graph/blob/master/example/curved-links/index.html) example but I got the same error.

Any help would be appreciated. Thanks !

**Comment by nisace** [comment]
Thanks for your reply. Unfortunately, I am having the same issue on my personal example and on the curved links example you mentioned. In both cases I get `three-forcegraph.module.js?1efb:417 Uncaught TypeError: line.geometry.setFromPoints is not a function`

**Comment by artyomtrityak** [comment]
@nisace do you have local THREE.js?

**Comment by nisace** [comment]
Yes. My dependencies are
```
"3d-force-graph": "^1.39.0",
"three": "^0.86.0",
```
My `package.json` history is
1. Install 3d-force-graph (which seemed to add both 3d-force-graph and three dependencies)
```
"3d-force-graph": "^1.22.0",
"three": "^0.86.0",
```
2. Update 3d-force-graph
```
"3d-force-graph": "^1.39.0",
"three": "^0.86.0",
```

Should I remove `three` from my `package.json`? or update it? I think I don't need this local dependency, but only for 3d-force-graph. I can't try it right now but I will try later.

**Comment by nisace** [comment]
I uninstalled `three` and `3d-force-graph`, then reinstalled `3d-force-graph` only and it's working now.

I just had the following warning message `npm WARN three-trackballcontrols@0.0.7 requires a peer of three@^0.86.0 but none is installed. You must install peer dependencies yourself.` but my issue is solved.

Thanks for your help !
