### ISSUE TITLE
Images and things

### ISSUE THREAD

**Issue by gitgitwhat** [vasturiano/3d-force-graph#11]
Great library!  I have a few questions/requests.  Is it possible to have a shape other than a sphere?  Can an image be applied as a texture to the node?  And can labels always be shown instead of just with mouseover?

**Comment by julienreszka** [comment]
It would be really nice indeed if we could see the labels without having to mousover.
Like here :
http://cnrtl.kodexlab.com/graph/noun/q/proximit%C3%A9

**Comment by vasturiano** [comment]
Thanks for the questions @gitgitwhat. 

Custom node shapes can be achieved using the `nodeThreeObject` property. Here's an example: https://vasturiano.github.io/3d-force-graph/example/custom-node-geometry/
This method also allows you to specify any custom material you wish, so you could use an image as wrapping texture.

For the labels, there is no current way out of the box to set all the labels on, they're merely a tooltip. But also with `nodeThreeObject` you can supply a combo object that includes both the node geometry and a text geometry representing the label. I intend to make an example of this option when I have a little time.

Let me know if this helps you use case!
