### ISSUE TITLE
ForceGraph3D is not defined

### ISSUE THREAD

**Issue by eechava6** [vasturiano/3d-force-graph#110]
Trying to integrate Electron/3D force graph 
in the electron app got this 
![image](https://user-images.githubusercontent.com/28983892/44808108-f93d8900-ab90-11e8-88ac-606b828d8362.png)

The code is the basic for a graph. 
![image](https://user-images.githubusercontent.com/28983892/44808122-0490b480-ab91-11e8-940d-edf3469b7d09.png)

With only three.js works fine 
![image](https://user-images.githubusercontent.com/28983892/44808145-15412a80-ab91-11e8-961f-590c3dcad531.png)

**Comment by vasturiano** [comment]
@eechava6 are you perhaps running it in a browser that doesn't support `Object.entries`?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries#Browser_compatibility

**Comment by eechava6** [comment]
![image](https://user-images.githubusercontent.com/28983892/44821477-77af2080-abbb-11e8-9366-494a8903841e.png)

Installed Object.entries with npm and still not working, 
im running in electron, 
"Electron is a framework for creating native applications with web technologies like JavaScript, HTML, and CSS. It takes care of the hard parts so you can focus on the core of your application." 

if it would help, this is the code of the only thing extra to Graph code: 
`
const {app, BrowserWindow} = require('electron');

let mainWindow;

// Quit when all windows are closed.
app.on('window-all-closed', function() {
  if (process.platform != 'darwin')
    app.quit();
});

// This method will be called when Electron has done everything
// initialization and ready for creating browser windows.
app.on('ready', function() {
  // Create the browser window.
  mainWindow = new BrowserWindow({
          width: 800, 
          height: 600, 
          frame:false, 
          transparent: false
  });

  //mainWindow.setIgnoreMouseEvents(true)

  // and load the index.html of the app.
  mainWindow.webContents.openDevTools();
  mainWindow.loadURL('file://' + __dirname + '/index.html');

  // Emitted when the window is closed.
  mainWindow.on('closed', function() {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null;
  });
});
`
