### ISSUE TITLE
Camera position to the original point

### ISSUE THREAD

**Issue by lucacinelli** [vasturiano/3d-force-graph#112]
Hi, 
i read some old issues about camera position, but i do not understand how to restore the original position of the camera without reload the page.
Then I have saved the {x, y, z} initial coordinates when i load the graph for first time. Consequently, i use these coordinates to call the function Graph.cameraPosition
Following the piece of code i have used:
`Graph.cameraPosition(
            { x: -281.8401338554948, y: -105.03035298715879, z: 353.9680681829602 }, 
            {x: 0, y: 0, z: -1},
            3000 
);`

Therefore, i'll think that there is a way to restore the original camera position, or to pass the object Graph to the "lookAt" parameter (i saw that you pass the object node instead of {x: 0, y: 0, z: -1} in the example "click-to-focus").
Thanks in advance

**Comment by vasturiano** [comment]
Hi @lucacinelli, the initial camera position, as mentioned in the docs is:

> By default the camera will face the center of the graph at a z distance proportional to the amount of nodes in the system.

All that you have to do is call `cameraPosition` with:
```
myGraph.cameraPosition({ x: 0, y: 0, z: 1000 })
```

You can adjust the `z` to taste to fit your particular case.

**Comment by lucacinelli** [comment]
Thanks, your suggestion works :)
Now, if i want to use the third argument that defines the duration in ms of the transaction, how can i modify the parameters in cameraPosition?
I tried: `myGraph.cameraPosition({ x: 0, y: 0, z: 1000 }, {}, 3000)`, but the camera rotates in a strange way and that's not the initial camera position.

**Comment by vasturiano** [comment]
Just make it point to `[0, 0, 0]` (the default). So:
```
myGraph.cameraPosition({ x: 0, y: 0, z: 1000 }, { x: 0, y: 0, z: 0 }, 3000)
```

**Comment by lucacinelli** [comment]
Oh well, it works.
Anyway, in the meantime i tried: `myGraph.cameraPosition({ x: 0, y: 0, z: 1000 },  null, 3000)` and i've obtained the same result :)
By the way, i'll use your last suggestion.
Thanks @vasturiano

**Comment by jsslngz** [comment]
Hey guys, I'm having an issue related to this. 
I'm trying to orbit my graph starting from the current position of the camera, what i'm doing now is:

![image](https://user-images.githubusercontent.com/36300056/58900725-15e58f00-86d6-11e9-8c45-91877cb17333.png)

but it doesn't work as expected.

**Comment by vasturiano** [comment]
Hi @jsslngz perhaps this example can provide some aid: https://vasturiano.github.io/3d-force-graph/example/camera-auto-orbit/
