### ISSUE TITLE
Set minimum distance between nodes?

### ISSUE THREAD

**Issue by freitaga** [vasturiano/3d-force-graph#113]
I'm making an explorable graph where each node is likely to share connections with any other node in the graph. After importing my data, the nodes are too densely compacted to be able to see the links between the nodes. 

Here is a screenshot of my app:

![](https://i.gyazo.com/b1ca71da6342c74aa5279a5af3209ce2.png)

Is this inherently how force graphs work or is there a way to get some minimum separation between all nodes?

**Comment by vasturiano** [comment]
@freitaga you can add a collision restriction force (even with a larger radius than the nodes so to include some margin), to prevent them from occupying the same space. Here's an [example](https://github.com/vasturiano/3d-force-graph/blob/master/example/collision-detection/index.html) that insludes a collision force.
