### ISSUE TITLE
Hide some lines from the scene

### ISSUE THREAD

**Issue by freitaga** [vasturiano/3d-force-graph#114]
I'm making an interactive scene out of the graph. On node click, I focus on the node and display only its connections to surrounding nodes along with some color changes. If I replace the links completely, the graph structure/physics take over and warp the graph. I figure I have to hide the other connections to maintain the graph structure. The options on the readme are set across the graph, so I need to chose which specific links to hide, whether it be calling object.visible = false on the 3js object, or setting its opacity to 0. Since the 3js scene is created from the graph function, I assume I have to target lines directly in 3js somehow unless there is an easier way.

**Comment by vasturiano** [comment]
@freitaga you can just use the method `linkVisibility`. This will only affect the visuals and not the internal physics engine. You can use it, for example onClick events like:
```
myGraph.onNodeClick(node => {
  myGraph.linkVisibility(link => shouldShowLink(link, node))
})
```

You should implement the logic in the `shouldShowLink`. A possible implementation to show only directly connected links would be:
```
function shouldShowLink(link, baseNode) {
  return link.source === baseNode || link.target === baseNode;
}
```

Let me know if you can get it working.

**Comment by freitaga** [comment]
This solution worked perfectly! Only had to add in coloring for link type. Thanks again 👍 

![](https://i.gyazo.com/9d607f3008d9a3c133363af70072269a.png)

**Comment by vasturiano** [comment]
Glad to hear. Your nodes look really stunning! Are those images?

**Comment by freitaga** [comment]
They're planets made from a sphere + planet texture. Its live over at  http://galactic.vision/planetary_quorum.html# if you want to check it out!
