### ISSUE TITLE
Is there something like this.graphData() for use within parameters?

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [vasturiano/3d-force-graph#115]
One related question, is there a way to access Graph.graphData() from within a parameter? I was trying to change link coloring based on source node type of doc loaded by jsonUrl():

    const Graph = ForceGraph3D()
      (document.getElementById('3d-graph'))
        .jsonUrl('../datasets/miserables.json')
        .linkAutoColorBy(d => {
          let { nodes, links } = this.graphData();
          console.log(nodes)
          return nodes[d.source].group
        })

But no luck...

**Comment by artyomtrityak** [comment]
did you try `Graph.graphData()`?

**Comment by Public-Health-Bioinformatics** [comment]
Yes, but it didn't work, perhaps because Graph isn't defined until the parameters functionally defined.

    let { nodes, links } = Graph.graphData();

nodes is undefined.

**Comment by Public-Health-Bioinformatics** [comment]
Consider this closed; I loaded data separately.
