### ISSUE TITLE
I would like to be able to dynamically add new nodes and links to my graph.

### ISSUE THREAD

**Issue by scottbyrns** [vasturiano/3d-force-graph#116]
Requests:

* A node can be added after the initial drawing of the graph
* A node can be linked to another node after the initial drawing of the graph

**Comment by vasturiano** [comment]
@scottbyrns this is already possible. Please see the example: [Dynamic data changes](https://vasturiano.github.io/3d-force-graph/example/dynamic/)

**Comment by stdob** [comment]
> @scottbyrns this is already possible. Please see the example: [Dynamic data changes](https://vasturiano.github.io/3d-force-graph/example/dynamic/)

@vasturiano Unfortunately, with a certain number of nodes and links, the addition of new data occurs with lags and slowly..

[ https://jsfiddle.net/ecLyodzu/ ]

**Comment by mys** [comment]
@stdob this is because every new addition creates new array from all previous data (nodes) and creates meshes again. I don't even talk about garbage collector operations here.. This could take much of CPU time.
