### ISSUE TITLE
Pan and Rotate not working in Angular Directive

### ISSUE THREAD

**Issue by MonkeyChap** [vasturiano/3d-force-graph#118]
Hi

The 3D layout is working really well (especially with nGraph as the engine). I've built it into my app as an Angular.js directive, and I've found the pan and rotate controls don't work as they do in the demos. Is there anything I need to do to enable them, or is Angular causing my problem here ?

Code is:

```
app.directive("threeForceGraph", function () {
    return {
        restrict: "E",
        scope: {
            gData: "=",
            gObj:"=",
            graphics:"=",
            renderer:"=",
            window:"="
        },

        link: function (scope, element, attrs) {

            scope.$watch('gData', function (newValue, oldValue) {
                if (scope.gObj == null)
                {
                    console.log("starting graph render !")
                    elem = element[0]
                    threedg = ForceGraph3D()
    
                    scope.gObj = threedg(elem);
    
                    scope.gObj.forceEngine('ngraph');
                }


                scope.gObj(element[0])
                .graphData(scope.gData);


                
            });





        }
    };
})
```

**Comment by mys** [comment]
If I remember correctly, the controls doesn't work with nGraph engine. Vasturiano should confirm that though.

**Comment by MonkeyChap** [comment]
Ah!  Thanks - I'll try the other layout engine. nGraph is the fastest though, right ?

**Comment by MonkeyChap** [comment]
Just tested it. They don't work with either layout engine. Mouse roller zoom works with nGraph, but none of the other controls do anything.

**Comment by vasturiano** [comment]
@MonkeyChap the controls should work regardless of the `forceEngine` used.
I'm thinking that possibly the issue is that you re-binding the graph to the element more than once.
Here: `scope.gObj = threedg(elem);` and here: `scope.gObj(element[0]).graphData(scope.gData);`.

The element binding should only be done once. I would try and replace the second line simply with `scope.gObj.graphData(scope.gData);` and see if that fixes it.

**Comment by frankfont** [comment]
We are running into something similar --- Pan and Rotate are not working (embedded in Angular 11 app).

How would you recommend we go about debugging this to find the root cause?
