### ISSUE TITLE
Get individual nodes, and set their colours

### ISSUE THREAD

**Issue by MonkeyChap** [vasturiano/3d-force-graph#119]
Maybe more of a question than an issue, but I can't see a way to get an individual node and set its colour. I'd tried:

myNode = graph.nodeId("n2") // the id given in the JSON for the node is "n2"
myNode.nodeColor("#f00")

It fails on the first line with an error "Invalid node identifier". I also tried it with a number 0 (and then also with a 1) in case it was an array index, but that also failed.

**Comment by vasturiano** [comment]
@MonkeyChap the method `nodeId` has a different purpose, to set the accessor function of nodes so the parser knows how they should be referenced from links.

To set a color per link you can simply use a callback function in the `nodeColor` prop, like so:
```
graph.nodeColor(node => shouldColorNodeSpecially(node) ? 'red' : 'blue')
```

Naturally, the logic in `shouldColorNodeSpecially` is up to you.
