### ISSUE TITLE
Implementing a clustering layout

### ISSUE THREAD

**Issue by jcho124** [vasturiano/3d-force-graph#124]
I'm working with the large data visualization graph and I was wondering if there is a clustering layout algorithm, such as [force-in-a-box](https://github.com/john-guerra/forceInABox), that would work in a 3D environment?

**Comment by vasturiano** [comment]
I believe `force-in-a-box` is strictly 2D. Also because it relies on hierarchical layout algorithms, like treemap and circle packing, for which there is currently no 3D versions, afaik.
However, there is this clustering force type: [d3-force-cluster](https://github.com/ericsoco/d3-force-cluster).
It is still 2D, but possibly much easier to port to 3D than force-in-a-box.

I also just wanted to mention that those layouts will actually work in a 3D environment out of the box. It's just that the internal algorithm won't take into account the 3rd dimension and probably the result will end up being a flat 3D graph.

**Comment by jcho124** [comment]
Thank you for the input, I'll definitely look into it. I do have another question regarding the large graph. Currently I'm working with around 63,000 nodes and around 179,728 links which slows down the process a bit and creates a hairball-like clustering of the nodes. Do you have any suggestions that would reduce the calculation process or reduce the hair-balling effect of a very large dataset? 

<img width="1680" alt="screen shot 2018-10-02 at 11 07 07 am" src="https://user-images.githubusercontent.com/26311227/46361615-b8bfa800-c633-11e8-8e6c-438099e6f253.png">

**Comment by vasturiano** [comment]
@jcho124 with that volume of elements is hard, but you can try two things:
1) Remove the build-in animation of the graph and make it jump directly to the final state by running iterations in the background. This will speed up things a little. You can do that by adding warmup ticks and removing cooldown ticks:
```
myGraph
  .warmupTicks(200)
  .cooldownTicks(0)
```
Here's an example, with about 7k nodes and 70k links
https://bl.ocks.org/vasturiano/34e0ac2ad391e33ad5dde43ec7ce3d40

2) Play around with the force engine settings to see what delivers a better and more intuitive visual separation of the nodes, also try calibrating the forces themselves (f.e. change link strengths, distances, node repulsion intensity). You can also introduce additional force types in the system to control the behavior, like a collision force, or a cluster one like you mentioned.

Hope that helps.

**Comment by jcho124** [comment]
Sorry to keep badgering, this is my first time using a force graph. But when I try to set the link strength using `.d3Force("link", d3.forceLink().strength(0.1))`
 I get a stretched graph like this: 
<img width="1680" alt="screen shot 2018-10-02 at 3 01 51 pm" src="https://user-images.githubusercontent.com/26311227/46373730-6e025800-c654-11e8-8b26-3cf23519501f.png">
Any idea what's causing it?

**Comment by jcho124** [comment]
It worked! thank you for your help :)
<img width="1680" alt="screen shot 2018-10-03 at 9 05 27 am" src="https://user-images.githubusercontent.com/26311227/46415731-81accd80-c6eb-11e8-8780-198a5452f0e9.png">

**Comment by WonderLabWoman** [comment]
Hi!  First of all thank you for your amazing work!!  I am using the A-frame version and am in need of some clustering too.  I have been looking at this: https://ialab.it.monash.edu/webcola/  It seems to be able to add all kinds of nice options, be it... in 2D.  Have you ever seen/considered it?  Do you think it could be a candidate for integration? Thank you!

**Comment by vasturiano** [comment]
@WonderLabWoman those are good ideas! Furthermore, they can also already be done with the current `3d-force-graph`, it's just a matter of adding the forces / engine configuration that enforces a certain set of restraints.

As example, here's one that establishes hierarchical layout constraints, using fixed dimension planes (with `fy`, that locks the `y` coordinates of nodes):
https://bl.ocks.org/vasturiano/cb1a9862f2235082c9c3a21ac8457196
