### ISSUE TITLE
How to go back after focusing nodes?

### ISSUE THREAD

**Issue by ghost** [vasturiano/3d-force-graph#128]
In the focusing nodes example, I can only focus on the node but not go back to default. I try to store the location of graph and give it back, but when I rotate the graph, it can not rotate properly. Could you give me some guide to have some methods to make the graph back?

**Comment by vasturiano** [comment]
@qianlongwuyong2018 at any point you can store the current camera position by doing
```
const savedPos = myGraph.cameraPosition();
```

whenever you wish to return to that position, you can just do:
```
myGraph.cameraPosition(savedPos, savedPos.lookAt);
```

if you wish to animate the transition, you can specify a third argument with the transition duration, in ms:
```
myGraph.cameraPosition(savedPos, savedPos.lookAt, 2000);
```

**Comment by vasturiano** [comment]
@qianlongwuyong2018 the new center of the graph (where it drag-rotates around) is defined by the `lookAt` (2nd argument of `cameraPosition`). If you wish to restore it to the initial state, you should use `{x: 0, y: 0, z: 0}` as `lookAt` argument.
