### ISSUE TITLE
Dimension reduction

### ISSUE THREAD

**Issue by mhebrard** [vasturiano/3d-force-graph#13]
I notice in one of your [example](https://bl.ocks.org/vasturiano/f59675656258d3f490e9faa40828c0e7) the use of **numDimensions**([_int_]).
In the example you delete then recreate the wole graph.

In my test, I would like to use the same data object. Updating the xyz of the nodes without deleting / recreating everything.

currently, when numDimensions is changed, the coordinates of the existing dimensions are updated as needed, but if numDimensions decrease, the coordinate persist...

It would be nice to add a step of clearing inside numDimensions method...
Here my code doing the job from outside (maybe not the best algo)
```
function toggleDimensions(num) {
  // Save dimensions
  numDim = num;
  // Reset coords
  if (numDim < 2) {
    graph.graphData().nodes.forEach(n => {
      n.y = 0;
      n.vy = 0;
      n.z = 0;
      n.vz = 0;
    });
  } else if (numDim < 3) {
    graph.graphData().nodes.forEach(n => {
      n.z = 0;
      n.vz = 0;
    });
  }
  reloadGraph();
}
```

**Comment by vasturiano** [comment]
Thanks @mhebrard, that's a good idea. Fixed in `v1.12.1`.
