### ISSUE TITLE
Link opacity function instead of constant

### ISSUE THREAD

**Issue by SimonDeDeyne** [vasturiano/3d-force-graph#134]
Hi,

Is there currently a way to pass a function to linkOpacity (just like linkColour) or does it need to be fixed to a constant number for all links?

Thanks,
Simon

**Comment by vasturiano** [comment]
@SimonDeDeyne `linkOpacity` is meant as a global so you can't pass an accessor function to it. However, if you want to customize the opacity per link, you can do it with the alpha channel of `linkColor`, like so: ```.linkcolor(link => `rgba(255,255,255,${link.opacity})`)```.

**Comment by vasturiano** [comment]
@somu2324 your code seems correct, but it will give you a barely noticeable variation, from opacity `0.8` to `1` (`rgb` statements). Are you certain it is not working?

**Comment by somu2324** [comment]
@vasturiano  I think your are correct, it will give me a barely noticeable variation.
Could you suggest, actually on the mouse hover i want to make some nodes more noticeable.  I though if I can achieve this by providing the high opacity value but i think is not much noticeable.

**Comment by vasturiano** [comment]
@somu2324 you could increase their size with `.nodeVal()`, or change their color like in https://vasturiano.github.io/3d-force-graph/example/highlight/
