### ISSUE TITLE
Two links in opposite directions between two nodes?

### ISSUE THREAD

**Issue by NicksonYap** [vasturiano/3d-force-graph#136]
Hi,

Awesome library here!

Given two nodes: `A` & `B`

`A` links to `B` (called `ab`)
`B` links to `A` (called `ba`)

![image](https://user-images.githubusercontent.com/5380731/47437357-fea70080-d7da-11e8-90ee-465808597c79.png)

Can the library properly render/present in such a way where u can see two or more links between two nodes?

Thanks

**Comment by NicksonYap** [comment]
Interesting example from Cytoscape:
http://js.cytoscape.org/demos/edge-types/

![image](https://user-images.githubusercontent.com/5380731/47437518-56de0280-d7db-11e8-8a30-06752cac2b2f.png)

**Comment by vasturiano** [comment]
Yes. You can just control the `linkCurvature` (and associated `linkCurveRotation`):
https://vasturiano.github.io/3d-force-graph/example/curved-links/

**Comment by NicksonYap** [comment]
@vasturiano  I've tried linkCurvature 

it seems to be rather limited, width and colours could not be set

Can the default width be adjusted to be thicker?

**Comment by vasturiano** [comment]
@NicksonYap Link colours on curved links should work. `width` however does not, it's only applicable in line object types, as mentioned in the docs. There's more details in this related issue: https://github.com/vasturiano/3d-force-graph/issues/108#issuecomment-417976336
