### ISSUE TITLE
porting features to aframe-forcegraph-component

### ISSUE THREAD

**Issue by jaronimoe** [vasturiano/3d-force-graph#138]
hi,
I intend to port certain features that the 3d-force-graph supports, over to the aframe/vr version,
for instance, the click-to-focus transition.

however, I am a bit confused by the packing of the code when trying to decipher it :)
for instance, I could not find the Graph.cameraPosition() function in the repository.
then I found out that I should actually look up your three-forcegraph that is packaged into the 3d-force-graph via your Kapsule component library. however, when I downloaded the three-forcegraph repo, again I could not find the "actual" graph source code, since it is again packaged together from some other components via Kapsule.

is there a best practice way of how I can access these packaged features (for instance the Graph.cameraPosition())?
the minified 3d-force-graph.js library contains the method but is of course not very readable.

I would greatly appreciate any pointers that would help me to find my bearings within the code!
kind regards

**Comment by vasturiano** [comment]
Hi @jaronimoe, thanks for reaching out! Sounds great to port some of the functionality to the a-frame component. :) 
`cameraPosition()` is actually a functionality of `three-render-objects`, a dependency of `3d-force-graph`, here:
https://github.com/vasturiano/three-render-objects/blob/master/src/three-render-objects.js#L116

Let me know if you run into any snags!
