### ISSUE TITLE
how to draw image png, jpg on a node?

### ISSUE THREAD

**Issue by audiorecorder** [vasturiano/3d-force-graph#139]
Is it possible draw a thumbnail image png, jpg on a node?
I would appreciate some sample.

**Comment by vasturiano** [comment]
@audiorecorder please see this newly added example: https://vasturiano.github.io/3d-force-graph/example/img-nodes/
Source: https://github.com/vasturiano/3d-force-graph/blob/master/example/img-nodes/index.html
