### ISSUE TITLE
onNodeOver ?

### ISSUE THREAD

**Issue by mhebrard** [vasturiano/3d-force-graph#14]
There is a convenient method **onNodeClick**(__fn__)

Do we have access to the node over method as well ?
By default, mouseover a node display it's name as text.
But is it possible to intersect this event and add a callback function ?

**Comment by vasturiano** [comment]
Added `onNodeHover` on v1.12.0. Thanks for the feature request!

**Comment by AmbroiseCouissin** [comment]
Hi @vasturiano! 

It would be great to have a onNodeOut(node) as well so that we can apply logic on the specific mouseout node.

It could be used to reset a color previously set on a node with onNodeHover.

Cheers!

**Comment by vasturiano** [comment]
@AmbroiseCouissin `onNodeHover(node)` gets called every time the mouse enters or leaves a node. The `node` parameter represents the new node that the mouse is over, or if it's directly over the background (no nodes to hover) it returns `null`. So you can use those values to keep state which node is currently hovered and reset your properties accordingly.

**Comment by AmbroiseCouissin** [comment]
@vasturiano yes, that's what I did. But I had to do something that looks like this: 
'''
let cosmosGraph = ForceGraph3D()
        (document.getElementById("3d-graph"))
        .onNodeClick(removeNode)
        .onNodeHover(mouseovered)
        .autoColorBy(n => n.type)
        .graphData(initData);

        var hoveredNodes: any[] = [];
        function mouseovered(node) {
          if (node != null) {
            node.__sphere.material = new THREE.MeshLambertMaterial({
              color: 0xd62728,
              transparent: true,
              opacity: 0.75,
              emissive: 0xffffff
            });
            hoveredNodes.push(node);
          } else {
            hoveredNodes.forEach(n => n.__sphere.material = new THREE.MeshLambertMaterial({
              color: n.color,
              transparent: true,
              opacity: 0.75,
              emissive: 0x000000
            }));
            hoveredNodes = [];
          }    
        }
'''

This could be handled by the library for a more user friendly touch maybe.

**Comment by mhebrard** [comment]
In my previous test with mouseover and mouseout events I often have problem of calling sequence. When mouse move, the events are called many times and actions orders are not consistent.

The best way I found is to save the hovered node in a state, and rely on mouseover for behavior (ignore mouseout)

Only one node is hovered at a time, you do not need an array:

```
var hovered = null;
function onHoverHandler(n) {
  if (n !== null) { // one node is hovered
    if (n.id !== hovered) { // different node
      // reset previous hover
      ...
      // highlight current hover
      ...
      // save hover in state
      hovered = n.id;
    } // else node is already hovered, no action
  } else if (hovered !== null) { // mouseout, no node hovered
    // reset previous hover
    ...
    // save hover in state
    hovered = null;
  }
}
```

**Comment by vasturiano** [comment]
@AmbroiseCouissin @mhebrard I've extended the `onNodeHover`/`onLinkHover` methods so that it includes the previous hovered object (if there was one) as 2nd parameter in the callback function. I.e.:
```
Graph.onNodeHover(node, previousNode => { /* do something with nodes  */ })
```

Using the second parameter will free you from having to locally store the previous node in order to undo any highlighting modifications. If there was no previous object (mouse enter directly from background), the 2nd param is `null`.

Hopefully this helps your case.

**Comment by mhebrard** [comment]
Thanks ! much easier

```
function onHoverHandler(n, prev) {
  if (n !== null) {
    // Highlight n
  }
  if (prev !== null) {
     // Reset prev
  }
}
```

**Comment by julienreszka** [comment]
Hi, I have tried this piece of code :
```
.onLinkHover((currentNode, prevNode) => {
            if (currentNode !== null) {
                console.log(currentNode);
                currentNode.__lineObj.material.color.r = 200
            }
            if (prevNode !== null) {
                prevNode.__lineObj.material.color.r = 0
            }
        })
```
But it colors all the links and uncolors all the links.
I expected it to color only the link I was hovering.
How can I fix this ?

**Comment by mhebrard** [comment]
That depend how you create your THREE objects. I notice a similar behavior once. If you create one object with material on top of your code, and use this object for all your node (like in a loop). Then all your node are instances of the same THREE object. So when you modify this object, all your nodes are modified... To avoid that, you need to create an object for each node. Or at least one different material for each color you need.

**Comment by ienaveen** [comment]
In the similar lines onmouseOver can we add a customer html snippet and attach it as a tool tip to the node??

**Comment by vasturiano** [comment]
@ienaveen you should be able to do that with the `.nodeLabel(node => <your html logic>)` method.

**Comment by vinodpotru** [comment]
Hi
Can anyone help on this.
how to find event element in onNodeHover? like onNodeClick have second parameter is event.
Is there aby possibility to get element on onNodeHover?

**Comment by schobernoise** [comment]
> Hi Can anyone help me on this. how to find event element in onNodeHover? like onNodeClick have second parameter is event. Is there aby possibility to get element on onNodeHover? Or Any Way to find event element using node object index Id?
> 
> I am Working on ForceGraph2D, version: "react-force-graph": "^1.37.1",
> 
> I want to display customize popup when I hover on Node so I need offsetX, offsetY, pageX and pageY values of Node element. I can achieve this on OnNodeClick(node, event) but unable to find node events details in OnNodeHover(node, prevNode).
> 
> Can anyone help me on this.

Having the same issue, there is no event I can use to facilitate my own tooltip. Maybe with something like useMouse a workaround could be found, but as for now, everything is super hacky with tooltips.
