### ISSUE TITLE
Output Final Coordinates of ALL the Nodes?

### ISSUE THREAD

**Issue by erdnase1902** [vasturiano/3d-force-graph#145]
First I want to thank you for making this awesome work!

I would like to know if it's possible to output the final coordinates of all the nodes after the simulation is completed? I can then perhaps save the final coordinates somewhere else or pass it into another function in some library?

Again, thanks for this excellent work!

**Comment by vasturiano** [comment]
@PananDeveloper  thanks for reaching out. To extract the coordinates, just look in your `data.nodes`. At any given moment after the simulation has started, each node should have the `x`, `y` and `z` attributes corresponding to their coordinates.

You can also detect when the simulation engine stops by adding a callback to `onEngineStop(<fn>)`.

**Comment by PananDeveloper** [comment]
Thanks for the reply.
Also, I would like to know if it's possible to just output the coordinates without rendering any graphics to the screen? It seems like it is not possible to run the simulation without calling `graphData()`, but calling `graphData()` will render graphics to the screen?

**Comment by vasturiano** [comment]
@PananDeveloper you could use a `domElement` that is not attached to the main document. That way the result won't be rendered on the page. Something like 
```
myChart = ForceGraph3d()(document.createElement('div'))
```
