### ISSUE TITLE
Export graph to .obj or .gltf

### ISSUE THREAD

**Issue by malakhovks** [vasturiano/3d-force-graph#146]
Hello,

is there a way to implement a graph **exporter to .obj or .gltf** from three.js lib?

Best regards!

**Comment by vasturiano** [comment]
@malakhovks honestly, I have no idea.

**Comment by vasturiano** [comment]
@malakhovks you can access the `ThreeJS scene` using `myGraph.scene()`. Would that suffice?

**Comment by malakhovks** [comment]
@vasturiano I implemented a graph exporter to .gltf using [GLTFExporter.js](https://github.com/mrdoob/three.js/blob/dev/examples/js/exporters/GLTFExporter.js) from [three.js](https://github.com/mrdoob/three.js) examples.
It would be great if you add  [GLTFExporter.js](https://github.com/mrdoob/three.js/blob/dev/examples/js/exporters/GLTFExporter.js) to your **unpkg.com** cdn.
And here is an example [graph2gltf.html](https://www.dropbox.com/s/txagvxekruovfid/graph2gltf.html?dl=0) you can add to your list of examples.

**Comment by vasturiano** [comment]
@malakhovks you can already get the exporter from `NPM`/`unpkg.com`, as part of the `three` package: https://unpkg.com/three/examples/js/exporters/GLTFExporter.js

**Comment by malakhovks** [comment]
@vasturiano Thanks! 👍

**Comment by rafaelbecks** [comment]
Hey @vasturiano  how are you? I'm facing the same problem as you trying to export the 3d model generated for the graph. Do you have the example you mentioned before anywhere? I see the dropbox link is broken. Thank you! I'll keep trying to export the object anyway (:

**Comment by rafaelbecks** [comment]
Hey @malakhovks how are you? I'm facing the same problem as you trying to export the 3d model generated for the graph. Do you have the example you mentioned before anywhere? I see the dropbox link is broken. Thank you! I'll keep trying to export the object anyway (:

**Comment by malakhovks** [comment]
@rafaelbecks , Hey!
You can try it: [graph-exporter-to-gltf.zip](https://github.com/vasturiano/3d-force-graph/files/3450136/graph-exporter-to-gltf.zip)
 
Just run server firstly `server-cors-python3.py`:

```bash
$ python3 server-cors-python3.py
```

And then you can serve page with random generated graph and click button to export it to `.gltf`:
[http://127.0.0.1:8000/graph2gltf.html](http://127.0.0.1:8000/graph2gltf.html)

**Comment by rafaelbecks** [comment]
@malakhovks Thanks for your response. In the end, I was able to export the graph with GLTFExporter using the code you mentioned above. Thanks for sending the code with the python server, I'll take a look to it.

**Comment by peestract** [comment]
Hi there @malakhovks , I am trying to get the exporter file you added to work - but when i click download it doesnt save anywhere... any advice?

**Comment by malakhovks** [comment]
> Hi there @malakhovks , I am trying to get the exporter file you added to work - but when i click download it doesnt save anywhere... any advice? I am running server first, then clicking button and getting this error - Uncaught TypeError: THREE.GLTFExporter is not a constructor

Hey @peestract , there is an issue with [Cross-Origin Read Blocking (CORB)](https://www.chromium.org/Home/chromium-security/corb-for-developers/) - a new browser security feature.
I tried to export with [graph-exporter-to-gltf.zip](https://github.com/vasturiano/3d-force-graph/files/3450136/graph-exporter-to-gltf.zip) and in developer console I firstly get:
> Cross-Origin Read Blocking (CORB) blocked cross-origin response https://unpkg.com/browse/three@0.147.0/examples/js/exporters/GLTFExporter.js with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

and then `Uncaught TypeError: THREE.GLTFExporter is not a constructor` cause it is not loaded.

I will try to solve this issue

**Comment by peestract** [comment]
Ah I see, thanks for having a look.

**Comment by peestract** [comment]
@malakhovks I got it to work by changing the script tag to a rawcdn - thanks for your work
