### ISSUE TITLE
Antialias option

### ISSUE THREAD

**Issue by moermansr** [vasturiano/3d-force-graph#147]
I was wondering if it possible to enable anti aliasing in the Three.js renderer. We can access the webGLrenderer through the renderer() method but the anti alias options needs to be set before the initalization. Any suggestions ?

**Comment by vasturiano** [comment]
@moermansr I've added support for it as described above. You can enable antialiasing by initializing the library like this:
```
var myGraph = ForceGraph3D({ rendererConfig: { antialias: true }});
```

**Comment by moermansr** [comment]
Awesome, Thanks.
