### ISSUE TITLE
how to use images instead of circle in 3d-force-graph using javascript

### ISSUE THREAD

**Issue by TamanaKarthick** [vasturiano/3d-force-graph#148]
Here I created nodes with circle now I want to add images . for example virtual machine nodes are all VM images then the virtual network has virtual network images. please help me guys, then tell me how to add images. like I mention.
<head>
  <style>
    body {
      margin: 0;
    }
  </style>

  <script src="//unpkg.com/3d-force-graph"></script>
  <script src="//unpkg.com/three"></script>
  
  <img src="legend2.png" alt="legend" align="top">
</head>

<body>
  <div id="3d-graph"></div>
  
  <script>
    const imgs = ['nicr1.png','rg.png','subnetr1.png','vm.png','vnet.png'];
    const elem = document.getElementById('3d-graph');
    let highlightLink = null;
    const Graph = ForceGraph3D()
      (elem)
      .jsonUrl('../datasets/miserables.json')
      .nodeLabel('id')
      .nodeAutoColorBy('group')
      .linkDirectionalParticles('value')
      .linkDirectionalParticleSpeed(d => d.value * 0.010)
      .linkWidth(link => link === highlightLink ? 5 : 1)
      .linkDirectionalParticleWidth(2)
      .onNodeHover(node => elem.style.cursor = node ? 'pointer' : null)
      .onNodeClick(node => {
        // Aim at node from outside it
        const distance = 40;
        const distRatio = 1 + distance / Math.hypot(node.x, node.y, node.z);

        Graph.cameraPosition(
          { x: node.x * distRatio, y: node.y * distRatio, z: node.z * distRatio }, // new position
          node, // lookAt ({ x, y, z })
          3000  // ms transition duration
        );
      });
  </script>
</body>

following are json I am using
{
	"nodes": [{
		"id": "rg-Red",
		"name":"VirtualMachine",
		"group": 1
	},{
		"id": "Vnet-Red2",
		"name":"VirtualNetwork",
		"group": 1
	},{
		"id": "Vnet-Red3",
		"name":"VirtualNetwork",
		"group": 1
	}
],
	"links": [{
		"source": "rg-Green",
		"target": "Vnet-Green",
		"value": 2
	},{
		"source": "Vnet-Green",
		"target": "SubNet-Green",
		"value": 2
	}
	,{
		"source": "SubNet-Green",
		"target": "NetworkInterface-Green",
		"value": 2
	}
	
]
}

**Comment by vasturiano** [comment]
@TamanaKarthick here's an example with using images as nodes: https://vasturiano.github.io/3d-force-graph/example/img-nodes/

**Comment by TamanaKarthick** [comment]
No sir, you give only images using variable declaration, and there is no value shown on images. so please give me an example for using images instead of circle nodes, using JSON. then also give threejs object clear example. there you are always using variable declaration. please give me value get from JSON.

**Comment by TamanaKarthick** [comment]
Then please also explain to me, how to add images, particular groups, for example, virtual machine nodes have only virtual machine images. please tell me, sir , this huge help for my career.

**Comment by TamanaKarthick** [comment]
then please at least tell me how to add threejs geometry into the node for the following code. you don't give an example of how to add geometry into nodes from reading JSON.  you give only using random variable declaration. I was really confused.

<script>
    // controls
    const controls = { 'DAG Orientation': 'td'};
    const gui = new dat.GUI();
    gui.add(controls, 'DAG Orientation', ['td', 'bu', 'lr', 'rl', 'zout', 'zin', 'radialout', 'radialin', null])
      .onChange(orientation => graph && graph.dagMode(orientation));

    // graph config
    const NODE_REL_SIZE = 1;
    const graph = ForceGraph3D()
      .dagMode('td')
      .dagLevelDistance(200)
      .backgroundColor('#101020')
      .linkColor(() => 'rgba(255,255,255,0.2)')
      .nodeRelSize(NODE_REL_SIZE)
      .nodeId('path')
      .nodeVal('size')
      .nodeLabel('path')
      .nodeAutoColorBy('module')
      .nodeOpacity(0.9)
      .linkDirectionalParticles(2)
      .linkDirectionalParticleWidth(0.8)
      .linkDirectionalParticleSpeed(0.006)
      .nodeThreeObject(({ nodes }) => new THREE.Mesh(
          [
            new THREE.BoxGeometry(Math.random() * 20, Math.random() * 20, Math.random() * 20),
            new THREE.ConeGeometry(Math.random() * 10, Math.random() * 20),
            new THREE.CylinderGeometry(Math.random() * 10, Math.random() * 10, Math.random() * 20),
            new THREE.DodecahedronGeometry(Math.random() * 10),
            new THREE.SphereGeometry(Math.random() * 10),
            new THREE.TorusGeometry(Math.random() * 10, Math.random() * 2),
            new THREE.TorusKnotGeometry(Math.random() * 10, Math.random() * 2)
          ][nodes%7],
          new THREE.MeshLambertMaterial({
            color: Math.round(Math.random() * Math.pow(2, 24)),
            transparent: true,
            opacity: 0.75
          })
        ))
      .d3Force('collision', d3.forceCollide(node => Math.cbrt(node.size) * NODE_REL_SIZE))
      .d3VelocityDecay(0.3);

    fetch('../datasets/d3-dependencies.csv')
      .then(r => r.text())
      .then(d3.csvParse)
      .then(data => {
        const nodes = [], links = [];
        data.forEach(({ size, path }) => {
          const levels = path.split('/'),
            level = levels.length - 1,
            module = level > 0 ? levels[1] : null,
            leaf = levels.pop(),
            parent = levels.join('/');

          const node = {
            path,
            leaf,
            module,
            size: +size || 20,
            level
          };

          nodes.push(node);

          if (parent) {
            links.push({source: parent, target: path, targetNode: node});
          }
        });

        graph(document.getElementById('graph'))
          .graphData({ nodes, links });
      });
  </script>

**Comment by TamanaKarthick** [comment]
Sir, tell me at least, how to threejs object into node reading data from JSON. or How to give color in node only I choose. you don't give any example like this. please , please , please
