### ISSUE TITLE
Custom link force

### ISSUE THREAD

**Issue by AmbroiseCouissin** [vasturiano/3d-force-graph#15]
Hi!

Would it be possible to add custom link force a bit like this?:
```
{
    "nodes": [ 
        (...)
    ],
    "links": [
        {
            "source": "id1",
            "target": "id2",
            "force": 5
        },
        (...)
    ]
}
```

**Comment by fedevela** [comment]
Mr. @vasturiano this would be such an amazing addition for us!!!! 

I and my superiors would be more than willing to spend the time and effort to implement this change, I would need to understand a little more to be able to do so.

I am available for this change!!!

Thank you very much in advance

**Comment by mhebrard** [comment]
d3.force engine implement this force with something like:
```
d3.forceSimulation()
.force('link', d3.forceLink().distance(d => d.weight));
```
 I didn't find this parameter in ngraph force engine...

P.S. It could be nice to have access to the parameters of other forces as well

**Comment by vasturiano** [comment]
I've added the ability to manipulate the d3 forces (v1.15.0 and up) using the props `d3Force`, `d3AlphaDecay` and `d3VelocityDecay`.

So @AmbroiseCouissin, for the schema you listed, you'd want to do something like:
```
Graph.d3Force('link').strength(d => d.force)
```

Goes without saying this only works when using the d3 engine. The ngraph engine parameters are not exposed for external config atm.

Here's an example of using custom force configuration: 
https://vasturiano.github.io/3d-force-graph/example/collision-detection/

Hopefully this helps your case. Let me know if it works out, and would love to see a demo if available. :)
