### ISSUE TITLE
Images are not loading properly

### ISSUE THREAD

**Issue by dnskmr** [vasturiano/3d-force-graph#150]
Hi Vasco Asturiano,

Thanks for good library,

In the example provided images as node, Ref: https://vasturiano.github.io/3d-force-graph/example/img-nodes/

Images are not lading properly and if I put my own images also pixel getting affected, In the provided example also cat image is not loaded properly. Kindly help me out how to load the image properly or do we have any function loading the images first then calling the graph data. 

I need to create plenty of dynamic examples with this library. Kindly reply me as soon as possible.

**Comment by vasturiano** [comment]
@dnskmr can you provide more details in which way is the above example not functioning properly? I'm currently able to load it fine.
