### ISSUE TITLE
How to Lock Particular node using 3d-force-graph?

### ISSUE THREAD

**Issue by TamanaKarthick** [vasturiano/3d-force-graph#151]
Hi, I want to set one node to nondraggable, so is there any option for this. please tell me about this.

**Comment by vasturiano** [comment]
@TamanaKarthick you could use either `.onNodeDrag` or `onNodeDragEnd` to reset the position of the node while dragging so that it remains fixed.

**Comment by TamanaKarthick** [comment]
> @TamanaKarthick you could use either `.onNodeDrag` or `onNodeDragEnd` to reset the position of the node while dragging so that it remains fixed.

thanks for your reply, can you provide an example for this.
