### ISSUE TITLE
Hi your Preview Sample not working, 3d-force-graph plugin problem.

### ISSUE THREAD

**Issue by TamanaKarthick** [vasturiano/3d-force-graph#152]
Hi your Preview Sample not working, 3d-force-graph plugin problem.

**Comment by DanielHHowell** [comment]
Seconding difficulty, seems to have been working until yesterday

**Comment by ArunRajdeveloper** [comment]
> Seconding difficulty seems to have been working until yesterday

download plugin in locally then run, maybe online plugin links are removed.

**Comment by markbaumgarten** [comment]
https://unpkg.com/3d-force-graph@1.43.4/index.js does not exist

https://unpkg.com/3d-force-graph@1.43.2 - seems to work though....

**Comment by vasturiano** [comment]
This is related to an issue going on in the cdn (unpkg): 
https://github.com/unpkg/unpkg.com/issues/156

If you need to fix it immediately, you can just reference the bundle file explicitly in your script tag:
```
https://unpkg.com/3d-force-graph/dist/3d-force-graph.min.js
```

**Comment by vasturiano** [comment]
`d3-force-3d` is at: https://unpkg.com/d3-force-3d@2.0.0/dist/d3-force-3d.min.js
