### ISSUE TITLE
How to Add the text details on Node click?

### ISSUE THREAD

**Issue by ArunRajdeveloper** [vasturiano/3d-force-graph#153]
Hi I want to Add the text details on Node click like following is possible to do in 3d-graph

I already try this, but this following steps are not working, if anything missing please mention.
type one:
.d3Force().on( 'click', function (d) {
            d3.select("h1").html(d.group); 
            d3.select("h2").html(d.discription); 
            // d3.select("h3").html ("Take me to " + "<a href='" + d.link + "' >"  + d.hero + " web page ⇢"+ "</a>" ); 
         })
type two:
            .onNodeClick(node => function (node) {
              d3.select("h1").html(node.group); 
              d3.select("h2").html(node.discription); 
              // d3.select("h3").html ("Take me to " + "<a href='" + d.link + "' >"  + d.hero + " web page ⇢"+ "</a>" ); 
           })
Expecting output
![capture](https://user-images.githubusercontent.com/45970001/50156671-61a5a700-02f5-11e9-9935-5164fb8351ba.JPG)

Reference Url//
http://bl.ocks.org/eesur/be2abfb3155a38be4de4

**Comment by vasturiano** [comment]
@ArunRajdeveloper this seems off:
```
.onNodeClick(node => function (node) {
  ...
})
```

Perhaps you mean:
```
.onNodeClick(node => {
  ...
})
```

**Comment by ArunRajdeveloper** [comment]
@vasturiano perhaps this not working, I doubt something I missing. if anything I miss here, please mention. 
.onNodeClick(node => {
              `<div class="centerTest">${node.id} </div>
            <br><span style="background-color: #FFE4C4" class="text-highlighted"><font color="black" size="2">
            ${node.group}
            ${node.discription}
            </font>
            </span>` 
           })

**Comment by ArunRajdeveloper** [comment]
@vasturiano Thank men it's working properly
.onNodeClick(node => {
              d3.select("h1").html(node.group); 
              d3.select("h2").html(node.discription); 
           })
