### ISSUE TITLE
Loading failed for 3D-force-graph script, 3d-force-graph is not defined

### ISSUE THREAD

**Issue by xuaero** [vasturiano/3d-force-graph#154]
Hi, thank you for this amazing plugin! However, it looks like the current 3D-force-graph script library is no longer working. Is there a way I can include an older/working version until there is a fix for this? Apologies for the neophyte question but I've been using it since June and need to wrap up this project asap. 
![screen shot 2018-12-18 at 11 35 25 am](https://user-images.githubusercontent.com/11555569/50172147-f7234580-02b9-11e9-92c5-055ab99a9392.png)

**Comment by vasturiano** [comment]
@xuaero this is related to an issue going on in the cdn (unpkg): 
https://github.com/unpkg/unpkg.com/issues/156

To fix it immediately, you just reference the bundle file explicitely in your script tag:
```
https://unpkg.com/3d-force-graph@1.43.4/dist/3d-force-graph.min.js
```
