### ISSUE TITLE
is possible to apply node filter using dat.gui

### ISSUE THREAD

**Issue by TamanaKarthick** [vasturiano/3d-force-graph#155]
Hi please tell me is possible to apply node filter using dat.gui.

**Comment by ArunRajdeveloper** [comment]
Hi, Karthik this is the solution for you, I think you can't filter in the node, but you can filter source data.

function filterConfiguration(chooseData, Graph) {
  const nodes = [], links = []
  console.log("choose data--------------->" + chooseData);
  qwest.get('../datasets/realData.json').then((_, newData) => {

    if (chooseData == 'Networks') {
      newData.nodes.forEach(node => {
        if (node.group == 'subnet' || node.group == 'networkInterface'
        || node.group == 'virtualNetwork' || node.group == 'publicIpAddress'
        || node.group == 'networkSecurityGroup' || node.group == 'Globe'
        || node.group == 'virtualMachine' || node.group == 'AvailabilitySet'
        || node.group == 'resourceGroup') {
          nodes.push(node)
        }
      })
      newData.links.forEach(link => {
        if (link.connectionID == 63 || link.connectionID == 32 ||
          link.connectionID == 21 || link.connectionID == 34
          || link.connectionID == 35 || link.connectionID == 02
          || link.connectionID == 01 || link.connectionID == 03
          || link.connectionID == 550 || link.connectionID == 09
          || link.connectionID == 06 | link.connectionID == 69) {
          links.push(link)
        }
      })

then frame .json like following

for node data
	 {
		"id": "samenetwork",
		"group":"virtualNetwork",
		"groupId":"group1234",
		"type":"1",
		"discription":"Type:virtualNetwork<BR>Location:EastUS"
	}
for link data
{
		"source": "dashboardavail2",
		"target": "winvm2",
		"_comment":"AVS to VM",
		"groupId":"dashboard",
		"connectionID": "69",
		"vulnerability":true,
		"vulnerabilityStatus":"High",
		"vulnerabilityBrief":"All ports are opened",
		"value": 64
	}
