### ISSUE TITLE
How to customise node link starting position?

### ISSUE THREAD

**Issue by ArunRajdeveloper** [vasturiano/3d-force-graph#156]
Hi, I want to create link node different position, what I am saying here, normally links are starting the same position in the node. but I want to customize that link starting position. first link starting 0th node position, and the second link starting 1st position from the node. is that possible to make a link like that?

**Comment by ArunRajdeveloper** [comment]
Hi, at least tell is possible or not.

**Comment by vasturiano** [comment]
@ArunRajdeveloper this is not possible currently. In the future I may add support for custom links, just like it currently exists for nodes.

**Comment by dodongjuan** [comment]
May I ask whats the purpose of linkThreeObject ?
