### ISSUE TITLE
Scene size

### ISSUE THREAD

**Issue by hdezandres** [vasturiano/3d-force-graph#157]
Hi, i'm trying to modify the scene size with 

Graph.renderer().setSize(new_height, new_width);

but does not modify it.

is posible to do and how?

Thanks!

**Comment by vasturiano** [comment]
@hdezandres if you want to set the size of the canvas you can simply do it directly on the Graph object:
```
Graph
  .width(new_width)
  .height(new_height)
```

**Comment by TamanaKarthick** [comment]
#155

**Comment by hdezandres** [comment]
@vasturiano, thanks for your help!
