### ISSUE TITLE
How to add Drag Option in threejs Geometry?

### ISSUE THREAD

**Issue by ArunRajdeveloper** [vasturiano/3d-force-graph#158]
I use theejs geometry into 3d-force-graph for node styling, hereby the problem is I cant drag that node. so please tell me, how to add drag option here.
![capture](https://user-images.githubusercontent.com/45970001/50395913-a2d20700-078c-11e9-83e4-3acafaefbd7f.JPG)

 .nodeThreeObject(({type}) => {
        
            var pictureMaterial = new THREE.MeshBasicMaterial({
                map: THREE.ImageUtils.loadTexture('../images/planets/land_ocean_ice_cloud_2048.jpg');
            });
            
            var colorMaterial = new THREE.MeshBasicMaterial({
                transparent: true,
                opacity: 0.75 ,
                color: colors[type]
            });
            
            var GlobeMaterial = [
            pictureMaterial, // Left side
            colorMaterial, // Right side
            colorMaterial, // Top side   ---> THIS IS THE FRONT
            colorMaterial, // Bottom side --> THIS IS THE BACK
            pictureMaterial, // Front side
            colorMaterial  // Back side
            ];
            var Globegeometry = new THREE.SphereGeometry(30,20,20);
            
            var GlobegeometryShape = new THREE.Mesh(Globegeometry, GlobeMaterial);
            
            var scene = new THREE.Scene();
           
            var sprite = new SpriteText('?');
            sprite.color = colors[1];
            sprite.textHeight = 50;
            sprite.position.set(0,50,0);

            scene.add(GlobegeometryShape);
            scene.add(sprite);

            return scene;
        }
)

Here without the scene, I can drag that node, but whenever I add a scene here, the drag option was disabled. so please tell me,  how to add drag option here.

**Comment by ArunRajdeveloper** [comment]
@vasturiano How to drag this, any suggestion you have..?if you have please tell me.

**Comment by vasturiano** [comment]
@ArunRajdeveloper please see this [example](https://github.com/vasturiano/3d-force-graph/blob/master/example/text-nodes/index.html#L21) on how to include a parent drag handle on a sprite or any set of custom node objects.

**Comment by ArunRajdeveloper** [comment]
thanks, I will try.
