### ISSUE TITLE
How to add collisions between nodes..?

### ISSUE THREAD

**Issue by ArunRajdeveloper** [vasturiano/3d-force-graph#159]
Hi, I want to add collisions between the node, an instance of one moving node striking violently against another. Because here overlapping one node to another node.

Then I am already trying this, this following are made the node resize, so please tell me without resizing, how to add collisions.
.d3Force('collide', d3.forceCollide(Graph.nodeRelSize()))

**Comment by ArunRajdeveloper** [comment]
why this not working, please tell me

**Comment by vasturiano** [comment]
@ArunRajdeveloper there's an example that features collision detection: https://vasturiano.github.io/3d-force-graph/example/collision-detection/

Does that help your case?

**Comment by ArunRajdeveloper** [comment]
I already try this. but there is a problem, I cant apply collision force to the cube. because of collision force only applicable for sphere and circles.

**Comment by vasturiano** [comment]
Collisions on non-round objects are tricky. You'd need a 3D version of this plugin [d3-bboxCollide](https://github.com/emeeks/d3-bboxCollide), which afaik does not exist.
