### ISSUE TITLE
Add support to MeshLine

### ISSUE THREAD

**Issue by AmbroiseCouissin** [vasturiano/3d-force-graph#16]
Hi @vasturiano,

It's not possible to increase line width according to: 
https://stackoverflow.com/questions/11638883/thickness-of-lines-using-three-linebasicmaterial

One possible replacement is https://github.com/spite/THREE.MeshLine.

Do you think it could be a good idea to support both and give the choice like for the choice between d3 and ngraph?

Cheers!

**Comment by Juleffel** [comment]
Implemented in https://github.com/vasturiano/three-forcegraph/pull/3

**Comment by vasturiano** [comment]
Closing this in favor of https://github.com/vasturiano/three-forcegraph/pull/3
