### ISSUE TITLE
Using SpriteText removes mouse events

### ISSUE THREAD

**Issue by NicksonYap** [vasturiano/3d-force-graph#161]
Hi

Once using SpriteText to remove nodes

We can no longer drag the nodes, or have onHover events

**Comment by vasturiano** [comment]
@NicksonYap yes, this happens because Raycaster has difficulty detecting Sprite object types. There is a related issue open: https://github.com/vasturiano/3d-force-graph/issues/127#issuecomment-429260750

**Comment by NicksonYap** [comment]
@vasturiano

Any idea how to perhaps add a fake mesh or 2D plane as background (maybe even transparent), so the the mouse can click the mesh behind the Sprite?

(I've never used Three.js before)

**Comment by vasturiano** [comment]
@NicksonYap I've added a spherical drag handle to the [text example](https://vasturiano.github.io/3d-force-graph/example/text-nodes/), so they can now be dragged. You can check out the Three.js code at: https://github.com/vasturiano/3d-force-graph/blob/master/example/text-nodes/index.html#L21

And yes, the mouse events do not work directly for any sprite type objects.
