### ISSUE TITLE
Pixelated for High DPI screens, when using Width & Height

### ISSUE THREAD

**Issue by NicksonYap** [vasturiano/3d-force-graph#162]
Hi,

Due to the way I make the 3D view size dynamic & responsive (sets width and height when container size changes)

Some high DPI devices produce pixelated images.

Is there a way to go around scaling issues, etc?
Probably a setting in Three JS?

The same goes for my Samsung S9 (high res)

It works fine on a regular 1080p monitor

![image](https://user-images.githubusercontent.com/5380731/50725143-20eec000-1134-11e9-83ca-d8a865d11fcf.png)

**Comment by vasturiano** [comment]
@NicksonYap thanks for the report. This is probably something at the ThreeJS level, as you mentioned. Do you see this happening also for other ThreeJS examples, or only when using `3d-force-graph`?

**Comment by NicksonYap** [comment]
@vasturiano

`3d-force-graph` is fine when full screen

I think it has something to do with the way I wrap or contain the `3d-force-graph` div

The problem may be similar to how when retina displays came out (iPhone)
Such that some images/icons would seem blur and require 2x the resolution to fix

For example:
The width pixel value is 500px in html/js
but the browser will render it at 1000px since the screen is high dpi otherwise the orignal 500px would look too small

However, the actual image (in out case, the 3D view) is still at 500px, making it blur

I believe that ThreeJS probably has it fixed, but may require us to configure manually?

I beliece these are related issues (from threejs or webgl)

Something to do with setting pixel ratio

https://github.com/jupyter-widgets/pythreejs/issues/103#issuecomment-308287477
https://github.com/giovannipizzi/seekpath/issues/15
https://github.com/mrdoob/three.js/issues/2833

How can I apply these to ThreeJS/WebGL through this library?

Thanks

**Comment by NicksonYap** [comment]
Note:

I also believe that the `width()` function may have assumed a devicePixelRatio of 1 (non high dpi)

ThreeJS might have automatically managed it but might be affected by the `width()` function

found docs for setting pixelRatio:

https://threejs.org/docs/#api/en/renderers/WebGLRenderer.setPixelRatio

**Comment by vasturiano** [comment]
@NicksonYap thanks for looking deeper into this. 

Since this is a renderer setting, I think possibly you could set it like this:
```
myGraph.renderer().setPixelRatio( window.devicePixelRatio );
```
Please do let me know if it does work for you, as it may be useful to encapsulate this config inside the lib so it just works by default.

**Comment by NicksonYap** [comment]
@vasturiano 

Yes, that did the trick!

I added that line right after I initialize `myGraph`

even with `.width()` called multiple times, the scaling correction is still in effect

**Comment by NicksonYap** [comment]
@vasturiano  i was trying to antialias
since I have text and on regular res screens & zoomed out, it can look like pixels are missing and hard to read

so what i did was double the `devicePixelRatio` and worked

however I don't think this is proper

how can we use this?:

https://threejs.org/docs/#api/en/renderers/WebGLRenderer.antialias

it seems it can only be added when initializing threejs

**Comment by NicksonYap** [comment]
@vasturiano 

Have updated to `v1.43.9` and I did this:

```js
const myGraph= ForceGraph3D({
        rendererConfig: {
          antialias: true
        }
      })(elem)
        ...
```

However, I don't see any visible difference/improvement at all

Doubling the scale looked better

any idea why it doesn't work?
