### ISSUE TITLE
How to add, lights into scene?

### ISSUE THREAD

**Issue by ArunRajdeveloper** [vasturiano/3d-force-graph#165]
Hi, I want to add lights in the scene, I already try following methods,

     var light = new THREE.PointLight(0xff0000, 50, 1)
      light.position.set(50, 50, 50);
      Graph.scene().add(light);

But this not working, why lights can't add here, if any mistake did here, please tell me what is the mistake here.

**Comment by dennisschumann** [comment]
You can do this like described, but consider:
1) The build does not contain the hole ThreeJS library - import the three.js before laoding the 3d-force-graph.js
2) 3d-force-graph already adding two lights which may overlap yours. Remove them from scene when adding your custom ones.

`...new three.AmbientLight(0xbbbbbb),
        new three.DirectionalLight(0xffffff, 0.6)...`
