### ISSUE TITLE
update node drag not working

### ISSUE THREAD

**Issue by ArunRajdeveloper** [vasturiano/3d-force-graph#166]
Hi, following code the node drag was not working, please tell me why here update node drag was not working.

 const enableNodeDrag1 = { 'Drag Option': 'null'}
  const enableNodeDraggui = new dat.GUI()
  enableNodeDraggui.add(enableNodeDrag1, 'Drag Option', ['true', 'false'])
    .onChange(enableNodeDrag1 => Graph && Graph.enableNodeDrag(enableNodeDrag1))

**Comment by vasturiano** [comment]
@ArunRajdeveloper can you post a live example showing the issue, so that it can be debugged?
