### ISSUE TITLE
Making the labels of the links always visible

### ISSUE THREAD

**Issue by alweish** [vasturiano/3d-force-graph#168]
Thanks for this awesome contribution, 

I have found many workarounds to show the labels of the nodes, but what about the labels of the links, Is there any workaround to make them always visible so viewers can see the full image, and understand the relationships between nodes without having to follow and hover the lines of the links one by one?

Another reason: Tooltips need a mouse, so it's only supported on computer devices.

**Comment by vasturiano** [comment]
@alweish thanks for reaching out.

I just added a new example with persistent link labels:
https://vasturiano.github.io/3d-force-graph/example/text-links/

This uses the two new props: `linkThreeObject` and `linkPositionUpdate`.

**Comment by alweish** [comment]
@vasturiano Wow! Worked perfectly, Thank you very much.

For the nodes, to show objects and persistent labels together, still, the only way is the nodeThreeObject, right?

**Comment by vasturiano** [comment]
@alweish yes, correct. Currently, the only shape for nodes provided out of the box are plain spheres. Anything else needs to be fabricated with custom `ThreeJS` code using `nodeThreeObject`.

**Comment by alweish** [comment]
Thanks @vasturiano
