### ISSUE TITLE
Right Click Option

### ISSUE THREAD

**Issue by FlashCodX** [vasturiano/3d-force-graph#169]
Hello is it possible to add a right click option in this lib, i would be very interesting to see a right click on a node and show some options... Very amazing work... good day

**Comment by vasturiano** [comment]
@OrionSJB thanks for your suggestion. I just added `onNodeRightClick` and `onLinkRightClick` event callbacks. Please pull the latest version (`v1.45.0`) and let me know if it works for you.

**Comment by OrionSJB** [comment]
Thank you so much!
