### ISSUE TITLE
Menu Option

### ISSUE THREAD

**Issue by FlashCodX** [vasturiano/3d-force-graph#171]
Hello, awesome job with the right click, option.
Would it be possible to add a menu with items on rightClick option , it would be cool to see, something like that.
Thank you!! Great work!

**Comment by vasturiano** [comment]
@OrionSJB thanks for your suggestion. I think that would be useful but probably falls outside of the scope of this library. That can always be done externally, now that there's programatic access to object right-click events.

**Comment by OrionSJB** [comment]
@vasturiano ,yes, you're probably right. Thank you! Have a good day!
