### ISSUE TITLE
Is there an API to dispose of everything?

### ISSUE THREAD

**Issue by PWKad** [vasturiano/3d-force-graph#174]
Couldn't find anything in particular, trying to dispose of the graph after it has been created.  Basically when it is removed from the DOM there are still drawings and references from the graph even when not displayed so simply trying to tear it down gracefully.

Thanks in advance!  This lib is great.

**Comment by vasturiano** [comment]
@PWKad if you clear the data (`.chartData({ nodes: [], links: [] })`) and pause the animation engine (`.pauseAnimation()`), that should halt all activity of the graph object.

**Comment by PWKad** [comment]
Perfect thanks!
