### ISSUE TITLE
Custom link creation

### ISSUE THREAD

**Issue by dodongjuan** [vasturiano/3d-force-graph#175]
I have a requirement where I need to draw/create a custom link path. I tried using linkThreeObject, but it looks like it does has no effect.

inkThreeObject(link =>{

const xIncrement = 150;
var srcNode = nodeMap[link.source];
var tgtNode = nodeMap[link.target];

var coordinates  = [];
coordinates[0]= 	new THREE.Vector3( srcNode.fx, srcNode.fy, srcNode.fz );
var x2 = srcNode.fx + xIncrement;
if(srcNode.fx > tgtNode.fx){
   x2 = srcNode.fx - xIncrement;
}
coordinates[1]= 	new THREE.Vector3( x2, srcNode.fy, srcNode.fz );
coordinates[2] = new THREE.Vector3( x2, tgtNode.fy, tgtNode.fz );
coordinates[3] = new THREE.Vector3( srcNode.fx, srcNode.fy, srcNode.fz );

const curve = new THREE.CatmullRomCurve3(coordinates);
const geometry = new THREE.Geometry();
geometry.vertices = curve.getSpacedPoints( 100 );
const material = new THREE.LineBasicMaterial( { color : 0x00ff00 } );
var curveObject = new THREE.Line( geometry, material );

console.log("Link   ", link.source, srcNode);

//var srcNode = this.nodeId(link.source);
//console.log("Link Source  ",srcNode,link.source);
//console.log("Link Target  ", link.target.fx,link.target.fy,link.target.fz);

return curveObject;
}) ;

**Comment by vasturiano** [comment]
@dodongjuan please create an example online that (on **codepen** for instance), that reproduces the issue you're experiencing.
