### ISSUE TITLE
how to add hyperlink on link bewteen two nodes?

### ISSUE THREAD

**Issue by FrankHui** [vasturiano/3d-force-graph#176]
Firstly many thanks for such great source.
And as a newbie on frontend, how can I add hyperlink on link between two nodes with this great framework?
To be specific, I want to right click on the link, then choose to jump to the hyperlink. 
I guess I can add "hyperlink" attribute to links in json file. Then what?

Any suggestions will be appreciated.

**Comment by vasturiano** [comment]
@FrankHui, assuming each link has a `hyperlink` attribute, you could do something like:
```
myGraph.onLinkRightClick(link => window.open(link.hyperlink));
```

**Comment by FrankHui** [comment]
Thanks! It works like a charm!
