### ISSUE TITLE
django can't find json file in index.html

### ISSUE THREAD

**Issue by FrankHui** [vasturiano/3d-force-graph#177]
I use Example text-nodes in django with pycharm, index.html's preview is good.
Starting service, Django just can't find json file in html.
```
Not Found: /datasets/miserables.json
```

But my code is 
```
jsonUrl('../datasets/miserables.json')
```
It seems a stupid path problem, while its preview is good.
I may ask the wrong person, but if you have any idea, please give me a hand.

Many thanks in advance.

**Comment by FrankHui** [comment]
I solve it accidently...

**Comment by EPurpl3** [comment]
And how did u solve it? ....
