### ISSUE TITLE
how to add search engine 

### ISSUE THREAD

**Issue by FrankHui** [vasturiano/3d-force-graph#178]
Sorry to bother you again.
I followed some 101 introduction. But the search box are out of the black background.
Besides, I'm wondering after search, fuzzy match and choose node,  how to highligth the node and its direct neighbour nodes and their links?

Any suggestion would be appreciated.

**Comment by gf0604** [comment]
How do you implement the search, I also want to achieve the same function

**Comment by vasturiano** [comment]
You can look into [this example](https://vasturiano.github.io/3d-force-graph/example/highlight/) for the highlighting functionality. Here's the source: https://github.com/vasturiano/3d-force-graph/blob/master/example/highlight/index.html

If you have a search box and want to use it to highlight/dim nodes/links, you can follow a similar pattern. It's all a matter of playing with the `nodeColor` and `linkWidth` methods.
