### ISSUE TITLE
Minimize link length as small as possible

### ISSUE THREAD

**Issue by Hyssopi** [vasturiano/3d-force-graph#180]
Hello.

Basically I have really small images (40px by 40px) as my nodes.
The links are far too long for these tiny images.
If I scale the images bigger, then it becomes really blurry.
So I just want to shorten the links.

Here is my code:
https://github.com/Hyssopi/Pokemon-Graph-2
and a working GitHub Pages:
https://hyssopi.github.io/Pokemon-Graph-2/

You can see the sprite image nodes if you zoom in a lot.

I look at this example: https://github.com/vasturiano/3d-force-graph/blob/master/example/manipulate-link-force/index.html
However I noticed something strange. If I set the `redDistance` to 25 for example, I see that the red links have different lengths. Why is this so?

Angle 1:
![image](https://user-images.githubusercontent.com/43843070/53624622-c151e580-3bb5-11e9-96b7-7bef4f26f0f8.png)

Angle 2:
![image](https://user-images.githubusercontent.com/43843070/53624648-d7f83c80-3bb5-11e9-8f0e-932bfa4582c8.png)

I think it can be easily reproduced.

I've also tried to put this example into my code but it has no effect on my link length.

**Comment by vasturiano** [comment]
@Hyssopi the link distance in that example is being adjusted by configuring the link force, like so:
```
myGraph.d3Force('link').distance(<your value>)
```

This tells the link force what the length fo the "spring" links at rest should be.

An alternative way to approach this issue, so you don't have to alter the force engine behaviour, is just to scale the nodes to the dimensions that suit you. That way, you're only changing the visual represention rather than the force engine internals.

**Comment by Hyssopi** [comment]
It's strange but `graph.d3Force('link').distance(1);` has no effect on the length of the links. It looks exactly the same as if I didn't include it.

**Without** `graph.d3Force('link').distance(1);`:
![image](https://user-images.githubusercontent.com/43843070/53708965-a320fb00-3dea-11e9-9905-ededce780726.png)

With `graph.d3Force('link').distance(1);`:
![image](https://user-images.githubusercontent.com/43843070/53708968-a87e4580-3dea-11e9-8ab6-07637914bc1a.png)
