### ISSUE TITLE
Changing Node Size and Link Distance

### ISSUE THREAD

**Issue by dennisschumann** [vasturiano/3d-force-graph#184]
Hello,

is there a simple way to change the node size as well as the link distance?

By default, nodes are 4x4x4 and the link distance by d3 has a constant with of 30. As I use some Three.js models, I like to increase nodes and links by factor 10.

But when I set a node to 40x40x40 (by using a own geometry with nodeThreeObject) and set the link distance to 300 (by d3Force('link').distance(...)), the graph layout looks strange...

Best regards!

**Comment by vasturiano** [comment]
@dennisschumann if you adjust the link force distance, you may also want to adjust the node repulsion force to be in balance with the larger distances. For example:
```myGraph.d3Force('charge').strength(-200)```

What is probably happening in your case it that the repulsion force is too weak at those large distances leading to an unstable layout.

**Comment by dennisschumann** [comment]
Works fine for me, thank you!!
