### ISSUE TITLE
height(NaN) problem

### ISSUE THREAD

**Issue by sbusch** [vasturiano/3d-force-graph#186]
We found an obscure bug. It's a rare edge case, but we thought it may be of interest for you, as it cost us some hours finding the cause:

We were calculating and setting the height (and width) with `.height()` (and `.width()` respectively). Part of the calculation was getting and subtracting the height of a header div.

Problem:

1. this `<div>` had been removed in a previous edit
2. jQuery('#div').height() then returned `undefined`
3. Using `undefined` in the calculation resulted in `NaN`
4. Graph method `.height()` was called with `NaN`
5. Rendered graph looked ok, *but*
6. Mouse event handlers set by `onNodeHover()` and `onNodeClick()` never fire

We didn't test calling `.width()`with `NaN`, but it may be "affected", too. 

Thanks for this lib!

**Comment by vasturiano** [comment]
Hi @sbusch, thanks for the report. I've just issued a fix that parses the input `width`/`height` parameters and checks for `isNaN` before applying them to the DOM. Thanks for catching this.
