### ISSUE TITLE
Layout not rendering if focused on another tab.

### ISSUE THREAD

**Issue by rdecapomaranca** [vasturiano/3d-force-graph#187]
Hello.

I noticed that if I switch tab before layout finishes rendering, and then come back to the tab with graph, the layout is the same as at the moment I switched tabs.

Here is the image of fully rendered layout (when waiting for it to render on tab):
![ontab](https://user-images.githubusercontent.com/7722193/54194996-dedc5480-44bd-11e9-8d00-2e8afeb217a4.png)

And here is the image of partially rendered layout (when waiting for it to render off the tab):
![offtab](https://user-images.githubusercontent.com/7722193/54195028-f287bb00-44bd-11e9-80fe-e7de360125bf.png)

Just to be clear. None of the images are zoomed in/out.

The way you achieve this is:
Open https://vasturiano.github.io/3d-force-graph/example/large-graph/ . Quickly change to new tab and wait a minute or two so the layout "finishes rendering". Then go back to the tab with graph and see that the layout didn't finish rendering.

Is there a way to fix this or is there a specific reason for this behaviour?

Thank you,
Nika

**Comment by vasturiano** [comment]
@rdecapomaranca that is because of the `cooldownTime` default setting to 15sec (`15000`). The engine stops ticking after that time is expired, whether the tab is in focus or not.
If you wish to change that behavior, I'd suggest setting `cooldownTime(Infinity)` and `cooldownTicks` to a sane amount, say `300`.

**Comment by rdecapomaranca** [comment]
Thank you for the fast answer. Correct me if I'm wrong, but doesn't that mean that layout generates only when the tab is in focus. If not, layout generation is in a way paused.
Can a layout be generated completely even when the tab is not in focus?

**Comment by vasturiano** [comment]
@rdecapomaranca what happens practically is that when you return to the tab (that has been paused because was not in focus), too much time has passed since the start (past the `cooldownTime` threshold), so the engine resumes rendering as tab gets focus but immediately stops.
