### ISSUE TITLE
Can't create a link to non existing node

### ISSUE THREAD

**Issue by AlvaroPaniaguaT** [vasturiano/3d-force-graph#188]
When i load json file, some link target points to empty nodes and can't load graph. 

![image](https://user-images.githubusercontent.com/14541134/54382726-d7b97000-4690-11e9-83a1-f9ec4c20e37b.png)

**Comment by vasturiano** [comment]
@AlvaroPaniaguaT it appears the links point to non-existing nodes. That causes a JS exception, intentionally. It's advisable to sanitize your data before feeding it to the graph.
