### ISSUE TITLE
save as png by clicking button 

### ISSUE THREAD

**Issue by nupurbiswas** [vasturiano/3d-force-graph#189]
Hi, I need some help. I want to keep a 'save' button in html like 
` <button id="save">save image</button> ` 
to save the current scene of 3D graph as png. How can I do it ? Please help.

**Comment by vasturiano** [comment]
@nupurbiswas have you tried using `toDataURL`, like so: http://learningthreejs.com/blog/2011/09/03/screenshot-in-javascript/

You can access the renderer via `myGraph.renderer()`.

**Comment by nupurbiswas** [comment]
Here is my code and it did not work. 

    <!DOCTYPE html>
    <html>
    <head>
    <script src="//unpkg.com/react@16/umd/react.production.min.js"></script>
    <script src="//unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>
    <script src="//unpkg.com/babel-standalone"></script> 
    <script src="//unpkg.com/react-force-graph-3d"></script>
    </head>
     <body>
     <div id="3d-graph" ></div>
    <script type="text/jsx">
    fetch("blocks.json").then(res => res.json()).then(data => {
    class FocusGraph extends React.Component {
    _handleClick = node => {
      // Aim at node from outside it
      const distance = 40;
      const distRatio = 1 + distance/Math.hypot(node.x, node.y, node.z);
      this.fg.cameraPosition(
        { x: node.x * distRatio, y: node.y * distRatio, z: node.z * distRatio }, // new position
        node, // lookAt ({ x, y, z })
        3000  // ms transition duration
      );
    };
    render() {
      return <ForceGraph3D
        ref={el => { this.fg = el; }}  
          graphData={data}
        width="900"
     />;
    }
    }
    ReactDOM.render(
    <FocusGraph />,
    document.getElementById('3d-graph')
     );
    });
     var canvas = document.getElementById("3d-graph");
     document.write("<img src='"+canvas.renderer.toDataURL("image/png")+"' alt='from canvas'/>");
     </script>
    <div id="bottom" style="display:inline"><p align ="bottom" 
    style="position:absolute;bottom:0px;right:10px;align:right"><button id="save" >Save current scene as png 
    </button></p></div>
     </body>
    </html>

**Comment by vasturiano** [comment]
@nupurbiswas I'm not certain that's the issue, but you should access the renderer via `myGraph.renderer()` instead of `canvas.renderer`.

**Comment by nupurbiswas** [comment]
@vasturiano Thanks for responding. I tried following also but did not work
`document.write("<img src=' "+myGraph.renderer().toDataURL("image/png")+" ' alt='from canvas'/>"); `

**Comment by vasturiano** [comment]
I'm not familiar with the `"+...+"` syntax in the `src` attribute. Is that executing the inner JavaScript?

**Comment by nupurbiswas** [comment]
Any other alternative way? Actually, I am quite new in js.

**Comment by vasturiano** [comment]
It seems you should probably run the code that manipulates the `img` `src` attribute on button click, like `<button onclick="() => <your code>">`.

**Comment by nupurbiswas** [comment]
Tried following one but not working

      <button onclick="myFunction()">Save graph as png </button>
      <script>
       function myFunction() {
       var myimg=document.getElementById("3d-graph");
      $('#3d-graph').renderer(function(myimg){
        saveAs(myimg, 'graph.png');
       });
        }
      </script>

**Comment by nupurbiswas** [comment]
Based on the discussion (https://github.com/vasturiano/3d-force-graph/issues/25), the issue is solved now. Working code is shared here for the benefit of the community. 

     <!DOCTYPE html>
     <html>
     <head>
     <script src="//unpkg.com/react@16/umd/react.production.min.js"></script>
     <script src="//unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>
     <script src="//unpkg.com/babel-standalone"></script> 
     <script src="//unpkg.com/react-force-graph-3d"></script>
     <script src="jquery-3.3.1.js"></script>
      <script src="FileSaver.js"></script> // https://github.com/eligrey/FileSaver.js/blob/master/src/FileSaver.js
      </head>
      <body>
       <div id="3d-graph" ></div>
       <script type="text/jsx">
      fetch("blocks.json").then(res => res.json()).then(data => {
       class FocusGraph extends React.Component {
       render() {
       return <ForceGraph3D
           ref={el => { this.fg = el; }}  
             graphData={data}
        />;
       }
        }
       ReactDOM.render(<FocusGraph />,
      document.getElementById('3d-graph')
       });
      <div id="savebutton"><button>Save graph as png </button></div>
      <script>
      var a, downloads = 0;
     $('#savebutton').click(function(){
      downloads = 0;
      a = requestAnimationFrame(download);
      );
      });

      function download(){
       if(downloads){
      cancelAnimationFrame(a);
       } else {
       $('#3d-graph canvas')[0].toBlob(function(blob){ 
      console.log(blob);
      saveAs(blob, 'graph.png');
       });
         }
       }
      </script>
