### ISSUE TITLE
Background Color not changing

### ISSUE THREAD

**Issue by shikharka** [vasturiano/3d-force-graph#19]
backgroundColor([str]) fetches the default color and sets new color but change is displayed

**Comment by vasturiano** [comment]
@shikharka calling `Graph.backgroundColor(<color>)` should update the background color, as long as you're using a version higher than `1.11.0`.
If it's not working for your case, can you send me some more details about your environment, maybe a code snippet.

**Comment by shikharka** [comment]
https://jsfiddle.net/vwuvgjtj/3/ 

Background color change
Node and Link color didn't

**Comment by shikharka** [comment]
https://jsfiddle.net/vwuvgjtj/3/

Background Color changed
Node and Link Color did'nt

**Comment by vasturiano** [comment]
The `nodeColor` and `linkColor` methods take an accessor attribute or function, not a constant. 
If you wish to specify a constant, you should do something like this:
```
Graph.nodeColor(d => '#ff0000')
```

**Comment by shikharka** [comment]
okay! thanks :)
