### ISSUE TITLE
Ngraph forceengine

### ISSUE THREAD

**Issue by Bernard912** [vasturiano/3d-force-graph#190]
Hi there,

Thank you very much for this great library. Unfortunately, I ran into a problem.
When I use ngraph engine, the cameraposition doesn't work.
It seems that in this mode we can't collect the position coordonates of the node (node.x =0, node.y=0,node.z=0).
How can I adapt the onNodeClick method to use it with the ngraph forceengine?
Thank you for your answer.

Part of your code below with ngraph forceEngine

Graph(elem)
    .forceEngine("ngraph")
    .jsonUrl('http://mywebsite/mytho.json')
    .onNodeClick(function (node){
	const distance = 200;
	const distRatio = 1 + distance/Math.hypot(node.x, node.y, node.z);
	Graph.cameraPosition(
	    { x: node.x * distRatio, y: node.y * distRatio, z: node.z * distRatio }, 
	     node, 
	     3000  
         );
   })

**Comment by vasturiano** [comment]
@Bernard912 in `ngraph` mode you can't read or write x, y, z coordinates directly on the nodes, like you can when using the `d3` engine. That is a limitation of the `ngraph` engine. You can still use `onNodeClick`, but you won't be able to do computations (like moving the camera) based on the nodes positions.

**Comment by Bernard912** [comment]
@vasturiano thank you for you reactivity and these precisions.
