### ISSUE TITLE
Kapsule stateInit is called during module import

### ISSUE THREAD

**Issue by artyomtrityak** [vasturiano/3d-force-graph#191]
stateInit is called during library import (https://github.com/vasturiano/3d-force-graph/blob/master/src/3d-force-graph.js#L169) 

For example:

```
const ForceGraph3D = require("3d-force-graph").default; // <- stateInit called
```

And executes code which does use at then end ES6 features that should be polyfilled, for example `new Map` usage here: https://github.com/vasturiano/d3-force-3d/blob/master/src/link.js#L60

But because it is executed immediately after import, polyfills are not in place yet.

Is it possible to not execute kapsule.initState on import?

**Comment by vasturiano** [comment]
@artyomtrityak this is related to `d3-force` including ES6 code in the ES module binding. There is more background on this change here: https://github.com/d3/d3-force/issues/134

If you need to support your application in older browsers that don't support ES6 syntax (such as IE11), I'd suggest configuring your application bundle to transpile the `d3-force-3d` module directly from `node-modules`.

**Comment by artyomtrityak** [comment]
@vasturiano thanks for answer! Map and Set are not transpiled but polyfilled (at least in babel). This is the core set of issue - polyfills are loaded more application but after node_modules. And because `stateInit` does executes immediately after import inside library polyfills are not in place at that moment.

I believe this code is related to `stateInit` call https://github.com/vasturiano/3d-force-graph/blob/master/src/kapsule-link.js#L3

**Comment by vasturiano** [comment]
@artyomtrityak yes, I see your point. `ThreeForceGraph` is instantiated at import time (using `linkKapsule`), as that's necessary to properly bind the 3d-force-graph kapsule definition.

What you can try is to dynamically import the `3d-force-graph` module, so that your polyfills run first.
But I'll reiterate that the core reason for the issue is in `d3-force` (inherited by `d3-force-3d`). If you are able to properly transpile that, your issue should go away. Does `babel-polyfill` not handle that?

**Comment by artyomtrityak** [comment]
`babel-polyfill` does have polyfills for `Map` and `Set`. But `babel-polyfill` loads after `node_modules`.

Webpack organizes it's bundle in order node_modules -> application specific data. I do not see any way to control `node_modules` load order.

Fix i did is:
I used to have 2 bundles - `vendor` (all node_module stuff including babel-polyfill) and `app` - application files.

Now i have 3 bundles: `polyfills` (loads first), `vendor` (loads second) and `app` (loads last).

It works but the only reason i moved polyfills out to separated bundle is stateInit which is called in import time before babel-polyfills come in place. And i did not find any way to control order of node_modules load.
