### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by DonaldAlan** [vasturiano/3d-force-graph#192]
Please update the webpage https://vasturiano.github.io/3d-force-graph/ to include instructions how to run the code.  I did `git clone https://github.com/vasturiano/3d-force-graph.git` to get the code. I couldn't directly load examples into the browser, due to `CORS request not http`. So I did `npm install`.   But after that I was lost.  I tried `node server` but that resulted in the error `Error: Cannot find module 'D:\Javascript\three_js\3d-force-graph\server'`.  How do I run the examples?

**Comment by vasturiano** [comment]
@DonaldAlan you can run the examples directly from the Github page, for example: https://vasturiano.github.io/3d-force-graph/example/basic/

If you want to load them locally from your machine you just have to serve them through a local HTTP server. No need to install `node_modules` or anything like that, unless you want to develop and modify the src code yourself.

**Comment by DonaldAlan** [comment]
Thanks. I got it working by doing
```
 npm install http-server -g
 http-server ./
```
and then visiting `http://127.0.0.1:8080`.
