### ISSUE TITLE
[Performance] Merge Geometry

### ISSUE THREAD

**Issue by BorisKourt** [vasturiano/3d-force-graph#193]
Would there be a good way to merge node geometries when not using animation (e.g. via `cooldownTime(0)`)

I am currently using some low-poly custom node geometries and want to optimize the scene as much as possible.

**Comment by vasturiano** [comment]
Unfortunately that's not possible right now out of the box. Mainly because it conflicts with all the interaction functionality that won't be possible if the geometries are merged. 

Of course, you could potentially do it externally by just post-processing the scene (accessible via `graph.scene()`).

**Comment by BorisKourt** [comment]
Thanks, I will try that.
