### ISSUE TITLE
ERROR - THREE.WebGLRenderer: Context Lost

### ISSUE THREAD

**Issue by HyeongHwanKim** [vasturiano/3d-force-graph#194]
I used react-force-graph.
Putting a curve on a link takes up a lot of memory and causes an error.
Please let me know the solution.

(Reference : force-graph loading 128 nodes 2886 links)
(Example source has same error)

Thanks.

<ForceGraph3D
              graphData={this.state.myData}
              ref={(el) => { this.graphEl = el }}
              nodeThreeObject={this.handleNodeThreeObj}
              cameraPosition={this.state.cameraPosition}
              // linkThreeObject={this.handleLinkThreeObj}
              // linkPositionUpdate={this.handleLinkPositionUpdate}
              linkLabel={(link) => {
                return `<b style="color: white; font-size: 20px">${link.source.label} - ${link.kind} - ${link.target.label}</b>`;
              }}
              nodeLabel={(node) => {
                return `<b style="color: white; font-size: 20px">${node.label}</b>`;
              }}
              onNodeClick={this.onHandleNodeClick}
              // onNodeHover={this.handleNodeHover}
              linkVisibility={link => {
                if (!this.state.clickNode) return true;
                if (this.state.clickNode === link.source.id || this.state.clickNode === link.target.id) return true;
                return false
              }}
              linkCurvature={'Curvature'}
              linkCurveRotation={'curveRotation'}
              linkMaterial={this.setMaterial}
            />

**Comment by vasturiano** [comment]
@HyeongHwanKim curved links are composed of 30 small line fragments, therefore they do consume more resources than straight lines, and impact performance in large graphs with many links.
If performance is important in your case, the best suggestion is to stick with straight lines.
I see in your case you're also using custom linkMaterials. Depending on how much reusing you're doing (not visible in your code) that may also lead to high memory usage.
Same for `nodeThreeObject`, you have not included that code. If you need any help in troubleshooting please provide a reduced example online that reproduces the error.
