### ISSUE TITLE
How to set zoom level(initial,min , max)??

### ISSUE THREAD

**Issue by shikharka** [vasturiano/3d-force-graph#20]

**Comment by vasturiano** [comment]
@shikharka the initial zoom level is calculated based on the number of nodes in the system, ina cubic relationship.
For reference, this is where that logic is applied:
https://github.com/vasturiano/3d-force-graph/blob/master/src/3d-force-graph.js#L132

There is no way currently to specify zoom max/min boundaries programmatically from outside the component.

**Comment by shikharka** [comment]
It will be a good to have feature

**Comment by vasturiano** [comment]
@shikharka from `v1.22.0` you can now specify a custom distance using `cameraPosition`. F.e:
```
myGraph.cameraPosition({ z: 1000 });
```

**Comment by shikharka** [comment]
Thanks! will check

**Comment by Doni44** [comment]
Hello, and is ther any wat to tell the graph not to move? I mean, the first time it'is like the 3D grapgh flies away from my div...

**Comment by vasturiano** [comment]
@Doni44 answered in #72.

**Comment by rdecapomaranca** [comment]
By exposing tbControls like you exposed camera and scene I was able to set the min and max zoom and also disable rotation which I needed to display a 2D graph. Could you maybe expose this, so that my code doesn't differ from the one on repository.

Thank you,
Nika

**Comment by shaliniBITC** [comment]
> By exposing tbControls like you exposed camera and scene I was able to set the min and max zoom and also disable rotation which I needed to display a 2D graph. Could you maybe expose this, so that my code doesn't differ from the one on repository.
> 
> Thank you,
> Nika

Hi, can you please explain how you set min and max zoom.

**Comment by HeeYong2** [comment]
Hi!
Can I know screen zoom level?

I want to show different information depending on the zoom level.

Thank you!!

**Comment by vasturiano** [comment]
@shaliniBITC you can access the various config of [TrackballControls](https://threejs.org/docs/#examples/en/controls/TrackballControls) via the `.controls()` method.
So, for min/max distance:
```js
myGraph.controls().maxDistance = 2000;
```
