### ISSUE TITLE
How can i set specific node's opacity ?

### ISSUE THREAD

**Issue by buddyy93** [vasturiano/3d-force-graph#205]
i tried Graph.nodeOpacity function but it sets all nodes opacity
what i want to achieve is when i hover on a node i want to set other nodes opacity to 50 percent except the one i hover on.

**Comment by vasturiano** [comment]
@buddyy93 thanks for reaching out. You can manage the opacity of each node independently by manipulating the alpha channel on the node color. For example, something like:
```
.nodeColor(node => `rgba(255, 0, 0, ${node.isHovered ? 1 : 0.5})`)
```
You can simply call that method every time your node hover state changes, so the new colors are applied.

Here is an example following a similar pattern:
https://vasturiano.github.io/3d-force-graph/example/highlight/

**Comment by buddyy93** [comment]
hi, thanks for your reply
will try it soon
