### ISSUE TITLE
How to change the node and link label text color. 

### ISSUE THREAD

**Issue by somu2324** [vasturiano/3d-force-graph#206]
**Is your feature request related to a problem? Please describe.**
Yes! may be if I want to change the tooltip text color according to background color.
**Describe the solution you'd like**
it will be good it you can provide direct method.

**Describe alternatives you've considered**
yes

**Additional context**

**Comment by vasturiano** [comment]
@somu2324 thanks for reaching out. 

You can style the tooltip to your taste using CSS overrides. Basically add CSS rules to the class `scene-tooltip`. The default styling is here:
https://github.com/vasturiano/three-render-objects/blob/master/src/three-render-objects.css#L10

**Comment by somu2324** [comment]
@vasturiano  not much clear. Could you provide me any example.

**Comment by vasturiano** [comment]
@somu2324 in your page's CSS, you can just add overriding rules. For example, if you wish the text to be blue:
```
.scene-tooltip {
  color: blue;
}
```

**Comment by somu2324** [comment]
Thanks @vasturiano , its working.

**Comment by somu2324** [comment]
I am using below two method for grouping the Nodes and link color
.nodeAutoColorBy('group')
.linkAutoColorBy(d => gData.nodes[d.source].group)

Above two methods pick color based on total number of group in my data set.

Can we provide custom color on bases on group by.  If so then please let me know how to do this?
