### ISSUE TITLE
How to add CSS3 effects to nodeThreeObject or add neon/glow effect to 3D Cube

### ISSUE THREAD

**Issue by MarcelK28** [vasturiano/3d-force-graph#207]
Hi I really love your work. I'm working on a project to show a topology diagram using a desing of my own where I would like to have a glow/neon effect around the cube. Similar to this [periodic table](https://threejs.org/examples/css3d_periodictable.html) but in this example they are using **THREE.CSS3DObject** to render the css3 effect, but your work does not allow me to use CSS3 within **nodeThreeObject** or does it?

I have tried other solutions such as Shaders, OutlinePass, EffectComposer, FXAAShader, etc, but the output wasn't great.

I'm basically looking to create a nice glowing/neon effect around the 3D cube. Could you please help how this could possible be achieved?

Many thanks

**Comment by vasturiano** [comment]
@MarcelK28 thanks for reaching out.

If I'm reading this correctly: https://github.com/mrdoob/three.js/blob/master/examples/js/renderers/CSS3DRenderer.js#L7
the `CSS3DObject` class actually extends `3DObject`. `nodeThreeObject` should accept any instance (or child classes) of `Object3d`, so it's possible that it just works. Have you tried it?

**Comment by MarcelK28** [comment]
Oh, I didn't know that, thank you very much. It is hard to find a proper example of it. How is it actually possible to create a 3D cube using `CSS3DObject`? Any idea?

**Comment by vasturiano** [comment]
I haven't used `CSS3DObject` so I can't be of much of much help there. Maybe a question for the ThreeJS folks?

**Comment by MarcelK28** [comment]
I have done and it works. But it looks like the performance is not so great when having more than 100 nodes due to the fact that each cube has 6 sides which are effectively 6 new instances of `CSS3DObject` times 100 nodes can drastically affect the experience.

**Comment by MarcelK28** [comment]
..actually, sorry again. I'm thinking, and please correct me/help me. What if I use D3.js force diagram in 3D mode and all my nodes will be as 3D cubes similar to this [one](https://bl.ocks.org/Niekes/ff4d3c8497d8436d4d8fdb9f0121d12d) so then I could actually use my glow/neon effect using `svg` or `css` and have like 1000s of them on the page without loosing any performance? Would that work? Is out there a D3.js-3D force diagram you know of? Many thanks

**Comment by vasturiano** [comment]
@MarcelK28 there is [d3-force-3d](https://github.com/vasturiano/d3-force-3d). That's a port of `d3-force` extended to function in three dimensions. That's what `3d-force-graph` uses under the hood as a force layout.

As for the performance, that seems particular to `CSS3DObject` so I can't help much. But with regular meshes often what helps is to share a single `Material` object among all the meshes, which limits the number of object instances and helps with performance. I don't know if something like that is applicable to this particular object type, or if there's some parts of it that can be shared between instances.

**Comment by MarcelK28** [comment]
I see. Can I change the shape of the node in [d3-force-3d](https://github.com/vasturiano/d3-force-3d) to a 3D cube, or svg, img or anything else?

I wouldn't mind using the `threejs` version of yours with `Material` and a custom img with a blur/glow around the outline (square) but as soon as the cube is created the cube looks strange because the glow is treated as a transparent background and the outline don't align anymore.

**Comment by vasturiano** [comment]
@MarcelK28 `d3-force-3d` doesn't do any rendering and has no concept of how the nodes are represented. It's purely a functional force layout engine. The rendering is performed by `3d-force-graph` abstraction layer that includes all the ThreeJS functionality, following the layout of `d3-force-3d`.

Again, I'm sorry that I can't help you with using `CSS3DObject`, I'm just not familiar with it.

**Comment by MarcelK28** [comment]
Many thanks @vasturiano
