### ISSUE TITLE
How to provide custom color for one group nodes.

### ISSUE THREAD

**Issue by somu2324** [vasturiano/3d-force-graph#210]
**Is your feature request related to a problem? Please describe.**
I am using below two method for grouping the Nodes and link color
.nodeAutoColorBy('group')
.linkAutoColorBy(d => gData.nodes[d.source].group)

Above two methods auto pick color based on total number of group in my data set.

Can we provide custom color on bases on group by. If so then please let me know how to do this?

**Describe the solution you'd like**
should be void method with two argument ( group id and color) --> as a result this method will color all nodes of a group in one color.

**Describe alternatives you've considered**

**Additional context**

**Comment by vasturiano** [comment]
@somu2324 those two methods are only a convenience functionality around the regular `color` methods that set automatic colors. If you wish to assign specific colors I suggest you use `nodeColor` and `linkColor` directly. Something like:
```
.nodeColor(node => groupColors[node.groupId])
```
Assuming you have an object with group colors called `groupColors`.
