### ISSUE TITLE
How to display two different link between the two adjacent node.  

### ISSUE THREAD

**Issue by somu2324** [vasturiano/3d-force-graph#212]
**Is your feature request related to a problem? Please describe.**
I want to display two different link between the nodes which have same width but they are separated with some distance. 
for example my model data is as follows 

const nodes = [{id: 1},{id: 2}]
const links = [{source: 1, target: 2},{source: 1, target: 2}]
gData = {nodes, links}

**Describe the solution you'd like**
-
**Describe alternatives you've considered**
-
**Additional context**
-

**Comment by vasturiano** [comment]
@somu2324 you can use `linkCurvature` to separate them, like in this example:
https://vasturiano.github.io/3d-force-graph/example/curved-links/

**Comment by somu2324** [comment]
Hi @vasturiano 
I tried to run above link example but unfortunately I am not able to see any 3D graph. I am using same code as in example also I am using same data set as explain in example.
const Graph = window.ForceGraph3D()
    (document.getElementById('graph-3d'))
      .linkCurvature('curvature')
      .linkCurveRotation('rotation')
      .linkDirectionalParticles(2)
      .graphData(gData);

but this will not display any think.  attaching the screen shot.
<img width="1663" alt="Screen Shot 2019-07-27 at 1 55 44 PM" src="https://user-images.githubusercontent.com/52206615/61992025-41ea1480-b076-11e9-824c-587da91f4c47.png">

**Comment by vasturiano** [comment]
@somu2324 if you copy the code exactly, you have to make sure your data follows the same syntax. In this case, the links are probably missing the `curvature` and `rotation` attributes.
Make sure to set values for those.

**Comment by somu2324** [comment]
yes I've copy the code exactly.  I am facing below exception.

three-forcegraph.common.js:671 Uncaught TypeError: line.geometry.setFromPoints is not a function
    at three-forcegraph.common.js:671
    at Array.forEach (<anonymous>)
    at layoutTick (three-forcegraph.common.js:619)
    at Function.tickFrame (three-forcegraph.common.js:588)
    at Function.comp.<computed> [as tickFrame] (kapsule.common.js:147)
    at FromKapsule.<computed> [as tickFrame] (three-forcegraph.common.js:1200)
    at Function._animationCycle (3d-force-graph.common.js:242)
    at comp.<computed> (kapsule.common.js:147)

<img width="1663" alt="Screen Shot 2019-07-29 at 2 57 01 PM" src="https://user-images.githubusercontent.com/52206615/62037446-6c240980-b211-11e9-9e05-f1a89df08f57.png">

**Comment by vasturiano** [comment]
Do you get the error on this page? https://vasturiano.github.io/3d-force-graph/example/curved-links/

If not, please make a reduced CodePen example that reproduces your issue, so that it can be debugged further.

**Comment by somu2324** [comment]
no I am not getting any error when I hit your link but when I copy source code any try to run in my project then I am facing exception. I did not change anything in source code. dataset also I am using excaly same as source code.

**Comment by vasturiano** [comment]
@somu2324 it's difficult to say, without a reproducible example. Perhaps you can share an example on https://codesandbox.io .
