### ISSUE TITLE
Custom link geometry WITH appended geometry too.

### ISSUE THREAD

**Issue by nihiloss141** [vasturiano/3d-force-graph#213]
![image](https://user-images.githubusercontent.com/52888738/61296534-35420280-a7d2-11e9-8033-ef445c04741f.png)

![image](https://user-images.githubusercontent.com/52888738/61296543-38d58980-a7d2-11e9-8d7f-2b43b11f766f.png)

At present, it is possible to modify the link geometry or append to it, I was wondering if it would be possible to allow both at the same time? At present, I can change the geometry of the link to a cone, OR add a label to the link using SpriteText, but not both. It would also be helpful if the linkColor and linkWidth could work on custom geometries.

**Comment by vasturiano** [comment]
@nihiloss141 you can use the method `linkThreeObjectExtend` to specify that you wish to extend the default link object with additional visual objects.
