### ISSUE TITLE
Color of different nodes

### ISSUE THREAD

**Issue by bennie84** [vasturiano/3d-force-graph#215]
I dont have a issue but i'm not really clear about how i can give different nodes different colors. For example i have de node 'Games' as parent and ' Fun' as child node. When i'm using 

.nodeColor(d => d.type=="Games" ? '#4caf50' : '#f44336')

I get the different color for Games and Fun what is good. But when i'm try to change more nodes like 'Learn' and 'Progress' in de same query, every node takes on the color of 'Games' and 'Fun'.

So how do i change the color of more then 4 different nodes to my own choosing without using

.nodeAutoColorBy('label')?

Thank you in advance :)

**Comment by vasturiano** [comment]
@bennie84 that should just be a matter of setting your conditional logic to the way you want it to be.
Something like:
```
.nodeColor(d => {
  if (d.type === 'Games') {
    return '#4caf50';
  } else if (d.type === 'Fun') {
    return '#f44336';
  } else if (...) {
    ...
  } ...
})
```

**Comment by bennie84** [comment]
Thanks alot. Its works for me :)
