### ISSUE TITLE
Hierarchical (DAG), links connection, collabsible 

### ISSUE THREAD

**Issue by MarcelK28** [vasturiano/3d-force-graph#219]
Hi @vasturiano 

I have a case (image attached) where I need to be able to create links

- from A1 to A in the same level

- from D1 to A from the level3 to level 0

Is this something that I can do in the DAG mode and preserve the node's position in their levels?

Also, does your library support collapsible functionality like D3 does? [example](https://jsfiddle.net/bizamajig/emog04zo/)

Many thanks
![hierarchy](https://user-images.githubusercontent.com/1974707/62209372-5c333380-b391-11e9-9559-499b40aa28cd.png)

**Comment by vasturiano** [comment]
@MarcelK28 thanks for reaching out. Your image doesn't have info on the direction of links, so it's hard to say how the automatic DAG mode would handle it.
But, if you want to manipulate the levels manually, I would suggest trying to manipulate the `fy` node attribute, to force a node onto a different level than its designated place.

As for the collapse/expand node functionality, that is not directly offered as part of the library but can be implemented by the consumer using `onNodeClick(...)` events to manipulate the data passed to `graphData()`.

**Comment by MarcelK28** [comment]
@vasturiano many thanks for coming back to me. For now, the direction of links is not needed, however, I might need to implement them in the later stage. Any idea?

When you say to change `fy` of each node, what if I had 100’s of nodes?  will have to change them all manually one by one? And also let’s say that I change the position of the node, will the link be moved and follow the node automatically? (What does `fy` do as opposed to normal position `x,y,z`?)

As for the collapse, yes you’re right I might need to use `onNodeClick` which is actually fine.

Many thanks again

**Comment by MarcelK28** [comment]
@vasturiano it worked! Your tip changing `fy` really worked and the links do follow the nodes. Thank you :)

One more question, all my nodes are very close to each other, is there a way to spread them more without changing the distance of the link?

**Comment by vasturiano** [comment]
@MarcelK28 you can spread the nodes wider globally by increasing the strength of the global (`forceManyBody`) repelling force (called `charge`) among all nodes.

This following example does something along those lines:
https://github.com/vasturiano/3d-force-graph/blob/master/example/text-nodes/index.html#L36

**Comment by abhay8051** [comment]
@vasturiano , I tried to hard code fy , but on rendering they are changed to different values, how can i prevent that. Also I tried to pass fx and fz but they do not get recognized
