### ISSUE TITLE
Hide nodes based nodeVal and camera zoom

### ISSUE THREAD

**Issue by clarklai** [vasturiano/3d-force-graph#221]
Hi @vasturiano,

How might we hide certain nodes (and links) based on their nodeVal and the camera zoom?

I am trying to render a fairly large graph (>5K nodes) and want to prevent rendering of "less significant" nodes/links when zoomed out for performance and clarity reasons.

Many thanks for the awesome repo!

**Comment by vasturiano** [comment]
@clarklai thanks for reaching out.

You can control a node's visibility dynamically using the method: `.nodeVisibility(node => /* your code /*)`.

The `nodeVal` you can get directly from the node attribute. 

As for the current camera zoom level, you can attach an event to camera position changes using the trackball `controls` object. Something like:
```
Graph.controls()
  .addEventListener('change', ev => console.log(ev.target.object.position));
```

From there, you can apply your logic as to how camera position affects the visibility of certain nodes.
