### ISSUE TITLE
Highlight multiple nodes at a time 

### ISSUE THREAD

**Issue by nupurbiswas** [vasturiano/3d-force-graph#222]
**Is your feature request related to a problem? Please describe.**
This is not an issue, rather I am stuck with a problem and hence looking for help. I wish to highlight a group of nodes (not neighbors) at a time. The group will be chosen from a checkbox list in HTML. 
**Describe alternatives you've considered**
Part of the js code is here and it is not working. I am working with 3D-force-graph. 

`        var selectgroup= document.getElementById("checkbox").value; // looks like "node1-node2" `
`        fctselectgroup(selectgroup); `
`        function fctselectgroup(selectgroup){`
`        var grnodes=selectgroup.split("-");`
`        traverseHighlight(grnodes);`
`        };`

**Comment by vasturiano** [comment]
@nupurbiswas if you have a list of nodes you wish to highlight, you can just set your logic on the node styling to do a lookup on that list.

Like in this example:
https://github.com/vasturiano/3d-force-graph/blob/master/example/highlight/index.html#L30

**Comment by nupurbiswas** [comment]
@vasturiano I agree with you that I have put the logic. In the mentioned example, the function (containing the logic) for node highlighting is included within interaction `.onNodeHover`. I want to keep it outside `.onNodeHover`. So I created a function, `function fctselectgroup(selectgroup)` and it has the list of nodes in `grnodes`. My specific issue is how to highlight these `grnodes` using `traverseHighlight` and/or `highlightNodes`.

**Comment by vasturiano** [comment]
@nupurbiswas whenever you wish to update the highlighted nodes you can just call `.refresh()` on your graph. Assuming your `nodeColor` function knows how to determine the nodes to highlight from your local state.
