### ISSUE TITLE
How to access the JSON? Is there a list with all the objects that can be accessed?

### ISSUE THREAD

**Issue by EPurpl3** [vasturiano/3d-force-graph#225]
I have a JSON with links, nodes, cookies and i try to access the cookies.

**Comment by vasturiano** [comment]
@EPurpl3 if you're loading your data via `jsonUrl(...)` keep in mind that the library only extracts the `node` and `links` attributes. These you can access programmatically by calling the getter `.graphData()`.

If you need to load additional data for your project you should do it externally to this module.

**Comment by EPurpl3** [comment]
Hi, thanks for the answer. I have another question about the JSON, i am trying to create the nodes size based on it's connections (links target length and links source length). So i use this code:

		.graphData(jsonServit)
		.nodeVal(node => {
				let selectedName = node.id;
				arrayJsonLinks = jsonServit.links;
				let LinksArray1 = [];
				let LinksArray2 = [];
				let LinksArray3 = [];

				console.log(arrayJsonLinks); // returns the array correctly on refresh
				LinksArray1 = $.grep(arrayJsonLinks, function(link, index) {
                                        console.log(link.target.id); // undefined on refresh
					return link.target.id == selectedName; // returns 0 on refresh
				});

				LinksArray2 = $.grep(arrayJsonLinks, function(link, index) {
					return link.source.id == selectedName;
				});

				LinksArray3 = LinksArray1.concat(LinksArray2);

				console.log("1 "+LinksArray1.length); // returns 0 on refresh
				console.log("2 "+LinksArray2.length); // returns 0 on refresh
				console.log("3 "+LinksArray3.length); // returns 0 on refresh

				//++once;
				//console.log(once);
				return LinksArray3.length;
		})

The problem is that the jQuery.grep returns undefined on refresh but returns the correct values on hover on any node. Even though the array is correct and is loaded the grep jQuery.grep doesnt execute correctly. I have tried with setInterval and in many other ways but doesnt work. Is there any way to access the JSON with the chart API? maybe it will work. Or is there another way to to make the nodes resize based on it's links that come and go? maybe a more optimized way? The JSON used is the one with "The Miserables" characters. Thanks

**Comment by vasturiano** [comment]
@EPurpl3 an approach you can try is to pre-compute the number of links for each node, and add an attribute to each node with this computed value, say `numLinks`. Then, in your `nodeVal` you can simply do `.nodeVal('numLinks')`.

You should run this pre-computation before you feed the data to the charting library, i.e. `.graphData(jsonServit)`.

**Comment by EPurpl3** [comment]
Thanks. And how do i add attribute to each node?

**Comment by vasturiano** [comment]
@EPurpl3 glad it worked out!
You can't apply different resolutions for different nodes. The method's parameter should be a single number indicating the resolution to apply to every node. Like `.nodeResolution(6)`.

**Comment by EPurpl3** [comment]
Oh, i get it, now i have changed it like this:

	let optimizareBile;
	if(jsonServitX.nodes.length <= 250){
		optimizareBile = 10;
	} else if(jsonServitX.nodes.length > 250 && jsonServitX.nodes.length <= 750){
		optimizareBile = 8;
	} else if(jsonServitX.nodes.length > 750 && jsonServitX.nodes.length <= 1200){
		setTimeout(function(){
			$(".name-selector label:nth-child(1)").click();
		}, 50);
		optimizareBile = 6;
	} else if(jsonServitX.nodes.length > 1200){
		setTimeout(function(){
			$(".name-selector label:nth-child(1)").click();
		}, 50);
		optimizareBile = 4;
	}

with this `.nodeResolution(optimizareBile)`, it works perfect. Thank you very much.
