### ISSUE TITLE
Can this be used side-by-side with existing three.js code?

### ISSUE THREAD

**Issue by freder** [vasturiano/3d-force-graph#226]
hi,

is this library meant to be used as a standalone solution only? -- or can it be added to an already existing three.js scene, for instance?

thanks

**Comment by vasturiano** [comment]
@freder if you wish to integrate it with an existing `three` scene, you should look into [three-forcegraph](https://github.com/vasturiano/three-forcegraph).

**Comment by freder** [comment]
I see – thank you!
