### ISSUE TITLE
The sprites are regenerated over and over again on hover on nodes

### ISSUE THREAD

**Issue by EPurpl3** [vasturiano/3d-force-graph#229]
Hi, i have added the id of the node as nodeThreeObject sprites with this code:

	function generateTitle() {
		Graph.nodeThreeObject(
			node => {
				const sprite = new SpriteText(node.id);
				sprite.color = '#BFBFBF';
				sprite.textHeight = 5;
				sprite.center.x = -0.3;
				sprite.center.y = 0.7;
				console.log(sprite); // will trigger each time i hover on a node
				return sprite;
			}
		)
	}

The problem is when i hover on a node. I use this script for `.onNodeHover`:

    let highlightNodes = [];
    let highlightLink = null;
	
	function showThisLink(link, baseNode) {
		return link.source === baseNode || link.target === baseNode;
	}
	function showAllLink(link) {
		return link;
	}
	

        .onNodeHover(
			node => {
				if ((!node && !highlightNodes.length) || (highlightNodes.length === 1 && highlightNodes[0] === node)) return;
				elem.style.cursor = node ? 'pointer' : null;
				Graph.linkVisibility(link => showThisLink(link, node));
				highlightNodes = node ? [node] : [];

				if(!highlightNodes.length && highlightNodes.length === 0) {
					Graph.linkVisibility(link => showAllLink(link));
				}
			}
		)

The lines `Graph.linkVisibility(link => showThisLink(link, node));` and `Graph.linkVisibility(link => showAllLink(link));` will cause the chart to recreate nodeThreeObject sprites over and over again. 

Here is a working example: https://jsfiddle.net/EPurpl3/qoz5dj31/

Is there a way to solve this?

Thank you.

EDIT: i have tried everything, even to comment some parts of the code of the unminified plugin but with no success. Whenever the "sceneNeedsRepopulating" it recalculates each and every sprite and for 1000 nodes takes a long long LONG time. It is a really bad performance problem. How can i skip recalculating the sprites? Please  help. Thank you.

**Comment by vasturiano** [comment]
@EPurpl3 every method you call that requires an update to the objects in the scene will need to recompute the ThreeJS objects and therefore re-call the `nodeThreeObject` code. 

But, you could try pre-calculating all the sprite objects and simply return them in the `nodeThreeObject`.

For example, for each node beforehand:
```
node.forEach(node => {
  const sprite = node.ownSpriteObj  = new SpriteText(node.id);
  sprite.color = '#BFBFBF';
  sprite.textHeight = 5;
  sprite.center.x = -0.3;
  sprite.center.y = 0.7;
})
```

And then:
```
.nodeThreeObject(node => node.ownSpriteObj);
```

**Comment by EPurpl3** [comment]
Brilliant, it works. On 1200+ nodes there is still a bit of lag but still, it is a lot faster, incomparable. Thank you.
