### ISSUE TITLE
Camera mouvement

### ISSUE THREAD

**Issue by mhebrard** [vasturiano/3d-force-graph#23]
It could be nice to have access to the camera position.
Let say, when user click on one node, the camera pan at a certain distance of that node.

using onNodeClick(fn) we can trigger an event on click,
but there is no way (as far as I know) to modify the camera position programmatically.

**Comment by AmbroiseCouissin** [comment]
Yes, I'd like to have this feature as well. It can get very useful when the graph is getting bigger.
Cheers

**Comment by vasturiano** [comment]
@mhebrard @AmbroiseCouissin from `v1.22.0` this is now supported using `.cameraPosition({ x, y, z })`.

Here's an [example of usage](https://vasturiano.github.io/3d-force-graph/example/camera-auto-orbit/).

Let me know if this works for your use case.
