### ISSUE TITLE
Are there any instruments to search a root node, all child nodes etc?

### ISSUE THREAD

**Issue by benderlidze** [vasturiano/3d-force-graph#234]
Any built in or any other lib to search root node, all child nodes in "links"
```
{
            "nodes": [
                //{ "id": "itemIndustry", "group": 1 },
            ],
            "links": [
                //{ "source": "itemIndustry", "target": "itemClass", "value": 1 },
            ]
        }
```

**Comment by vasturiano** [comment]
@benderlidze this library doesn't offer any convenience graph traversal algorithm methods, it's focus is on representation. But there's possibly other libs out there that do this type of data manipulation.

**Comment by EPurpl3** [comment]
You can use grep to filter your JSON like this:

        // filter source
		let LinksArray = [];
        let linkedNodesArray = [];
        if (opt1 == 1 || opt2 == 1) {
		    LinksArray = $.grep(jsonServit.links, function(link) {
			    return link.source.id == selectedName;
		    });
		    linkedNodesArray = [].concat(SelectedNodeArray);
		    for(let i = 0; i < LinksArray.length; i++) {
			    linkedNodesArray = linkedNodesArray.concat(
                    $.grep(jsonServit.nodes, function(link) {
				        return link.id == LinksArray[i].target.id && link.id != LinksArray[i].source.id;
			        })
                );
		    }
		}


              //filter target
		let LinksArrayTarget = [];
        let linkedNodesArrayTarget = [];
        if (opt1 == 1 || opt3 == 1) {
		    LinksArrayTarget = $.grep(jsonServit.links, function(link) {
			    return link.target.id == selectedName;
		    });
            if (opt1 == 0) {
		        linkedNodesArrayTarget = [].concat(SelectedNodeArray);
            }

		    for(let i = 0; i < LinksArrayTarget.length; i++) {
			    linkedNodesArrayTarget = linkedNodesArrayTarget.concat(
                    $.grep(jsonServit.nodes, function(link) {
				        return link.id == LinksArrayTarget[i].source.id && link.id != LinksArrayTarget[i].target.id;
			        })
                );
		    }

		}

Than you can refresh the chart with the filtered data.
