### ISSUE TITLE
How to stop the inertia after move the graph with mouse 

### ISSUE THREAD

**Issue by benderlidze** [vasturiano/3d-force-graph#235]
When you move the graph with mouse there is some inertia/momentum after releasing the mouse button. Is there any way to switch it off? Thanks

**Comment by vasturiano** [comment]
@benderlidze you can configure the `trackball` controls behavior, like:
```myGraph.controls().staticMoving = true```
or 
``Graph.controls().dynamicDampingFactor = 1e-3```
