### ISSUE TITLE
Custom node geometries example not working with certain Materials

### ISSUE THREAD

**Issue by HansvdLaan** [vasturiano/3d-force-graph#236]
First of all, thank you very much for this awesome library! I've been playing around with it for the last couple of week and I'm having lots of fun building a small graph visualizer. 😄 

**Description:**

I'm trying to change the shape of my nodes as shown in the custom node geometries examples. Unfortunately, it seems this example is broken. While while trying out the example the library silently crashes and no graph is shown. 

I think it has something to do with the Materials. The example works when I don't specify a material for the meshes or when I use the MeshBasicMaterial. When I try to use MeshLambertMaterial (as in the example) or MeshPhongMaterial it doesn't work.

I have created a codesandbox which show this issue: [sandbox](https://codesandbox.io/s/tender-antonelli-tgm7d?fontsize=14).

**Comment by vasturiano** [comment]
@HansvdLaan the issue lies with the `three` imports. You should get the named imports from the module, instead of using the common JS `require`. Here's a fixed [sandbox](https://codesandbox.io/s/billowing-shape-2jcqd).

**Comment by HansvdLaan** [comment]
Thanks for the help. This fix didn't solve the issue for me completely however. Changing the imports in my own application still had it fail silently. 

The difference between my application and the example I posted is that I imported ForceGraph3D from "react-force-graph", not from "react-force-graph-3d". Changing my imports to obtain the graph from the latter solved the issue entirely. 

Is there a difference between the 2 versions? (([react-force-graph version](https://codesandbox.io/s/three-imports-react-force-graph-kgmr5))

**Comment by vasturiano** [comment]
@HansvdLaan there is no difference in the source code or functionality, it's just a different import method. However, in `react-force-graph` the other component variants are also available. 
In the VR variant it's also importing its own version of `threejs`, which should theoretically be tree-shaken out of the build if unused, but if not the `threejs` imports may conflict and cause some side-effects, which may be the root of the issue in this case.
In your case, it's recommended to use the isolated module `react-force-graph-3d` if you can.
