### ISSUE TITLE
Is it possible to change one node object on node click?

### ISSUE THREAD

**Issue by benderlidze** [vasturiano/3d-force-graph#239]
For example I want to change node object from circle to triangle on click on one exact node, all other should stay the same.
As I understand I should redraw ALL nodes, right?
Any way to change only one node as scene is too big.
Thanks
```
.onNodeClick(node => {
        
      });
```

**Comment by Alexithemia** [comment]
On my .onNodeClick I added the node.id to a variable (or array to select multiple), and included 
```
.nodeThreeObject((node) => node.id === selectedNode ? /* new three object */ : null)
```
or
```
.nodeThreeObject((node) => selectedNodes.includes(node.id) ? /* new three object */ : null)
```

Null returns the normal spheres, and when it matches being selected it will use a THREE object you create. You will need to import Three as well.

**Comment by benderlidze** [comment]
@Alexithemia could you help me here ?
https://jsfiddle.net/dp7rv0ga/2/

**Comment by Alexithemia** [comment]
@benderlidze you would need to put your original starting node geometry instead of null. For optimization it is best to have one pre-rendered, at least the geometry, then put it into a mesh there. with your specified color material.

```
const defaultGeo = new IcosahedronGeometry(5, 0);
const selectedGeo = newConeGeometry(5, 5, 3);
myGraph.nodeThreeObject((node) => handleNodeGeometries(node));

handleNodeGeometries(node) {
    const color = handleColor(node) //handle color selection here;
    const material = new THREE.meshPhongMaterial({ color: color});
    if(node.id === selected) {
        return new THREE.mesh(selectedGeo, material);
    }
    return new THREE.mesh(defaultGeo, material);
}
```
