### ISSUE TITLE
Create a link with no force or not change node DAG mode level

### ISSUE THREAD

**Issue by Alexithemia** [vasturiano/3d-force-graph#240]
On my graph I have nodes with children, following your expanding graph structure, but I also will have relationship link showing between some nodes on the same level. 

These relationship links are moving nodes that should be on the same level, down a level in DAG mode layouts.

Maybe a manual way to set DAG mode levels for the nodes so they don't move?

I'm guessing I may have to create mock DAG modes manually since I cannot have circular links?

Any recommendation?

**Comment by vasturiano** [comment]
If you have links connecting siblings in your hierarchy it's possible that your data structure is not a DAG, and therefore will not be able to represent it as such. In DAG mode it's assumed that every link relationship is hierarchical.
