### ISSUE TITLE
Add support for link object accessor function to linkOpacity

### ISSUE THREAD

**Issue by HansvdLaan** [vasturiano/3d-force-graph#242]
LinkOpacity is one of the few methods which expects a getter/setter instead of a link object accessor function. In my opinion, being able to set the opacity of individual edges could be an interesting feature.

An use case would be to use opacity as an indicator of how "important" a link is in your current view. This would allow the user to more easily focus on the links which matter, and reduce clutter on the screen more efficiently than using color, size, etc.

**Comment by HansvdLaan** [comment]
Ofcourse, it would also be interesting to extend this functionality to node opacity.

**Comment by vasturiano** [comment]
@HansvdLaan it's possible to set different opacities per link (or node) by using an alpha channel syntax, like `nodeColor(node => 'rgba(255, 0, 0, 0.7)')`.

This is why the `linkOpacity` prop is more of a global value that applies to all the links equally, after the individual color opacities have been applied. It's also used for caching and reusing object materials to improve with performance and memory management, so less cardinality is better.
