### ISSUE TITLE
Disable specific node

### ISSUE THREAD

**Issue by EPurpl3** [vasturiano/3d-force-graph#244]
**Is your feature request related to a problem? Please describe.**
I have to filter some nodes.

**Describe the solution you'd like**
The easiest way would be to be able to disable the nodes from JSON, with jQuery Grep. To search with grep the ID or the color that you want to disable and to add a key named "disabled" true of false.

**Describe alternatives you've considered**
To move the object in JSON from "nodes" to "disabledNodes".

**Additional context**
I know that this amazing library was not made to sort/filter/create/manipulate JSON's, it just draws the bubbles but would be nice if it would've had some extra features by default to be able to filter JSON's.

**Comment by Alexithemia** [comment]
Probably best to actually have a disabled node array. Push the ID of the nodes you want disabled into the array.

Then there are two ways you can hide them. Either not graph them at all, which could cause some force issues with things being unlinked, or you can turn them invisible.

To not graph them at all you would need to filter the nodes and links before they are passed to the .graphData function.
```
myGraph.graphData(filterData());

filterData() => {
    const visibleNodes = [];
    const visibleLinks = [];
    nodeList.map(node => {
        if (disabledArray.includes(node.id)) {
             return;
        }
        visibleNodes.push(node);
    }
    linkList.map(link => {
       if(disabledArray.includes(link.source.id) || disabledArray.includes(link.target.id)) {
            return;
       }
       visibleLinks.push(link);
    }
    return { nodes: visibleNodes, links: visibleLinks };
}
```

It would be easier to just turn them invisible.
```
myGraph.nodeVisibility(node => disabledArray.includes(node.id) ? false : true)
    .linkVisibility(link=> disabledArray.includes(link.source.id) || disabledArray.includes(link.source.id) ? false : true)
```

**Comment by EPurpl3** [comment]
Than you, this looks great, i will test it today.

**Comment by EPurpl3** [comment]
It is working great. As i have already used my own way to select the objects that will have to be disable, before i have read your message, i have only used the part to make the nodes invisible.

Works amazing, thank you very much.
