### ISSUE TITLE
Links are not visible in transparent parts of sprites

### ISSUE THREAD

**Issue by Alexithemia** [vasturiano/3d-force-graph#248]
In the picture below you can see the issue I am referring to. If the image or sprite you are using for a node has transparency the line of the link is covered up, but not the arrow. I would like to be able to see the link in that transparent section.

![image](https://user-images.githubusercontent.com/44597137/67700980-103a5f80-f97d-11e9-845f-64d6a60f8763.png)

This specific example uses crates a canvas, draws according to set rules, then uses the canvas as a texture for a sprite. The canvas background is transparent, as you can see the other nodes in those areas as well as the arrows of the links, but not the actual link lines.

**Comment by EPurpl3** [comment]
You can try to disable the depth test like this: `Graph.renderer().context.disable(Graph.renderer().context.DEPTH_TEST)` where "Graph" is your chart (const Graph = ForceGraph3D()(document.getElementById('3d-graph')).graphData(gData).........).

**Comment by Alexithemia** [comment]
Unfortunately that puts all links drawn over all nodes, even the non-transparent part of the sprite. So even the links that would be behind the nodes in the picture above are drawn on top.
