### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by mhebrard** [vasturiano/3d-force-graph#25]
It could be nice to be able to take a screenshot of the view.

I tested with
```
$('canvas')[0].toDataURL("image/png");
```
but the canvas is empty.

If I understand well, we need to access the renderer and convert it to png
```
renderer.domElement.toDataURL()
```

see an example there:
https://stackoverflow.com/questions/40444995/how-to-convert-render-from-three-js-to-png-file

It would me nice to have this kind of feature in 3d-force-graph, something like 
```
myGraph.screenshot()
```
With maybe an option for new background color, or transparent background (is that too much? ^.^")

**Comment by vasturiano** [comment]
@mhebrard `renderer.domElement` simply returns the canvas DOM element, so assuming you're getting the canvas element that is controlled by 3d-force-graph with `$('canvas')[0]`, the two instructions should actually be equivalent.

If you're getting an empty image, could it be a timing issue? You'd need to wait until the objects are actually rendered on the canvas before taking the png screenshot.

The background color/transparency can already be set by doing something like: `.backgroundColor('rgba(0,0,0,0)')`.

Let me know if you're able to get it working.

**Comment by mhebrard** [comment]
Oh I see...
Thanks for the reply... I will test that and let you know

**Comment by AABoyles** [comment]
I just spent a ton of time on this, and I think I've got a working hack.
```js
var a, downloads = 0;

//This can be any event. I've got an export button:
$('#3d_network_export').click(function(){
  downloads = 0;
  //Calling this kicks off a loop that repeatedly calls the passed function.
  a = requestAnimationFrame(download);
});

function download(){
  //So we don't call this function a bunch of times, let's cancel the loop after the first
  if(downloads){
    cancelAnimationFrame(a);
  } else {
    //Obviously, you should swap this out for a selector that gets only the 3D graph
    $('#3d-network canvas')[0].toBlob(function(blob){
      //Powered by [FileSaver](https://github.com/eligrey/FileSaver.js/)
      saveAs(blob, 'a.png');
    });
  }
}
```
This _cannot_ be the right way to accomplish this, but it seems to work.

**Comment by nupurbiswas** [comment]
@AABoyles It is not working for me. It shows console error 
Uncaught TypeError: $(...)[0].toBlob is not a function at download

**Comment by AABoyles** [comment]
@nupurbiswas Just sanity checking, here--is your selector (the `...` in your console error) actually selecting a canvas? [toBlob](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) is a method of canvas elements.

**Comment by nupurbiswas** [comment]
@AABoyles I have used your code and here it is. It is not working for me.

      <div id="3d-graph" ></div>
     <script>
     const elem = document.getElementById('3d-graph');
     const Graph = ForceGraph3D()(elem)
     .width(300)
     .height(300)
     .backgroundColor('grey')
      .jsonUrl('blocks.json')
      </script>
      <div id="savebutton" ><button>Save graph as png </button</div>
     <script>
      var a, downloads = 0;
       $('#savebutton').click(function(){
      downloads = 0;
       a = requestAnimationFrame(download);
     });

    function download(){
     if(downloads){
     cancelAnimationFrame(a);
     } else {
     $('#3d-graph')[0].toBlob(function(blob){
        console.log(blob);      
      saveAs(blob, 'a.png');
       });
     }
     }
     </script>

**Comment by AABoyles** [comment]
Right, you code *isn't* selecting a canvas. Change `download` to this:

```javascript
function download(){
  if(downloads){
    cancelAnimationFrame(a);
  } else {
    $('#3d-graph canvas')[0].toBlob(function(blob){ //See? Select a canvas, not the div that wraps it.
      console.log(blob);
      saveAs(blob, 'a.png');
    });
  }
}
```

**Comment by nupurbiswas** [comment]
@AABoyles Thanks a lot for pointing out my mistake. It is working now. Thanks again.

**Comment by icodeajk** [comment]
requestanimationFrame is useful
