### ISSUE TITLE
`text-nodes` handle issue in `graphData` update

### ISSUE THREAD

**Issue by bboyseiok** [vasturiano/3d-force-graph#252]
**Describe the bug**
unexpected handle issue with `text-nodes` example when nodes are added dynamically or scene is updated.

**To Reproduce**
Using current version : 
https://unpkg.com/three-spritetext@1.2.0/dist/three-spritetext.min.js
https://unpkg.com/three@0.110.0/build/three.js
https://unpkg.com/3d-force-graph@1.56.4/dist/3d-force-graph.min.js

1. Go to `text-nodes` example, and open debugger console.
2. Running `Graph.graphData(Graph.graphData())` gives unexpected behavior:
![force_graph_3d_issue2](https://user-images.githubusercontent.com/31088908/69225448-c6cae200-0bc1-11ea-8769-9494c9f593a1.JPG)
where it shows the handles to be visible.
3. running `Graph.nodeColor(node => 'transparent')` gives the void instead of transparency:
![force_graph_3d_issue3](https://user-images.githubusercontent.com/31088908/69225580-f7128080-0bc1-11ea-9e42-4cd2728dda45.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome

**Additional context**
Running `Graph.graphData` to update graph info would be necessary if one wants to modify text nodes. If adding handles with `SphereGeometry` is the supported way to work with text-sprites, then I feel there should be way to add text nodes dynamically and so. 

I tried setting sprite object as the root object (instead of the way shown in the `text-nodes` example where `SphereGeometry` is given as the root THREE object.) results in the nodes being invisible, so I am struggling with the issue right now. Maybe it's related to the updateObj function or something like that.

**Comment by Alexithemia** [comment]
Run Graph.refresh() after.

Alternatively you don't really event need the sphere geometry inside the .nodeThreeObject, just making the mesh out of the sprite works.

**Comment by bboyseiok** [comment]
> Run Graph.refresh() after.
> 
> Alternatively you don't really event need the sphere geometry inside the .nodeThreeObject, just making the mesh out of the sprite works.

Wow it worked like a charm. thanks!
