### ISSUE TITLE
Various problems/questions

### ISSUE THREAD

**Issue by fabisch30** [vasturiano/3d-force-graph#254]
Hello everyone,

I now been working with 3d-force-graph about 4 weeks. It makes really a lot of fun and is way better then most of the other tools I used for graph visualisation.

During that time I came up with some problems/questions. Hopefully you can help me:

1. I could not get the information about source or target after I clicked on an link and don`t know why (maybe not possible?).

`.onLinkClick( link => window.alert(link.source) )`

Would be the easiest way to explain it.

2. I could not manage to implement to change .enableNodeDrag after you click on an button. 

```
function func() {
  var checkBox = document.getElementById("checkBox1");
  if (checkBox1.checked == true){
    Graph.enableNodeDrag(false);   
  } else {
    Graph.enableNodeDrag(true);
  }
}
```
The function func will be executed after you clicked on an checkbox.

3. Is it correct that if you import your data with .jsonimport() you can not make any changes on the graph. For example change color of the node you clicked on. I made that experience.

4. Is there a way to change the distance between the nodes, I saw your example but this Graph.distance() did not worked properly and you dont find it in the list of all functions you gave.

5. The color of my nodes is auto colored with .autoColoredby(). However, it seems not to be possible to change the color of the node you clicked on, and then apply  .autoColoredby(). again. So how should a handle that?

**Comment by Alexithemia** [comment]
After making any changes to the 3d graph setup, adding dragging, changing colors etc you need to run graph.refresh().

**Comment by fabisch30** [comment]
Hi Alexithemia,

thank you for your answer. So far I didn`t need that Graph.refresh() (and did not know this existed). But this really could solve most of the problems I had. I will try that out the next days. Thank you very much!

**Comment by fabisch30** [comment]
Also, i came up with an 6 question:

6. Is it possible to change the color of the Navigation Infos at the bottom?

**Comment by Alexithemia** [comment]
4. Graph.distance is not a thing. In his [example](https://github.com/vasturiano/3d-force-graph/blob/master/example/manipulate-link-force/index.html) he uses graph.d3Force('link').distance();

6. Unfortunately not. You can edit the library and make a PR though, should be a simple addition.

**Comment by fabisch30** [comment]
Again thank you Alexithemia. I will try out graph.d3Force('link').distance(); the next days.

Thank you so much for your help!

**Comment by vasturiano** [comment]
For # 6, you can override the css in your app. The existing styling is defined on this file: https://github.com/vasturiano/3d-force-graph/blob/master/src/3d-force-graph.css

**Comment by vasturiano** [comment]
# 5: the `autoColorBy` methods only have an effect on objects that don't have a defined color. It's just a convenience method but you don't have to use it. In any case, if you wish to reset the node/link's color state, you can just set it back to `null` or `undefined`, this will cause the automatic color to apply again.

**Comment by vasturiano** [comment]
3.  You should be able to make any configuration updates to the component, regardless of whether you load your data via `.graphData` or `.jsonUrl`.

**Comment by vasturiano** [comment]
1. and 2. it's difficult to say without a reproducing example. Likely the issue lies outside the code segments you posted. Could you please do a minimal  [codepen](https://codepen.io/) highlighting each issue?

**Comment by fabisch30** [comment]
Thank you vasturiano!
I will try to solve the problems by myself after your and Alexithemia`s help here. If i`m not able to I will post a more precisely code slice here. Thank you!

**Comment by fabisch30** [comment]
So problems 2 and 3 are solved. Thank you!

**Comment by fabisch30** [comment]
Lets start with 1:

Heres my code:
```

<html>
<head>

<script src="https://unpkg.com/3d-force-graph/dist/3d-force-graph.min.js"> </script> 

</head>
	
<div id='graph_container'> </div>

<script>

var gData = {
    "nodes": [
        {
          "id": "id1",
          "name": "name1",
          "value": 10
        },
        {
          "id": "id2",
          "name": "name2",
          "value": 10
        },
        {
          "id": "id3",
          "name": "name3",
          "value": 10
        },
        {
          "id": "id4",
          "name": "name2",
          "value": 10
        },
        {
          "id": "id5",
          "name": "name1",
          "value": 10
        }
    ],
    "links": [
        {
            "source": "id1",
            "target": "id2"
        },
        {
            "source": "id1",
            "target": "id3"
        },
        {
            "source": "id1",
            "target": "id4"
        },
        {
            "source": "id4",
            "target": "id5"
        },
        {
            "source": "id3",
            "target": "id2"
        }
    ]
}

var Graph = ForceGraph3D()(document.getElementById('graph_container'))
            .graphData(gData)
            .width(1505)
            .height(550)
            .backgroundColor("grey")
            
            .linkColor(link => 'black')
            .linkWidth(link => 3)
            .linkOpacity(1)            
           
            .onLinkClick(link => window.alert(link.target));

</script>
</body>
</html>
```

I hope this is enough. If theres a better way to show my code to you let me know. I am new to this so I dont have used codepen.

**Comment by fabisch30** [comment]
5 would be the most important thing to solve:

Heres my code for that:

```
<html>
<head>

<script src="https://unpkg.com/3d-force-graph/dist/3d-force-graph.min.js"> </script> 

</head>
	
<div id='graph_container'> </div>

<script>

var gData = {
    "nodes": [
        {
          "id": "id1",
          "name": "name1"
        },
        {
          "id": "id2",
          "name": "name2"
        },
        {
          "id": "id3",
          "name": "name3"
        },
        {
          "id": "id4",
          "name": "name2"
        },
        {
          "id": "id5",
          "name": "name1"
        }
    ],
    "links": [
        {
            "source": "id1",
            "target": "id2"
        },
        {
            "source": "id1",
            "target": "id3"
        },
        {
            "source": "id1",
            "target": "id4"
        },
        {
            "source": "id4",
            "target": "id5"
        },
        {
            "source": "id3",
            "target": "id2"
        }
    ]
}

var Graph = ForceGraph3D()(document.getElementById('graph_container'))
            .graphData(gData)
            .width(1505)
            .height(550)
            .backgroundColor("grey")

            .nodeAutoColorBy('name')
            
            .onBackgroundClick(() => Graph.nodeColor(node => undefined))
            
            .onNodeClick(node1 => Graph.nodeColor(node2 => (node1.id == node2.id) ? "black" : undefined));

</script>
</body>
</html>
```
What i want:

Click on an node and the color of that node changes. 
Click on the background and the color should reset to the original colors (the autoColoredbyGroup).

**Comment by fabisch30** [comment]
Regarding 3, a new problem just came up.
Lets say I want to do something like that:

```
gData.links.forEach(link => { function() })
```

This worked fine while I was importing my data with `.graphData(gData)`. But since i use `.jsonUrl('../jsonimport3.json')`, gData is no longer defined, so how should I approach that.

**Comment by vasturiano** [comment]
1  - `link.target` points to a node object, so you probably want to do `window.alert(link.target.name)`.

3 - You can get the graph data by calling `myGraph.graphData()` (without any arguments).

5 - You can get there by setting specific color attributes on your nodes, like:
```
    .onBackgroundClick(() => Graph.nodeColor(''))

    .onNodeClick(node1 => {
      gData.nodes.forEach(node2 => node2.color = (node1.id == node2.id) ? "black" : undefined)
      Graph.nodeColor('color');
    });
```

**Comment by fabisch30** [comment]
@vasturiano : THANK YOU! Seems like all those things work as they supposed to do now.

And I think I even solved the distance thing by myself (after looking closer into your example :) ).

One last question remains:

I could not change the Navigation Colors. I did the following:

I saved the file

`<script src="https://unpkg.com/3d-force-graph/dist/3d-force-graph.min.js"> </script> 
`
in my directory and changed the part

```
graph-info-msg {
  top: 50%;
  width: 100%;
  text-align: center;
  color: lavender;
  opacity: 0.7;
  font-size: 22px;
  position: absolute;
  font-family: Sans-serif;
}


```

into


```
graph-info-msg {
  top: 50%;
  width: 100%;
  text-align: center;
  color: black;
  opacity: 0.7;
  font-size: 22px;
  position: absolute;
  font-family: Sans-serif;
}
```


It does not work. Do you have another approach for that. I dont understand what you mean with 

> override the css in your app 

Thank you for your help!

**Comment by fabisch30** [comment]
7. I am sorry but i have another question...how do I changed the zooming speed.
Is it even possible to adjust that?

**Comment by vasturiano** [comment]
@fabisch30 nice you were able to get it working.

As for the CSS you can just create a CSS rule in your app that overrides the existing styling, like:
```
.graph-info-msg {
  color: black !important;
}
```

For 7, you can control the zoom speed and other parameters by manipulating the controller. F.e.
```
myGraph.controls().zoomSpeed = 3;
```

See more info here: https://threejs.org/docs/#examples/en/controls/TrackballControls

**Comment by fabisch30** [comment]
@vasturiano : again thank you so much! I figured out the zooming thing, but was not able to change the color of the navigation info.
Here`s one simple example, where the color does not change. Probably missing one simple argument.

```
<html>
<head>

<script src="https://unpkg.com/3d-force-graph/dist/3d-force-graph.min.js"> </script> 

<style>

.graph-info-msg {
  color: white !important;
}

</style>

</head>
	
<div id='graph_container'> </div>

<script>

var gData = {
    "nodes": [
        {
          "id": "id1"
        },
        {
          "id": "id2"
        }
    ],
    "links": [
        {
            "source": "id1",
            "target": "id2"
        }
    ]
}

var Graph = ForceGraph3D()(document.getElementById('graph_container'))
            .graphData(gData);

</script>
</body>
</html>
```

**8**. And also while I was reading [https://threejs.org/docs/#examples/en/controls/TrackballControls](url) I thought it should be possible to change the .maxDistance. Because right now, the zooming in with the mouse stops at some point. You can not fly straight from one side TROUGH the graph to the other side. It stops (approximately in the middle). I thought `Graph.controls().maxDistance = Infinity` would solve that, but it didn`t:

For example I added in your example [https://github.com/vasturiano/3d-force-graph/blob/master/example/large-graph/index.html](url) simply at the end `Graph.controls().maxDistance = Infinity`. But it didn`t work. Still stops in the middle.

**Comment by vasturiano** [comment]
6 - Sorry I gave you the wrong classname, it should be:
```
.scene-nav-info { color: white !important; }
```

8 - I think `maxDistance` is meant to define the distance away from the center of the chart. With those controls you will not be able to cut through the center of the chart. For that purpose you might want to try the `controlType: 'fly'` initialisation option. Here's an example: https://vasturiano.github.io/3d-force-graph/example/controls-fly/

(use wasd and arrow keys to navigate)

**Comment by fabisch30** [comment]
@vasturiano : thank you!!!

Do you see another way of doing that while keeping `controlType: _trackball_` ?? Because _fly _controls__ I don`t like for the use of my graph.

**Comment by vasturiano** [comment]
@fabisch30 the controls that are available with `threejs` are listed here: https://github.com/mrdoob/three.js/tree/master/examples/js/controls

As far as I know there are none in which it's possible to rotate the graph but still be able to cut through the center.

**Comment by fabisch30** [comment]
OK! I will take a look at some of the other controls.

@vasturiano : Thank you soo much for all your help. It was really helpful. I will continue to work with this library.
