### ISSUE TITLE
Various problems/questions 2

### ISSUE THREAD

**Issue by fabisch30** [vasturiano/3d-force-graph#256]
Hi, it`s me again...came up with some new questions and hope you can help me the same way you did in the first place:

**1.** Can I get all the other attributes of an node, if i just have the id of that node. Like 
`nodeID("123").name` gets me the name of the node with the id "123". What i do is the following, but that`s of course not optimal:

```
Graph.graphData().nodes.forEach(node => {
    if (node.id == inputID){
        nodeName = node.name;
    }
})  


// So inputID would be "123" and it returns nodeName, the name of that node with id equal to "123".
```

**2.** I changed the distance of the link and because of that, the node are now to close :) Any possibility of changing the node distance? Attached goes a screenshot and i hope you understand what i mean:

![graph](https://user-images.githubusercontent.com/58147719/70624053-aec60b80-1c1f-11ea-8b78-4cd2121448fd.PNG)

This i have for changing the link distance:

```
Graph
  .d3Force('link')
  .distance(link => 4000);
```

**Comment by Alexithemia** [comment]
1. The set of data sent into the graph is edited by the graph and will include all the data you get using your method.
So Example 
```
const data = {
  nodes: [ { id: '1' }, { id: '2' }, { id: '3' } ],
  links: [...]
};

myChart.graphData(data);
```
You could 
```
const findNode = (id) => {
  return data.nodes.find(node => node.id === id)
}
```
This is still a loop to find it in the array, but you could always create a map out of all the nodes/links in data after you add one or they are all graphed.

2. You will need to increase manyBody force to have them repel eachother, or you could add/increase their collision force.

**Comment by fabisch30** [comment]
@Alexithemia : thank you for your quick answer.

Could you be so kind and give a little example code. Because with the documentation i found regarding _manyBody force_, i was not able to do it. Thank you.

**Comment by Alexithemia** [comment]
https://github.com/d3/d3-force#forceManyBody
```
myChart.d3Force('charge', d3.forceManyBody().strength(-30));
```
you will have to bring in that package for d3-force, more negative for higher repel strength, positive for attraction.

**Comment by fabisch30** [comment]
@Alexithemia : I very much appreciate your help here, but still i`m not able to do it. I downloaded some packages (probably missing still some) and add your code line above. But does not work. Here goes a little example:
```

<html>
<head>

<script src="https://unpkg.com/3d-force-graph/dist/3d-force-graph.min.js"> </script> 

<script src="https://d3js.org/d3-quadtree.v1.min.js"></script> 
<script src="https://d3js.org/d3-dispatch.v1.min.js"></script> 
<script src="https://d3js.org/d3-timer.v1.min.js"></script> 
<script src="https://d3js.org/d3-force.v2.min.js"></script> 
<script src="https://raw.githubusercontent.com/d3/d3-force/master/src/constant.js"></script>
<script src="https://raw.githubusercontent.com/d3/d3-force/master/src/jiggle.js"></script>
<script src="https://raw.githubusercontent.com/d3/d3-force/master/src/simulation.js"></script>
<script src="https://d3js.org/d3-quadtree.v1.min.js"></script>
<script src="https://d3js.org/d3-dispatch.v1.min.js"></script>
<script src="https://d3js.org/d3-timer.v1.min.js"></script>

</head>

<div id='graph_container'> </div>

<script>

var gData = {
    "nodes": [
        {
          "id": "id1",
          "name": "name1"
        },
        {
          "id": "id2",
          "name": "name2"
        },
        {
          "id": "id3",
          "name": "name3"
        },
        {
          "id": "id4",
          "name": "name2"
        },
        {
          "id": "id5",
          "name": "name1"
        }
    ],
    "links": [
        {
            "source": "id1",
            "target": "id2"
        },
        {
            "source": "id1",
            "target": "id3"
        },
        {
            "source": "id1",
            "target": "id4"
        },
        {
            "source": "id4",
            "target": "id5"
        },
        {
            "source": "id3",
            "target": "id2"
        }
    ]
}

var Graph = ForceGraph3D()(document.getElementById('graph_container'))
    .graphData(gData)

Graph
  .d3Force('link')
  .distance(link => 400)

  .d3Force('charge', d3.forceManyBody().strength(-300)); //this right here changes nothing

</script>
</body>
</html>
```

**Comment by vasturiano** [comment]
@fabisch30 keep in mind that you shouldn't chain multiple calls to `.d3Force` since they return values different than the main Graph object. It's better to do this instead:
```
  Graph.d3Force('link').distance(link => 400);
  Graph.d3Force('charge').strength(-300);
```

**Comment by fabisch30** [comment]
@vasturiano : again, thank you so much for your help...it works after your advice perfectly on this little example and hopefully tomorrow with my real graph. Thanks a lot!
