### ISSUE TITLE
Transparent sections of Text/Canvas/Sprite nodes cover Links

### ISSUE THREAD

**Issue by Alexithemia** [vasturiano/3d-force-graph#257]
In the picture below you can see the issue I am referring to. I am using a canvas object that is being drawn with transparency but the line of the links is covered up in the transparent section, but not the link's arrow or other nodes. I would like to be able to see the link in that transparent section. This also Happens with your text as nodes example and likely would with the sprite example, but those are square images anyway.

![image](https://user-images.githubusercontent.com/44597137/70628480-dac89900-1bed-11ea-9932-eac37172060e.png)

This specific example uses crates a canvas, draws according to set rules, then uses the canvas as a texture for a sprite. The canvas background is transparent, as you can see the other nodes in those areas as well as the arrows of the links, but not the actual link lines.

**Comment by mbusbyHub** [comment]
I'm experiencing the same issue. If I change the link material with something like
`.linkMaterial(link => {
        return new THREE.MeshBasicMaterial({});
      })`

then the issue no longer exists, but now the linkColor function isn't setting the color of my links properly.

**Comment by Alexithemia** [comment]
@mbusbyHub Thats great if that works, you would need to color the material provided instead now though.
