### ISSUE TITLE
 (document.getElementById('3d-graph'))

### ISSUE THREAD

**Issue by coderofsalvation** [vasturiano/3d-force-graph#259]
Can you explain something?

document.getElementById('3d-graph').nodeThreeObject      // does not exist

(document.getElementById('3d-graph')).nodeThreeObject    // now exist

**Comment by vasturiano** [comment]
@coderofsalvation `nodeThreeObject` is a method of the `3d-force-graph` object, not a DOM node object. So version 1 doesn't make much sense. Version 2 also wouldn't work, unless it's prefixed by an instantiation of the `3d-force-graph` object, like:
```
ForceGraph3D()
  (document.getElementById('3d-graph'))
  .nodeThreeObject(...)
```

**Comment by coderofsalvation** [comment]
aaah wait now I see.. :)
I didn't realize the ForceGraph3D-function was returning a function.
The 'graph' inside my brain probably lost its force when I wrote that issue ;)
