### ISSUE TITLE
Dynamic reloading of graph without reloading everything

### ISSUE THREAD

**Issue by AmbroiseCouissin** [vasturiano/3d-force-graph#26]
Hi @vasturiano,

Is it possible to change the initial data without reloading everything with Graph.graphData({ nodes, links });?

Thanks,

**Comment by vasturiano** [comment]
@AmbroiseCouissin the only method currently to load data directly onto the component is `graphData`. But, the method can also be used to apply incremental data updates. Here's a dynamic example of that:
https://vasturiano.github.io/3d-force-graph/example/dynamic/
