### ISSUE TITLE
Retrieve the neighborhood of a node.

### ISSUE THREAD

**Issue by LeMoussel** [vasturiano/3d-force-graph#261]
How to retrieve the neighborhood of a node?

For example, with `Sigma.js`, there is a [sigma.plugins.neighborhood](https://github.com/jacomyal/sigma.js/tree/master/plugins/sigma.plugins.neighborhoods#sigmapluginsneighborhood) (a method)  that you can query to retrieve neighborhoods.

It's useful to provide a neighborhoods navigation inside a big graph instead of just displaying it.

**Comment by vasturiano** [comment]
@LeMoussel thanks for reaching out. Graph traversal algorithms and processing is really outside of the scope of this module. 
But you can always use another lib to handle that for you, for example [graphlib](https://github.com/dagrejs/graphlib/wiki).
