### ISSUE TITLE
Display label next to nodes?

### ISSUE THREAD

**Issue by maxcorbeau** [vasturiano/3d-force-graph#266]
Hi there,
I was looking at the doc for an option to add node labels next to the circles, similarly to:
https://bl.ocks.org/mapio/53fed7d84cd1812d6a6639ed7aa83868

All I found was unrelated:

- **nodeLabel**: decide what value to use as node label
- **linkLabel**: decide what value to use as link label
- https://vasturiano.github.io/3d-force-graph/example/text-nodes/: replaces circles with labels

**Is there an option to set node labels next to the node circles? If not can one be added please**

**Comment by vasturiano** [comment]
@maxcorbeau you can set `nodeThreeObjectExtend(true)` to maintain the default spheres while adding the text.

A bigger challenge is how to dynamically offset the nodes' labels themselves to minimize overlapping. The example you posted above uses a force repelling strategy among all the labels. That functionality could similarly be implemented consumer side using [d3-force-3d](https://github.com/vasturiano/d3-force-3d) (`d3-force` ported to a 3 dimensional system). 
It's not trivial, but it's possible!

**Comment by maxcorbeau** [comment]
I see, thanks
