### ISSUE TITLE
Export ability to stop animation

### ISSUE THREAD

**Issue by ChRonX13** [vasturiano/3d-force-graph#27]
Many thanks to your work on this great library! :)

Was hoping if it would be possible to expose out a method/callback/property so that one can issue a request to stop the animation. This would be useful when navigating away from the graph to another page, as currently this just keeps on ticking and chews up CPU cycles even though the graph is no longer on the screen.

Normally this would be done by issuing the following call:
`window.cancelAnimationFrame(requestID);`

**Comment by sharkaev** [comment]
same issue. I have over 1 biilion nodes. and it's difficult to render first animation.
P.S. Your web component is awesome!

**Comment by ChRonX13** [comment]
@vasturiano apologies if my terminology are incorrect! I guess I'm not referring to the 'simulation' engine itself...in fact, I'm already using those above parameters to freeze the visualisation at a given period of time. What I have found is that even though once the graph has finished 'settling', there is still a large number of requests from the `requestAnimationFrame(animate);` call. 

Now in the scenario where we do have a large number of visual elements on the screen, the amount of processing time to re-render the visualisation can drastically slow down (depending on hardware). In my particular scenario, even when I navigate away from the current canvas to another part of my application, these animation frame callbacks are still occurring, even with the visualisation not actually on the screen anymore. This below image is a profile after the visualisation has loaded but after I have navigated to another page in my application.

![Profile](https://i.imgur.com/ydUzh9Y.png)

My current workaround has been to execute the following logic upon navigation away from the visualisation given that I do not have a reference `animate` object that you  used when requesting the original animation.

`
    for (var i = 1; i < 99999; i++) {
      window.cancelAnimationFrame(i);
    }
`

My hope, if you agree, was that we could programatically get a handle or a binding to allow us to request a stop of this animation for various scenarios (eg. page navigation, if modals were overlayed on top of the visualisation to display other information etc).

Hope that makes sense!

Once again, many thanks for your efforts in your components and libraries! Have been thoroughly impressed and grateful for your contributions! :)

**Comment by vasturiano** [comment]
Ok, I see. Thanks for the explanation @ChRonX13.

I've added a method to the component which lets you do this: `stopAnimation()`. If you use the latest version of the library (`1.21.0`) you should be able to cancel the rendering cycle and save some performance.

Let me know if it works for you!

**Comment by ChRonX13** [comment]
@vasturiano looks great! working a treat :) many thanks again :)

**Comment by jsslngz** [comment]
@vasturiano how do i restart the animation after using the `stopAnimation()`

**Comment by vasturiano** [comment]
@jsslngz `.resumeAnimation()`. Also, to pause the animation you should use the new name: `.pauseAnimation()`

**Comment by melchisedech333** [comment]
@vasturiano Thank you very much, your message helped me a lot.
