### ISSUE TITLE
Issues with rendering custom 3D objects as graph links

### ISSUE THREAD

**Issue by klaraseitz** [vasturiano/3d-force-graph#273]
I would like to render various geometrical shapes onto links. I have been able to do that with nodes. But for links I was only able to make sprites and lines work. (as in the examples)

Here are two things I tried which failed. Can you see where I went wrong or what the issue is?

```
graph(element)
  .graphData(graphData)
  .linkThreeObjectExtend(false)
  .linkThreeObject((link) => {
    let geometry = new THREE.ConeBufferGeometry( 5, 20, 32 );
    let material = new THREE.MeshBasicMaterial( {color: 0x0000ff} );
    return new THREE.Mesh( geometry, material );
})
```
==> I would expect this to render a cone (at the center of the link I guess)
But instead nothing between the nodes shows up at all. 

```
graph(element)
  .graphData(graphData)
  .linkThreeObjectExtend(false)
  .linkThreeObject((link) => {
    let path = new THREE.Path();
    path.absellipse(0, 0, 4, 2, 0, 2*Math.PI, null, null);
    let points = path.getPoints();
    let geometry = new THREE.BufferGeometry().setFromPoints( points );
    let material = new THREE.LineBasicMaterial({ color: 0x0000ff });
    return new THREE.Line( geometry, material );
})
```
==> I would expect this to draw an ellipse at (0,0,0) (which would eventually get translated to the center of the link I guess)
Instead the usual link line is drawn. This leads me to believe that what I return is seen as falsy and thus ignored, just the material is not ignored. the line has the color which I defined in the LineBasicMaterial. I do not get any error messages in the console.
I did however get an error when I did not use BufferGeometry from Threejs (only Geometry from Threejs).

It would be great to see how I can get any kind of 3D Geometry onto the links. 
Also, I was wondering how the geometry then can be scaled or aligned along the edge, since no coordinated of the source of target node are available when setting up the linkThreeObject.

**Comment by vasturiano** [comment]
@klaraseitz thanks for reaching out.
If you use custom links via `linkThreeObject`, you should also implement the behaviour of `linkPositionUpdate`, which defines how the current link position is applied to the three object you declared as link. This cannot easily be generalised since every custom link object is different and should therefore be declared together with `linkThreeObject`.

You can see it done in this example:
https://github.com/vasturiano/3d-force-graph/blob/master/example/text-links/index.html#L28

The method signature is:
```
.linkPositionUpdate(fn(linkObject, { start, end }, link))
```

**Comment by klaraseitz** [comment]
Thanks! That worked!
