### ISSUE TITLE
Graph.controls().maxDistance didn't work

### ISSUE THREAD

**Issue by zp1112** [vasturiano/3d-force-graph#276]
I wanted to limit the distance of perspectivecamera,but it didn't work.But setting minDistance is working.

I set this.Graph.controls().maxDistance = 400; but when I console the control, I saw the maxDistance was 50000 but not 400.

**Comment by vasturiano** [comment]
Thanks for the report @zp1112! I've just published an update that should fix the issue you described. 👍
