### ISSUE TITLE
How to make the camera only rotate horizontally and vertically without including tilted rotation

### ISSUE THREAD

**Issue by zp1112** [vasturiano/3d-force-graph#280]
Sorry to report a problem but not bug,I want to know how you make the camera only rotate horizontally and vertically without including tilted rotation,like this.
![image](https://user-images.githubusercontent.com/14245159/74399962-8644d280-4e57-11ea-89fb-e78f80f8ddf0.png)

**Comment by vasturiano** [comment]
@zp1112 you can just switch to [orbit controls](https://github.com/vasturiano/3d-force-graph#initialisation), as in this example: https://vasturiano.github.io/3d-force-graph/example/controls-orbit/
