### ISSUE TITLE
Updating clicks after resize

### ISSUE THREAD

**Issue by Herinn** [vasturiano/3d-force-graph#284]
Hello, I'm having trouble updating the clicks on my graph every time the window resizes. I handle window resize this way : 
 ``` 
   handleWindowResize() {
      window.addEventListener('resize', () => {
        this.graph.camera().aspect = window.innerWidth / window.innerHeight;
        this.graph.camera().updateProjectionMatrix();
        this.graph.renderer().setSize(window.innerWidth, window.innerHeight);

        // my problem is the following line :
        this.graph.onNodeClick(node => this.onClick(node)); 
    },
```
I expected something like this to works, but I have to refresh the page everytime there's a resize if I want to click on a node.

Am I doing it wrong ? Any idea on how the handle this ? 

Thank you for your time and all the effort on this library

**Comment by vasturiano** [comment]
@Herinn you can just update the `.width(<val>)`and `.height(<val>)` methods whenever you wish to resize the canvas, no need to manipulate the camera/renderer objects since that's automatically done internally.

Does that fix your issue?

**Comment by Herinn** [comment]
Yes thank you ! It works with this :
```
window.addEventListener('resize', () => {
     this.graph.height(window.innerHeight);
     this.graph.width(window.innerWidth);
});
```
