### ISSUE TITLE
About Capacity and GPU Acceleration

### ISSUE THREAD

**Issue by xyjigsaw** [vasturiano/3d-force-graph#287]
Hi, there. Sorry to bother, I have several problems. 
Is there a limit on capacity? How many points and edges are supported at most (regardless of the device)? Can I use GPU for acceleration？

**Comment by vasturiano** [comment]
Hi @xyjigsaw, thanks for reaching out.

The rendering performance highly depends on the hardware that it's running on, both CPU and GPU wise, so there's not a single truth for hard limits.
It also depends on the complexity of your nodes/link objects if you're using custom objects, and whether you're animating the force-graph iteration or jumping straight into the final stable state.

For reference, here are two "larger" examples:
* With ~4k elements: https://vasturiano.github.io/3d-force-graph/example/large-graph/
* With ~75k elements (no interim animation): https://bl.ocks.org/vasturiano/raw/34e0ac2ad391e33ad5dde43ec7ce3d40/

**Comment by xyjigsaw** [comment]
Thank you for replying.
