### ISSUE TITLE
control controls()

### ISSUE THREAD

**Issue by fabisch30** [vasturiano/3d-force-graph#288]
So i want to automate my application and import different graphs where i than can change linkDistance/zoomSpeed/... and all of this so that the graph looks good (different graphs need different settings). I got inspired by [this](https://vasturiano.github.io/3d-force-graph/example/manipulate-link-force/) and do this also with those sliders/controls. 
Two questions:

**1)**  When i change my size of the nodes, the nodes keep moving. Why is this and how to stop this. Because in bigger graphs where i have a big linkDistance (so that the nodes do not overlap) and then change the size of the nodes, all of a sudden they overlap again. Here`s a small example:

```
<head>
  <script src="//unpkg.com/dat.gui"></script>
  <script src="//unpkg.com/3d-force-graph"></script>
</head>

<body>
  <div id="3d-graph"></div>

  <script>
    // Create Random tree
    const N = 20;
    const gData = {
      nodes: [...Array(N).keys()].map(i => ({ id: i })),
      links: [...Array(N).keys()]
        .filter(id => id)
        .map(id => ({
          source: id,
          target: Math.round(Math.random() * (id-1)),
          color: id % 2
        }))
    };

    const graph = ForceGraph3D()
      (document.getElementById('3d-graph'))
        .nodeLabel(node => node.id)
        .linkOpacity(1)
         .linkColor(link => 'red')
        .graphData(gData);

    const linkForce = graph
      .nodeVal(node => settings.redDistance)
    
    //Define GUI
    const Settings = function() {
      this.redDistance = 20;
    };

    const settings = new Settings();
    const gui = new dat.GUI();

    const controllerOne = gui.add(settings, 'redDistance', 0, 100);

    controllerOne.onChange(updateLinkDistance);

    function updateLinkDistance() {
      linkForce.nodeVal(node => settings.redDistance);
      graph.numDimensions(3);
    }
  </script>
</body>
```

**2)**  Most important I would also like to change the attraction of the nodes like the linkDistance in your example. But thats giving me problems as it is not working properly. See:

```
<head>
  <script src="//unpkg.com/dat.gui"></script>
  <script src="//unpkg.com/3d-force-graph"></script>
</head>

<body>
  <div id="3d-graph"></div>

  <script>
    // Create Random tree
    const N = 20;
    const gData = {
      nodes: [...Array(N).keys()].map(i => ({ id: i })),
      links: [...Array(N).keys()]
        .filter(id => id)
        .map(id => ({
          source: id,
          target: Math.round(Math.random() * (id-1)),
          color: id % 2
        }))
    };

    const graph = ForceGraph3D()
      (document.getElementById('3d-graph'))
        .nodeLabel(node => node.id)
        .linkOpacity(1)
         .linkColor(link => 'red')
        .graphData(gData);

    const linkForce = graph
      .d3Force('charge')
      .strength(link => settings.redDistance);
    
    //Define GUI
    const Settings = function() {
      this.redDistance = -5;
    };

    const settings = new Settings();
    const gui = new dat.GUI();

    const controllerOne = gui.add(settings, 'redDistance', -100, 0);

    controllerOne.onChange(updateLinkDistance);

    function updateLinkDistance() {
      linkForce.strength(link => settings.redDistance);
      graph.numDimensions(3);
    }
  </script>
</body>
```

**3)** Also want to change rotation speed. How do i get _Graph.controls().rotateSpeed = 0.1_ in a format like _Graph.controls().rotateSpeed(rotate => 0.1)_ ? Or is there no need for that?

Thank you very much for any help!

**Comment by vasturiano** [comment]
@fabisch30 thanks for reaching out.

1) The nodes move because modifying attributes that influence the force-simulation causes the engine to re-heat, so it can automatically react to the new configuration. The re-heat runs for the duration of the least of `cooldownTicks` and `cooldownTime`. So, if you don't wish the force engine to react as a result, you just have to set `.cooldownTicks(0)` before you modify one of these properties.

2) It seems like you are setting negative values to the strength. That is disadvisable for most use cases of the `forceLink` as it yields unpredictable results. You can read more about the details here: https://github.com/vasturiano/d3-force-3d#link_strength

3) `Graph.controls().rotateSpeed = 0.1` is the only correct syntax, as that's how [TrackballControls](https://threejs.org/docs/#examples/en/controls/TrackballControls) work.

**Comment by fabisch30** [comment]
Thank for replying that fast.

**1.** That`s what I was looking for. Thanks!

**2.** So I want to avoid the nodes of overlapping (after I changed the link distance) and Graph.d3Force('charge').strength(node => number) worked for that purpose. Is there another way of doing this? Because the link you sent refers to _link strength_ and i am not sure if thats what I need?

**3.** How then would I implement that. I tried to start with a input field where you write down the zoomSpeed and it will update after you click on the button. But so far the after I click on the button, you can not zoom at all. Any advice?

```
<head>
    <script src="//unpkg.com/3d-force-graph"></script>
  </head>
  
  <body>
        <div><input type="search" id="text" placeholder="zoomSpeed">
        </div>
        <div><button id = "button1" onclick="function1()"> Press </button></div>
       
    <div id="3d-graph"></div>
  
    <script>
      var gData = {"nodes": [
    {"id": "1"}, 
    {"id": "2"}, 
    {"id": "3"}, 
    {"id": "4"}, 
    {"id": "5"}, 
    {"id": "6"}, 
    {"id": "7"}, 
    {"id": "8"}, 
    {"id": "9"}, 
    {"id": "10"}, 
    {"id": "11"}, 
    {"id": "12"}, 
    {"id": "13"}], 
    "links": [
        {"source": "1", "target": "2"}, 
        {"source": "2", "target": "3"}, 
        {"source": "3", "target": "4"}, 
        {"source": "4", "target": "5"}, 
        {"source": "5", "target": "6"}, 
        {"source": "6", "target": "7"}, 
        {"source": "7", "target": "8"}, 
        {"source": "8", "target": "9"}, 
        {"source": "9", "target": "10"}, 
        {"source": "10", "target": "11"}, 
        {"source": "11", "target": "12"}, 
        {"source": "12", "target": "13"}, 
        {"source": "13", "target": "1"}, 
        {"source": "6", "target": "2"}, 
        {"source": "7", "target": "3"}
        ]}
  
      var graph = ForceGraph3D()(document.getElementById('3d-graph'))
          .graphData(gData);

          graph.controls().zoomSpeed = 0.1

          function function1(){
            var zoomSpeed = document.getElementById("text")
            graph.controls().zoomSpeed = parseFloat(zoomSpeed)
            graph.refresh()
          }

 
    </script>
  </body>
```

**Comment by vasturiano** [comment]
2) Ah I see, I missed that you were affecting the strength of the `manyBody` force, not the `link`.
That configures the repelling force among all the nodes, if that's what you wish to control.
https://github.com/vasturiano/d3-force-3d#manyBody_strength

3) Perhaps you're setting a very low value to `zoomSpeed`, causing it to halt? What is the output of `console.log(parseFloat(zoomSpeed))`? You also don't need to call `graph.refresh()` btw. 👍

**Comment by fabisch30** [comment]
Ok so for **3.** I simply missed `.value` for the HTML Element. So just doing `document.getElementById("text").value` is enough.

But **2)** gives me big problems:

> That configures the repelling force among all the nodes, if that's what you wish to control.

I want to avoid nodes of overlapping and in some older [issue request](https://github.com/vasturiano/3d-force-graph/issues/256) that was recommended. It works fine if I set the value manually, try out different and see which one is the best. But thats not practicable if I want to load different graphs without changing my code. For that purpose I want to control the repelling of nodes with an slider but as you see in the code, that does so far not work.

So either my code is crap (probably) or I should use some other configuration? 

I understand that going from a high repelling value to an low will not change anything but the other way around I want that the nodes move away from each other the higher the repelling value is.

**Comment by vasturiano** [comment]
Ok, I understand. So you have to remember that the whole system has a balance of forces, with the `forceLink` generally being the dominant one. The `forceManyBody` (charge) generally acts secondarily for spreading the nodes around while maintaining the established links distances.

Also, if you wish to prevent node overlaps, possibly a better strategy is to use [forceCollide](https://github.com/vasturiano/d3-force-3d#forceCollide).
You can even adjust the nodes' radius according their size.

You can see an example of it in use here: https://github.com/vasturiano/3d-force-graph/blob/a436be569f1cdc71cabe281a8cf7ecbf4f4cb710/example/tree/index.html#L39

**Comment by fabisch30** [comment]
OK so from what I read in the documentation it indeed seems that the _collision force_ is the right approach for that but i have still problems just to apply that to an graph. What am I missing?

<head>
    <script src="//unpkg.com/3d-force-graph"></script> 
    
  </head>
  
  <body>
       
    <div id="3d-graph"></div>
  
    <script>
      var gData = {"nodes": [
    {"id": "1"}, 
    {"id": "2"}, 
    {"id": "3"}, 
    {"id": "4"}, 
    {"id": "5"}, 
    {"id": "6"}, 
    {"id": "7"}, 
    {"id": "8"}, 
    {"id": "9"}, 
    {"id": "10"}, 
    {"id": "11"}, 
    {"id": "12"}, 
    {"id": "13"}], 
    "links": [
        {"source": "1", "target": "2"}, 
        {"source": "2", "target": "3"}, 
        {"source": "3", "target": "4"}, 
        {"source": "4", "target": "5"}, 
        {"source": "5", "target": "6"}, 
        {"source": "6", "target": "7"}, 
        {"source": "7", "target": "8"}, 
        {"source": "8", "target": "9"}, 
        {"source": "9", "target": "10"}, 
        {"source": "10", "target": "11"}, 
        {"source": "11", "target": "12"}, 
        {"source": "12", "target": "13"}, 
        {"source": "13", "target": "1"}, 
        {"source": "6", "target": "2"}, 
        {"source": "7", "target": "3"}
        ]}
  
      var Graph = ForceGraph3D()(document.getElementById('3d-graph'))
          .graphData(gData)
           .d3Force('collision', d3.forceCollide(node => 5));

 
    </script>
  </body>

**Comment by vasturiano** [comment]
@fabisch30 you need to import that force into your app, as part of the [d3-force-3d](https://github.com/vasturiano/d3-force-3d) package. If also requires you import `d3-octree`, like here:
https://github.com/vasturiano/3d-force-graph/blob/a436be569f1cdc71cabe281a8cf7ecbf4f4cb710/example/tree/index.html#L6-L7

**Comment by fabisch30** [comment]
YES! thanks a lot.
