### ISSUE TITLE
Support for multiple links for same sources and targets

### ISSUE THREAD

**Issue by AmbroiseCouissin** [vasturiano/3d-force-graph#29]
Hi,

It could be cool to have some kind of support when we have multiple links for the same sources and targets.

Right now, if we have several links for the same source and same target, the two lines representing the links are at the same place which makes it difficult to visually see, hover or select them.

Cheers

**Comment by vasturiano** [comment]
@AmbroiseCouissin thanks for the request. Do you have an example of how you would envision the separation of the multiple links?
If you play with the link opacities and colors you can probably get a visual distinction by using the color additions. But that won't help if you wish to hover on them separately.

An alternative approach would be to merge the multiple links into a single data point and combine the attributes of both in a combo list associated with each link object, which information could be displayed on hover.

**Comment by AmbroiseCouissin** [comment]
@vasturiano I was thinking that maybe it could look a bit like this:
https://s3.amazonaws.com/dev.assets.neo4j.com/wp-content/uploads/20170704121511/product-page-connections-diagram.svg

But what you propose works as well.

Thanks!

**Comment by EmmaU25** [comment]
@AmbroiseCouissin Hey, You can show me how you achieved?
