### ISSUE TITLE
display multiple paths of nodes

### ISSUE THREAD

**Issue by fabisch30** [vasturiano/3d-force-graph#290]
So for the purpose of network analytics I have a backend connection to an python script which gives me for two nodes all the paths with a given length. I want to display all of those paths now (meaning all the links which are included in that path).
If I just want to display one of them thats easy:

Lets say `nodes_list = [node1, node2, node3, node4]` is my exact path. Then I do:

`Graph.linkVisibility(link => (nodes_list.includes(link.target.id) && nodes_list.includes(link.source.id) && (nodes_list.indexOf(link.target.id) - nodes_list.indexOf(link.source.id) == 1)) ? true : false)`

That works fine. But now I have a dictionary containing all the paths:

json = {1: [node1, node2, node3, node4], 2: [node1, node3, node5, node4], 3: [node1, node3, node2, node4]}

Note that nodes can be in multiple arrays. My approach was to join all those nodes in one array and then do the same as I did for the case of just one path. Meaning I have

`[node1, node2, node3, node4, node1, node3, node5, node4, node1, node3, node2, node4]`

Thats when I recognized that nodes can be multiple times in that array, meaning that .indexOf() will always give me the first index of that node. Any ideas for that?

**Comment by vasturiano** [comment]
@fabisch30 it seems you'll just need a different way to iterate through your `node_list`, to find adjacent pairs of nodes. Instead of using `indexOf`, you could use [array.find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) and add your own logic:
```
linkExists = !!nodes_list.find(
  (node, idx) => 
    idx > 0 && 
    nodes_list[idx-1] === link.source.id && 
    node === link.target.id
  )
```

**Comment by fabisch30** [comment]
Thanks a lot for that!
