### ISSUE TITLE
linePrecision warnings causing performance issues

### ISSUE THREAD

**Issue by pdteam** [vasturiano/3d-force-graph#291]
Hi there,

When running any example using the current unpkg libraries, every refresh of the graph drops a warning into the console stating "_3d-force-graph.min.js:2 THREE.Raycaster: .linePrecision has been deprecated. Use .params.Line.threshold instead._". This warning is posted hundreds of times per second, causing performance issues.

Downloading the library locally and replacing the .linePrecision with .params.Line.threshold removes the warning.

**To Reproduce**
Go to https://vasturiano.github.io/3d-force-graph/example/async-load/ 
Press F12 and navigate to the Console window in the debug panel.
![screenshot of 3d force graph](https://user-images.githubusercontent.com/19784828/76350325-ec4f3900-62e1-11ea-8111-f6ff7078dcb0.PNG)

Can this warning be removed from the official version so the CDN can be used?

Thanks

Janak

**Comment by RaulPROP** [comment]
It's been solved in [this commit of the three-render-object](https://github.com/vasturiano/three-render-objects/commit/f5060340e54db5a596a221c2bf865ffe5a826aa1), the dependency to that library just needs to be updated to the 1.12.3.

**Comment by RaulPROP** [comment]
The versioning has been updated in the version 1.60.1

This issue can be closed now.
