### ISSUE TITLE
event on renderingStop

### ISSUE THREAD

**Issue by fabisch30** [vasturiano/3d-force-graph#293]
Bigger graphs take a while until they are completely displayed or until the engine stops rendering.
I want then invoke an event at that moment. How do I access the engine (more precisely the moment the graph is fully loaded and the engine stops (meaning the nodes stop moving)) ?

**Comment by RaulPROP** [comment]
You can put a callback function in the `onEngineStop` function.

Like:

```
graph.onEngineStop(() => customCallback())

```

**Comment by fabisch30** [comment]
I tried that out at first, but the callback function is executed too early. See (i just added .engineStop() in the basic example):

```
<head>
  <style> body { margin: 0; } </style>

  <script src="//unpkg.com/3d-force-graph"></script>
  <!--<script src="../../dist/3d-force-graph.js"></script>-->
</head>

<body>
  <div id="3d-graph"></div>

  <script>
    // Random tree
    const N = 300;
    const gData = {
      nodes: [...Array(N).keys()].map(i => ({ id: i })),
      links: [...Array(N).keys()]
        .filter(id => id)
        .map(id => ({
          source: id,
          target: Math.round(Math.random() * (id-1))
        }))
    };

    const Graph = ForceGraph3D()
      (document.getElementById('3d-graph'))
      .onEngineStop(window.alert())
        .graphData(gData);
  </script>
</body>
```

**Comment by RaulPROP** [comment]
`onEngineStop` expects a function. The problem is that you are not passing a function, you are calling it.

So instead of 

```
.onEngineStop(window.alert())
```

you should do

```
.onEngineStop(() => window.alert())
```

or

```
.onEngineStop(window.alert.bind(this))
```

[here's the codepen solving it](https://codepen.io/raulprop/pen/bGdKYMw).

**Comment by fabisch30** [comment]
Thanks!

**Comment by fabisch30** [comment]
@RaulPROP do you have a suggetsion on how I would handle the following:

I only want .onEngineStop() to be executed after the graph is fully rendered, but not on an .onNodeClick() event.

I tried to work with an dummy variable like:

```
testEngine = true
Graph.onEngineStop(() => testEngine ? function1() : false)
Graph.graphData(JSON.parse(json))
testEngine = false
```

I set `testEngine = true` when I upload an graph and after that `false`. But apparently this only causes `function1()` to be never executed.

Do you have another idea?

**Comment by RaulPROP** [comment]
I would do something [like this.](https://codepen.io/raulprop/pen/bGdKYMw)

Basically, the function that you call on the first `onEngineStop` re-writes the `onEngineStop` callback.

```javascript
var graph = ForceGraph3D();
graph.onEngineStop(() => function1());
graph.graphData(JSON.parse(json));

function1() {
    doSomething();
    graph.onEngineStop(() => {});
}
```

In the case that you are rendering new data and, thus, needing `function1`again, i would wrap that login in a function (and calling it when needed).

e.g.:

```javascript
var graph = ForceGraph3D();

function loadData(json) {
    graph.graphData(JSON.parse(json));
   graph.onEngineStop(() => function1());
}

function1() {
    doSomething();
    graph.onEngineStop(() => {});
}
```

**Comment by fabisch30** [comment]
Thanks a lot again for your help!
