### ISSUE TITLE
Reversible Directional Arrows

### ISSUE THREAD

**Issue by beqa-bumbeishvili** [vasturiano/3d-force-graph#294]
is it possible to reverse directional arrows? I would like COVID-19 and H1N1 to refer to virus, even though virus is their parent

is it possible to do?

![directional links](https://user-images.githubusercontent.com/16163067/76958259-d5879280-6930-11ea-8bf7-28d319d45841.png)

**Comment by vasturiano** [comment]
@beqa-bumbeishvili you can also swap the relationship of nodes in your link data, by switching `source` with `target`, since the arrows always point from `source` to `target`.

**Comment by beqa-bumbeishvili** [comment]
will try it, Thanks
