### ISSUE TITLE
linkColor() setter not working

### ISSUE THREAD

**Issue by Tymek** [vasturiano/3d-force-graph#296]
**Describe the bug**
I couldn't change link color calling `.linkColor()` with rgb value

**To Reproduce**
1. Go to https://codesandbox.io/s/sharp-mccarthy-vlwrx
2. Remove last 2 lines
3. See no red :worried: 

**Expected behavior**
`graph.linkColor('#ff0000')` should change link color

**Desktop:**
 - OS: Arch Linux (64-bit)
 - Browser Chromium
 - Version 80.0.3987.132 (Official Build)

**Additional context**
`linkMaterial()` is a work-around. Works fine for me, color is applied.

**Comment by vasturiano** [comment]
@Tymek `linkColor` takes an accessor function, it should be instead:
```
graph.linkColor(() => "#ff0000");
```

**Comment by Tymek** [comment]
Thank you! `[str or fn]` confused me, with other setters working directly.
