### ISSUE TITLE
WARNING: Too many active WebGL contexts. Oldest context will be lost.

### ISSUE THREAD

**Issue by rishabhjha708** [vasturiano/3d-force-graph#303]
I am getting this Warning when changing the graphData again and again ?
Unless I am refreshing the page, this warning is being generated

**Comment by RaulPROP** [comment]
It's a problem with the [three.js](https://github.com/mrdoob/three.js/) library. It shouldn't be a problem.

**Comment by rishabhjha708** [comment]
Oh thanks @RaulPROP , for reply
