### ISSUE TITLE
Using 3d-force-graph and d3-force(2-d) graph

### ISSUE THREAD

**Issue by rishabhjha708** [vasturiano/3d-force-graph#304]
One problem is occurring that in 1 tab I have created a 3-d force graph using this library and in another tab, I have created a 2-d graph using d3 for same graph data. 
Problem is I am changing the d3 force values in 2-d then the same value are automatically taken by 3-d graph. Can there be a way for separating the 2 graph properties ?

**Comment by vasturiano** [comment]
@rishabhjha708 you should clone the data before handing it over to the second component, so that the manipulation of each of the node/link objects by one component does not affect the other.

**Comment by rishabhjha708** [comment]
yes, @vasturiano , that was the problem, I was just using assignment operator for making copies of graph data.
Now, I used `var clonedObj = Object.assign({}, graphObj);` and it solved the problem
