### ISSUE TITLE
img-nodes is not working correctly.

### ISSUE THREAD

**Issue by detteiu** [vasturiano/3d-force-graph#307]
img-nodes is not working correctly on demo page.
https://vasturiano.github.io/3d-force-graph/example/img-nodes/

And, on my environment also facing that nodes don't show up. I referenced the demo code.
Could you check if what is going wrong?

Thank you in advance.

**Comment by RaulPROP** [comment]
For me it is working just fine.

**Comment by detteiu** [comment]
Thank you for the comment.
On my different machine, it is found that it is working fine.
Maybe my environment issue. 
I will close the issue.
