### ISSUE TITLE
How do I search for a node based on its id/name and then focus the node?

### ISSUE THREAD

**Issue by yunfeijing** [vasturiano/3d-force-graph#308]
For example if there is a search bar as a "form" in the body, when I search for a specific node (type in the id or name), the graph should put and focus the node at the center of the screen.
I'm not sure how can I search for a node in the graph, since the raw json has been converted to a graph.

**Comment by RaulPROP** [comment]
**Search for a node given its id**
From the converted data (that can be access with `graph.graphData()`), you need to check the id of the nodes. Those nodes are in the property `nodes`.

One way could be:
```javascript
const idToFind = 10; // the id you want to find
const data = graph.graphData();
const nodes = data.nodes;

// this will be undefined if there are no nodes that have that id
const node = nodes.find((n) => n-id === idToFind);
```

---

**Focus a node**
Use the `graph.cameraPosition(position, lookAt, transitionMS)` function.

Basically you need to cumpute the position you want to put the camera (in a `{x, y, z}` format) and pass that as the first argument. Then pass the node as the second argument (that node already has its position in a `{x, y, z}` format), and the time (in miliseconds) you want to make that transition last as the third argument.

```javascript
const cameraPosition = {x: 10, y: 50, z: -30};
graph.cameraPosition(cameraPosition, node, 1000);
```

**Comment by JonThom** [comment]
(If the issue has been solved you can close it)
