### ISSUE TITLE
How can i change only material for link?

### ISSUE THREAD

**Issue by MaksZhukov** [vasturiano/3d-force-graph#310]
I need to change material for the link and I do it in linkThreeObject, but I have some issue about it, my links don't look well as I expected.
https://codesandbox.io/s/objective-diffie-t0xdd?file=/src/App.js

**Comment by vasturiano** [comment]
@MaksZhukov that's because you need to do the required transformations to your cylinder geometries so that they're oriented correctly.

If you just wish to change the material, I would recommend using `.linkMaterial(link => ...)` instead, as that's a simpler approach.

**Comment by MaksZhukov** [comment]
@vasturiano Ok, thank you! I will try it!
