### ISSUE TITLE
how can I set different sizes for different nodes?

### ISSUE THREAD

**Issue by saeid-azizi** [vasturiano/3d-force-graph#312]
**Is your feature request related to a problem? Please describe.**
I just want to know, is it possible to set different sizes for some specific nodes?
The nodeVal set size for all nodes.

**Comment by RaulPROP** [comment]
Just create a function that has a node as an input and the size (volume) as a value.

```javascript
const graph = ForceGraph3D(); // Create the graph as you want
graph.nodeVal((node) => customNodeVolume(node));

function customNodeVolume(node) {
    return (Math.random() * 10) + 4; // custom value
}
```

**Comment by saeid-azizi** [comment]
Dear RaulProp Thanks for the reply.

**Comment by Alexithemia** [comment]
`graph.nodeVal(node => node.out-degree)`

Should be all you need. If you have a value set for them.

**Comment by saeid-azizi** [comment]
Thanks for the reply.
so, in this case, I think I have to process nodes with a map function to extract out-degree key and pass it into the nodeVal.
do you think it's the right way to do it?

**Comment by JonThom** [comment]
@saeid-azizi if your issue is solved can you please close it? Thanks!

**Comment by RaulPROP** [comment]
> Thanks for the reply.
> so, in this case, I think I have to process nodes with a map function to extract out-degree key and pass it into the nodeVal.
> do you think it's the right way to do it?

No, you just need to set the `.nodeVal` callback of the `graph` object [as mentioned here](https://github.com/vasturiano/3d-force-graph/issues/312#issuecomment-612638297) and [here](https://github.com/vasturiano/3d-force-graph/issues/312#issuecomment-613230194).

The `nodeVal` callback already iterates over every node.
