### ISSUE TITLE
How to update position of nodes without re-call GrapData

### ISSUE THREAD

**Issue by volkov-a-dev** [vasturiano/3d-force-graph#315]
Hey. I have a problem understanding how to update the positions of nodes in a graph.
When I click on the button, I would like to display the nodes in the center of the graph.
The second problem, when I click on the button, I have a list of indicators and I need to update the positions of all nodes.
What method could I use to solve this problem? Without re-call function grapData.
Thanks in advance!

**Comment by vasturiano** [comment]
@volkov-a-dev as described in [this section of d3-force-3d](https://github.com/vasturiano/d3-force-3d#simulation_nodes), you can directly manipulate the positions of nodes by setting `x`, `y` and `z` attributes on each of the nodes.

Furthermore, if you want the simulation engine to not also affect those nodes, you can fix them, by adding `fx`, `fy` and `fz` attributes.

**Comment by volkov-a-dev** [comment]
@vasturiano thank you for your response and help .
