### ISSUE TITLE
change directio of particles

### ISSUE THREAD

**Issue by fabisch30** [vasturiano/3d-force-graph#316]
_Is it possible to change the direction of the particles_? Because in my case, they are moving in the wrong direction. They moving from target -> source.

The arrows are pointing correct in the direction source -> target...

I don`t understand how this can be since particles and arrows are based on the same graph and on the same links.

**Comment by RaulPROP** [comment]
The Readme says:

> **linkDirectionalParticles([num, str or fn])**
> link object accessor function, attribute or a numeric constant for the number of particles (small spheres) to display over the link line. The particles are distributed equi-spaced along the line, **travel in the direction source > target**, and can be used to indicate link directionality.

So they should be traveling from source to target.

**Comment by fabisch30** [comment]
@RaulPROP I know ... It says the same about the arrows and yet the arrows and particles are pointing/moving in different directions.

**Comment by RaulPROP** [comment]
![Arrow + Particles](https://i.postimg.cc/TwHzqHBN/Screencast-2020-04-21-131105.gif)

As you can see I can not reproduce your behavior.

Can you create a [CodePen](https://codepen.io/) (or similar) and reproduce it?

**Comment by fabisch30** [comment]
I did the same and did get the expected result (as you). I dont have any idea as arrows/particles depend on the same link object. Look at the attached picture. Thats all I do.
![Capture](https://user-images.githubusercontent.com/58147719/79860596-35130b00-83d3-11ea-8c13-5fb93bf08cba.PNG)


Thats why I asked if theres a chance to change the direction of particles?

**Comment by RaulPROP** [comment]
Can you try to just send one particle and see what happens?

My guess is that they are going in the expected direction, but there are too many going too fast that it looks like it's going in the reverse direction. Just like an optical illusion.

**Comment by fabisch30** [comment]
haha indeed that was the problem. thanks a lot!
