### ISSUE TITLE
Is there a way to temporarily shut down the force engine?

### ISSUE THREAD

**Issue by ohsorry** [vasturiano/3d-force-graph#318]
I want to close the physics simulation after the layout is finished, only use the physics engine to initialize the layout, and then I can drag a node without constraints (and not involving other nodes), 
What should I do?

**Comment by ohsorry** [comment]
I know that by setting `fx, fy, fz` to make the nodes fixed, can the physical constraints be permanently turned off after the layout is finished?

**Comment by vasturiano** [comment]
@ohsorry `.cooldownTicks(0)`

**Comment by ohsorry** [comment]
this is what i want:
``` javascript
    graph.cooldownTime(1000);
    graph.onEngineStop(()=>{
        console.log('stoped');
        graph.cooldownTicks(0);
    });
```
wonderful!
