### ISSUE TITLE
Setting font colour for labels

### ISSUE THREAD

**Issue by jaysonh** [vasturiano/3d-force-graph#32]
Is there an easy way to set the font colour for the labels in the auto colored example?

**Comment by vasturiano** [comment]
@jaysonh I've just added support for HTML content in the node/link labels. So, (from `v1.24.0`) you can easily style your labels. F.e., to change the text color:
```
myGraph.nodeLabel(d => `<span style="color: purple">${d.name}</span>`)
```
or if you'd like the labels to match the node colors, just do `color: ${d.color}` instead.
Works for `linkLabel` too.

Hopefully this will help your use case.
