### ISSUE TITLE
Provide an example of postProcessingComposer?

### ISSUE THREAD

**Issue by Lorenzowy** [vasturiano/3d-force-graph#321]
**Describe the solution you'd like**
A demo where the nodes have a glowing effect using Bloom 
https://vanruesc.github.io/postprocessing/public/demo/#bloom

**Describe alternatives you've considered**
I'm not sure how to use the exposed `postProcessingComposer` as most examples online also require `camera`, `scene `and `renderer`

**Comment by vasturiano** [comment]
Thanks for reaching out @Lorenzowy.

Just added an example that shows how to apply a bloom rendering effect:
https://github.com/vasturiano/3d-force-graph/blob/master/example/bloom-effect/index.html#L20-L24
https://vasturiano.github.io/3d-force-graph/example/bloom-effect/

**Comment by Lorenzowy** [comment]
Apologies, I'll admit I haven't been able to figure it out.

I use your package in React, and so it looks something like:
`<ForceGraph3D ref={ref} graphData={data} postProcessingComposer={} />`

As such I'm not sure how to apply your above code for `postProcessingComposer`

**Comment by vasturiano** [comment]
@Lorenzowy `postProcessingComposer` is a component **method**, not prop.
You must access it using your component ref, for example in your `componentDidMount` section:
```js
componentDidMount() {
  const bloomPass = ...;
  myGraphRef.current.postProcessingComposer().addPass(bloomPass);
}
```

Also this is more of a question for the [react-force-graph](https://github.com/vasturiano/react-force-graph) repo.

**Comment by Lorenzowy** [comment]
Thanks so much! So i realized that `ref.current` didn't have `postProcessingComposer()`, only the following:

```
{
current:
camera: ƒ ()
cameraPosition: ƒ ()
controls: ƒ ()
d3Force: ƒ ()
d3ReheatSimulation: ƒ ()
emitParticle: ƒ ()
graph2ScreenCoords: ƒ ()
pauseAnimation: ƒ ()
refresh: ƒ ()
renderer: ƒ ()
resumeAnimation: ƒ ()
scene: ƒ ()
stopAnimation: ƒ ()
__proto__: Object
__proto__: Object
}
```


Regardless, I got it to work using `scene`, `camera`, `renderer`

```
var renderScene = new RenderPass( ref.current.scene, ref.current.camera );

var bloomPass = new UnrealBloomPass( new THREE.Vector2( window.innerWidth, window.innerHeight ), 1.5, 0.4, 0.85 );
bloomPass.renderToScreen = true;
bloomPass.threshold = 0;
bloomPass.strength = 1.5;
bloomPass.radius = 0;

let composer = new EffectComposer( ref.current.renderer );
composer.setSize( window.innerWidth, window.innerHeight );
composer.addPass( renderScene );
composer.addPass( bloomPass );

function render() {
  composer.render();
  requestAnimationFrame(render);
}
render();
```

**Comment by vasturiano** [comment]
@Lorenzowy which version of `react-force-graph` are you using? `postProcessingComposer` method was added in `1.33.1` of `react-force-graph` and `1.15.0` of `react-force-graph-3d`.
