### ISSUE TITLE
OrbitControls properties

### ISSUE THREAD

**Issue by Tazeg** [vasturiano/3d-force-graph#325]
Hello, thank you for this great project.
I have set the graph to use OrbitControls with : 

```js
let graph = ForceGraph3D({ controlType: 'orbit' })
```

But how to change properties like `.autoRotate` or `.enableDamping` ?

So the questions also extends to TrackballControls and FlyControls.
Maybe i missed something but I couldn't find anything in the Readme or the issues about that.

Properties are on : 

- https://threejs.org/docs/#examples/en/controls/OrbitControls
- https://threejs.org/docs/#examples/en/controls/TrackballControls
- https://threejs.org/docs/#examples/en/controls/FlyControls

Thanks.

**Comment by RaulPROP** [comment]
You can access the controller with `graph.controller()`.

So you could access those properties with

```js
graph.controller().autoRotate;
graph.controller().enableDamping;
```

**Comment by Tazeg** [comment]
All right. Thanks. I did : 

```js
graph.controls().enableDamping = true
```

It works fine.
