### ISSUE TITLE
Adding val parameter to json reduced the node size

### ISSUE THREAD

**Issue by adithyan-ak** [vasturiano/3d-force-graph#327]
json file : https://github.com/adithyan-ak/3d-directed-graph/blob/master/data.json
Initially when the json had no val paramter, the graph was zoomed and large by default. 
![image](https://user-images.githubusercontent.com/34126904/82435067-643f9980-9ab1-11ea-935c-fcc58fb38b90.png)

But later when i added the val parameter to the json data, it suddenly became like this

![image](https://user-images.githubusercontent.com/34126904/82435043-5d188b80-9ab1-11ea-9380-015827932c7b.png)

This is the js code im using

` <script>
    const elem = document.getElementById('3d-graph');

    const Graph = ForceGraph3D()
      (elem)
      
        .jsonUrl('https://raw.githubusercontent.com/adithyan-ak/3d-directed-graph/master/data.json')
        .nodeRelSize(30)
        .nodeResolution(30)
        .nodeLabel('id')
        .nodeVal('val')
        .nodeAutoColorBy('group')
        .onNodeHover(node => elem.style.cursor = node ? 'pointer' : null)
        .onNodeClick(node => {
       	console.log(node)
       	var nodename = node.id
       	var nodevalue = node.val
       	 getdata(nodename, nodevalue);
          // Aim at node from outside it
          const distance = 40;
          const distRatio = 1 + distance/Math.hypot(node.x, node.y, node.z);

          Graph.cameraPosition(
            { x: node.x * distRatio, y: node.y * distRatio, z: node.z * distRatio }, // new position
            node, // lookAt ({ x, y, z })
            3000  // ms transition duration
          );
        });
  </script>`

**Comment by vasturiano** [comment]
@adithyan-ak thanks for reaching out.

It seems you are referring mainly to the size of the nodes. You can calibrate that using the `.nodeResolution` method.

**Comment by adithyan-ak** [comment]
Hey @vasturiano , thanks for the reply. Please look at my script. I have already calibrated.nodeResolution from the default value 8 to 30. But the node size still stays the same. Please help!

**Comment by vasturiano** [comment]
@adithyan-ak could you please create a minimal example on [codepen](https://codepen.io/) so we  can have a deeper look?

**Comment by adithyan-ak** [comment]
@vasturiano here's the properly working 3d-graph with source json that has no **val** parameter. 
https://codepen.io/adithyan-ak/pen/wvKNvrb

Here's the 3d-graph after adding val paramter to the json : https://codepen.io/adithyan-ak/pen/bGVzGRP

Please see the difference between the two graphs. After adding **Val** parameter to the nodes in source json, the size of all the nodes has been drastically reduced.Despite the .nodeResolution is set to 30 in the above given graph, it is drastically small.

**Comment by vasturiano** [comment]
@adithyan-ak thanks for making those examples.

By looking here: https://raw.githubusercontent.com/adithyan-ak/3d-directed-graph/cdabe1c5c2b6d1fcc673b37c73d3a65ef7eaa821/data.json

It seems the attribute you're using for calculating the nodes' sizes (`nodeVal('val')`) points to non-numeric values (strings).

The library will attempt to coerce those values to a number which in the majority of cases will be either `0` or a small size. That explains why the nodes are showing so small.

If you want to size your nodes dynamically, please point to an attribute/method that returns a numeric value.

**Comment by adithyan-ak** [comment]
@vasturiano thanks a lot for the clear explanation.
