### ISSUE TITLE
Node Drag Problem.

### ISSUE THREAD

**Issue by sergey93620** [vasturiano/3d-force-graph#328]
hello. 
i am using 3d-force-graph library for chart.
but i found some problem.
i have created custom node as Three.Group.
but node drag is not working.
        .nodeThreeObject((d) => {
        
![Annotation 2020-05-25 181446](https://user-images.githubusercontent.com/55302766/82825320-b0287f00-9eb3-11ea-9bd6-35ca05b2ea69.png)
    let size = 10;
            let imagePath = "";

            if (d.nodeKind === "tenant.application_profile.endpoint_group.endpoint") {
                size = 5;
                imagePath = ICONMAP[d.nodeType].pngurl;
            } else if (d.nodeKind === "tenant.application_profile.endpoint_group") {
                size = 10;
            } else if (d.nodeKind === "tenant.application_profile") {
                size = 15;
            } else if (d.nodeKind === "tenant.hosting_provider") {
                size = 10;
                imagePath = ICONMAP[d.nodeType].pngurl;
            } else if (d.nodeKind === "tenant.hosting_provider.hosting_location") {
                size = 10;
                imagePath = ICONMAP["hosting_location"].pngurl;
            } else if (d.nodeKind === "tenant.hosting_provider.hosting_target") {
                size = 10;
                imagePath = ICONMAP["hosting_target"].pngurl;
            } else if (d.nodeKind === "tenant.hosting_provider.hosting_target.hosting_domain") {
                size = 10;
                imagePath = ICONMAP["hosting_domain"].pngurl;
            } else if (d.nodeKind === "tenant") {
                size = 20;
                imagePath = ICONMAP["empy:tenant"].pngurl;
            }

            var group = new THREE.Group();

            if (imagePath !== "") {
                var spriteMap = new THREE.TextureLoader().load(imagePath);
                var spriteMaterial = new THREE.SpriteMaterial({ map: spriteMap });
                var sprite = new THREE.Sprite(spriteMaterial);
                sprite.scale.set(size, size, 1);
                group.add(sprite);
            }

            var mainObj = new THREE.Mesh(
                new THREE.DodecahedronGeometry(size),
                new THREE.MeshLambertMaterial({
                    // color: highlightNodes.has(d) ? 'rgb(44,43,33,1)' : d.nodecolor ? d.nodecolor : "#ff00ff",
                    color: "#ffffff",
                    transparent: true,
                    opacity: 0.3
                })
            );

            const txtsprite = new SpriteText(d.name);
            txtsprite.color = highlightNodes.has(d) ? 'rgb(44,43,33,1)' : d.nodecolor ? d.nodecolor : "#ff00ff";
            txtsprite.textHeight = 1;
            txtsprite.padding = 2;
            txtsprite.position.y -= (size + 5);
            txtsprite.material.opacity = 0.5;

            group.add(mainObj);
            group.add(txtsprite);

            return group;
        });

So i tried to create mesh , then input this group as children in new mesh

            group.add(mainObj);
            group.add(txtsprite);

            var geometryt = new THREE.BoxBufferGeometry(size, size, size);
            var materialt = new THREE.MeshBasicMaterial({
                 color: 0xffff00,
                 transparent: true,
                 opacity: 1
             });
             var mesht = new THREE.Mesh(geometryt, materialt);
             mesht.add(group);
             return mesht;
        })

drag was working, but node link was break. link was not working.

im looking forward to let me know solution.
Thanks.

**Comment by vasturiano** [comment]
@sergey93620 thanks for reaching out.

The issue is due to the fact that your top object in `nodeThreeObject` seems to be a group, and the [DragControls](https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/DragControls.js) have trouble with dragging groups. 

I would suggest using an invisible mesh as top object instead of a group, so it can serve as a drag handle, like in this example:
https://github.com/vasturiano/3d-force-graph/blob/master/example/text-nodes/index.html#L20-L24

Regarding your second issue, can you provide more details?

**Comment by sergey93620** [comment]
thanks for your support.
i solved this problem.
my first code is working now.
Thanks.
