### ISSUE TITLE
ngraph physics parameter configuration

### ISSUE THREAD

**Issue by Zolmeister** [vasturiano/3d-force-graph#332]
ngraph seems to handle large graphs more efficiently than d3 ([e.g.](https://wolfram-model-explorer.zolmeister.com/?rule={{{1,2,3}}-%3E{{1,4,3},{5,6,2},{5,6,4},{5,6,5}}}&init={{1,1,1}}&steps=6)).

However dealing with large graphs requires tuning the physics parameters (e.g. to reduce drag).

I'd like to be able to [configure the ngraph parameters](https://github.com/anvaka/ngraph.forcelayout#configuring-physics). e.g.
```js
forcegraph.ngraphPhysics({
  springLength: 30,
  springCoeff: 0.0008,
  gravity: -1.2,
  theta: 0.8,
  dragCoeff: 0.02,
  timeStep: 20
})
```

**Comment by vasturiano** [comment]
Thanks @Zolmeister, it's a good suggestion. I've added the option to the api, it follows the exact syntax you mentioned above.
