### ISSUE TITLE
Type alias 'ForceGraph3DInstance' circularly references itself.

### ISSUE THREAD

**Issue by PeterRakke** [vasturiano/3d-force-graph#333]
When using 3d-force-graph in TypeScript I'm receiving a compile:

`ERROR in ../node_modules/3d-force-graph/dist/3d-force-graph.d.ts:75:6 - error TS2456: Type alias 'ForceGraph3DInstance' circularly references itself.`

I'm using version 1.63.0.

Not sure how and if I can fix this myself?

Kind regards,

Peter Rakké

**Comment by vasturiano** [comment]
@PeterRakke  make sure to upgrade to a recent version of TypeScript.

This issue was solved in TS version 3.7.0:
https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/

**Comment by PeterRakke** [comment]
Thanks, very helpful!
