### ISSUE TITLE
Multiple 3d Force Graph for Comparison?

### ISSUE THREAD

**Issue by LearnerNP** [vasturiano/3d-force-graph#335]
This is not a bug but a question to the developer. Can we have two (or even multiple graphs) side by side? I want to have to 3d force graph side by side and support comparison between two graphs?

**Comment by vasturiano** [comment]
@LearnerNP you can easily render multiple graphs side by side on the same window.
Just instantiate each one with a different DOM node. 
They should behave independently, assuming they are given different graphData objects.
