### ISSUE TITLE
On Node Double Click event Listener

### ISSUE THREAD

**Issue by lumariaap15** [vasturiano/3d-force-graph#336]
If I wanted to add another event listener, in this case, a Node Double Click event listener, what would be a good approach?

**Comment by vasturiano** [comment]
@lumariaap15 you can derive a double click detection from the single click events, by monitoring consecutive clicks on a node that happen within a short period of time.

**Comment by lumariaap15** [comment]
@vasturiano Thank you! I don't know why I hadn't considered doing it like that. It turned to be as easy as this:
```
var lastNodeClick = 0;
var Graph = ForceGraph3D().onNodeClick(node => {
                var d = new Date();
                var t = d.getTime();
                if((t - lastNodeClick) < 500) {
                    //it's a double click
                }else{
                   //just one click
                }
                lastNodeClick = t;
            })
```
