### ISSUE TITLE
Unable to displace a network correctly

### ISSUE THREAD

**Issue by josenxx** [vasturiano/3d-force-graph#337]
<img width="1091" alt="截屏2020-06-26 下午8 18 53" src="https://user-images.githubusercontent.com/10823996/85910029-b3809480-b7ea-11ea-9ed6-63901b061589.png">
Hello. I create a json file in the same syntax as the miserables.json. However, this is my result. 
[https://s1.ax1x.com/2020/06/27/Ny3afe.png](url). Everything is stacked on top of each other. Here is my json file.
[net.json.zip](https://github.com/vasturiano/3d-force-graph/files/4839707/net.json.zip)
Any help is greately appreciated.

**Comment by vasturiano** [comment]
@josenxx thanks for reaching out.

It's hard to say without more info. Can you make an example that reproduces the issue on https://codepen.io/ ?

**Comment by josenxx** [comment]
<script src="https://gist.github.com/josenxx/8a8b96f20a86efb485b429624b7dc54b.js"></script>

**Comment by josenxx** [comment]
You can see it Here.
https://codepen.io/josenxx/live/RwrZZpq

**Comment by vasturiano** [comment]
Thanks for making the example.

It appears you have missing nodes in the data. As seen in the console:
```
Error: node not found: 501.2 Address identification.
```

You have a similar node, but it's missing a `.` at the end:
```js
{"id": "501.2 Address identification", "group": "Title 3"}
```

**Comment by josenxx** [comment]
Thanks. I fixed the problem. Really Appreciate your help.
