### ISSUE TITLE
how can the node's label and link's label always be displayed

### ISSUE THREAD

**Issue by shimizuiyori** [vasturiano/3d-force-graph#34]
now，only when my mouse moves to the top will it be displayed
thank you

**Comment by vasturiano** [comment]
@shimizuiyori if you'd like the labels to be displayed as part of the node itself, instead of solely on the tooltip, the best approach is if you use a custom node geometry that includes the label as a sprite, using the method `.nodeThreeObject(<object>)`.

I've just added an example which shows how this can be done:
https://vasturiano.github.io/3d-force-graph/example/text-nodes/

**Comment by Benkevych** [comment]
@vasturiano what if i need tooltip with label always be visible?

**Comment by vasturiano** [comment]
@Benkevych by principle the tooltips are only shown when hovering over nodes/links. If you want the labels to be always shown as part of the node objects, please look at the example above.

**Comment by artipixel** [comment]
@vasturiano Do you have any idea how we can combine those two? Maybe show the text inside the node or create a 3d object that has text and a node? It will be a good feature as you can't navigate through big amount of nodes without hovering every single one to see what it means... 
Your solution and example is super! But one thing that is missing that way is the option to drag the nodes (bug or feature?) so when we have a lot of them and spaces are uncontrollable we can't navigate.
I mean, the logic is already implemented, can't we just have an option of it to be always on? And can I ask why does the tooltips are shown by principle that way? It could be awesome to add even more detailed tooltip, like one with icons or a line that connects to the dot. 

Awesome library btw!

**Comment by mys** [comment]
@artipixel the only way to show label next to each node is to draw custom geometry via `.nodeThreeObject(...)`. Use eg. SpriteText + BoxGeometry grouped as a node like I did in my [visualization](https://steemverse.com/).
https://github.com/mys/steemverse/blob/master/js/engine.js#L170

**Comment by gitvge** [comment]
I think this is now solved with "linkThreeObjectExtend(true)
