### ISSUE TITLE
zoomToFit is no more working

### ISSUE THREAD

**Issue by Silverhawk83** [vasturiano/3d-force-graph#340]
Hello,

I have tested the recently implemented nodeFilterFn of the zoomToFit, to zoom in the graph to fit one node.
But whatever the returned boolean of the function (1 true on the selected node, or just "true" to fit the whole graph), the camera is not moving.
I have also tried to make a console.log in the function, and it's displaying in the console, so the code is run.
But at the end, I have tested without this function "Graph.zoomToFit(400, 500)", but even that does not move the camera.

It was working on a previous version, before I have made "npm update" to the latest version (1.65.1) to test the nodeFilterFn.

Can you see on your side if the zoomToFit function is correctly working? 

Thank you for your impressive package by the way!

**Comment by vasturiano** [comment]
@Silverhawk83 thanks for reaching out.

[This example](https://vasturiano.github.io/3d-force-graph/example/fit-to-canvas/) is using the `zoomToFit` method. It should scale the graph after a few seconds when the force engine is finished. Is that working on your browser?

This is the relevant snippet:
https://github.com/vasturiano/3d-force-graph/blob/af5aecec1e600a81eb38be9596dc4b0c5eb2c735/example/fit-to-canvas/index.html#L29-L30

**Comment by Silverhawk83** [comment]
I have tested it again, and it seems it was because I used 500 as second parameter whereas my canvas was smaller than that (Maybe it could be good to send a warning to the console in this case), when I put 10, it is working.
However, even when I use the 3rd parameter to zoom on a unique node among the graph, it moves the camera but on the whole nodes set.

This is the function I am using:
  Graph.zoomToFit(400, 10, node => node.id === nodeID)
with nodeID the id of the node I want to zoom in.

Do you have any idea about this problem? Is it a misuse, or is there a bug in the code?

**Comment by vasturiano** [comment]
@Silverhawk83 if the node is on the outer parts of the graph you may not see much of a change. This is because the `zoomToFit` functionality will not automatically point the camera directly at the node, so it still needs to accomodate for a point of view wide enough to fit a sphere with a radius as large as the distance between the node and the graph center.

Hope that makes sense.

**Comment by Silverhawk83** [comment]
@vasturiano but I have the same result if I use
Graph.zoomToFit(400, 10, node => node.id === nodeID)
or
Graph.zoomToFit(400, 10)
It zooms to the whole graph.

I would like to make a function that move the camera to make the center of the view on the desired node.

When the zoomToFit function wasn't able to handle this 3rd parameter, I have made this:
`  var foundNode = Graph.graphData().nodes.find(item => item.id === nodeID);
  var camRot = Graph.camera().rotation;
  if (foundNode !== undefined) {
    Graph.cameraPosition({ x: foundNode.x + 50*camRot._x, y: foundNode.y + 50*camRot._y, z: foundNode.z + 50*camRot._z }, foundNode, 750)
  }`
That would move the camera onto the desired node, without modifying the camera orientation.

However, When I do this, the navigation axis (trackball) becomes weird for translation.

Do you have an idea about how can I achieve this?

**Comment by vasturiano** [comment]
@Silverhawk83 the trackball controls assume that your camera is pointing at the very center of the scene (point `0,0,0`). And that is the central point around which everything else revolves. When the camera position is manually modified that central focus point is changed, switching the center of all the rotation axes. That is probably what you're experiencing.

This is also the reason why the `zoomToFit` intentionally does not alter the rotation center but simply zooms in/out to fit the necessary bounding sphere.

There is an example which modifies the camera position (on node click), but it has probably a similar effect to what you already have:
https://vasturiano.github.io/3d-force-graph/example/click-to-focus/

**Comment by Silverhawk83** [comment]
@vasturiano Yes, this is exactly the problem you have in this example, after zooming to a node, when you translate the camera using the right button of the mouse, the axis are changed.

So there is currently no way to avoid this? I would really like to keep using the trackball control as intended after zooming to a node.

**Comment by vasturiano** [comment]
@Silverhawk83 you can always revert the central point (target) of the trackball controls back to its original setting of `0,0,0`:
```js
myGraph.controls().target = new THREE.Vector3(0, 0, 0);
```
This should bring it back to normal.

Regarding a modifier key (like ALT) detection, you can do it easily by looking into the `event` parameter of the `onNodeClick` method, like:
```js
.onNodeClick((node, event) => {
  if (event.altKey) {
     // your code
  }
})
```

Here's [an example](https://vasturiano.github.io/3d-force-graph/example/multi-selection/) that uses modifier keys to trigger node multi-selection:
https://github.com/vasturiano/3d-force-graph/blob/f5f859d5c6b94f4b54d43e8b2f6eb547a6610d86/example/multi-selection/index.html#L31-L41

**Comment by Silverhawk83** [comment]
@vasturiano
 `myGraph.controls().target = new THREE.Vector3(0, 0, 0);`
This is not working, the camera axis in translation are still changed.

I am trying to look at the functions and the differences in variables, but I couldn't find it for the moment.

If you have any other ideas, I will test them.

**Comment by Silverhawk83** [comment]
@vasturiano It was not working as well.
As I couldn't find anyway to "repair" the axis, I've tried again to zoom in a way the axis would not change, and it seems I found a way to do so (keeping the camera axis unchanged before and after the zoom):
```Javascript
// Zoom to a node
function zoomToNode(nodeID) {
  var foundNode = Graph.graphData().nodes.find(item => item.id === nodeID);
  const dataCamera = Graph.cameraPosition();
  const distance = 0.05;
  if (foundNode !== undefined) {
    Graph.cameraPosition({
      x: foundNode.x + distance * (dataCamera.x - dataCamera.lookAt.x),
      y: foundNode.y + distance * (dataCamera.y - dataCamera.lookAt.y),
      z: foundNode.z + distance * (dataCamera.z - dataCamera.lookAt.z)
    },
      foundNode, 500)
  }
}
```
As this is more an issue of THREE.js and I found a bypass, I will close this issue.

Thank you for your support.
