### ISSUE TITLE
images as nodes AND text in links?

### ISSUE THREAD

**Issue by LalaLuna22** [vasturiano/3d-force-graph#352]
Hi there, thank you in advance for any help! 

I am using the "images as nodes" example code and I would really like to add some text on the links, like this example: [https://github.com/vasturiano/3d-force-graph/blob/master/example/text-links/index.html](url)

But the moment I try to fetch a .json file with the text for the links, everything goes blank on my page. I suspect it has something to do with how the graph is being generated in both examples.

Is there a way to fetch a .json without affecting the graph generated by the images, and call the data inside the .json file just for the links? 

Or maybe there is a way to generate graph with images from a .json file completely instead of the method seen in the "images as nodes" example? 

I am fairly new to coding, so any help is much appreciated, thank you. 

Here is the code I have at the moment: 
````
<head>
  <style> body { margin: 0; } </style>

  <script src="//unpkg.com/react@16/umd/react.production.min.js"></script>
  <script src="//unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>
  <script src="//unpkg.com/babel-standalone"></script>
    
  <script src="//unpkg.com/three"></script>

  <script src="//unpkg.com/3d-force-graph"></script>
  <!--<script src="../../dist/3d-force-graph.js"></script>-->
</head>

<body>
  <div id="3d-graph"></div>

    
  <script>
      
    const imgs = ['1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg', '6.jpg', '7.jpg', '8.jpg', '9.jpg', '10.jpg', '11.jpg', '12.jpg', '13.jpg', '14.jpg', '15.jpg', '16.jpg', '17.jpg', '18.jpg', '19.jpg', '20.jpg', '21.jpg', '22.jpg', '23.jpg', '24.jpg', '25.jpg', '26.jpg', '27.jpg', '28.jpg', '29.jpg', '30.jpg', '31.jpg', '32.jpg', '33.jpg', '34.jpg', '35.jpg', '36.jpg', '37.jpg', '38.jpg', '39.jpg', '40.jpg', '41.jpg', '42.jpg', '43.jpg', '44.jpg' ];

    // Random connected graph
    const gData = {
      nodes: imgs.map((img, id) => ({ id, img })),
      links: [...Array(imgs.length).keys()]
        .filter(id => id)
        .map(id => ({
          source: id,
          target: Math.round(Math.random() * (id-1))
        }))
    };

    const Graph = ForceGraph3D()    
    .backgroundColor('#ffffff')
    .linkColor(() => 'rgba(0,0,0,0.9)')
    .linkWidth (0)
    .linkResolution([8])
    .linkDirectionalParticles(2)
    .linkDirectionalParticleWidth(0.5)

    
    .onNodeClick(node => {
          // Aim at node from outside it
          const distance = 40;
          const distRatio = 1 + distance/Math.hypot(node.x, node.y, node.z);

          Graph.cameraPosition(
            { x: node.x * distRatio, y: node.y * distRatio, z: node.z * distRatio }, // new position
            node, // lookAt ({ x, y, z })
            3000  // ms transition duration
          );
        })
    
      (document.getElementById('3d-graph'))
       .nodeThreeObject(({ img }) => {
        // use a sphere as a drag handle
        const obj = new THREE.Mesh(
          new THREE.SphereGeometry(7),
          new THREE.MeshBasicMaterial({ depthWrite: false, transparent: true, opacity: 0 })    
        );

        // add img sprite as child
        const imgTexture = new THREE.TextureLoader().load(`./imgs/${img}`);
        const material = new THREE.SpriteMaterial({ map: imgTexture });
        const sprite = new THREE.Sprite(material);
        sprite.scale.set(12, 12);
        obj.add(sprite);

        return obj;
          
           // add text as child
          
      })
      .graphData(gData);
  </script>
</body>

`````

**Comment by vasturiano** [comment]
@LalaLuna22 thanks for reaching out.

It's not overly clear what problem you are experiencing. Could you make a minimal example on [codepen](https://codepen.io/) that reproduces your issue, so we can debug it a bit further?

**Comment by LalaLuna22** [comment]
Hi @vasturiano  thank you so much for getting back to me. 

I'm sorry if my post wasn't clear, at the moment the code I have is working fine, I'm just generating a graph with images as nodes, but I am at a loss on which way to go regarding adding text in the links of the graph, and keep the images as nodes as well.

I guess my question is: is there a way to generate a graph that includes both images and text? 

I would be grateful for any help, or if there is an example or method already out there, you would be so kind as to point me to it. 

Thank you so much for your time.

**Comment by LalaLuna22** [comment]
Hi @vasturiano thank you so much for getting back to me. 

I apologize for the lack of clarity in my previous post, I have gone over the examples in the library and I have figured it out. 

I just needed to fetch the images from the .json file instead of using the method from the "images as nodes" example. 

Thank you so much for this amazing library!
