### ISSUE TITLE
When adding text in links THREE.Matrix3: .getInverse() can't invert matrix, determinant is 0

### ISSUE THREAD

**Issue by Alexithemia** [vasturiano/3d-force-graph#354]
**Describe the bug**
Adding text sprites to links causes this warning to appear repeatedly.

**To Reproduce**
I cannot get it to reproduce in a JSfiddle or on your text in link example, it may have to do with something else I am doing with my graph, but this warning only started when adding these link text sprites.

**Expected behavior**
It works and has no errors but repeats this error thousands of times.

**Screenshots**
![image](https://user-images.githubusercontent.com/44597137/88962020-72592580-d26b-11ea-9b0d-3a9370eceba6.png)

 - OS: Windows 10
 - Browser: Chrome
 - Version: 84.0.4147.89

**Additional context**
It works fine I would just like to remove the warning from appearing. It probably has something to do with my personal setup, but I am unsure of where to start.

Edit: The screenshot is of the 2D graph, but the issue happens in 3D only, and the warnings seem to reduce performance.

**Comment by vasturiano** [comment]
Hi @Alexithemia, 

I would expect to see the same warnings on [this example](https://vasturiano.github.io/3d-force-graph/example/img-nodes/), but that doesn't seem to be the case.

Maybe it's related to the `threeJs` version in your application. Do you per change have multiple versions of `three` in your dependency tree?

**Comment by Alexithemia** [comment]
I was using an older version of three, I updated to to same version as 3d-force-graph is using and it fixed it. Thank.s
