### ISSUE TITLE
Display nodes with image sprites and other nodes with geometries?

### ISSUE THREAD

**Issue by LalaLuna22** [vasturiano/3d-force-graph#361]
Hi, I am trying to make a graph from a dataset, where some nodes would have an image and other nodes would be created with a simple geometry, perhaps identified by groups (so nodes "group" : 1 = displayed with nodes as images and nodes "group":2 displayed with a sphere geometry).

I have looked at the examples in the main page,  "images as nodes" and "custom node geometries" but I can't figure out how I could separate my nodes by groups and then assign them images or geometry accordingly. 

I believe I  would need an if statement to implement this but I'm at a loss of how/where to place the if statement to make two different meshes?  

By looking at the "custom node geometries" I see an array inside the new mesh containing just the geometries, and in the "images as nodes"  a "const obj" contains the mesh object to which then we can add a child sprite with the image. With these two examples I was trying to find a way to merge them, but as I mentioned above, I can't figure out how to do it.

I add both codes I was looking at for clarity's sake:

1. Custom geometries:
` .nodeThreeObject(({ id }) => new THREE.Mesh(
          [
          array of geometries
          ]`

2. Images as nodes:
` .nodeThreeObject(({ img }) => {

         const obj = new THREE.Mesh(
          new THREE.SphereGeometry(7),
          new THREE.MeshBasicMaterial({ depthWrite: false, transparent: true, opacity: 0 })
        );
        const imgTexture = new THREE.TextureLoader().load(`./imgs/${img}`);
        const material = new THREE.SpriteMaterial({ map: imgTexture });
        const sprite = new THREE.Sprite(material);
        sprite.scale.set(12, 12);
        obj.add(sprite);
`

I am a rookie when it comes to three.js programming and I was hoping somebody could point me to the right direction regarding structure/syntax to implement this function, if its even possible? 

Thank you so much in advance for any help, much appreciated!

**Comment by vasturiano** [comment]
@LalaLuna22 thanks for reaching out.

You should be able to put that conditional inside the `nodeThreeObject` method, something like:

```js
.nodeThreeObjects(node => {
  if (isAnImage(node)) { // this conditional is your implementation
    // return image code
  } else {
    // return geometry code
  }
})
```

**Comment by LalaLuna22** [comment]
@vasturiano your example was great and it was such a simple solution!  

Thank you so much for taking time to help a newbie!
