### ISSUE TITLE
Get all nodes in a graph

### ISSUE THREAD

**Issue by nitzanorchestra** [vasturiano/3d-force-graph#367]
Is it possible to get all nodes in the graph? 
What about the center-point of the graph? 

Thanks.

**Comment by Alexithemia** [comment]
By default center point should always be 0,0,0 unless you have changed the forces.

You can get all nodes by using the getting method of .graphData

`myGraph.graphData().nodes`

**Comment by RaulPROP** [comment]
If by any chance by center point you mean the point that the camera is looking at, you can get it with `graph.controls().target;`

**Comment by nitzanorchestra** [comment]
thanks, will try those.
