### ISSUE TITLE
add onGraphClick event

### ISSUE THREAD

**Issue by nitzanorchestra** [vasturiano/3d-force-graph#369]
I need to unselect node after I selected it using 'onNodeClick' event, but I can't find event for board click. Is there an option to add an event which capture the graph canvas click itself? or any unfocus?

**Comment by Alexithemia** [comment]
I don't think there is any internal functionality for selecting node, just clicking them fires a specified function.

**Comment by nitzanorchestra** [comment]
yes, but I want to 'unfocus' for them and discovered I can't do that, thus, I need a listener on the graph canvas itself.

**Comment by RaulPROP** [comment]
The event for clicking the background is `onBackgroundClick` [as explained here](https://github.com/vasturiano/3d-force-graph#interaction).

**Comment by nitzanorchestra** [comment]
thanks, working!
