### ISSUE TITLE
Screen2GraphCoords

### ISSUE THREAD

**Issue by Alexithemia** [vasturiano/3d-force-graph#371]
I know you put the other method in a few months ago at my request, but I am hoping to put in a way to create nodes at a specific selected location.

Possibly just a raycaster.setFromCamera(clickedPoint, camera), and the user could provide or use a default distance to get a point on the raycaster with raycaster.ray.at(distance);

I have this working in my graph this way, just thought it may be worth including.

**Comment by vasturiano** [comment]
@Alexithemia I've just added this utility method. It has the signature:
```js
screen2GraphCoords(x, y, distance)
```
As for the default distance, I left it at`0`. The value really depends from case to case, so setting a fixed one will probably just introduce more confusion than help.

And thanks for the feature request!
