### ISSUE TITLE
Sticky tooltip

### ISSUE THREAD

**Issue by MajorCarrot** [vasturiano/3d-force-graph#374]
Is there a way to have the tooltip text shown below the node on hover currently, be visible always?

So there is a node and the tooltip text below that for all nodes at all times.

**Comment by vasturiano** [comment]
@MajorCarrot you can build a node using `.nodeThreeObject` that includes your text in it. Like in this example:
https://vasturiano.github.io/3d-force-graph/example/text-nodes/

Using `nodeThreeObjectExtend(true)` you can choose to maintain the original node shape and extend it with the text.

**Comment by MajorCarrot** [comment]
Ah. Thanks!
