### ISSUE TITLE
Question: Make `linkThreeObject` and `linkMaterial` work together

### ISSUE THREAD

**Issue by jakubbania** [vasturiano/3d-force-graph#375]
Hi, I have noticed an interaction that bugs me and does not allow for both `linkThreeObject` and `linkMaterial` to work together. 

**What I would like to achieve?**
Dashed line, that displays text in links.

**What do I know about the problem so far**
By debugging these two link methods, I have noticed that both of them require `linkPositionUpdate` to do stuff as described below:
- `linkMaterial` requires calling `computeLineDistances` to display dashed material properly,
- `linkThreeObject` requires calculation of middlePos that needs to be assigned to sprite object

The issue is, that depending on one of the above, 
- `linkObject` in `linkPositionUpdate` is either `Line` (when linkMaterial is being used) 
- or `Sprite` (when linkThreeObject is being used). 

Sprite does not have `computeLineDistances` method and I didnt find a way to access `Line` inside `Spirte`, when using both of mentioned methods. If I try to do both, the following error appears, which I think confirms my theory
```
Uncaught TypeError: lineObj.computeLineDistances is not a function
```

I have illustrated this problem in a short fiddle, combining code from: 
https://vasturiano.github.io/3d-force-graph/example/text-links/ 
and #224 

https://jsfiddle.net/b9h5ad7w/

**Question**
How can I make this work? 
Could you please provide some insights on how to solve this issue or make my case work

**Comment by Alexithemia** [comment]
Did you use .linkThreeObjectExtend(true)? and I'm not sure about processing order but I would try making the links dashed first, by calling .linkMaterial then .linkThreeObject if you haven't already

**Comment by jakubbania** [comment]
Yes, as shown in fiddle: `linkThreeObjectExtend` is set to true. Changing order of these metods doesn't really help contribute to the final result - the only thing it does it 'silences' the error message.

**Comment by Alexithemia** [comment]
Since the object is extended, there are two line objects on the links. Luckily, the link itself is provided as the third variable passed to the link position update function. You can dive down into the link to get to the correct object and run `computeLineDistances` there. 

`.linkPositionUpdate((sprite, {start, end}, link) => {
          const middlePos = Object.assign({}, ...['x', 'y', 'z'].map(c => ({
          	[c]: start[c] + (end[c] - start[c]) / 2
          })));
          link.__lineObj.children[0].computeLineDistances() 
          Object.assign(sprite.position, middlePos);
        })`

FIddle
https://jsfiddle.net/cqtrw7y3/8/

**Comment by jakubbania** [comment]
Love it, that solves the problem, thanks! 
A bit of diving down is required, yeah, I still need to check if any corner cases apply that this third variable wont be there.
