### ISSUE TITLE
Permanent link's width regardless of camera position / zoom 

### ISSUE THREAD

**Issue by nitzanorchestra** [vasturiano/3d-force-graph#378]
Is there a way to set link width but to keep it always at the same width regardless of the camera position / zoom? 

thanks.

**Comment by Alexithemia** [comment]
I mean it does stay the same, it just looks smaller due to perspective. If you wanted it to look the same at all time you would need to change its size constantly depending on the distance from the camera.

**Comment by nitzanorchestra** [comment]
Isn't there easier solution like a zero value (taken from the documentation): "A value of zero will render a ThreeJS Line whose width is constant (1px) regardless of distance"

**Comment by vasturiano** [comment]
@nitzanorchestra in the constant width mode (`linkWidth = 0`) Three's `LineBasicMaterial ` is used to style the line.
As you can [see here](https://threejs.org/docs/#api/en/materials/LineBasicMaterial.linewidth) even though this material has a `linewidth` attribute it is always 1 (px) due to WebGL limitations. That's why it's not possible to change the constant width.

> Due to limitations of the OpenGL Core Profile with the WebGL renderer on most platforms linewidth will always be 1 regardless of the set value.

**Comment by nitzanorchestra** [comment]
So you say even if I make a pr to your library regarding that line's width it won't work because of openGL limitations?

**Comment by vasturiano** [comment]
@nitzanorchestra these are good questions to ask the maintainers of ThreeJs. They will have more insight about possible workarounds than in this lib.

**Comment by nitzanorchestra** [comment]
They gave me this example, not using basic Line 
https://threejs.org/examples/webgl_lines_fat
I'll further research it, and update here for other people looking for the same thing in the future.

**Comment by nitzanorchestra** [comment]
So, I'm trying to use a custom Line2 through linkThreeObject, but it to be problematic: 
Do I need to give it a position? if so, I use link.source/link.target but in sometimes it gives me the points and sometimes it gives the node names as a string, why is that?
