### ISSUE TITLE
Access active scene

### ISSUE THREAD

**Issue by tscgist** [vasturiano/3d-force-graph#38]
First, it is a fantastic application. 
My question: How is it possible to access the active scene?

**Comment by vasturiano** [comment]
@tscgist thanks for reaching out. If you intend to do manipulation on the scene level, I'd recommend switching to using the lower level component [three-forcegraph](https://github.com/vasturiano/three-forcegraph). You'll have to maintain the Three renderer/scene scaffolding yourself but that sounds like it's exactly what you're looking for.
**3d-force-graph** is mainly a convenience wrapper of the above if you don't want to be bothered with the Three configuration and are looking for a smart default higher-level expression of the component.
Let me know if that works for you.

**Comment by tscgist** [comment]
Thank you for your fast answer. I found a way to access the scene myself. I just added a new graph method to return the scene the same way the camera position is returned.

**Comment by piaaaac** [comment]
@tscgist could you share how you did that?

**Comment by vasturiano** [comment]
An update on this, from `v1.30.0` on, there is a new method exposed: `scene()`. This can be used to access the ThreeJS scene and extend it with other objects.
