### ISSUE TITLE
how to change navigationInfo?

### ISSUE THREAD

**Issue by SepidehAlassi** [vasturiano/3d-force-graph#380]
This is basically a question:

I would like to change the `navigationInfo`, but I could not find how to do it in the documentation. 
By default, the `navigationInfo` shows `Right-click:pan`. However, I am using the right-click for another purpose (opening a webpage), and I would like to update the `navigationInfo` accordingly.
Can you please tell me how to do it?

**Comment by vasturiano** [comment]
@SepidehAlassi thanks for reaching out.

For this I would recommend switching off the default navigation info note (using `showNavInfo(false)`) and writing your own custom one externally that you can overlay with the graph canvas.

**Comment by SepidehAlassi** [comment]
@vasturiano I see, thanks for the quick reply.
