### ISSUE TITLE
Display node label in a fixed position 

### ISSUE THREAD

**Issue by IndexCollapsingMemory** [vasturiano/3d-force-graph#386]
I have kind of long node labels and I would love to be able to display them in a fixed position in the graph canvas, maybe using "onNodeHover" or "onNodeClick" event. 

Is there a way to achieve this? 

I have tried like this:
`.nodeLabel(node => `<span style="border:1px black solid; background-color: black; color: yellow;  vertical-align:text-top;" >${node.object} <br><br> ${node.description}</span>`)`

As it is dependent on where the mouse is, it overrides any positions I try to give it. 
I don't know how I could go around achieving this, any help is greatly appreciated! 

Thank you!

**Comment by RaulPROP** [comment]
You can use the `onNodeHover` function to get the name to display and use a custom HTML element to display it [as shown here](https://codepen.io/raulprop/pen/ZEWjzQG?editors=1111).

**Comment by IndexCollapsingMemory** [comment]
@RaulPROP Thank you so much, that worked perfectly! 

It was so very helpful to see an example on how to implement the `onNodeHover` function! 

Really appreciated your help and quick response.
