### ISSUE TITLE
Changing nodes and edges

### ISSUE THREAD

**Issue by tscgist** [vasturiano/3d-force-graph#39]
Hi, is it possible to change nodes and edges without forcing to reload the graph?
I try to change the size of a single node by using an external event which triggers the graph. 

Everything works fine, but **graphData** forces the graph to reload. Only the weight of nodes has changed. No further nodes where added or edges changed etc. 

Any idea how to prevent the graph from reloading.

**Comment by vasturiano** [comment]
@tscgist if you're using the default force engine `d3` the graph should not reset the nodes positions, but simply re-heat the simulation, when calling node/link accessor methods.
The same is true for when feeding new data dynamically. Here's an example of that:
https://vasturiano.github.io/3d-force-graph/example/dynamic/

If you wish to not even have the simulation be re-heated on updates, then I'd suggest to prepend your update calls with `.cooldownTicks(0)`. This will tell the engine not to run any ticks from that point forth. Here's a codepen illustrating that:
https://codepen.io/vasturiano/pen/VXvEPw

Please keep in mind that this is only applicable for the `d3` engine, as `ngraph` does not support memorizing the position of nodes between updates and always resets.

**Comment by tscgist** [comment]
Ah. That is really cool.
