### ISSUE TITLE
Multiple edges with same source and target

### ISSUE THREAD

**Issue by fabianschn** [vasturiano/3d-force-graph#392]
Is it possible to have multiple edges with same source and target displayed as different edges?

The only thing I managed to do is having two edges with reversed source and target (one edge from A -> B and one from B -> A) using the .linkCurvature() method. When having same source and target the .linkCurvature() has no effect.

**Comment by fabianschn** [comment]
Never mind. Found it [here](https://vasturiano.github.io/3d-force-graph/example/curved-links/).

**Comment by RaulPROP** [comment]
It is true that, by default, two links with the same source and target will cause the same link.

However, you can have an extra parameter that can differentiate those links and use that parameter in the `linkCurvature` function [like this](https://codepen.io/raulprop/pen/wvGQdeP?editors=0011).
