### ISSUE TITLE
Limit scene to certain height and width

### ISSUE THREAD

**Issue by nitzanorchestra** [vasturiano/3d-force-graph#397]
**Is your feature request related to a problem? Please describe.**
I want the graph nodes stay within boundary of certain height and width. 

**Describe the solution you'd like**
An option to set scene equals to graph's height and width.

**Comment by vasturiano** [comment]
@nitzanorchestra the graph coordinates system is decoupled from the screen coordinates system. You can convert from graph coordinates to screen coordinates using the utility function `graph2ScreenCoords(x, y, z)`.

If you wish to alter the zooming at any point to make all your nodes fit within the canvas, you can use the convenience method `zoomToFit()`.

On the other hand, if you actually want to introduce container-like forces that prevent the nodes from going outside a certain box (in graph coordinates), I recommend you look at [d3-force-limit](https://github.com/vasturiano/d3-force-limit).

**Comment by nitzanorchestra** [comment]
thanks.
