### ISSUE TITLE
Question -> Text in links, how can I position text in curved links?

### ISSUE THREAD

**Issue by MardariG** [vasturiano/3d-force-graph#398]
This is how my graph looks right now, the text from both links is in the middle of the straight one.

![image](https://user-images.githubusercontent.com/8759158/95747362-fb93cc00-0ca0-11eb-8492-49552e77a8f4.png)

How can I position them correctly? Thanks!

**Comment by vasturiano** [comment]
@MardariG thanks for reaching out.

I suppose you're using `linkThreeObject` to generate the text for the links. And if so, then you must be defining a position for those items via a `linkPositionUpdate` method. In this method you can specify the position of your custom link elements according to your own custom logic.

**Comment by MardariG** [comment]
@vasturiano 

 I thought maybe there is an example or someone implemented this. I will try to implement it myself. Thank you, great library!
