### ISSUE TITLE
Access State Data and expose tbControls in the State

### ISSUE THREAD

**Issue by roonie007** [vasturiano/3d-force-graph#40]
Hey @vasturiano ,

Is it possible to add a methode that will expose the objects in the state ?

The camera, the scene ?

```javascript 
methods: _extends({
  getState: function getState(state) {
    return state;
  },
  cameraPosition: function cameraPosition(state, position) {
    // Setter
    if (position) {
      var x = position.x,
          y = position.y,
          z = position.z;

      if (x !== undefined) state.camera.position.x = x;
      if (y !== undefined) state.camera.position.y = y;
      if (z !== undefined) state.camera.position.z = z;
      state.camera.lookAt(state.forceGraph.position);
      return this;
    }

    // Getter
    return state.camera.position;
  },
  stopAnimation: function stopAnimation(state) {
    if (state.animationFrameRequestId) {
      cancelAnimationFrame(state.animationFrameRequestId);
    }
    return this;
  }
}, linkedFGMethods),
```

and could you also add the tbControls to the state so that we can control the Camera LookAt ? 

```javascript
var tbControls = new threeTrackballcontrols(state.camera, state.renderer.domElement);
state.tbControls = tbControls;
state.renderer.setSize(state.width, state.height);
state.camera.far = 20000
```

Thanks

**Comment by vasturiano** [comment]
@roonie007 if you wish to manipulate the three elements directly, I'd recomend switching to [three-forcegraph](https://github.com/vasturiano/three-forcegraph). That will provide you with just the force directed graph itself as a Three Object3D element which you can include in your scene as you see fit.
`3d-force-graph` is mainly a convenience wrapper that takes care of that scaffolding with some smart defaults.
Having said that, if you wish to control the camera position and direction, that is actually possible in `3d-force-graph` using the method `.cameraPosition([{x,y,z}],[lookAt])`.
