### ISSUE TITLE
Responsive 3rd-force graph 

### ISSUE THREAD

**Issue by cnrajahp** [vasturiano/3d-force-graph#400]
I am looking for responsive 3rd-force graph canvas, could help if any body know/have a solution.

**Comment by vasturiano** [comment]
@cnrajahp thanks for reaching out.

This functionality is beyond the scope of this library, but you can easily use a 3rd party module to monitor window resize events and inject `width` and/or `height` properties into `3d-force-graph`.

For example, if you would use [element-resize-detector](https://github.com/wnr/element-resize-detector) to pick one, you would just need to do something like:
```js
const Graph = ForceGraph3D()
  (document.getElementById('3d-graph'));

elementResizeDetectorMaker().listenTo(
  document.getElementById('3d-graph'),
  el => Graph.width(el.offsetWidth)
);
```

[Here is an example](https://vasturiano.github.io/3d-force-graph/example/responsive/) of this setup, and you can find the [example code here](https://github.com/vasturiano/3d-force-graph/blob/master/example/responsive/index.html).

**Comment by cnrajahp** [comment]
@vasturiano  thank you for your solution, it working fine
