### ISSUE TITLE
Responsive height for a 3rd-force graph

### ISSUE THREAD

**Issue by cnrajahp** [vasturiano/3d-force-graph#403]
Hi,

I got the following solution for responsive 3rd-force graph canvas, this is only responsive on width.
could please help if anybody knows/have a solution for height.

const Graph = ForceGraph3D()
  (document.getElementById('3d-graph'));

elementResizeDetectorMaker().listenTo(
  document.getElementById('3d-graph'),
  el => Graph.width(el.offsetWidth)
);

Thanks,
Raja

**Comment by RaulPROP** [comment]
[As vAsturiano said in this reply to your issue](https://github.com/vasturiano/3d-force-graph/issues/400#issuecomment-708910734):

Just as you can update the `width` property by calling it from the `Graph` object, you can update the `height` with `Graph.height`:

```js
const Graph = ForceGraph3D()(document.getElementById('3d-graph'));

elementResizeDetectorMaker().listenTo(
    document.getElementById('3d-graph'),
    (el) => {
        Graph.width(el.offsetWidth);
        Graph.height(el.offsetHeight);
    }
);
```

**Comment by cnrajahp** [comment]
@RaulPROP thank you, it's working fine
