### ISSUE TITLE
Link length based on link attribute

### ISSUE THREAD

**Issue by G-IsTheName** [vasturiano/3d-force-graph#404]
Is there a way to control each link length?
I'm adding another **attribute** name Value (or maybe Length) to base the length of the line/link. 

  "links": [
    {"source": "1", "target": "2", "value": 2},
    {"source": "1", "target": "3", "value": 6},
    {"source": "1", "target": "4", "value": 10},
    {"source": "4", "target": "8", "value": 2}
  ]

Is there a way to get the data from the **attribute Value**?

Thanks in advance!
BTW Great work!

**Comment by vasturiano** [comment]
@G-IsTheName please see this example: https://vasturiano.github.io/3d-force-graph/example/manipulate-link-force/

**Comment by G-IsTheName** [comment]
> @G-IsTheName please see this example: https://vasturiano.github.io/3d-force-graph/example/manipulate-link-force/

Sorry, I'm new to this. This really doesn't answer my question.
This example uses data from the GUI, not from jsonURL database.

**Comment by vasturiano** [comment]
You can find the source for that example here: https://github.com/vasturiano/3d-force-graph/blob/master/example/manipulate-link-force/index.html

But in a simple way you can manipulate the distance of each link by doing:
```js
myForceGraph.d3Force('link').distance(link => /* your logic */)
```

The docs for that distance method can be found [here](https://github.com/vasturiano/d3-force-3d#link_distance).

**Comment by G-IsTheName** [comment]
I manage to solve the problem. I used the below code to get the attribute "value" of nodes from the db-ref.json

> 	  const linkForce = Graph
> 	  	.d3Force('link')
> 	  	.distance(link => link.value)
