### ISSUE TITLE
Include current build in "dist" folder within package

### ISSUE THREAD

**Issue by Plarixtu** [vasturiano/3d-force-graph#41]
Would it be possible to include the current build within "dist" folder in the package, so you do not have to build it yourself in case you don't want to install all the building tools on your machine?

**Comment by vasturiano** [comment]
@Plarixtu I prefer not to commit the dist folder to the repo, has it's mainly focused on the source code. If you wish to access the build files, you can get them through the npm registry, as they are published there. 
Doing `npm install 3d-force-graph` should include the dist folder.
