### ISSUE TITLE
Shape / layout of the whole viz - Can we get globe like experience?

### ISSUE THREAD

**Issue by JeevanSekar** [vasturiano/3d-force-graph#411]
With the same blocks.json data , I am able to get that globe like look. It is wicked awesome. 

But when I added my own data , the layout changed to something like in https://vasturiano.github.io/3d-force-graph/example/basic/

Anyway we can achieve this?

**Comment by JeevanSekar** [comment]
Any answer on this please?

**Comment by vasturiano** [comment]
@JeevanSekar the final state of the graph highly depends on the nature of the data itself, and the topology of how the nodes are interconnected.

For the blocks example what makes it get that shape is the fact that there's a lot of disconnected sub-graph segments, therefore the nodes tend to occupy the space uniformly, expanding outwards in a spherical manner.

The other example you mentioned is more like a tree structure, so possibly your data has a similar topology.

**Comment by JeevanSekar** [comment]
Thank you
