### ISSUE TITLE
Graph Tooltip - floating border or padding

### ISSUE THREAD

**Issue by ZanQ** [vasturiano/3d-force-graph#415]
Hi, so I've followed up on another thread and added rss changes to the .scene-tooltip, but now the canvas has a floating border whenever the cursor is not on a Node or Link.

```
.scene-tooltip {
    position: relative;
    left: 30px;
    border: 3px solid #73AD21;
    color: rgb(0, 0, 0) !important;
    border-radius: 3px;
    padding: 10px;
    text-align: center;
}
```

Is there another way around this? 

Thanks in Advance.

<img width="311" alt="Untitled" src="https://user-images.githubusercontent.com/23181580/101931857-3af27200-3b97-11eb-89dc-33e024ed0e2e.png">

<img width="407" alt="Untitled 2" src="https://user-images.githubusercontent.com/23181580/101931862-3c239f00-3b97-11eb-8b02-24d1cc5f463c.png">

**Comment by RaulPROP** [comment]
What I did in [this example](https://codepen.io/raulprop/pen/NWrQZBX?editors=0111) was to wrap the label in a `span`, and then style that `span`. By doing that, when there is no node hovered, the label is an empty `div`, but when a node is hovered it has the style that you want.

**Comment by ZanQ** [comment]
Worked perfect, thanks Raul!
