### ISSUE TITLE
Appearing blink on node/link hover . 

### ISSUE THREAD

**Issue by shashidhar568** [vasturiano/3d-force-graph#417]
I tried adding 3d object with nodeThreeObject and then added  https://vasturiano.github.io/3d-force-graph/example/highlight/ feature to it . Then, after hovering on node/link there was a blink appearing on graph .

![Screenshot from 2020-12-14 19-01-57](https://user-images.githubusercontent.com/20983972/102087006-ed982e00-3e3e-11eb-9a22-63bf72a9606d.png)

Below is the code  : 

index.html : 
<html>
<head>
    <style>
        body {
            margin: 0;
        }
    </style>
    <link rel="stylesheet" href="../dist/entity-universe.umd.css">
</head>
<body style="background: black;">
    <script>   
        window.onload = function () {
            // Generate random tree
            const N = 30;
            const groups = ['entities', 'groups', 'contexts', 'engagements']
            const gData = {
                nodes: [...Array(N).keys()].map(i => ({ id: i, group: groups[i % 4] })),
                links: [...Array(N).keys()]
                    .filter(id => id)
                    .map(id => ({
                        source: id,
                        target: Math.round(Math.random() * (id - 1))
                    }))
            };
            var ent = new EntityUniverse("3d-graph", gData);
        }
    </script>
    <script src="../dist/entity-universe.umd.js"></script>
</body>
</html>

The below is my .ts file : 

import * as THREE from 'three'
import ForceGraph3D from '3d-force-graph'

class EntityUniverse {
  graph: any
  // highlightNodes: any
  highlightLinks: any
  hoverNode: any
  hoverLink: any
  constructor(domId: string, data: any) {
    this.highlightLinks = new Set()
    this.hoverNode = null
    this.hoverLink = null
    this.init(domId, data)
  }

  updateHighlight() {
    // trigger update of highlighted objects in scene
    this.graph
      .linkWidth(this.graph.linkWidth())
      .linkDirectionalParticles(this.graph.linkDirectionalParticles())
  }

  init(domId, gData: any) {
    gData.links.forEach((link: any) => {
      const a = gData.nodes[link.source]
      const b = gData.nodes[link.target]
      !a.neighbors && (a.neighbors = [])
      !b.neighbors && (b.neighbors = [])
      a.neighbors.push(b)
      b.neighbors.push(a)
      !a.links && (a.links = [])
      !b.links && (b.links = [])
      a.links.push(link)
      b.links.push(link)
    })

    // render force graph
    this.graph = ForceGraph3D()(document.getElementById(domId))
      .nodeThreeObject(({ id }: any) => {
        const texture = new THREE.TextureLoader().load('https://static.remove.bg/sample-gallery/graphics/bird-thumbnail.jpg')
        texture.minFilter = THREE.LinearFilter
        const material = new THREE.MeshLambertMaterial({ map: texture, opacity: 0.8, transparent: true })
        const mesh = new THREE.Mesh(
          [
            new THREE.BoxGeometry(20, 20, 20),
            new THREE.ConeGeometry(10, 20),
            new THREE.CylinderGeometry(10, 10, 20),
            new THREE.SphereGeometry(10),
          ][id % 4], material
        )
        return mesh
      })
      .graphData(gData)
      .nodeLabel((d: any) => {
        return `<span style="color: white">${d.group}</span>`
      })
      .linkWidth((link: any) => this.highlightLinks.has(link) ? 4 : 1)
      .linkDirectionalParticles(link => this.highlightLinks.has(link) ? 4 : 0)
      .linkDirectionalParticleWidth(4)
      .onNodeHover((node: any) => {
        // no state change
        if ((node && this.hoverNode === node)) {
          return
        }

        this.highlightLinks.clear()
        if (node) {
          node.links.forEach((link: any) => this.highlightLinks.add(link))
        }

        this.hoverNode = node || null

        this.updateHighlight()
      })
      .onLinkHover((link) => {
        if ((!link && !this.highlightLinks.size) || (link && this.hoverLink === link)) {
          return
        }
        this.highlightLinks.clear()
        if (link) {
          this.highlightLinks.add(link)
        }
        this.hoverLink = link || null
        this.updateHighlight()
      })
  }
}

**Comment by shashidhar568** [comment]
This is version issue

**Comment by pc4ucode** [comment]
> I tried adding 3d object with nodeThreeObject and then added https://vasturiano.github.io/3d-force-graph/example/highlight/ feature to it . Then, after hovering on node/link there was a blink appearing on graph .
> 
> ![Screenshot from 2020-12-14 19-01-57](https://user-images.githubusercontent.com/20983972/102087006-ed982e00-3e3e-11eb-9a22-63bf72a9606d.png)
> 
> Below is the code :
> 
> index.html :
> 
> <style> body { margin: 0; } </style> <script> window.onload = function () { // Generate random tree const N = 30; const groups = ['entities', 'groups', 'contexts', 'engagements'] const gData = { nodes: [...Array(N).keys()].map(i => ({ id: i, group: groups[i % 4] })), links: [...Array(N).keys()] .filter(id => id) .map(id => ({ source: id, target: Math.round(Math.random() * (id - 1)) })) }; var ent = new EntityUniverse("3d-graph", gData); } </script> <script src="../dist/entity-universe.umd.js"></script>
> The below is my .ts file :
> 
> import * as THREE from 'three' import ForceGraph3D from '3d-force-graph'
> 
> class EntityUniverse { graph: any // highlightNodes: any highlightLinks: any hoverNode: any hoverLink: any constructor(domId: string, data: any) { this.highlightLinks = new Set() this.hoverNode = null this.hoverLink = null this.init(domId, data) }
> 
> updateHighlight() { // trigger update of highlighted objects in scene this.graph .linkWidth(this.graph.linkWidth()) .linkDirectionalParticles(this.graph.linkDirectionalParticles()) }
> 
> init(domId, gData: any) { gData.links.forEach((link: any) => { const a = gData.nodes[link.source] const b = gData.nodes[link.target] !a.neighbors && (a.neighbors = []) !b.neighbors && (b.neighbors = []) a.neighbors.push(b) b.neighbors.push(a) !a.links && (a.links = []) !b.links && (b.links = []) a.links.push(link) b.links.push(link) })
> 
> ```
> // render force graph
> this.graph = ForceGraph3D()(document.getElementById(domId))
>   .nodeThreeObject(({ id }: any) => {
>     const texture = new THREE.TextureLoader().load('https://static.remove.bg/sample-gallery/graphics/bird-thumbnail.jpg')
>     texture.minFilter = THREE.LinearFilter
>     const material = new THREE.MeshLambertMaterial({ map: texture, opacity: 0.8, transparent: true })
>     const mesh = new THREE.Mesh(
>       [
>         new THREE.BoxGeometry(20, 20, 20),
>         new THREE.ConeGeometry(10, 20),
>         new THREE.CylinderGeometry(10, 10, 20),
>         new THREE.SphereGeometry(10),
>       ][id % 4], material
>     )
>     return mesh
>   })
>   .graphData(gData)
>   .nodeLabel((d: any) => {
>     return `<span style="color: white">${d.group}</span>`
>   })
>   .linkWidth((link: any) => this.highlightLinks.has(link) ? 4 : 1)
>   .linkDirectionalParticles(link => this.highlightLinks.has(link) ? 4 : 0)
>   .linkDirectionalParticleWidth(4)
>   .onNodeHover((node: any) => {
>     // no state change
>     if ((node && this.hoverNode === node)) {
>       return
>     }
> 
>     this.highlightLinks.clear()
>     if (node) {
>       node.links.forEach((link: any) => this.highlightLinks.add(link))
>     }
> 
>     this.hoverNode = node || null
> 
>     this.updateHighlight()
>   })
>   .onLinkHover((link) => {
>     if ((!link && !this.highlightLinks.size) || (link && this.hoverLink === link)) {
>       return
>     }
>     this.highlightLinks.clear()
>     if (link) {
>       this.highlightLinks.add(link)
>     }
>     this.hoverLink = link || null
>     this.updateHighlight()
>   })
> ```
> 
> } }

About the node comment blinking, I'm also having the same problem in the implementation here in my project

I started to implement a project using the graphic with image as nodes, when I do some interaction to change the color of the node, the node starts blinking

![image](https://github.com/vasturiano/3d-force-graph/assets/45580393/615e662e-0861-4396-98ec-1ecea5abcd85)


Here's a basic demo I did on Stackblitz:
https://stackblitz.com/edit/github-qxfmyz?file=src%2Fmain.ts

In the demo, I made an interaction when I click on the node it changes color, indicating that this node is selected, sometimes this interaction is making the nodes of the graph blink

@vasturiano and @shashidhar568  did you manage to find a solution?
