### ISSUE TITLE
How to run without Local Server ?

### ISSUE THREAD

**Issue by Heidernlee** [vasturiano/3d-force-graph#419]
Hi, I've checked the following issue
https://github.com/vasturiano/3d-force-graph/issues/192

and now I know it worked on Local Server.
but since it's based on JavaScript , can I run it without local server but only Browser ?
I downloaded [3d-force-graph.min.js] and import it like this : 
[<script src="3d-force-graph.min.js"></script>] for [/example/click-to-focus/index.html].

but there's only [Loading...] showed up on the Chrome, Should I do something else ?

**Comment by RaulPROP** [comment]
In order to use any example in local you just need to comment the `unpkg` import and uncomment the local one (`../../dist/3d-force-graph.js`).

The [click-to-focus](https://github.com/vasturiano/3d-force-graph/blob/master/example/click-to-focus/index.html) head should look like this:

```js

<head>
  <style> body { margin: 0; } </style>

  <!--<script src="//unpkg.com/3d-force-graph"></script>-->
  <script src="../../dist/3d-force-graph.js"></script>
</head>

```

**Comment by Heidernlee** [comment]
@RaulPROP 
Thanks for your response. 
Did I download the wrong sourcecode ?
there's no [/dist] folder on master-branch.
and only a 15kb [3d-force-graph.js] file in the [/src] folder

**Comment by RaulPROP** [comment]
That's because the `dist` folder is created once the project is compiled.

You need to run `npm run build` for that.

**Comment by Heidernlee** [comment]
@RaulPROP 
Thanks for the reponse.
Turns out, Chrome cannot load json file from Local Machine, It has to be a Local Server.....
Now I finally got a reason to use IE Edge... It's OK
