### ISSUE TITLE
seems this example no longer work...

### ISSUE THREAD

**Issue by wizzhi** [vasturiano/3d-force-graph#420]
nothing rendered for now while it was working few weeks ago.

**Comment by wizzhi** [comment]
I mea the example of "Bloom Post-Processing Effect" at https://vasturiano.github.io/3d-force-graph/example/bloom-effect/

**Comment by NickSchmitt** [comment]
Seems to be a problem with `Graph.postProcessingComposer`. @vasturiano any idea what the issue might be or any workarounds?

**Comment by vasturiano** [comment]
There was an incompatibility with the newly released version on the `UnrealBloomPass` from ThreeJS `0.124.0`. I've upgraded `three` within this module to the latest version which should fix the issue. 

Thanks for the heads up!

**Comment by wizzhi** [comment]
cool, it is working happily now.

**Comment by jmiguelv** [comment]
Hi, this issue seems to be back with version `0.128.0` of `three`.

**Comment by vasturiano** [comment]
Thanks for the heads up @jmiguelv. This was a different error from before.
Switching the dynamic filter import in the example from `unpkg` to `skypack` fixes the issue.
