### ISSUE TITLE
How can I build 3d-force-graph from scratch?

### ISSUE THREAD

**Issue by ddooley** [vasturiano/3d-force-graph#427]
Are there instructions for how to make a local build of 3d-force-graph?  Having cloned it from github onto my Mac with Big Sur OS, when i run "npm install" it raises an error

    ...
    src/index.js → dist/3d-force-graph.js, dist/3d-force-graph.min.js...
    babelHelpers: 'bundled' option was used by default. It is recommended to configure this option explicitly, read more here: 
    https://github.com/rollup/plugins/tree/master/packages/babel#babelhelpers
    [!] (plugin node-resolve) TypeError: url.pathToFileURL is not a function
    TypeError: url.pathToFileURL is not a function

Pardon my naievity but I wasn't able to see from google searches what the "babel" problem was, except maybe having to do with ES5 vs ES6 coding differences.

Regards,

Damion

**Comment by vasturiano** [comment]
@ddooley thanks for reaching out.

The `babelHelpers` message is merely a warning and can be ignored.
But when I run `npm install` I can't replicate your `TypeError` from `node-resolve`. Are you still experiencing this issue? If so, which version of `node` and `npm` are you using?

**Comment by ddooley** [comment]
Ah.  I got npm updated on my computer and problem went away. 

Thanks, and sorry to trouble you.  

And p.s. I see that text sprites now have option of background, which is great.

Cheers,

Damion
