### ISSUE TITLE
How would one apply post-processing?

### ISSUE THREAD

**Issue by gdbassett** [vasturiano/3d-force-graph#43]
I'd like to try and apply aggressive depth of focus similar to http://shaderism.com/depth-of-field-with-custom-autofocus/ but am unsure of how to reference the THREE.js objects to do so.  Is there a defined way to do so?

**Comment by vasturiano** [comment]
Thanks for reaching out @gdbassett. I don't know much about that technique, so can't provide in depth advice. But the graph provides a means to specifying your own Three objects for nodes: `.nodeThreeObject()`. Here's a usage example: https://vasturiano.github.io/3d-force-graph/example/custom-node-geometry/

This lets you keep references to the Three objects and apply other processing.

Another (less obvious) way to find the three objects associated with each of your node/links is to actually look in your `graphData` structure. Each node/link should have an internal property called `__threeObj` which points to the associated three object.

```
{  
   "id":"1",
   "x":-15.31939841608478,
   "y":26.545855541061,
   "z":78.58912678726857,
   "__threeObj":{  
      "object":{  
         "geometry":"113588E2-1F6F-4495-AFFC-4B917B2B7C3C",
         "material":"F8B20FFC-3036-40B3-A59B-152A640D70DE",
          ...
      },
      ...
   },
   ...
}
```

Let me know if either way works for you.

**Comment by greennomad424242** [comment]
@vasturiano  could you indicate how to access those internal properties in code? 

I'm trying to access the underlying object's x,y, and z values. 

I'm having a weird situation where the code below returns an undefined when I call Graph.graphData().nodes[0].x  , but I'm able to get that value when I use the console (see attached image). 



      <script>
      var  Graph = ForceGraph3D();
   
       var data =[];
           fetch('not_miserables.json').then(res => res.json()).then(data => {
            Graph = ForceGraph3D()
            (document.getElementById('graph'))
        .graphData(data)
        .nodeId('id')
        .nodeVal('val')
        .nodeLabel('id')
        .nodeAutoColorBy('group')
        .linkSource('source')
        .linkTarget('target')
        .d3Force("link",
        d3.forceLink().strength(d => d.flow))
       .d3Force("charge", d3.forceManyBody().strength(-5));

    }).then(data =>{

      console.log(Graph.graphData().nodes[0]);
      console.log(Graph.graphData().nodes[0].x);

    });
   </script>


<img width="1078" alt="screen shot 2019-02-13 at 4 35 31 pm" src="https://user-images.githubusercontent.com/979533/52754211-901ac800-2fae-11e9-8840-aa21f6ab8f6f.png">

**Comment by vasturiano** [comment]
@greennomad424242 possibly it's a timing issue. I can't see the rest of your code, but when you're calling the `console.log`, it's possible that the force engine has not yet started and therefore not assigned the initial `x,y,z` attributes.
One way to be sure is to use the `onEngineTick()` first event to be sure the engine has started. :)
