### ISSUE TITLE
How to select node without .onNodeClick or .onNodeHover?

### ISSUE THREAD

**Issue by nathanturczan** [vasturiano/3d-force-graph#436]
I would like to select / highlight a node by the node's ID or index number. Does anyone have a thought as to how to accomplish this?

**Comment by RaulPROP** [comment]
Change the data accordingly and use the [`graph.refresh()`](https://github.com/vasturiano/3d-force-graph#render-control) function to redraw all the nodes.

**Comment by nathanturczan** [comment]
@RaulPROP there is no need to change any data or redraw the nodes, I simply want to "select" one of the nodes. Right now I am trying to modify the [Click To Focus](https://github.com/vasturiano/3d-force-graph/blob/master/example/click-to-focus/index.html) example, swapping out .onNodeClick() with a listener that is waiting for a "currentNode" variable to update. Rather than clicking on a node to focus on it, I would like to type in that node's ID to focus on it. Here's what I'm thinking:

`<script>
    const elem = document.getElementById('3d-graph');
    var currentNode = "someID"

    const Graph = ForceGraph3D()
      (elem)
        .jsonUrl('../datasets/miserables.json')
        .nodeLabel('id')
        .nodeAutoColorBy('group')
        .onNodeHover(node => elem.style.cursor = node ? 'pointer' : null);

    currentNode.registerListener(node => {
          // Aim at node from outside it
          const distance = 400;
          const distRatio = 1 + distance/Math.hypot(node.x, node.y, node.z);

          Graph.cameraPosition(
            { x: node.x * distRatio, y: node.y * distRatio, z: node.z * distRatio }, // new position
            node, // lookAt ({ x, y, z })
            3000  // ms transition duration
          );
        });

  </script>`

**Comment by RaulPROP** [comment]
What I meant by change the data was to change the variable that says which node is selected and then use that variable in the function that says what's the color of a node.

[I've made this codepen showing what I mean](https://codepen.io/raulprop/pen/wvoYMxP?editors=1011).

**Comment by nathanturczan** [comment]
Thank you so much @RaulPROP , super helpful!

**Comment by nathanturczan** [comment]
I'm trying to substitute the "nodeColor" functionality for a "focus camera on selected node" functionality, like in this example:

https://github.com/vasturiano/3d-force-graph/blob/master/example/click-to-focus/index.html

My goal is to use the dropdown in the top right to select the node, and then the camera focuses on that node.

I've got something kind of working (https://codepen.io/nathanturczan/pen/RwKERBP), but I don't think it's right to put camera functionality in the nodeColor function.

But I'm not sure how to go about this. Any advice?

**Comment by morLight** [comment]
try like this:
https://codepen.io/mor_light/pen/qBRLPmX?editors=1010

**Comment by nathanturczan** [comment]
Awesome, thank you @morLight !
