### ISSUE TITLE
Transparent background not working (see issue #24)

### ISSUE THREAD

**Issue by jlangner-hubble** [vasturiano/3d-force-graph#437]
Issue #24 has come back, and this is a blocker for me. If I use the following example code, there is never a transparent background on the canvas. Is this possible anymore?

```jsx
<ForceGraph3D
    rendererConfig={{
	    alpha: true,
    }}
    backgroundColor={'rgba(0,0,0,0)'}
    ref={fgRef}
    graphData={data}
/>
```

Is the above code wrong or missing something? Is there a new / alternate way to do this?

**Comment by vasturiano** [comment]
@jlangner-hubble is this example not working for you? 
https://codesandbox.io/s/force-graph-transparent-background-4t1db

**Comment by jlangner-hubble** [comment]
Yes that codepen works. Seeing that example caused me to take a step back... turns out that using the Bloomfilter (`import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass';`) was causing the issue! I'm going to dig into that and see if I can reconcile it.

**Comment by nikkwong** [comment]
Were you able to figure out how to apply a transparent background whilst keeping the bloom filter?

**Comment by jlangner-hubble** [comment]
@nikkwong sorry I haven't. I'm still curious if this is possible, but I wasn't able to do any further digging.
