### ISSUE TITLE
Access current alpha value

### ISSUE THREAD

**Issue by pournaki** [vasturiano/3d-force-graph#438]
I believe this is related to [this PR](https://github.com/vasturiano/three-forcegraph/pull/23).

My use-case is the following: I want to add a custom force to the system, which depends on the graph's current alpha value. An example for such a force would be the following: 

```
function force(alpha) {
  for (var i = 0, n = nodes.length, node, k = alpha * 0.1; i < n; ++i) {
    node = nodes[i];
    node.vx -= node.x * k;
    node.vy -= node.y * k;
  }
}
```

Now I would like to get the current alpha value using for example `let alpha = Graph.d3Alpha()`. What could I do? I am using `<script src="//unpkg.com/3d-force-graph"></script>` to import the library.

Thank you!

**Comment by RaulPROP** [comment]
In that same PR [there is a discussion](https://github.com/vasturiano/three-forcegraph/pull/23#discussion_r407763008) that concludes in that `d3Alpha` should not be exposed so the API doesn't snowball.

**Comment by pournaki** [comment]
Thanks for the quick reply! 

> `d3Alpha` should not be exposed so the API doesn't snowball.

I see. Is there another way to implement a custom force that somehow depends on `alpha`? Maybe using `onEngineTick`?

**Comment by boostpaal** [comment]
Or using a `postProcessingComposer`

**Comment by vasturiano** [comment]
@pournaki when you define a custom force function and add it to the engine, it will be passed the `alpha` parameter as sole argument, at every tick of the simulation engine.

You can read more about it in the docs: https://github.com/vasturiano/d3-force-3d#simulation_tick

And you can see here for a usage example:
https://github.com/vasturiano/d3-force-3d/blob/b6e1c3e89847fe5c2415991f8e854eab675423a8/src/x.js#L11-L15

**Comment by pournaki** [comment]
Thank you very much @vasturiano! So **can** custom force functions have only `alpha` as the sole argument? Or in other words, is it possible to add additional arguments?

**Comment by vasturiano** [comment]
@pournaki the inclusion of the `alpha` argument into the force functions is part of the `d3-force` api specification. I don't think you can expect any other arguments without modifying `d3-force`. But, which other arguments did you have in mind for extending that function call with?

**Comment by pournaki** [comment]
I figured out my problem: I needed to pass on a variable to the force from within another function. I realized that I just needed to make that variable global, and now I only need `alpha` as the sole argument for the force. Thanks a lot for your help!
