### ISSUE TITLE
NPM build script fails on windows

### ISSUE THREAD

**Issue by Plarixtu** [vasturiano/3d-force-graph#44]
Building project during npm install fails because the script is using linux commands that are not available on windows.

In package.json you have the line `"build": "rm -rf dist && mkdir dist rollup -c"`- but the command `rm` does not exist on windows. I delete evereything except `rollup -c` from that line and created the dist folder manually. That seemed to work, but maybe there are more issues on windows that I didn't discover yet.

**Comment by vasturiano** [comment]
@Plarixtu good point, thanks for the heads up. When I have a moment, I'll convert the scripts to use [rimraf](https://github.com/isaacs/rimraf) instead, which has support for windows.
