### ISSUE TITLE
Restriction on node positions

### ISSUE THREAD

**Issue by sihnatse** [vasturiano/3d-force-graph#440]
Thanks for visualisation tool! It's amazing.

My request relates to a specific way of visualization, which might be useful for others. The dataset that I have to visualize is relatively large, 500 nodes and 15000 links. With available settings the overall view appears informative and nice. If specific parts of the graph, or relationships between those parts, need to be explored an extra segregation criteria would be very helpful. Specifically, a criteria which is to be applied to the nodes, like a group. Then restrict movement within the group in one dimension, so all the nodes belonging to the group are allowed to move freely only in the other two dimensions. By this way the dataset gets teared apart and visualization might look like 2.5 dimensional. I have tried different forces between the groups, but not all nodes in one group are linked and, as a result, the nodes occur mixed distributed in space.

![IMG_0228](https://user-images.githubusercontent.com/34723840/110289660-094c4400-7fea-11eb-99fe-d9ee68837e91.jpg)

Update: Added a sketch to show the idea.

**Comment by jaygray0919** [comment]
We learned how to do a version of your question following this example: https://jsfiddle.net/EPurpl3/qoz5dj31/1/
The author is https://codepen.io/raulprop/pens/public?cursor=ZD0wJm89MSZwPTEmdj00NDI0MzA3Mg==
But we have not learned how to construct a tree that navigates from top level to bottom level. 

We also tried to do this: http://bl.ocks.org/GerHobbelt/3071239 but ran short of "experimentation time."

Will watch this thread in case others have a solution.

**Comment by sihnatse** [comment]
I've realized that it can be accomplished by inserting fictitious links between nodes of the same group, adjust forces for those links toward stronger attraction and then make the links to be zero width.

**Comment by sihnatse** [comment]
This issue seemingly raises a very specific demand on visualization. In the end, the graph plotted by this app with somewhat default settings looks a little more insightful, in my opinion, than one with the constraints said above. Both are good for their purposes. Below I’m attaching `3d-force-graph` variant and the one made using Fruchterman and Reingold algorithm in Unreal Engine for the same dataset. For those who are interested. Thanks to @jaygray0919 for comment!

![Screenshot 2021-03-01 at 11 40 05 copy](https://user-images.githubusercontent.com/34723840/113978299-16a45a80-9844-11eb-8206-1f2251cf1f6c.png)

![Screenshot 2021-04-06 at 19 30 00 copy](https://user-images.githubusercontent.com/34723840/113978342-22901c80-9844-11eb-965f-dd4f23653b91.png)
