### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by edro15** [vasturiano/3d-force-graph#442]
Hi, we're using your library as part of [this Splunk visualization](https://splunkbase.splunk.com/app/4611/) and we'd like to update this library from 1.60.11 to 1.67.8 to fix vulnerabilities found in threeJS deps. 

Bundle is done using webpack, browser is Chrome 88.0.4324.150.

Unfortunately when running the app with the latest version of 3d-force-graph, we get the following error:

`Uncaught SyntaxError: Cannot use import statement outside a module` 

![image](https://user-images.githubusercontent.com/25966020/110543216-520b1680-812a-11eb-9af7-088d61c3ed23.png)

Have you already experienced it? Do you have any suggestion or hint to fix it?
Thanks a lot.

**Comment by vasturiano** [comment]
@edro15 at first glance that looks like the import of threeJS own drag controls: https://github.com/mrdoob/three.js/blob/master/examples/jsm/controls/DragControls.js

Is it possible that you're doing these module imports from node? As mentioned in the [threejs docs](https://threejs.org/docs/#manual/en/introduction/Installation) node imports, particularly with regards to examples code like `DragControls` can be complicated.

> Second, Node.js support for ES modules is ... complicated. As of Node.js v12, the core library can be imported as a CommonJS module, with require('three'). However, most example components in examples/jsm cannot. Future versions of Node.js may resolve this, but in the meantime you may need to use workarounds like esm to enable your Node.js application to recognize ES modules.

**Comment by edro15** [comment]
@vasturiano thanks for your reply. 

This issue has been fixed by:
* Making sure `package.json` was interpreting all `.js` files as ES modules by adding `"type": "module"`,
* Upgrading `webpack` to a newer version (4) and editing its configuration to comply w/ change above, 
* Editing the source file to comply w/ changes above 

For whoever is experiencing a similar issue, you'll find more details [here](https://github.com/splunk/splunk-3D-graph-network-topology-viz/pull/16/commits/6ca1c25e8f77d445669143ed40f4722b84a294ca).

Thanks for your support, closing this.
