### ISSUE TITLE
Provide support for automatic size/width mappings to node size / link width

### ISSUE THREAD

**Issue by khughitt** [vasturiano/3d-force-graph#445]
**problem**

It is often useful to map node/link attributes to node size/link width.

**solution**

provide convenience functions similar to `nodeAutoColorBy` and `linkAutoColorBy`, but for mapping from node/link attributes to size/width.

**Describe alternatives you've considered**

it looks like the setters used to specify node/link color can be passed a function, e.g.

```
(document.getElementById('3d-graph'))
  .jsonUrl('network.json')
  .nodeColor(node => node.color ? 'red' : 'blue' );
```

however, the setter for node size only accepts a single numeric value to be applied to all nodes, so it seems like that approach won't work for node size.

`linkWidth` does accept a function to assign width, so one can do soemthing like:

```
(document.getElementById('3d-graph'))
  .jsonUrl('network.json')
  .linkWidth(link => link.value);
```

Although, it still could be helpful (if it's not too much effort) to  provide a convenience function to simply specify a field to be used for the mapping, in cases where the desired link width has already been computed.

**related**

Along these lines, it could also be handy in some situations to be able to similarly map from node/link attributes to _opacity_, so that could be another useful set of helper functions to consider adding.

**Comment by khughitt** [comment]
Lol. nevermind! I realized almost immediately after submitting this that this already is possible.. I was just looking in the wrong place..

The `nodeVal` function does pretty much exactly what I had in mind, e.g.:

```
    const Graph = ForceGraph3D()
      (document.getElementById('3d-graph'))
        .jsonUrl('network.json')
        .nodeVal(node => Math.random() * 100)
```

I still don't see an obvious way to adjust opacity in a similar manner, so if you have any suggestions on that front, feel free to share them, but otherwise I'm closing this as a non-issue.

**Comment by vasturiano** [comment]
@khughitt you can adjust the color opacity by adding an alpha channel to the color definition via `rgba`. Like so:
```js
nodeColor(() => 'rgba(255, 0, 0, 0.6)')
```

**Comment by khughitt** [comment]
Awesome -- That will do it! Thanks again.
