### ISSUE TITLE
How to run in nodejs, outside browser

### ISSUE THREAD

**Issue by Plarixtu** [vasturiano/3d-force-graph#45]
Is it possible to let the force graph be virtually run on a node server outside a browser environment? I would like to just virtually simulate the graphing and extract the data in order to send them to connected clients (trying to synchronize their graphing displays by doing that)

**Comment by vasturiano** [comment]
@Plarixtu I suppose it should be possible, even though tbh I haven't actually tried to run it in a node environment. One issue you'll probably hit is if there is no `document` global var in node, so you'll need some dom simulation module to provide that. Something like jsdom: https://github.com/jsdom/jsdom

But, there is an alternative approach - if you don't care about the rending of the nodes and want to handle that yourself, you could just use the [d3-force-3d](https://github.com/vasturiano/d3-force-3d) layout engine directly, as that doesn't interact with the DOM.

**Comment by Plarixtu** [comment]
That's great, I'll be looking into these solutions, thanks! Best would propably be to do pre proccessing with d3-force-3d server side and then use this data to initialize 3d-force-graph on client views.
