### ISSUE TITLE
Link Label, Curved Lines & Self Links - Not Playing Nicely?

### ISSUE THREAD

**Issue by asmwp** [vasturiano/3d-force-graph#450]
**Describe the bug**
This is probably a combination of 2 things. I have initially been trying to set the .linkLabel property 

`.linkLabel(link => { link.linkLableText })`

But this never shows anything on the graph, not even on mouse over

So I then tried adding a sprite like this

```
 .linkThreeObjectExtend(true)
 .linkThreeObject(link => {
       // extend link with text sprite
       const sprite = new SpriteText(link.linkLableText);
       sprite.color = 'white';
       sprite.textHeight = 0.5;
       return sprite;
})
.linkPositionUpdate((sprite, { start, end }) => {
      const middlePos = Object.assign(...['x', 'y', 'z'].map(c => ({
             [c]: start[c] + (end[c] - start[c]) / 2 // calc middle point
      })));

      // Position sprite
      Object.assign(sprite.position, middlePos);
 })
```
Now this works fine in so far as I can now see text on my link even though it is not actually a label.

Now this is fine until I need to make the lines curved. So I add these 2 lines

```
.linkCurvature(0.5)
.linkCurveRotation(0.5)
```

Now the links are curved as I expect BUT the sprite text no longer appears over the link line, in fact the link text still shows in the same place as it would if the link line were still straight between point nodes.

Now I dont know if the .labelText was actually working if that would take care of the positioning of the text on a curved line. failing that I assume that some sort of change to the calculated position of the sprite is required but that is way out of my ability range at the moment. 

So is the linkLabel not working actually a bug?

**Expected Behaviour:**
1. I would expect that if .linkLabel is set then it would appear on the graph
2. Adding a sprite to the link to show the text the sprite should remain attached to the link when the line is curved?

Using a sprite to add text
![With_Sprite](https://user-images.githubusercontent.com/18737037/112728472-5f444580-8f1f-11eb-9fcb-b010b24c93b0.PNG)

Using a sprite and adding a curve to the link line
![With_Sprite_and_curve](https://user-images.githubusercontent.com/18737037/112728473-5fdcdc00-8f1f-11eb-9e37-50a3be113b3d.PNG)

Using the linkLabel property on it's own
![With_LabelText](https://user-images.githubusercontent.com/18737037/112728474-60757280-8f1f-11eb-93a7-1327a687e6f1.PNG)

**Comment by vasturiano** [comment]
@asmwp thanks for reaching out.

As per your `linkPositionUpdate` code above, you are actually defining where you want the label to be positioned. In this case in the half-way point between the two nodes:
```js
.linkPositionUpdate((sprite, { start, end }) => {
      const middlePos = Object.assign(...['x', 'y', 'z'].map(c => ({
             [c]: start[c] + (end[c] - start[c]) / 2 // calc middle point
      })));

      // Position sprite
      Object.assign(sprite.position, middlePos);
 })
```

If you'd like it to be located elsewhere, you just have to modify that logic.

**Comment by asmwp** [comment]
Thank you for replying so quickly. I thought that would be the case. So I assume that the .linkLabel, if working, wouldn;t be the answer then? In which case would you happen to know which properties/values that I have to take into consideration to be able to find the correct position on a curved line? Or if there is a formulae that I need to used to be able to calculate center point position of the curve?

**Comment by vasturiano** [comment]
@asmwp the `linkLabel` prop refers to text shown on link tooltip, not permanently shown text as you're intending. 

To calculate the middle position of curved links you should plug in some bezier curve math. There was an example on how to do that for the 2D `force-graph` component. The issue is [here](https://github.com/vasturiano/force-graph/issues/39). Perhaps that can help in your case.

**Comment by asmwp** [comment]
Excellent, thank you for your assistance and I will take a look at what you have suggested.

**Comment by asmwp** [comment]
Unfortunately your suggestion has only partially helped but I think I am going in the right direction however looking at the equation in the link you provided I am missing a couple of properties from my link object:
![image](https://user-images.githubusercontent.com/18737037/112749401-14c3d700-8fba-11eb-9a91-cf3062dd9d0f.png)

__controlPoints does not seem to exist. There is however a property called __curve but I am unsure of the value to use
![image](https://user-images.githubusercontent.com/18737037/112749483-56548200-8fba-11eb-9294-56ff6e21cc33.png)

I appreciate that this is not really an issue or bug anymore but I am so close to solving my problem I just thought I would post anyway.

**Comment by asmwp** [comment]
I am such an idiot! Ok, for the positioning I have actually figured it out so am posting here in case anybody else neds it. Following on from the excellent guidance from vasturiano and the link he provided I used the example code to calculate the position of the sprite on the link and after realising that I was using code that was originally meant for a 2D view I amended it take into account the additional thrid dimension, so here it is:

```
   .linkPositionUpdate((sprite, { start, end }, link) => {
         const middlePos = getQuadraticXY(
         0.5,
         start.x,
         start.y,
         start.z,
         link.__curve.v1.x,
         link.__curve.v1.y,
         link.__curve.v1.z,
         end.x,
         end.y,
         end.z
    );

     // Position sprite
     Object.assign(sprite.position, middlePos);
 })
```
```
    // Calculate position of text sprite on curved line
    function getQuadraticXY(t, sx, sy, sz, cp1x, cp1y, cp1z, ex, ey, ez) {
         return {
                     x: (1 - t) * (1 - t) * sx + 2 * (1 - t) * t * cp1x + t * t * ex,
                     y: (1 - t) * (1 - t) * sy + 2 * (1 - t) * t * cp1y + t * t * ey,
                     z: (1 - t) * (1 - t) * sz + 2 * (1 - t) * t * cp1z + t * t * ez
           };
    }
```
Can anybody can see anything wrong with this?

Now all I need to do is figure out how to change the text orientation to run in the same direction as part of the link line?
