### ISSUE TITLE
problems when getting the position of nodes?

### ISSUE THREAD

**Issue by damonAlreadyTaken** [vasturiano/3d-force-graph#459]
First i want to thank the author and all the contributors of this project, it really helps me a a lot!
but now i have a problem while getting the position of the nodes, here is the code:

`Graph.graphData().nodes.forEach(function (node) {
             console.log(node);
            console.log(node.x);
            console.log(node.__threeObj.position.x);`
and the results are like:
![image](https://user-images.githubusercontent.com/47476574/113703192-1190bf80-970d-11eb-98b6-f5a13a18400b.png)

You may notice that node.x is undefined, and node.__threeObj.position.x is not the same as x. I wonder why is this happening and how to get the x in node?
Thanks a lot!

**Comment by RaulPROP** [comment]
Duplicate of #443

**Comment by damonAlreadyTaken** [comment]
> Duplicate of #443

thanks! didn't find that one while searching
