### ISSUE TITLE
Using Offline Layout Algorithm

### ISSUE THREAD

**Issue by DayOfThePenguin** [vasturiano/3d-force-graph#467]
Hi,

Is there a way of stopping the force-directed algorithm from running on a graph, fixing the position of all nodes, and using only the graph interaction features of the library?  I am using 3d-force-graph to visualize the connections between wikipedia pages ([example](https://dayofthepenguin.github.io/wikimap/interactive_demo.html)) and in order to visualize large graphs (15k+ nodes), I want to offload the force-directed layout algorithm to my server and do only visualization in the browser.

My current solution is inspired by the solution described in issue 90, [Node with Fixed Position](https://github.com/vasturiano/3d-force-graph/issues/90), except instead of only specifying fx, fy, fz for one node, I specify an fx, fy, fz for every node in a json file generated by a python script.  Is this the most efficient way to run a force-directed layout on a server and then load the generated json file into the browser to interact with?

The solution above will stop me from adding additional nodes to the graph dynamically and being able to drag nodes around, correct?

Alternatives I tried:
1. I tried freezing the animation after ~5 seconds using `Graph.pauseAnimation()`, but that also freezes the interaction and doesn't really solve my problem.

Thanks!  Huge fan of this library!

**Comment by RaulPROP** [comment]
You can set the `cooldownTicks` property (_Getter/setter for how many build-in frames to render before stopping and freezing the layout engine_) to 0.

**Comment by DayOfThePenguin** [comment]
Awesome, thanks!

**Comment by jokroese** [comment]
Hi @DayOfThePenguin, I'm in a similar position and I'm wondering if this approach (prerendering positions and fixing each node in that place) ended up being the solution you went with?

If you had any further developments with this approach, I'd be very grateful to hear :)
