### ISSUE TITLE
After zooming with the mouse wheel, the mouse hover event no longer takes effect.

### ISSUE THREAD

**Issue by fhtwl** [vasturiano/3d-force-graph#470]
**Describe the bug**
After zooming with the mouse wheel, the mouse hover event no longer takes effect.

**To Reproduce**
Running the example "bloom-effect" will cause the above problems. After the mouse wheel works, the mousehover event is no longer triggered

**Expected behavior**
I hope you can give you solutions or ideas for the problem. Thank you very much

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: Microsoft Edge 
 - Version: 90.0.818.56

**Comment by aleksabobic** [comment]
I'll just add to this issue. In general the hover effect stops triggering after zoom event (e.g. [highlight example](https://vasturiano.github.io/3d-force-graph/example/highlight/)). However, as soon as you click on the graph the hover effect works again. My guess would be that focus gets lost on mouse scroll. 

OS: macOS Big Sur
Browser: Seems to be browser independent (Firefox as well as all possible variations of Chromium)

**Comment by vasturiano** [comment]
Thanks for the report! This should now be fixed in the latest version (`1.69.9`).
