### ISSUE TITLE
about dynamic graph 

### ISSUE THREAD

**Issue by lgsh007** [vasturiano/3d-force-graph#473]
https://github.com/vasturiano/3d-force-graph/tree/master/example/dynamic , i am not able to modify this example, 
i need to support nodes=[{},{}...]  links=[{},{}...] , who can provide such example. or document of related
thanks!

**Comment by emirth** [comment]
[Input JSON syntax ](https://github.com/vasturiano/3d-force-graph#input-json-syntax) in the documentation indicates that any node we expect to link to will need an ``id`` attribute, so although we can include empty node objects in our graph data, I don't think we can reliably link to those empty objects, i.e., examples like this one will render the empty nodes OK but creating any links related to them would seem to present a challenge:

```
<head>
  <style>body { margin: 0; }</style>
  <script src="//unpkg.com/3d-force-graph"></script>
</head>
<body>
  <div id="3d-graph"></div>
  <script>
    const elem = document.getElementById('3d-graph');
const data = {nodes: [{}, {}, {}], links: [{}, {}, {}]}
    const Graph = ForceGraph3D()(elem)
      .enableNodeDrag(false)
      .graphData(data);
    let counter = 0
    setInterval(() => {
      const nodeId = ++counter
      data.nodes.push({id: nodeId })
      data.links.push({source: nodeId, target: randomInt(1, nodeId) })
      Graph.graphData(data);
    }, 1000);

    function randomInt(min, max) {
      return Math.floor(Math.random() * (max - min + 1) + min);
    } 
  </script>
</body>
```

**Comment by lgsh007** [comment]
> [Input JSON syntax ](https://github.com/vasturiano/3d-force-graph#input-json-syntax) in the documentation indicates that any node we expect to link to will need an `id` attribute, so although we can include empty node objects in our graph data, I don't think we can reliably link to those empty objects, i.e., examples like this one will render the empty nodes OK but creating links to them presents a challenge:
> 
> ```
> <head>
>   <style>body { margin: 0; }</style>
>   <script src="//unpkg.com/3d-force-graph"></script>
> </head>
> <body>
>   <div id="3d-graph"></div>
>   <script>
>     const elem = document.getElementById('3d-graph');
>     const data = {nodes: [{}, {}, {}], links: [{}, {}, {}]}
>     const Graph = ForceGraph3D()(elem)
>       .enableNodeDrag(false)
>       .graphData(data);
>     let counter = 0
>     setInterval(() => {
>       const nodeId = ++counter
>       data.nodes.push({id: nodeId })
>       data.links.push({source: nodeId, target: randomInt(1, nodeId) })
>       Graph.graphData(data);
>     }, 1000);
> 
>     function randomInt(min, max) {
>       return Math.floor(Math.random() * (max - min + 1) + min);
>     } 
>   </script>
> </body>
> ```

**Comment by lgsh007** [comment]
@emirth thanks very much
