### ISSUE TITLE
Release the fixed position when drag the nodes, Ease effect to fixed nodes, Camera Transition

### ISSUE THREAD

**Issue by yunison** [vasturiano/3d-force-graph#474]
Hi! Before start, I'm glad to know your library.
I'm working on my project by the below sequence.

1. create nodes on the sphere surface by fixed position
2. release the fixed position and apply force on my graph by pressing a button.

**I want to give these fixed nodes the force when I drag them which is like the initial one.** 
(interacting with each other, nodes and links on their position)

I tried to give the value <null> when I drag the nodes because I know that the fixed nodes are not affected by the force.
However, they go out the canvas infinitely.
How can I give them collision force on their position?

**The reason why I didn't use 'radial force' or 'DAG mode'**
-> Radial force doesn't make my database sphere like a sphere.
-> DAG Mode(radialout) can't create shaggy links like my one.
-> my database structure is like [this](https://raw.githubusercontent.com/vasturiano/3d-force-graph/master/example/datasets/d3-dependencies.csv).

**Also, can I give the transition(ease) to the node position when fixed positions re-assigned?**

**and I can't use the transition built-in cameraPosition()**

You can see my example on my **[codepen](https://codepen.io/yunison/pen/qBrLZxw)**.
Thank you for I could use your awesome library.

**Comment by vasturiano** [comment]
@yunison thanks for reaching out.

I think one of the things that are contributing to your nodes apparently moving out of their positions is the **centering** force that is still active - it attempts to balance the graph center of gravity by moving the few nodes that are free.

You can disable it via:
```js
myGraph.d3Force('center', null)
```

**Comment by yunison** [comment]
Thank you for your quick feedback.
It works very well.

and I have one more question about node transition.
Is there any idea for a nice transition when the node's position changes from the initial state to fixed?

**Comment by vasturiano** [comment]
I noticed you're doing 
```js
.onNodeDrag((node) => {
    node.fx = null;
    node.fy = null;
    node.fz = null;
});
```
You may want to do this on `onNodeDragEnd` instead, to not interfere with the drag interaction.

**Comment by yunison** [comment]
Oh, I couldn't come up with nodeDragEnd. Thank you!

However, my question was about how to give the node transition effect from the **initial state position** affected by force **to the fixed position** is not affected by force.
(Scattered nodes move softly to their fixed position.)
I updated [my codepen. Link is here!](https://codepen.io/yunison/pen/qBrLZxw)
You can see the situation what I mean when you toggle the checkbox.

I've really appreciated your effort. 🙏
![1](https://user-images.githubusercontent.com/54765660/122382952-5ce50b00-cfa5-11eb-9a6e-dd899d4d7374.png)

**Comment by vasturiano** [comment]
Ah ok, I see what you mean now.

Well, I think the better way to do that is to use some form of tweening library (like [tween.js](https://github.com/tweenjs/tween.js/)) to interpolate the fixed positions of the nodes over a period of time, to create the effect of a transition between the two modes.

**Comment by yunison** [comment]
Thanks a lot. I'll try it!
