### ISSUE TITLE
Pause/resume force simulation

### ISSUE THREAD

**Issue by S1r0hub** [vasturiano/3d-force-graph#475]
Hey there,
I searched for a way to pause (and later resume) the force simulation
and found some older issues where you already described how to do it:
- #47
- #170

I now know that you have to call the following to "pause" the force engine:
```javascript
myGraph.cooldownTicks(0)
```

And the following to resume:
```javascript
myGraph.cooldownTicks(Infinity)
```

And this works (*kind of*).  
Sadly, once I want to resume, **all nodes stay freezed** and only start moving again when I drag a node.

I already used `myGraph.d3ReheatSimulation()` after setting the cooldown ticks to infinity.
But this just "restarts" the whole simulation from its current state as far as I understood (by setting alpha to 1).

Is there another way to do it so that the force engine continues exactly where it was paused?

Thanks in advance!

**Comment by S1r0hub** [comment]
> 
> 
> You also have the `pauseAnimation` and the `resumeAnimation` methods of the [render control section](https://github.com/vasturiano/3d-force-graph#render-control).

Thanks for the reply.
Maybe I should have mentioned that I want to keep user interaction working.
This method is therefore not suitable, as it pauses the whole render cycle.

**Comment by vasturiano** [comment]
Though it's not directly its purpose, you could try to fabricate this effect by setting `d3AlphaMin(1)` when you want to pause, and back to `d3AlphaMin(0)` when you wish to resume.

**Comment by S1r0hub** [comment]
> Though it's not directly its purpose, you could try to fabricate this effect by setting `d3AlphaMin(1)` when you want to pause, and back to `d3AlphaMin(0)` when you wish to resume.

Good idea. I just tried it but the result is the same as for using cooldownTicks.
The force engine pauses just fine but on resume, everything stays freezed until I drag a node manually.

**Comment by vasturiano** [comment]
You may need to increase the `cooldownTime` to prevent the engine from automatically stopping after a certain time.

**Comment by S1r0hub** [comment]
> You may need to increase the `cooldownTime` to prevent the engine from automatically stopping after a certain time.

Tried it. Still the same result.

I just recently added some node highlighting (similar to your example) and noticed that calling the following "wakes" the force engine up again:
```javascript
graph.nodeColor(graph.nodeColor());
```
I don't know why that is but it could be a temp. fix.

**Comment by S1r0hub** [comment]
And the following also wakes it up:
```javascript
graph.refresh();
```
How "expensive" is this operation (especially for large graphs)?
Is it like a general "render" tick?
If so, I would consider this as a fix.

**Comment by vasturiano** [comment]
@S1r0hub I've applied a fix to the lib so you don't need to do any refreshing when modifying the value of `d3AlphaMin`. The lib should react internally to this change.
Please try with the latest version.

**Comment by S1r0hub** [comment]
@vasturiano Works just fine now. Thanks for the fix!
