### ISSUE TITLE
Is there a way to have nodes with different opacity?

### ISSUE THREAD

**Issue by ChrisTriant** [vasturiano/3d-force-graph#483]
Hello and thanks for your work.

I'm trying to have different opacity for some of the nodes but since the .nodeOpacity() doesn't receive functions, i can't think of another way to do it. Even if i change the opacity attribute of a specific node, it doesn't change the actual opacity even with .refresh().
Is there a workaround?

**Comment by vasturiano** [comment]
@ChrisTriant thanks for reaching out.

You can just set the alpha channel on the node color, like so:
```js
.nodeColor(node => 'rgba(255, 0, 0, 0.6)')
```

**Comment by ChrisTriant** [comment]
Thank you for your answer.

After playing around with it a little, a made it work with .refresh() but it is quite laggy. To be more specific im trying to change the opacity (via the color property) of the node i clicked and focused on. Is there a way to make the change and render it without refreshing?

**Comment by RaulPROP** [comment]
You can set again the same function to the `nodeColor` method [like shown here](https://codepen.io/raulprop/pen/JjNVVVL).

**Comment by ChrisTriant** [comment]
> You can set again the same function to the `nodeColor` method [like shown here](https://codepen.io/raulprop/pen/JjNVVVL).

It worked as a charm. Thanks a ton @RaulPROP !
