### ISSUE TITLE
Is there any example for usage in react+typescirpt project?

### ISSUE THREAD

**Issue by SherloqueChang** [vasturiano/3d-force-graph#485]
In a `.tsx` file, I only know that I can use `import ForceGraph3D from '3d-force-graph'` to import module. However, when it comes to  `render()` method in my class, the code given in the example seems incompatible. I don't know what to do with this situation.

**Comment by vasturiano** [comment]
Duplicate of https://github.com/vasturiano/react-force-graph/issues/312
