### ISSUE TITLE
Update node/link attributes without re-calculating force

### ISSUE THREAD

**Issue by l3utterfly** [vasturiano/3d-force-graph#486]
First of all, great project, the graphs generated using your library look amazing.

However, we ran into an issue where our graph is generated in real-time from server side data. Specified link colours go from white to blank over time, when the server pushes an update, the link go back to white. The colour decay is achieved by using the `linkColor` function, and reading a lookup table of the link id <-> colour.

Every 200ms, the link colour changes from white gradually to black (based on a mathematical decay constant). This is done via the "setInterval" function updating the lookup table.

We found the graph will only reflect the change if we do this:
````
let { nodes, links } = this.network.graphData();

// we update the link attributes here

this.network.graphData({
  nodes: nodes,
  links: links
});
````

This works well, except that the graph forces seem to recalculate every time we re-assign the data. So the effect is the graph keeps "twitching".

Is there anyway to update the graph without recalculating forces, since we are only updating link colours.

**Comment by P31N** [comment]
@l3utterfly  Quick question, i am trying to do a real time refresh without having to reload the whole interface every time as it would be quite resource intensive, could you expand a bit on how the data being server  side is being interogated to view for any changes in the graph?
