### ISSUE TITLE
How to refer to the graph object in another function?

### ISSUE THREAD

**Issue by Hollie7** [vasturiano/3d-force-graph#488]
Hi, I'm really sorry as this might be a stupid question, but I have checked the examples and issue lists and couldn't find an appropriate answer or example. My problem is, is it possible to initialize the graph object in one function and refer to it in another function?

Such as

`function SHOW_UPDATE_FORCE(dataset){
    const Graph = ForceGraph3D()
    Graph(document.getElementById('3d-graph'))
        .graphData(dataset);
}

function highlight_nodespaths(dataset){
    var Graph = ....
    // change its attributes
}
`

The reason that I want to write in this way is because I'm trying to modifying a code which was not designed by me in the first place, so I really hope to reduce the work and risk of modification. 

I have tried several ways but the browser warns that "xxx is not a function". So I hope to seek some help. 
Thanks for reading!

**Comment by vasturiano** [comment]
@Hollie7 you just have to keep a reference to the graph instance (your first `Graph` variable) in your application state. Then you can refer to it to invoke any other methods you desire elsewhere.
