### ISSUE TITLE
Fading Text as you go further and further?

### ISSUE THREAD

**Issue by kvietcong** [vasturiano/3d-force-graph#493]
Is there a way to attach nodes with text that fade away as you go further and further away. It is pretty cluttered when you just leave them all on. Thanks for the great library and for any help.

This is what I have atm
```javascript
        <ForceGraph3D
            controlType="orbit"
            graphData={data}
            nodeThreeObjectExtend={true}
            nodeAutoColorBy="group"
            linkWidth={2}
            nodeResolution={10}
            nodeVal={({value}) => value}
            linkCurvature={1}
            nodeThreeObject={node => {
                // Any way to fade this?
                const sprite = new SpriteText(notes[node.id].title);
                sprite.color = node.color;
                sprite.textHeight = node.value;
                sprite.padding = 5;
                return sprite;
            }}
        />
```

**Comment by vasturiano** [comment]
@kvietcong I would just suggest to make the nodes text color slightly transparent (opacity <1). It may create an effect similar to what you're describing. Other than that I do not know of any other way to achieve that.

**Comment by kvietcong** [comment]
Got it thanks for the quick reply
