### ISSUE TITLE
Providing access to d3Force in React component

### ISSUE THREAD

**Issue by kvietcong** [vasturiano/3d-force-graph#494]
**Is your feature request related to a problem? Please describe.**
It would be great if I could access the d3Forces from the React component. As of right now, it seems that you can't because you have to provide a string to actually access it.

**Describe the solution you'd like**
Have the d3Force prop be available and have the function return the string to modify and the function to modify the actual force.

**Describe alternatives you've considered**
I'm using NextJS right now and I can't get the imports working like the script tags. I would rather not use the script tags.

Thank you for any help. I appreciate this great library

**Comment by vasturiano** [comment]
@kvietcong you can already access the existing d3 forces, or even add new forces to the system.

For example:
* forceLink: `myGraph.d3Force('link')`
* forceManyBody: `myGraph.d3Force('charge')`
* forceCenter: `myGraph.d3Force('center')`

**Comment by kvietcong** [comment]
Sadly, I haven't been able to figure out how to get the reference to `myGraph` in React.

This is my current code:
```jsx
        <ForceGraph3D
            controlType="orbit"
            graphData={data}
            nodeThreeObjectExtend={true}
            nodeAutoColorBy="group"
            linkWidth={2}
            nodeVal={({value}) => value}
            linkDirectionalParticleResolution={2}
            linkDirectionalParticles={8}
            linkDirectionalParticleWidth={1}
            linkDirectionalParticleSpeed={0.005}
            nodeLabel={node => notes[node.id].title}
            nodeThreeObject={node => {
                const sprite = new SpriteText(notes[node.id].title);
                sprite.color = node.color;
                sprite.textHeight = node.value;
                sprite.padding = 5;
                return node.value >= 6 ? sprite : null;
            }}
            onNodeClick={node => {
                console.log(node.id)
                Router.push(`/atlas/page/${node.id}`)
            }}
        />
```

I'm using NextJS and I've been having troubles getting script tags to work properly. Is there anyway to access the forces from the props? Or is there a way to get a reference to the `myGraph` variable you are using? I tried using the `useRef` hook but it didn't work (the current value kept returning `retry` which was weird)

**Comment by vasturiano** [comment]
@kvietcong this is more a question for the React binding module, but in any case have you tried following an example that does this, for instance:
https://github.com/vasturiano/react-force-graph/blob/e67177b3522e2ffd212f807cbb6b74ed04a39ab6/example/tree/index.html#L41-L47

**Comment by kvietcong** [comment]
Sadly I've been trying to get useRef to work but it refuses to grab the reference. However, I'm thinking it is due to how I had to import the library due to Next.js' dynamic importing rules. I will close this issue and open one on the Next.js page. Thanks for your help.
