### ISSUE TITLE
Is there a callback for .jsonUrl() ?

### ISSUE THREAD

**Issue by Qiming-Liu** [vasturiano/3d-force-graph#498]
I would like to asynchronously load JSON via jsonURL(), then get graphData(), but I keep getting Array(0)

Here is an example:
https://codepen.io/prossliu/pen/gOxMPaJ

![image](https://user-images.githubusercontent.com/68600416/137870174-a473d0bf-6aa3-4b1e-ab4b-35d02f0e70eb.png)

Does jsonURL() have a callback method, or is there an alternative method?

Thanks

**Comment by vasturiano** [comment]
@Qiming-Liu it's a synchronicity issue. You can extract the data loaded via `jsonURL` using `graphData()`, but only after the http request has finished and the data has been populated in the component. Before then, it will just be empty.

**Comment by Qiming-Liu** [comment]
Thank you. I will do your recommendation.
Currently `jsonURL` is working very well. 
If not use `jsonURL` I need to implement an ajax request JSON function.
I think a later version of `jsonURL` would be great if it had an optional callback.
Thank you again for your great project.

**Comment by ducknificient** [comment]
hi, i want to copy example from https://github.com/vasturiano/3d-force-graph/blob/master/example/highlight/index.html 

but i can't find a way to replace gData from json. Is there any example that's using from .json instead of gData ?

**Comment by vasturiano** [comment]
@ducknificient not for that specific example, because it's statically generated data. But you can just shift to use `.jsonUrl` if you have it in a separate json file. Or else do the fetch yourself and load it via `graphData` as normal.
