### ISSUE TITLE
Pan does not work anymore, when cameraPosition is set manually.

### ISSUE THREAD

**Issue by smoes** [vasturiano/3d-force-graph#50]
Once `cameraPosition` was set manually, pan (right mouse down, move) does not work anymore. Is that intended? Other controls (zoom, rotate) are still working properly.

**Comment by vasturiano** [comment]
Hi @smoes, the pan functionality should remain working even after the cameraPosition has been set programmatically. 

If you try this example:
https://vasturiano.github.io/3d-force-graph/example/click-to-focus/

When you click on a node the camera moves programmatically, and the pan functionality should remain available afterwards. Does that work for you?

**Comment by smoes** [comment]
Hmmm it does, actually.

I just made some experiments and it just happens if I don't pass a parameter for `lookAt` which should be optional, right? Then, the pan does not work anymore.

**Comment by vasturiano** [comment]
@smoes that's totally right. That was a bug in the lib, that's now fixed.  If you pull the latest version, you should be able to pan even after changing the cameraPosition without a lookAt param.
Thanks for reporting, this is how we make the library better. :)

**Comment by smoes** [comment]
Wow, that was fast! Thanks for the fix!
