### ISSUE TITLE
how to set highlight nodes/links after dynamic add nodes

### ISSUE THREAD

**Issue by royhuang813** [vasturiano/3d-force-graph#507]
[highlight](https://vasturiano.github.io/3d-force-graph/example/highlight/)
[dynamic](https://vasturiano.github.io/3d-force-graph/example/dynamic/)

I expect that after adding new nodes, when I hover new nodes, there will be a highlight effect, but it's doesn't work and error.
there is my codes:
```
const imgs= ['a.png', 'b.png', 'c.png']

// get data
function generateData(imgs) {
  const data = {
    nodes: imgs.map((img, id) => ({ id, img })),
    links: [...Array(imgs.length).keys()]
      .filter(id => id)
      .map(id => ({
        source: id,
        target: Math.round(Math.random() * (id-1))
      }))
  }
  return data
}

// add neighbors for highlight
function addLinksNeighbors(data) {
  // cross-link node objects
  data.links.forEach(link => {
    const a = data.nodes[link.source]
    const b = data.nodes[link.target]
    !a.neighbors && (a.neighbors = [])
    !b.neighbors && (b.neighbors = [])
    a.neighbors.push(b)
    b.neighbors.push(a)

    !a.links && (a.links = [])
    !b.links && (b.links = [])
    a.links.push(link)
    b.links.push(link)
  })
  return data
}

const data = generateData(imgs)
const gData = addLinksNeighbors(data)
this.graph(dom).graphData(gData)
...

// mock add new node
setInterval(() => {
  const { nodes, links } = this.graph.graphData()
  const id = nodes.length
  const data = addLinksNeighbors({
    nodes: [...nodes, { id, img: 'other.png' }],
    links: [...links, { source: id, target: Math.round(Math.random() * (id - 1)) }]
  })
  this.graph.graphData(data)
}, 1000)
```

![image](https://user-images.githubusercontent.com/29953318/144208023-ef9ece61-6f14-4c5a-9d44-56addb397c8f.png)

when I debug it, the addlinksneighbors function returns many other attributes, I don't know how to set the neighbor relationship for dynamically added nodes.
can you help me, thx!

**Comment by vasturiano** [comment]
@royhuang813 as documented [here](https://github.com/d3/d3-force#link_links), the link `source` and `target` attributes get converted into node object pointers after the force initialization. 

This is why you're getting `data.nodes[link.source] === undefined`. You shouldn't expect those attributes to always be numeric ids, specially after the engine starts running.

**Comment by royhuang813** [comment]
> @royhuang813 as documented [here](https://github.com/d3/d3-force#link_links), the link `source` and `target` attributes get converted into node object pointers after the force initialization.
> 
> This is why you're getting `data.nodes[link.source] === undefined`. You shouldn't expect those attributes to always be numeric ids, specially after the engine starts running.

Thanks a lot~
