### ISSUE TITLE
Show node labels which are close to camera

### ISSUE THREAD

**Issue by LuciusCao** [vasturiano/3d-force-graph#516]
Hi, I'm trying to visualize the relationship of a certain amount knowledge components (KC), with each node representing a KC and each link representing the relation between two KCs. In my app, I would like to show KC's name in node labels. However when I try to set the nodes' label via `nodeLabel((node) => node.name)`, all KC's name show up in the graph, which is really a lot.

Is it possible, I can only show the nodes label within certain distance from the camera? Or only show the node which I click on, and nodes related to the one I choose.

**Comment by vasturiano** [comment]
@LuciusCao thanks for reaching out.

Setting `nodeLabel` should only activate the tooltip labels, shown only when a node is hovered. Unless you are extending the default node shape using `nodeThreeObject` to show text instead, you shouldn't be seeing all the labels at once.

**Comment by LuciusCao** [comment]
@vasturiano you are right. I checked my code, I do extend the default node object with an html tag to show the labels.  But how can I achieve the result in which the graph only shows nodes close enough to the camera, to avoid all labels being displayed at once and overlap with each other.

**Comment by vasturiano** [comment]
You can selectively choose the representation per node in the `nodeThreeObject`. If that method returns `false` for a node it will fallback to its default representation. 
If you want base the decision on the proximity to the camera you can compute the 3D distance on demand by comparing the node's coordinates with the camera location (which can be retrieved via `.cameraPosition()`).

**Comment by LuciusCao** [comment]
Wow! it works, thank you. 

Here is another problem I've just ran into. I tried to display the graph (about 350 nodes) in a web view on an android tablet, everything goes on well. However when I tap on a node to focus on it, the whole graph gets laggy. The FPS goes from 60 down to 15. 

I also tried a smaller graph with about 100 nodes, and didn't run into the problem. Any idea why this happened?

**Comment by vasturiano** [comment]
Could it be that as you're tapping the node you are dragging it slightly, so it re-heats the force engine and nodes start re-adjusting? The force engine requires extra cpu to do its calculations so that could explain it.

**Comment by LuciusCao** [comment]
No, I don't think so. I've set `enableNodeDrag` to `false`

**Comment by vasturiano** [comment]
Do you have a simple reproducing example you could share on https://codepen.io/ ?

**Comment by LuciusCao** [comment]
I don't have one on hand, but I think I can quickly make a reproducing example tomorrow. And here is the video I recorded, from which you can see the first 10 seconds performs well. However, from the 15th second, where I tapped on a node and perform the camera movement, the whole graph becomes laggy.

and the rendering engine we used in web view is Android System WebView 74.0.3729.186.
https://user-images.githubusercontent.com/15772264/148231764-d74d59f7-7d67-49bf-8312-10a0b5cc617c.mp4

**Comment by LuciusCao** [comment]
I found the problem, the popup after tapping a node did some DOM operation, and cause the performance problem on my tablet. Thank you for your help. @vasturiano

**Comment by voidray** [comment]
I'm also trying the same thing. I put Graph.cameraPosition() inside .nodeThreeObject to see the values (using console.log), but in the console the values are written only initially when the page/graph loads. Is there something else I'm missing? 
I would like to display/hide the text per node depending on the current distance when navigating through the graph.
