### ISSUE TITLE
Camera position animation

### ISSUE THREAD

**Issue by Benkevych** [vasturiano/3d-force-graph#52]
Is it possible to change camera position on node focus in transition, not jumping instantly?

**Comment by vasturiano** [comment]
@Benkevych you can just place the `cameraPosition()` call inside an animation tween function. That should do it.

**Comment by vasturiano** [comment]
@Benkevych I've added a tween transition to the node focus example: https://vasturiano.github.io/3d-force-graph/example/click-to-focus/

**Comment by Benkevych** [comment]
@vasturiano awesome, thank you for help

**Comment by Benkevych** [comment]
@vasturiano i get an error because 'lookAt' from Graph.cameraPosition() is undefined...

**Comment by vasturiano** [comment]
Please make sure to use the latest version of the lib. It should include that attribute.

**Comment by Benkevych** [comment]
@vasturiano whoops, sorry, missed an update.
One more question: Can i somehow group nodes in specific area, without connecting them with links?

**Comment by Benkevych** [comment]
@vasturiano i think this can be made by setting opacity for each link, but foe now linkOpacity accepts only a number, not a function, can you make this so i can set different opacity for each link?
