### ISSUE TITLE
Cannot change node color on click

### ISSUE THREAD

**Issue by ingodahn** [vasturiano/3d-force-graph#520]
I want to change the color of a node when it is clicked. 

I can achieve node color change - in 2D and in 3D - by calling, say, `node.color='brown'`. To connect the color change to node click I use a function `nodeClicked` as in `Graph.onNodeClick((node) => nodeClicked(node))` with 
`function nodeClicked(n) {
  n.color = "brown";
}`

This works fine in 2D force-graph but not in 3D. An example is on https://codepen.io/dahn/pen/OXEdZr .

**Note**: Even when I call the color change onNodeClick directly, and not through a function, the color doesn't change.

**Comment by vasturiano** [comment]
@ingodahn in the 3D mode you need to invoke `.nodeColor` to tell the component that the node colors need to be updated. The fact it works in 2D out of the box is just a coincidence, due to the way the underlying frame engine works.

So,  you can do something like:
```js
.onNodeClick(node => {
      node.color = 'brown';
      Graph.nodeColor('color');
})
```

**Comment by ingodahn** [comment]
Thanks for your quick help. Perhaps you could add your comment to the 
nodeColor documentation.

**Comment by ingodahn** [comment]
This is working fine now with sphere nodes. Can I have the same with text nodes (it works in 2D)? If not with color then possibly with some text decoration? And would it be possible to format the text string in nodes, e.g. using line breaks for long names?

**Comment by vasturiano** [comment]
@ingodahn it's the same case. You need to re-invoke `.nodeThreeObject` when you add the node `color` attribute because that's where that attribute is read.

As for the text style, you are in full control of it since you're writing the custom `nodeThreeObject` method.

**Comment by ingodahn** [comment]
Thanks, that's fine.
