### ISSUE TITLE
Bloom Post-Processing Effect Error Relative References

### ISSUE THREAD

**Issue by RiyanAmanda** [vasturiano/3d-force-graph#522]
error shown : Relative references must start with either "/", "./", or "../".

i guest the error is on this code below:
import { UnrealBloomPass } from '//cdn.skypack.dev/three/examples/jsm/postprocessing/UnrealBloomPass.js';

and this example [Bloom Post-Processing Effect](https://vasturiano.github.io/3d-force-graph/example/bloom-effect/) also got this error.

anybody knows how to fix this?

**Comment by vasturiano** [comment]
@RiyanAmanda thanks for reaching out.

This is most likely related to the recent change in `three` to use import maps: https://github.com/mrdoob/three.js/pull/23255

Perhaps there is an alternative way to import this as a js module in the browser that works with the new `import ... from 'three'` in those example files. For now, one can just pin to the previous version before the import maps change (`0.136`):
```js
import { UnrealBloomPass } from '//cdn.skypack.dev/three@0.136/examples/jsm/postprocessing/UnrealBloomPass.js';

```
