### ISSUE TITLE
GLTF/GLB as a node

### ISSUE THREAD

**Issue by JockDaRock** [vasturiano/3d-force-graph#526]
I see an example where you can use images as node with the force graph. I have been trying to use the same methodology with an apple glb file, but that does not seem to work. Is there a way to use GLB files for the node in the force graph?

**Comment by JockDaRock** [comment]
could also be an obj file as well... I have tried a lot of loading of files with different threejs loaders with no success and I can't seem to find any examples of doing this either

**Comment by vasturiano** [comment]
@JockDaRock thanks for reaching out.

This should be easily achievable using Three's [GLTFLoader](https://threejs.org/docs/#examples/en/loaders/GLTFLoader). 

Something along the lines of:
```js
new GLTFLoader().load('myObj.gltf', gltf => myGraph.nodeThreeObject(gltf.scene));
```

**Comment by JockDaRock** [comment]
@vasturiano Thank you so much for your response. That seems to work well. Greatly appreciate you helping as fast as you did

kind regards

**Comment by JockDaRock** [comment]
Hey @vasturiano I thought I had all of this sorted, but I ran into a problem when trying to do a few different glb files.

When I use this method:

```
new GLTFLoader().load(nodeObj.type, function (gltf) {
        gltf.scene.scale.multiplyScalar(10);
        Graph.nodeThreeObject(gltf.scene)
    })
    ```
It renders all of the nodes the same glb.

But when I use this method:

.nodeThreeObject((node) => {
        new GLTFLoader().load(node.type, function (gltf) {
          gltf.scene.scale.multiplyScalar(10);
          return gltf.scene
        })
      })
     
I was expecting this to iterate over different types and make each node 1 of 3 predetermined glb files... instead, I am getting the defaut sphere for my rendered node.

What am I doing wrong? How can I fix this?

Kind Regards

**Comment by vasturiano** [comment]
@JockDaRock I would expect that. In this call:
```js
.nodeThreeObject((node) => {
        new GLTFLoader().load(node.type, function (gltf) {
          gltf.scene.scale.multiplyScalar(10);
          return gltf.scene
        })
      })
```
you are essentially implicitly returning `undefined` in your `nodeThreeObject` method, which the module interprets as a fallback to its default node shape.

The issue is in the architecture of your callback functions, they should be in the reverse nesting. I'd recommend you pre-load all the GLTF objects you wish to use as your nodes. Once they're loaded, you can reference them in your `nodeThreeObject` method.

**Comment by JockDaRock** [comment]
Thank you for your help! I hope you are well and sorry for the late reply. I was able to resolve this issue with your help.

Kind Regards
