### ISSUE TITLE
Access to simulation.on()?

### ISSUE THREAD

**Issue by sbusch** [vasturiano/3d-force-graph#53]
I need access to the [simulation.on](https://github.com/vasturiano/d3-force-3d#simulation_on), so I'll be able to listen to the "end" event in order to change camera position after the simulation has stabilized.

If I read the source correctly, the simulation object doesn't get exported to "user land".

Thanks for your cool library!

**Comment by mys** [comment]
+1, am struggling hard to be able to catch 'end' event too.

I have managed to retrieve `state.d3ForceLayout` which contains eg. **`on()`**, `restart()` or `stop()` methods. Hovewer both 
```
state.d3ForceLayout().on('tick', () => { console.log('tick'); });
state.d3ForceLayout().on('end', () => { console.log('end'); });
```
don't output. 
@vasturiano, does [forceSimulation](https://github.com/vasturiano/d3-force-3d/blob/master/src/simulation.js) override the d3 simulation.on methods?

**Comment by vasturiano** [comment]
@mys @sbusch I've added two additional methods to expose this functionality: `.onEngineTick()` and `onEngineStop()`. They are called at every tick and when the layout freezes, respectively.

Please check the latest version of the lib (`1.36.0`).

And let me know if you experience any issues.
