### ISSUE TITLE
Is it possible to combine html-nodes with custom geometry ?

### ISSUE THREAD

**Issue by scenaristeur** [vasturiano/3d-force-graph#531]
i would like to combine html nodes https://github.com/vasturiano/3d-force-graph/blob/master/example/html-nodes/index.html with custom node geometry https://github.com/vasturiano/3d-force-graph/blob/master/example/custom-node-geometry/index.html.

Is it possible ? 

html node

![image](https://user-images.githubusercontent.com/4020744/160565227-fedcedb5-9e06-4a3f-a7f2-59792f46576e.png)

custom node geometry

![image](https://user-images.githubusercontent.com/4020744/160565839-54bb9892-9bd6-4bcd-b34c-8ceefbdeb5c0.png)

for now i can display custom node but a sphere persist and i don't know how to return a combination of custom geometry + html label. 

Do you have an idea , Thxs 

here is what i get for now 
https://scenaristeur.github.io/agent/?source=https%3A%2F%2Fspoggy-test2.solidcommunity.net%2Fpublic%2Fbrains%2Fshapes%2F

with that code https://github.com/scenaristeur/agent/blob/8ad914fffab48fe46d51489e486d9afa2ce44e8e/src/plugins/graph3d-plugin.js#L66

i've tried with group but the graph does not delete old labels on refresh https://github.com/scenaristeur/agent/blob/99ad7b7aa2b0241b87bd83e94471ac515437b24d/src/plugins/graph3d-plugin.js#L113

**Comment by vasturiano** [comment]
@scenaristeur thanks for reaching out.

There should be no problem with combining `CSS2DObject` with regular meshes in your `nodeThreeObject` function. Using a Group to include both should work without any issues.

I'm not sure why you're not seeing labels disappear on data changes but could be an unrelated issue. Are you still experiencing that?

**Comment by scenaristeur** [comment]
@vasturiano  thxs for taking time, here is what i get with groups
 it is what i get with Groups (label persists + sphere persist) (label persistance could be similar to https://blog.katastros.com/a?ID=01700-391eab1a-8493-45a9-aaae-8231a005b399 , i will try)

https://user-images.githubusercontent.com/4020744/162703920-1e7c94ae-ee39-4b2c-807b-0687fe687f40.mp4

but even without groups, label don't appear but the sphere is always here


https://user-images.githubusercontent.com/4020744/162705893-52d0bdfe-0f60-44f3-adb0-da75dfd03dd3.mp4

**Comment by vasturiano** [comment]
@scenaristeur to not render the node default object (sphere), you just need to set `nodeThreeObjectExtend(false)`. In fact, it is `false` by default, so perhaps it's been actively set in your code?

**Comment by scenaristeur** [comment]
> to not render the node default object (sphere), you just need to set nodeThreeObjectExtend(false). 
-> yes i've set it to true, otherwise nothing represent the node and we can't click it / select it.

For this point, i need both : show a shape if one is defined, and the default sphere if none is defined . So i used a test like https://github.com/scenaristeur/agent/blob/4dd111fcb84dddbae03d939185c5ff1e5c06643d/src/plugins/graph3d-plugin.js#L33

https://scenaristeur.github.io/agent?source=https://spoggy-test2.solidcommunity.net/public/Shapes and Default/
![image](https://user-images.githubusercontent.com/4020744/162897262-a81e9436-81a5-4ebb-bd34-d67663b90956.png)

Data is stored as jsonld https://spoggy-test2.solidcommunity.net/public/Shapes%20and%20Default/

For the sphere hidden, it's ok, but not yet for the label as you can see. I did not succed yet with the label but it seems it's an issue with three.js & vue.js as mentionned here https://blog.katastros.com/a?ID=01700-391eab1a-8493-45a9-aaae-8231a005b399 not with your awesome https://github.com/vasturiano/3d-force-graph

**Comment by vasturiano** [comment]
> For this point, i need both : show a shape if one is defined, and the default sphere if none is defined.

For these cases you can just return `false` in your `nodeThreeObject`, and it will fallback to the default representation. As mentioned in the docs:

> Node object accessor function or attribute for generating a custom 3d object to render as graph nodes. Should return an instance of [ThreeJS Object3d](https://threejs.org/docs/index.html#api/core/Object3D). If a falsy value is returned, the default 3d object type will be used instead for that node.
