### ISSUE TITLE
Best way to change the color of all nodes in a graph?

### ISSUE THREAD

**Issue by tiny-witch** [vasturiano/3d-force-graph#536]
I'm sure there is an easy solution here but I'm dealing with a graph where none of my nodes have group attributes. I know that nodeColor likes to have a function and giving it a simple color string, ie `.nodeColor('rgb(255,0,0');`  doesn't work and results in the graph just using the default node material. Does anyone know the best way to change the color of all of the nodes?
For convenience, here is my sample data json if that makes things easier:
` {
    "nodes":[
        {"id": "A"},
        {"id": "B"},
        {"id": "C"},
        {"id": "D"}
    ],
    "links":[
        {"source": "A", "target": "B"},
        {"source": "A", "target": "C"},
        {"source": "A", "target": "D"}
    ]
} `
and my sample code:
`
const Graph2 = ForceGraph3D()
        (document.getElementById('graph2'))
          .jsonUrl('./data.json')
          .nodeLabel('id')
          .enableNodeDrag(false)
          .zoomToFit(0,10, node =>true)
          .enableNavigationControls(true)
          .nodeColor('rgb(255,0,0');
`

**Comment by vasturiano** [comment]
```js
.nodeColor(() => 'rgb(255,0,0)')
```
