### ISSUE TITLE
cannot get previous real camera position

### ISSUE THREAD

**Issue by FPRM** [vasturiano/3d-force-graph#538]
**Describe the bug**
cannot get current real camera position for further rendering

**Environnement**
VueJs 2.6

**To Reproduce**
1. I have a method that create a render from a graphdata JSON
2. I have some methods that alter data depending on user interaction in form ( alter size/color/opacity, etc....) and node click
    2.1 when user clicks on a node the path to the shorter neareast nodes (3 level) changes size and color 
4. On interaction i want to render the graph again, but at same camera position, angle and zoom level  

**Expected behavior**
onNodeCLick methods calls another method in wich i will first be able to retreive camera position. wich x,y,z 3 vector of rotation, and zoom level. then process to data transformation and then render a new force graph 3D with the previous camera position, angle and zoom level.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser chrome
 - Version 100.0

template
```
<template>
  <div id="app">
      <v-row
         no-gutters
         class="mt-n5"
      >
      <v-col cols="2">
         <v-card
            elevation="2"
            outlined
            class="mx-2"
         >
            <v-card-text>
               <p>hello</p>
            </v-card-text>
   
            <v-card-actions>
            <v-btn
               outlined
               rounded
               text
            >
               Button
            </v-btn>
            </v-card-actions>
         </v-card>
      </v-col>
       <v-col cols="10">
          <div ref="mygraph"/>
      </v-col>
      </v-row>

    
  </div>
</template>
```

script methods
```
<script>
import ForceGraph3D from '3d-force-graph';
import * as THREE from 'three'


export default {
  name: 'App',
  data(){
    return {
      rootdata:{},
      graphdata:{},
      cameracontrol:null,
      graph:null
      }
   },
  mounted() {
     this.rootdata = require('@/config/data.json')
     this.graphdata = this.rootdata
     this.renderGraph()
   },
   methods: {
      changedata(node) {
         console.log(node)
         const graphcamera  = ForceGraph3D()(this.$refs.mygraph).cameraPosition()
         console.log(graphcamera)
         // alter data here
         this.renderGraph()

      },
      renderGraph(){
         console.log('render graph')
         const graph = ForceGraph3D()
         .backgroundColor('#10103b')
         .zoomToFit()
         .onNodeClick(nodes=>{this.changedata(nodes)})
         graph(this.$refs.mygraph).graphData(this.graphdata)
         graph.d3Force('link').distance(link=>link.length)
         
         graph.linkColor(link=>link.linkcol)
         graph.nodeThreeObject((nodes) =>{
            return new THREE.Mesh(
               new THREE.SphereGeometry(nodes.val*0.8),
               new THREE.MeshLambertMaterial({
                  color: nodes.color,
                  transparent: true,
                  opacity: nodes.opacity
               })
            )
         })       

      }
   },
}
</script>
```

**Comment by vasturiano** [comment]
@FPRM thanks for reaching out. To follow your issue a little closer, it's better if you could make a reduced interactive example on https://codesandbox.ai that demonstrates the problem.

In any case, I see you are extracting the camera position on `const graphcamera  =  ...`, but that variable is not being used for anything.

**Comment by FPRM** [comment]
I find my way out. I put a looped timeout to watch the coordinate and set them in a variable so i could reset the previous Field of view when re render the graph.
I don't know if it's the cleaner way. but it do the Job. Thanks anyway
