### ISSUE TITLE
lineHoverPrecision seems not reacting

### ISSUE THREAD

**Issue by machmuel** [vasturiano/3d-force-graph#542]
**Describe the bug**
regardless of my used vlue for lineHoverPrecision (like 10 or 500), the linkLabels only appear, when I hover strictly above the link line.

**To Reproduce**
trivial

**Expected behavior**
Show linkLabel, when mouse hover 10 pixels (?) r less away from it.

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu
 - firefox
 

**Additional context**
I´ll share my code:

**Comment by machmuel** [comment]
[index.zip](https://github.com/vasturiano/3d-force-graph/files/8770360/index.zip)

Uploaded file, as the editor did not allow for such large files.

**Comment by vasturiano** [comment]
@machmuel keep in mind that hover precision is only applicable for default links based on [ThreeJS Line](https://threejs.org/docs/#api/en/objects/Line). If you have set a `linkWidth` other than `0`, or build your own custom link object, it is no longer applicable. For those cases, the regular Three object raycast intersection logic is used.
