### ISSUE TITLE
Better performance suggestion

### ISSUE THREAD

**Issue by AivarGabd** [vasturiano/3d-force-graph#549]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when a big graph with a lot of **links** drops fps when it starts moving.

**Describe the solution you'd like**
If it is possible to take apart one big graph and make them less dependenting on each over.

**Describe alternatives you've considered**
Instead, on one same page create few big graphs and connect them with lines.
![Group 3](https://user-images.githubusercontent.com/78880503/174642990-e17c50a4-1f7e-4328-884f-4e062747c0cf.png)

**Comment by vasturiano** [comment]
@AivarGabd I don't believe that's possible, at least not within a single instance of `3d-force-graph`. Each node in the graph is considered for the computation of the forces that leads the system into equilibrium.
What you can do is reduce the number of engine ticks that run during the cooldown phase, or after a node drag, using the `cooldownTicks(<num>)` method.

**Comment by AivarGabd** [comment]
Oki, i am using nodeResolution, still big thanks, love your work btw
