### ISSUE TITLE
Need some help to implement multiple layers visualize.

### ISSUE THREAD

**Issue by wangqinghuan** [vasturiano/3d-force-graph#550]
Sorry, this is just a question and need some minds.
Do you have any minds or practice on doing similar effect to this demo? Any  feedback is appreciated.
![image](https://user-images.githubusercontent.com/22762150/174701380-7da7c8a3-cd5c-45a9-b01d-276749263898.png)

**Comment by vasturiano** [comment]
@wangqinghuan there is this somewhat similar example:
https://vasturiano.github.io/3d-force-graph/example/tree/

**Comment by wangqinghuan** [comment]
Thank you.@vasturiano
