### ISSUE TITLE
Nodes tend to bundle up and stay attracted to each other

### ISSUE THREAD

**Issue by aadithya-sesh68** [vasturiano/3d-force-graph#551]
<img width="811" alt="Screenshot 2022-06-22 at 9 54 00 AM" src="https://user-images.githubusercontent.com/54074609/175094436-e02dc43d-5db5-4b7f-99d1-7a9a4af52bfb.png">
<img width="832" alt="Screenshot 2022-06-22 at 9 54 41 AM" src="https://user-images.githubusercontent.com/54074609/175094581-ca0ed307-5654-4ee1-aaa3-a0c931bbd6d1.png">

How to disable or tweak this property so that I can see the edges present? PFA the code below: 

import React, { useRef } from 'react'
import { useQuery, gql } from '@apollo/client'
import ForceGraph3d from 'react-force-graph-3d'

export default function GraphViz() {
  const fgRef = useRef()
  const MODIFIED_CRIME_JUNCTIONS_QUERY = gql`
    {
      Crime {   
        crime_id
        type_of_crime
        recency
        nearest_crime_jn {
          _id
        }
      }
        Junction {
          _id
          x
          y
          street_count
          vulnerability_score
      }
    }
  `
  const { loading, error, data } = useQuery(MODIFIED_CRIME_JUNCTIONS_QUERY)
  if (error) return <p>Error</p>
  if (loading) return <p>Loading</p>
  //console.log(data)
  //console.log(data.Crime[0]['nearest_crime_jn'][0]['street_count'])

  var nodes = new Set()
  var edges = new Set()

  data.Junction.forEach((jn) => {
    nodes.add({
      id: jn._id,
      x: jn.x,
      y: jn.y,
      street_count: jn.street_count,
      vulnerability_score: jn.vulnerability_score,
      color: 'blue',
    })
  })

  console.log(nodes)

  data.Crime.forEach((c) => {
    nodes.add({
      id: c.crime_id,
      type_of_crime: c.type_of_crime,
      recency: c.recency,
      name: c.crime_id,
      color: 'red',
    })
    c.nearest_crime_jn.forEach((edge) => {
      edges.add({
        source: c.crime_id,
        target: edge._id,
      })
    })
  })

  console.log(nodes)

  const graph = {
    nodes: [...Array.from(nodes)],
    links: [...Array.from(edges)],
  }
  console.log(nodes)

  return (
    <ForceGraph3d
      ref={fgRef}
      graphData={graph}
      width={'80%'}
      height={'100vh'}
      backgroundColor={"#22272b"}
      numDimensions={2}
      forceEngine={'d3'}
      nodeRelSize={2}
      d3VelocityDecay={0.7}
      rendererConfig={{
        antialias: true,
        alpha: true,
        logarithmicDepthBuffer: true,
      }}
      nodeVal={100000}
      onEngineStop={() => {
        fgRef.current.controls().maxDistance = 3000000
        fgRef.current.camera().near = 2000000
        fgRef.current.camera().far = 2000000000
      }}
      onNodeRightClick={(node) => {
        var info = Array.from(nodes).filter((obj) => obj.id == node.id)
        console.log(info)
      }}
      linkVisibility={true}
    />
  )

**Comment by Deaponn** [comment]
You can use `forceCollide` to space out your nodes
```
import { forceCollide } from "d3-force-3d";

fgRef.current.d3Force(
        "collide",
        forceCollide(50)
);
```

**Comment by aadithya-sesh68** [comment]
Thank you!
