### ISSUE TITLE
Question: Fix all nodes to a given position

### ISSUE THREAD

**Issue by guillemfigols** [vasturiano/3d-force-graph#559]
I'm trying to represent the following JSON file for a project. (It's not the real one, but it has the same structure )
~~~
{
    "nodes": [
        {"id":0,"y":-50,"x":21.6, "z": 10},
        {"id":1,"y":100.229637146,"x":155.395904541, "z": 15},
        {"id":2,"y":46.6591949463,"x":-207.792068481,"z": 16},
        {"id":3,"y":27.60389328,"x":133.966064453,"z":20},
        {"id":4,"y":126.531860352,"x":-26.9523639679,"z":30},
        {"id":5,"y":163.070098877,"x":-86.976524353,"z":40}   
    ],
    "links": [
        {"source":0, "target":1},
        {"source":1, "target":2},
        {"source":3, "target":4},
        {"source":5, "target":2},
        {"source":5, "target":3}
    ]}
~~~

The thing is that all nodes have to be fixed and cannot be mutable, so I'm not really interested in the force-directed algorithm (instead I'm interested in the responsiveness and the aesthetics which this component provides, I want to be able to move through the graph, zoom in, zoom out, ...). How could I accomplish this? I've seen that i can fix the nodes to a given position using `fx`, `fy`, `fz`, but if I'm not mistaken, I have to do this manually for every node... is there a way to do it for all the nodes? (I'm dealing with more than 1000 nodes)

Thank you!

**Comment by vasturiano** [comment]
@guillemfigols you should just need to add those f* attributes once, something like:
```js
myData.nodes.forEach(d => {
  d.fx = d.x;
  d.fy = d.y;
  d.fz = d.z;
})
```
