### ISSUE TITLE
Paint two different graphics

### ISSUE THREAD

**Issue by EmmaU25** [vasturiano/3d-force-graph#56]
Hi, look, I do not know if I've already talked to you about the subject but I'm trying to do this

At the beginning I paint a graph as indicated by your documentation with the variable
Graph = ForceGraph3D ()

with the functions that I need, but in a certain point of my application I want to paint another graphic but different from the one that is already painted. I use the same variable that is "Graph" with the exception that now I pass new data to draw them

but what it does is just draw me the new graphic on which it was already drawn. I sent you an image of the problem

The all white graphic is the new one that I painted

Image example link https://ibb.co/m0E4xS

I tried to declare the variable "Graph = null" to delete everything but it does not work

the only solution I've seen is to reload the entire page, would like to know if there is a possibility to paint a new graphic without reloading the page?

**Comment by vasturiano** [comment]
Hi @EmmaU25 thanks for reaching out. 
If you wish to pass new data to an existing graph all you need to do is call 
`myGraph.graphData(<my new dataset>)`

The graph will dynamically react to these data changes and remove all nodes/links that are not present in the new data structure.
Here's an example of dynamic data changes: [example](https://vasturiano.github.io/3d-force-graph/example/dynamic/) | [source](https://github.com/vasturiano/3d-force-graph/blob/master/example/dynamic/index.html).

Does that example work for you?

Keep in mind that you do **not** have to re-initialize the Graph by calling `myGraph(<my dom element>)`, simply calling `.graphData(...)` should suffice.
