### ISSUE TITLE
Question:weaken text overlap

### ISSUE THREAD

**Issue by wangqinghuan** [vasturiano/3d-force-graph#565]
Hi
This is a [Graph](http://www.clickcat.cloud/graph) based on [3d-force-graph](https://github.com/vasturiano/3d-force-graph).Node text overlaps as 
![image](https://user-images.githubusercontent.com/22762150/184565558-b29c8648-ad03-4ade-9bdf-7632e51020ef.png)
How to weaken text overlap?

**Comment by wangqinghuan** [comment]
Or fades backend node text.

**Comment by vasturiano** [comment]
@wangqinghuan you could try adding some transparency to your labels (f.e. by setting the text color to an `rgba` value). That will potentially make it more readable.
