### ISSUE TITLE
Display label for "Close Nodes"

### ISSUE THREAD

**Issue by anaclumos** [vasturiano/3d-force-graph#576]
Would it be possible to display labels (or tooltips) for close-enough nodes?

**Comment by Mush-A** [comment]
@anaclumos @vasturiano  Hello Anaclumos! This is quite possible by mapping over the 3d objects and checking their distance from the camera. A callback can be used like this:

```
const showLabel = (Graph, distance) => {
    Graph.graphData().nodes.map(node => {
        if (Graph.camera().position.distanceTo( node.__threeObj.position ) <= distance) {
            <code to show label>
        }
    })
}
```
This callback can be used in the event the camera changes position or using the animation loop like this:
```
const DISTANCE = 800 // world units.

Graph.renderer().setAnimationLoop(() => showLabel(Graph, DISTANCE))
```
I think using the camera position change event might be more efficient.
