### ISSUE TITLE
Particles emitted not deleted on re-render, and no method to delete / clear them

### ISSUE THREAD

**Issue by AshleySetter** [vasturiano/3d-force-graph#577]
**Describe the bug**
I am using ForceGraph3D to display some graphical data, and the data displayed is toggle-able, I have a useEffect hook which alters the graphData when the mode is switched and this works great! However we are also using the emiParticle method, when the mode is switched the graphData changes the ForceGraph3D re-renders, but the particles remain, now with no nodes to travel to, they continue to sit on the graph forever, until the page is refreshed. How can i clear these particles on changing the graphData?

**To Reproduce**
A minimal example with the logic to reproduce the issue is shown below:

```
import {ForceGraph3D} from "react-force-graph";

function MyComponent({data1, data2) {
  const graphRef = useRef();
  const [altMode, setAltMode] = useState(false);
  const [graphData, setGraphData] = useState({nodes: [], links: []});
  const [counter, setCounter] = useState(0);

  // Load Graph Data
  useEffect(() => {
    const myGraphData = altMode ? data1 : data2;
    setGraphData({...myGraphData});
  }, [query, ipMode]);

  // Particle emission
  useEffect(() => {
    if (!graphRef.current || !graphRef.current.cameraPosition) return () => {};

    const timer = setInterval(() => {
      setCounter(((counter + 1) % (events && events.length)) || 0);
      if (counter % 2) {
        const {source, target, altSource, altTarget} = events && events[counter] || {};
        const emitSource = altMode ? altSource : source;
        const emitDestination = altMode ? altTarget : target;
        const link = graphData.links.find(({source, target}) => {
          return source.id === emitSource && target.id === emitDestination;
        });
        graphRef.current.emitParticle(link);
      }
    }, 50);

    return () => clearInterval(timer);
  });

  return (
    <>
      <Button
        onClick={() => setAltMode(!altMode)}
      >
        {altMode ? "Alternate Mode" : "Normal Mode"}
      </Button>
      <ForceGraph3D
          backgroundColor="rgba(0,0,0,0)" // transparent
          width={size.width} height={size.height}
          ref={graphRef}
          graphData={graphData}
          nodeLabel={(node) => node.name}
          nodeColor={(node) => highlightedNodes.has(node.id) ? shadeHexColor(node.color, 0.5) : node.color}
      />
    </>
  )
}
```

**Expected behavior**
Either the particles should be deleted on new graphData being provided, or a method should be exposed to delete particles.

**Screenshots**
![image](https://user-images.githubusercontent.com/14869658/199255467-e41bf986-c8b8-4407-af8b-8b450dfe614b.png)
The white dots are my particles,

**Comment by vasturiano** [comment]
@AshleySetter thanks for your bug report.

I've just [pushed a fix](https://github.com/vasturiano/three-forcegraph/commit/8a5fd0fe021f18f5cce1fe457d6a8d28a0880a9b) for this specific issue onto the underlying package `three-forcegraph`. So if you upgrade your inner dependencies and `three-forcegraph` to latest (1.39.7) this should be fixed. Single emitted particles will be removed at the same time that the corresponding link is removed.

**Comment by AshleySetter** [comment]
Thanks for fixing this issue, this works great, see [example codesandbox](https://codesandbox.io/s/silly-carson-jfpydu)
