### ISSUE TITLE
Problem - Links to the same state

### ISSUE THREAD

**Issue by EmmaU25** [vasturiano/3d-force-graph#58]
Hello Vasco now I have a problem, because I realized that the library does not create links that leave a state but its destination is the same state

I apologize so much but I can not find what the problem is

thank you very much for your attention

**Comment by EmmaU25** [comment]
quisiera que se mostrará como esto

http://3.bp.blogspot.com/-0Ge6eutgGMw/TfvKlhkJKHI/AAAAAAAAACs/L3TqIyNuEjc/s1600/BUCLE1.png

**Comment by vasturiano** [comment]
@EmmaU25 just to let you know that this self-loop view is now possible, using the `linkCurvature` property.
Here's an [example](https://vasturiano.github.io/3d-force-graph/example/curved-links/).

Let me know if that works out for you.

**Comment by EmmaU25** [comment]
Thank u so much for that, but what is the value of ## curvature et rotation???

source: 0, target: 1, curvature: 0, rotation: 0

**Comment by EmmaU25** [comment]
hi vasco I tested the updates and it works perfect except that now the clickNode function is not accurate, I do not know why. Indeed I tested the example that you have on github and it's the same problem

thank you so much

**Comment by EmmaU25** [comment]
yes, it is the same problem, but, the problem is the animation, that is, I have to click the node 2 or 3 times to activate it and that started after updating the package

**Comment by vasturiano** [comment]
@EmmaU25 do you experience the click issues only immediately after rotating the canvas, or also when the system is at a complete rest for at least a few seconds?

**Comment by EmmaU25** [comment]
I just tried the two situations and the problem happens only immediately after rotating the canvas, because if after I let the graphics rest for a second, the first click works
