### ISSUE TITLE
Need help with making nodes have square, circle, and image from group number

### ISSUE THREAD

**Issue by peestract** [vasturiano/3d-force-graph#583]
Hi,
I've been looking over all the great examples and help you have given others. I am a beginner, and for the life of me I cannot figure out how to use shapes with images. 

I am using the Les Miserables example dataset you worked with in your 'multi dimensional force graph example' where you have the different dimensions. 

What I would love to accomplish is to be able to make all nodes in group 1 a circle sphere, nodes in group 2 an image, and nodes in group 3 a square box. 

Any assistance you could provide would be incredible!

**Comment by vasturiano** [comment]
@peestract thanks for reaching out.

Have you seen this example, which uses different geometries for the nodes?
https://vasturiano.github.io/3d-force-graph/example/custom-node-geometry/

All you should need to do is adapt that example to have the decision logic of which shape to use based on the node group (or some other attribute of the node data point).

**Comment by peestract** [comment]
Hi @vasturiano - thanks so much for your response. 

I have seen that example. I am having difficulty including the geometries into my  'nodeThreeObject'
This is what I have - as you can see I am able to specify that group 1 should have the specific image, but not sure how to include the same for geometries...

.nodeThreeObject(node => { 
        
            const imgTexture = new THREE.TextureLoader().load('https://picsum.photos/100/100/?random');
            const material = new THREE.SpriteMaterial({ map: imgTexture, color: node.colour, side: THREE.DoubleSide, depthWrite:false });
            const sprite = new THREE.Sprite(material);
          sprite.scale.set(12, 12); 
          const label = new SpriteText(node.id);
            label.material.depthWrite = false; // make sprite background transparent
            label.color = node.color;
            label.textHeight = .3;
            sprite.add(label)
            if (node.group === 1) {
                return sprite;
              }
            })
            
            
            
            
           For geometries, I have the example below, but not sure how to make that work with the above - and be able to do that same thing above for a specific group number.
           
           .nodeThreeObject(group => new THREE.Mesh(
    new THREE.BoxGeometry(3, 3, 5),
     new THREE.MeshBasicMaterial({
       color: group.color,
       transparent: true,
      opacity: group.opacity
    })
     
   ))

**Comment by peestract** [comment]
Hi again, I was able to do it successfully with this 

.nodeThreeObject(node => { 
            
            const imgTexture = new THREE.TextureLoader().load('https://picsum.photos/100/100/?random');
            const material = new THREE.SpriteMaterial({ map: imgTexture, color: node.colour, side: THREE.DoubleSide, depthWrite:false });
            const sprite = new THREE.Sprite(material);
          sprite.scale.set(12, 12); 
          const label = new SpriteText(node.id);
            label.material.depthWrite = false; // make sprite background transparent
            label.color = node.color;
            label.textHeight = .3;
            sprite.add(label)
            
            if (node.group === 1) {
                return sprite;
              }
              const box = new THREE.Mesh(
                new THREE.BoxGeometry(1, 1, 1),
                new THREE.MeshBasicMaterial({ color: node.color})
              )
            if (node.group === 2) { return box; }
            
            })





Another question though - are you able to apply labels to geometries???

**Comment by vasturiano** [comment]
You probably want to combine it with this other example that uses text as nodes?
https://vasturiano.github.io/3d-force-graph/example/text-nodes/

**Comment by peestract** [comment]
Yes, except when I do that - the sprite image is filled with the default sphere... 
Thanks a lot for helping on this, I admire this work you do.

**Comment by vasturiano** [comment]
@peestract you need a combination of both. You can include both custom geometry and a text object encapsulated in [ThreeJS Group](https://threejs.org/docs/#api/en/objects/Group).

**Comment by peestract** [comment]
Thank you @vasturiano
