### ISSUE TITLE
Can't make nodes to stick at defined fixed x y z position.

### ISSUE THREAD

**Issue by sab4a** [vasturiano/3d-force-graph#589]
**Describe the bug**
Can't make nodes to stick at defined fixed x y z position.

I tried fixed:true on nodes but it does not work..
disabling forces via d3force does not set up graph properly.

**Screenshots**
https://imgur.com/a/8uSC7yn

For example, it is floating on the left side and gets dragged, how can I set it to stick at the predefined x,y,z position?

**Comment by RaulPROP** [comment]
You just need to set the position at the `fx`, `fy` and `fz` properties.

**Comment by sab4a** [comment]
> You just need to set the position at the `fx`, `fy` and `fz` properties.

Hi, thanks for your response!

My array with nodes and links has only x y z coordinates, how can I set fx fy and fz properties?

**Comment by sab4a** [comment]
I've added fx fy fz properties with   

```
this.data.nodes.forEach(node => {
    node.fx = node.x;
    node.fy = node.y;
    node.fz = node.z;
  });
```

<img width="343" alt="image" src="https://user-images.githubusercontent.com/36389381/208696233-11c0f4b5-7578-4c30-a2ed-2d297efde41c.png">

Now its a single dot

**Comment by RaulPROP** [comment]
Maybe the `fx`, `fy` and `fz` properties that you are fixing are the same point.

If you give each node a position to `fx`, `fy` or `fz`, that value will not be changed by the force engine.

[Example](https://codepen.io/raulprop/pen/dyjPPjR)

**Comment by sab4a** [comment]
https://codepen.io/ProxyMoxy/pen/JjBozqQ

no it's not the same, can you pleasel look at this?

**Comment by RaulPROP** [comment]
Your positions are too close to each other, taking into account the volume of the spheres they overlap.

Just multiply the `x`, `y` and `z` by 20 and you are good to go [(like in this example)](https://codepen.io/raulprop/pen/ZEjGEQJ).

**Comment by sab4a** [comment]
Ohh... Thank you sir!
