### ISSUE TITLE
IE10 crashes in import phase

### ISSUE THREAD

**Issue by artyomtrityak** [vasturiano/3d-force-graph#59]
When 3d-force-graph library is included it crashes in IE10.
IE10 is not supported in THREE.js but the issue itself is that library crashes in import phase, not runtime phase so

```js
import ForceGraph3D from "3d-force-graph";
```

crashes application in IE10 without possibility to fallback and show that IE is not supported for 3d graph.

I can work on PR to fix this in few days, just want to let you know.

**Comment by vasturiano** [comment]
Thanks for flagging this @artyomtrityak.
I don't have a copy of IE10 at hand right now so can't reproduce, but do you if it's specific to IE10 (and lower I guess)? Is IE11 and Edge working fine in this respect?

Also, were you running the `import` statement directly on the browser, or is it being bundled by Webpack or similar?

**Comment by artyomtrityak** [comment]
@vasturiano yeah, i'm using webpack to build it. IE11 works fine because it supports WebGL. It's fine that library does not work for IE10 but it should not crash in import phase. I'll make a PR on weekend.

**Comment by artyomtrityak** [comment]
@vasturiano the issue is a bit more complex. (linkKapsule)[https://github.com/vasturiano/3d-force-graph/blob/master/src/kapsule-link.js] method calls `stateInit` for three-render-objects.

This happens in runtime even `ForceGraph3D()` has not been called, in import phase.
Do you expect that stateInit should be called at that moment even if 3d graph is not rendered for this page?

**Comment by vasturiano** [comment]
Thanks for this research @artyomtrityak. 
> Do you expect that stateInit should be called at that moment even if 3d graph is not rendered for this 
> page?

Yes, this is expected. `stateInit` is ran at component instantiation, and the instantiation is necessary to extract the prop defaults. Also, the consuming `linkKapsule` is ran at import phase as it is necessary to define the `3d-force-graph` component interface itself. 

> 1. Check if WebGL is available here and if not return null.
It solves IE10 issue but library itself still calls dummy kapsule and initialize webgl context even it is not needed at that moment.

I believe it would have to be prior to the linking functionality [here](https://github.com/vasturiano/3d-force-graph/blob/master/src/3d-force-graph.js#L20). 

> 2. Change linkKapsule method and do not create dummy kapsule. It solves IE10 issue and also removes unnecessary webql renderer creation.

In this case, the props of `3d-force-graph` would not be properly defined, if the defaults are not extracted.

I think there's a third option: do the WebGL check directly in `three-render-objects`, possibly in the location where the renderer is [instantiated](https://github.com/vasturiano/three-render-objects/blob/master/src/three-render-objects.js#L145).

Could you include a few more details about the JS error that occurs in IE10, and the line where it errors?

Thanks!

**Comment by vasturiano** [comment]
An update on this, I've modified `three-render-objects` to not call the WebGLRenderer on instantiation (`stateInit` method), but on component initialisation (`init` method). This way, it's no longer called by `linkKapsule`.
Could you please try with `v1.31.2` and let me know if this fixes the issue?

**Comment by artyomtrityak** [comment]
@vasturiano will check and update today

**Comment by artyomtrityak** [comment]
@vasturiano it works great. Thank you!
