### ISSUE TITLE
Selection of Multi Nodes using a Window

### ISSUE THREAD

**Issue by mdavis95** [vasturiano/3d-force-graph#6]
Would it be possible to select multiple nodes using a bounding box window?  I dug a little and have no idea how to add that.

**Comment by mdavis95** [comment]
https://bountify.co/allow-multiple-selecting-nodes-via-a-mouse-selection-area-3d-force-graph-threejs-2

**Comment by vasturiano** [comment]
@mdavis95 I think a feasible manner to achieve that would be to use a system of raycasters: https://threejs.org/docs/#api/core/Raycaster to determine which objects fall within a certain viewbox. Similar to what is happening here for detecting object clicks: https://github.com/vasturiano/3d-force-graph/blob/master/src/3d-force-graph.js#L99

An alternative option would be to play with a secondary camera FOV adjusted to the selected viewbox and detect objects in sight using a Frustum: https://threejs.org/docs/#api/math/Frustum

None of those is currently implemented in 3d-force-graph but I'd be more than happy to accept a PR for this feature if you get something working. :)

**Comment by mdavis95** [comment]
Thanks for the pointers.  I will dig into it a little and see what I can come up with.

**Comment by SquabbyZ** [comment]
I feel like I've implemented the box selection function, and I'll sync the code instance later.
