### ISSUE TITLE
Problem with node drag

### ISSUE THREAD

**Issue by gitgitwhat** [vasturiano/3d-force-graph#60]
For some reason, I can not get the node drag to work.  In this example, I have a number of nodes but no links.  My graph setup is pretty standard as seen below.  I use an onClick handler in order to get the camera scroll effect that is so cool.  

            const elem = document.getElementById('3d-graph');
            Graph = ForceGraph3D()
            (elem)
                .graphData(_graphdata)
                .forceEngine("d3")
                .showNavInfo(false)
                .enablePointerInteraction(true)
                .enableNodeDrag(true)
                .nodeLabel('name')
                .nodeColor('color')
                .onNodeHover(node => elem.style.cursor = node ? 'pointer' : null)
                .nodeThreeObject(node => {
                    return groupNodeWithItems(node);
                })
                .onNodeClick(node => {
                    // Aim at node from outside it
                    const distance = 150;
                    const distRatio = 1 + distance/Math.hypot(node.x, node.y, node.z);
                    Graph.cameraPosition(
                        { x: node.x * distRatio, y: node.y * distRatio, z: node.z * distRatio }, // new position
                        node, // lookAt ({ x, y, z })
                        3000  // ms transition duration
                    );
                });

But trying to click and drag a node just causes the scene to move.

**Comment by vasturiano** [comment]
@gitgitwhat thanks for getting in touch. I don't see anything immediately wrong with the code you included. If you post an illustrating example on [codepen](https://codepen.io/) or similar I'm happy to have a closer look.

**Comment by gitgitwhat** [comment]
Here's a codepen example that shows node dragging issue.

https://codepen.io/anon/pen/VxKLGe

**Comment by vasturiano** [comment]
Thanks for the example. I see what the issue is. It's related to the fact that your `nodeThreeObject` function is creating a Group:
```
var group = new THREE.Group();
  group.add(mesh);
  return group;
```
Unfortunately dragging of groups is not supported by the Three drag controls:
https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/DragControls.js

For this particular example you don't really need a group because it has only one child. But you may need it in the real case.

I'll look into it when I have some time.

And thanks for the report!

**Comment by gitgitwhat** [comment]
That's just a simple example but in my use case I have a whole bunch of objects added to the group.  I also tried it with Object3D which the docs say that Group is nearly identical to but with the same result.

**Comment by somu2324** [comment]
Hi @vasturiano  I also try to drag the node bu enabling .enableNodeDrag(true) function, but it is not working. 
Code to draw 3D graph is below

let highlightNodes = [];
    let highlightLink = null;

    const Graph = window.ForceGraph3D()
    (document.getElementById('graph-3d'))
      .showNavInfo(false)
      .graphData(gData)
      .nodeColor(node => highlightNodes.indexOf(node) === -1 ? 'rgba(0,255,255,0.6)' : 'rgb(255,0,0,1)')
      .nodeLabel(node => highlightNodes.indexOf(node) === -1 ? '' : 'Node ' + (node.id + 1))
      .nodeAutoColorBy('group')
      .linkLabel(link => (link.source.id+1) +' to '+(link.target.id+1))
      .linkWidth(link => link === highlightLink ? 6 : 4)
      .linkDirectionalParticles('value')
      .linkDirectionalParticleWidth(6)
      .enableNodeDrag(true)
      

      .onNodeHover(node => {
        // no state change
        if ((!node && !highlightNodes.length) || (highlightNodes.length === 1 && highlightNodes[0] === node)) return;

        highlightNodes = node ? [node] : [];

        updateGeometries()
      })
      .onLinkHover(link => {
        // no state change
        if (highlightLink === link) return;

        highlightLink = link;
        highlightNodes = link ? [link.source, link.target] : [];

        updateGeometries()
      })

      .onNodeClick(node => {
          // Aim at node from outside it
          const distance = 40
          const distRatio = 1 + distance/Math.hypot(node.x, node.y, node.z)
          Graph.cameraPosition(
            { x: node.x * distRatio, y: node.y * distRatio, z: node.z * distRatio }, // new position
            node, // lookAt ({ x, y, z })
            3000  // ms transition duration
          )
        })

**Comment by vasturiano** [comment]
@somu2324 the previous issue was related to using a `Group` as a custom `nodeThreeObject`. Are you using `nodeThreeObject` in your code?

**Comment by somu2324** [comment]
@vasturiano no i am not using nodeThreeObject. 
Actually not able to understand what was happened. After my 3D model rendered,  I can drag node one time only after that i can not drag the node. 
Could you please help me. my 3D graph rendered code is same as in my previous comment.

**Comment by vasturiano** [comment]
@somu2324 could you make a minimal example that reproduces your issue on [codepen](https://codepen.io/) or similar? That'll make it easier to troubleshoot your case.

**Comment by somu2324** [comment]
Here is the example link.
https://codepen.io/somu2324/pen/YoYpJG

**Comment by vasturiano** [comment]
@somu2324 it's been some time, but I just fixed a bug in the library that was causing the drag to malfunction in your case. If you load the codepen example above you can see that it's fixed. 👍  

If you're pulling from npm, make sure to update to the latest version (`1.56.0`) to get the fix.
