### ISSUE TITLE
Dashed link with custom THREE.js dashedLineMaterial

### ISSUE THREAD

**Issue by PixDay** [vasturiano/3d-force-graph#609]
**The bug**
I try to have a dashed link using `linkThreeObject` and a custom [THREE.LineDashedMaterial](https://threejs.org/docs/index.html?q=line#api/en/materials/LineDashedMaterial)

When giving this custom material, the link is having a basic unicolor material, and become a line instead of a segment

**To Reproduce**
Create few nodes and links
On your ForceGraph3D use the `.linkThreeObject` method and for every link return a three cylinderGeometry mesh that contain a DashedLineMaterial

**Expected behavior**
Link are no longer segment but lines and they are not dashed line

 - OS: windows 10
 - Browser Google Chrome 111.0.5563.147 (64 bits)

**Comment by vasturiano** [comment]
@PixDay if that's the underlying issue, but I believe you can't apply `LineDashedMaterial` to meshes like cylinders. It needs to be applied to a [Line](https://threejs.org/docs/#api/en/objects/Line) object.

**Comment by PixDay** [comment]
Right, I see, do we have a way to set a line object for the links ( and make its distance set automatically between the two nodes) so I can set the DashedLineMaterial on my line that will be a Line Three object

**Comment by vasturiano** [comment]
@PixDay the positioning and length of the link is handled by `linkPositionUpdate`, so if you leave that to default you don't need to worry about implementing it.
So, all you need to do is implement `linkThreeObject`, in which you set a `Line` object with `LineDashedMaterial`.

**Comment by ZiadJ** [comment]
@vasturiano Is there a way to add a texture to the cylinders?

**Comment by vasturiano** [comment]
@ZiadJ you can do it with `linkMaterial`.

**Comment by PixDay** [comment]
@vasturiano If I use `linkThreeObject` to set a line object with `lineDashedMaterial` I have a curved line and it's not dashed do you know if it's normal behavior, or how I can make the lines straight and dashed?

**Comment by vasturiano** [comment]
@PixDay that's difficult to tell without more info. Could you make a reduced example on https://codepen.io/?

You can also try with just setting your `lineDashMaterial` on `linkMaterial` and not override `linkThreeObject`.

**Comment by PixDay** [comment]
@vasturiano  I understand, sorry, I did manage my issue with the curved link (I just had the wrong curvature and rotation value in my link object)

For the line material and object in the `linkThreeObject` here is my code:

```
const material = new THREE.LineDashedMaterial({
            color: "red",
            dashSize: 100,
            gapSize: 20,
            linewidth: 15,
            scale: 5,
        });
        const points = [];
        points.push(new THREE.Vector3(0, 0, 0));
        points.push(new THREE.Vector3(0, 0, 0));
        let line = new THREE.Line(new THREE.BufferGeometry().setFromPoints(points), material);
        return line;
```

**Comment by PixDay** [comment]
Nevermind, it's perfectly working this came from my big graph, the gap and dash size were very small, and I couldn't see them but they were existing 

I also needed to set a value to my Vector3 to make them visible

I will mark this issue as solved and close it.


Do you know if elements (nodes and / or links that are modified from ThreeObject methods are able to change size with linkWidth or nodeRelSize methods ?

Thanks for the help

**Comment by vasturiano** [comment]
> Do you know if elements (nodes and / or links that are modified from ThreeObject methods are able to change size with linkWidth or nodeRelSize methods ?

No. These are only means to control the default node/link representation. If you're doing custom objects those attributes are ignored.
