### ISSUE TITLE
.nodeThreeObjectExtend is not a function

### ISSUE THREAD

**Issue by PixDay** [vasturiano/3d-force-graph#610]
**Describe the bug**
`.nodeThreeObjectExtend is not a function` appear when I'm trying to use it with `ForceGraph3D`

**To Reproduce**
Create a ForceGraph3D with this settings and calls:
```
ForceGraph3D({controlType: "orbit", extraRenderers:[new CSS2DRenderer()], rendererConfig: {antialias: true}})
    (document.getElementById('d-graph'))
    .forceEngine("d3")
    .numDimensions(3)
    .width(window.innerWidth)
    .height(window.innerHeight)
    .d3Force('center', null)
    .d3Force('charge', null)
    .d3Force('collide', d3.forceCollide(FforceCollide).strength(0.6))
    .d3Force('radial', d3.forceRadial(FradialForce).strength(0.6))
    .nodeColor(FcolorNode)
    .linkWidth(FlinkWidth)
    .linkColor(FlinkColor)
    .linkOpacity(0.6)
    .linkCurvature('curvature')
    .linkCurveRotation('rotation')
    .nodeLabel(FnodeLabel)
    .linkDirectionalArrowRelPos(1)
    .nodeThreeObject(FnodeThreeObject)
    .cameraPosition({z: 9000})
    .warmupTicks(13)
    .graphData(FgetGraph())
    .nodeThreeObjectExtend(true)
```

**Expected behavior**
To set the nodeThreeObjectExtend to `true`

**Screenshots**
![image](https://user-images.githubusercontent.com/33284435/230590742-4defcb04-7659-4690-bc70-26cfb1277fb5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 / Linux
 - Browser: Google Chrome

Do you have any idea where this error comes from?

**Comment by RaulPROP** [comment]
Can you show what `FgetGraph` does?

It's probably related to that implementation returning `null` or `undefined`, so the call to `graphData` returns the data loaded in the graph (which at the time is `{ nodes: [], links: [] }`

**Comment by PixDay** [comment]
It returns an object with arrays of nodes and links and other data I'm using:

![image](https://user-images.githubusercontent.com/33284435/230717032-2e434b09-d982-4da3-9012-230397e3e339.png)

Do you mean the error comes from my array of nodes or links being empty?

**Comment by RaulPROP** [comment]
My guess is that either `FgetGraph` is nota function (you are calling it like a function) or it is returning a nullable value.

What happens if you remove the `.nodeThreeObjectExtend(true)` part? Does it render anything?

**Comment by PixDay** [comment]
If I comment `.nodeThreeObjectExtend` my visu is working fine

Since I added `.nodeThreeObjectExtend` and a block of code in FnodeThreeObject to return a CSS2DObject for my nodes
I'm having the error above

If i just comment le `.nodeThreeObjectExtend` my graph works except that my nodes are not displayed, only the links are displayed

**Comment by RaulPROP** [comment]
Can you try to reproduce it in [codepen](https://codepen.io)?

**Comment by PixDay** [comment]
The error came from my imports, I don't really understand why it wasn't working but now I using Vite to bundle everything and it "works"

I have another issue I don't know if I forget to enable a setting or something but when setting  `.nodeThreeObjectExtend(true)` to true my nodes modified with `.nodeThreeObject(FnodeThreeObject)` have an additional default node and names are not displayed :( 

![image](https://user-images.githubusercontent.com/33284435/230748719-b4f8d1ed-854d-43b7-b1ac-c632cc86fde0.png)

We can see in the top right node that it's a mix between a torus knot and a sphere

**Comment by RaulPROP** [comment]
I think that when `nodeThreeObjectExtend` is `true` the default node object will also be rendered.

**Comment by PixDay** [comment]
Okay, I think I can handle them with with nodeRelSize,
But do you have any idear why nodes name are not displayed ?

**Comment by RaulPROP** [comment]
What does `FnodeLabel` returns?

**Comment by PixDay** [comment]
It returns a string, that is a concatenation of its id and name

**Comment by RaulPROP** [comment]
If I'm not mistaken, you should pass to `nodeLabel` the name of the node property that you want to show as the label.

So you should first set a property to your nodes called `label` and then pass `'label'` to `nodeLabel`.

**Comment by PixDay** [comment]
It seems to do the same things it return a string by accessing an attribute of my object but only display it when my mouse is hovering it 🤔

**Comment by RaulPROP** [comment]
Oh, yes, `nodeLabel` only shows the label when the node is hovered. If you want a different solution you will need to craft if yourself with `html` and `js` or do something like [this example](https://vasturiano.github.io/3d-force-graph/example/html-nodes/) ([source](https://github.com/vasturiano/3d-force-graph/blob/master/example/html-nodes/index.html)).

**Comment by PixDay** [comment]
Yes I'm trying to get to this result using CSS2DRenderer and CSS2DObject, but I only got this default node from 3d-force-graph

In nodeThreeObject I'm returning a new `CSS2DObject` but it's like the browser ignore it, the HTML element are not even create

**Comment by RaulPROP** [comment]
I can not help you with that unless you can reproduce it in codepen

**Comment by PixDay** [comment]
I understand, I think I will recode a method for the labels because I can't hide the default node, thank you very much for the help I'm closing this issue, and hope this can help others

Thank you again 👍
