### ISSUE TITLE
is there a way to build nested graphs? 

### ISSUE THREAD

**Issue by itsPreto** [vasturiano/3d-force-graph#619]
For abnormally large datasets the large number of elements being rendered at once inevitable takes a tool on the responsiveness of the graphs. I was thinking about a way to declutter these large graphs by "nesting" the common nodes under a parent. 

This would in essence allow for any number of parent/child graphs in a tree like structure where each time you click on a parent node it navigates into the child graph.

Is something like this possible with the current engine?

**Comment by vasturiano** [comment]
https://vasturiano.github.io/3d-force-graph/example/expandable-nodes/
