### ISSUE TITLE
Single Node Error

### ISSUE THREAD

**Issue by atlllas** [vasturiano/3d-force-graph#620]
I have a .json describing 1630 nodes and ~800 links but when I try to load the html file, all I end up with is a single node in the middle

What might be the cause of this error?

![image](https://github.com/vasturiano/3d-force-graph/assets/84005063/62739b24-ba4f-4047-b45c-a5a677a195f5)

**Comment by vasturiano** [comment]
@atlllas there is likely an error in your code, does anything show up on the browser console? Also, do you have a reproducing example, on https://codepen.io/ for instance?

**Comment by atlllas** [comment]
Ah thank you for the reminder, I checked the console log and one of the nodes in the links array was missing. I'll be sure to check the console next time!
