### ISSUE TITLE
Any way to change/remove this dialogue -> Left-click: rotate, Mouse-wheel/middle-click: zoom, Right-click: pan

### ISSUE THREAD

**Issue by atlllas** [vasturiano/3d-force-graph#621]
I'd like to add my own dialogue to the bottom of the force graph instead of 

Left-click: rotate, Mouse-wheel/middle-click: zoom, Right-click: pan

How can I edit the css properties of the 3d-forcegraph so that these changes are reflected?

`          #3d-graph .graph-info-msg {
          opacity: 0.01; 
          }`
          
This is what I've tried.

**Comment by itsPreto** [comment]
.scene-nav-info {
    bottom: 5px;
    width: 100%;
    text-align: center;
    color: slategrey;
    opacity: 0;  // you want this set to 0 or just display to none
    font-size: 10px;
}
