### ISSUE TITLE
attracting unlinked nodes of the same color

### ISSUE THREAD

**Issue by itsPreto** [vasturiano/3d-force-graph#622]
did some digging around the net and could not find examples of how this can be done-- do you know of any way to achieve this grouping functionality?

**Comment by vasturiano** [comment]
@itsPreto you could add an additional [link force](https://github.com/vasturiano/d3-force-3d#links) that connects the nodes you want to group, to generate an attraction force between them.

Keep in mind this won't draw any lines between them, it will just influence their behaviour.

**Comment by itsPreto** [comment]
Ohh invisible links to connect them, that makes sense! Do you know if these invisible links would add a lot of overhead to the already memory taxing task of rendering a large graph? I guess I can just try it out, thank you!

**Comment by vasturiano** [comment]
I don't think it will add any noticeable overhead. Most of the load of representing large graph structures has to do mostly with the rendering phase. The force engine calculations are fairly more performant in comparison.

**Comment by lucaslemos94** [comment]
@itsPreto Did you get it?
