### ISSUE TITLE
rotate not available when the 3D graph is inside a html tab/div container

### ISSUE THREAD

**Issue by PatrickF-mbse** [vasturiano/3d-force-graph#627]
Hi,

I am trying to create a webpage with various tab and generate a graph per tab.   I pasted the basic example code inside an html tab as below and the graph is appearing on the page. I can select nodes and drag them, I can zoom using the mouse scroll but the rotate and pan are not working.  I was wondering if anybody had an idea why?   not sure to look for a fix on the html side or look on the 3d graph code. 

(Note: when I open the same script without extra html tabs (level 2 div)  , the rotate function work fine.

<div class="tab-pane fade border border-dark" id="graph">
            <div id="toolbar-graph">
              
            </div>
            <div class="separator"></div>

            
            <div id="graph-container">
              <head>
                <style> body { margin: 10; } </style>
              
              </head>
            
                <script>
                  const Graph15 = ForceGraph3D()
                    // (document.getElementById('3d-graph'))
                    (document.getElementById('graph-container'))
                    .width(500)
                    .height(500)
                      //.jsonUrl('../datasets/miserables.json')
                      .jsonUrl('../datasets/sysmlv2classgraph2.json')
                      .nodeLabel('id')
                      .nodeAutoColorBy('group')
                      .onNodeDragEnd(node => {
                       // node.fx = node.x;
                       // node.fy = node.y;
                       // node.fz = node.z;
                      });
                </script>
            </div>
          </div>
![image](https://github.com/vasturiano/3d-force-graph/assets/115640877/bd65b150-87b3-4916-8f70-16cba9f80ed9)

**Comment by vasturiano** [comment]
@PatrickF-mbse if you're still having this issue, could you make a simplified reproduceable example on https://codesandbox.io/ so that we can have a closer look?

**Comment by PatrickF-mbse** [comment]
Hi

Thank you for the follow up. I am using node so I am not sure how I can create a simpler demo and put it online (just an amateur webapp development learning).

I am redering html page with 3D force graph inside and when the user click on a button on the client side, it send a "get file" to the server , then the server send the html file to the client UI with a graph to be displayed in a tab. I am sending 3 graphs going to 3 tabs.

After a few days searching online, I could not find a solution to the mouse problem and found a work around as I noticed that when I selected a tab before the "get file" , the mouse was working in this specific tab only. Must be an html/node js thing I think...maybe not a good practice to send many file at the same time. 

Workaround is to select a tab, then relaid the page then click the "get file" command. I will need to find a better way later to display 3 graphs at the same time.

Anyway thank you for the follow up.

**Comment by PatrickF-mbse** [comment]
I am using a workaround for now ( manual reload of the page).

**Comment by vasturiano** [comment]
@pury thanks for creating that example.

This must be somehow an issue with Three [Trackball](https://threejs.org/docs/#examples/en/controls/TrackballControls) controls.

If you use instead [Orbit](https://threejs.org/docs/#examples/en/controls/OrbitControls) controls it is fine, by doing this:
```js
controlType="orbit"
```

I'm not sure why the rotation interaction in Trackball is not functioning properly if the element is mounted hidden. Maybe it's worth making an example that focuses just on that and takes `3d-force-graph` off the loop.

**Comment by vasturiano** [comment]
I've just created a simple ThreeJs example that shows the rotation issue whenever the `TrackballControls` are instantiated on a hidden element:
https://codesandbox.io/p/sandbox/three-trackball-hidden-issue-p8vtyz
