### ISSUE TITLE
Can a single image be used for the background of a 3D force graph?

### ISSUE THREAD

**Issue by POKEZHANG** [vasturiano/3d-force-graph#633]
Can a single image be used for the background of a 3D force graph?
Now only the background color can be changed.

**Comment by vasturiano** [comment]
@POKEZHANG not directly out of the box, but you can simply add a skysphere to the scene rendered with your own image as material texture. That should lead to the outcome you're asking.

**Comment by POKEZHANG** [comment]
> @POKEZHANG not directly out of the box, but you can simply add a skysphere to the scene rendered with your own image as material texture. That should lead to the outcome you're asking.

thank you so much!wish you a happy life~
