### ISSUE TITLE
selective use of d3Force('collision', d3.forceCollide

### ISSUE THREAD

**Issue by PatrickF-mbse** [vasturiano/3d-force-graph#634]
Hi,
A little question:

I trying to display an hierarchical structure  in the Z direction and planar XY. On the picture below, case 1 does not use a the D3 collide function  and case 2 use it. I noticed it is applying it to all the nodes.  

 I would like to apply the collide function  for the large rectangular shape based on a dimension L1  and a different collide based on a different node size L2.  => to have picture 1 but spaced only for the rectangular shape with the small rectangular plate and yellow nodes staying inside the larger plate they belong to.

Do you think this collide function can work for specific set of nodes? I tried the code ( case 2) but it did not spaced the rectangular layer  (const geometry = new THREE.BoxGeometry(node.l1, node.l2, node.l3 || 10);)

not sure if this D3 collide function can work on a subset of nodes?  

Thankyou

case1:  ok working
        //this works test 1                                             //node.L1
   Graph_g5.d3Force('collision', d3.forceCollide(node => Math.cbrt(500) * NODE_REL_SIZE))
   Graph_g5.d3VelocityDecay(0.3)

case2:
  //test 2 only for package
    Graph_g5.d3Force('collision', (node) => {
     if (node.subtype === 'layer') {
        return Graph_g5.forceCollide(node => Math.cbrt(500) * NODE_REL_SIZE);
      } else {
        return null; // No collision force for other nodes
      }
    })
    Graph_g5.d3VelocityDecay(0.3)

Case 1: .d3Force('charge').strength(-50)  &  Fz set
![image](https://github.com/vasturiano/3d-force-graph/assets/115640877/a8ff6bcb-df39-405d-a1db-a82d1dc9307c)

Case 2 collide &  .d3Force('charge').strength(-50);  &  Fz set
![image](https://github.com/vasturiano/3d-force-graph/assets/115640877/9e1bf191-02f8-4a9e-a14e-eac54f12002e)

**Comment by vasturiano** [comment]
@PatrickF-mbse I believe you just need to return radius `0` for the nodes you don't want the collision force to act. That essentially deactivates it. Something like:
```js
.d3Force('collision', d3.forceCollide(node => node.subtype === 'layer' ? Math.cbrt(500) * NODE_REL_SIZE : 0))
```

**Comment by PatrickF-mbse** [comment]
@vasturiano    Hi, thank you very much for the tip. it worked for the large panels and the smallest elements stayed closer but they are still trying to fill a space in between the big panels.  Maybe enforcing the link distance between specifics elements could bring them back. Anyway thank you. Progress. 

I could try to compute the position before creating the graph but I would prefer a solution that allows to "self arrange".  I feel it almost like an hierarchy of "collide" functions or connected independent graphs..

.Anyway thank you, I will investigate further the d3 physics api.  This use of "node => node.subtype === 'layer' ?" is a good method i was not aware of.


![image](https://github.com/vasturiano/3d-force-graph/assets/115640877/066cd4e7-20d7-4d6c-b891-32cdedde33ce)

**Comment by PatrickF-mbse** [comment]
..
