### ISSUE TITLE
Check if Camera is Moving and Disable Hover Events

### ISSUE THREAD

**Issue by NabeelUppel** [vasturiano/3d-force-graph#635]
On node hover function can be quite intensive depending on how many nodes are on the graph.
When the camera moves (or graph?) and my moves is stationary but hovers over a node due to the movement my graph jumps a bit. 
It would be cool to be able to disable hover effects if we can detect if the camera (or graph) is moving.

**Comment by vasturiano** [comment]
@NabeelUppel thanks for reaching out.

You can easily achieve that by hooking in to the `start` and `end` events of the [trackball controls](https://threejs.org/docs/#examples/en/controls/TrackballControls) and then disabling/enabling hover functionality via `.onNodeHover`.

**Comment by NabeelUppel** [comment]
Thank you will definitely look into that.
