### ISSUE TITLE
Nodes start disappearing after awhile and get computed radius is NaN error. 

### ISSUE THREAD

**Issue by NabeelUppel** [vasturiano/3d-force-graph#637]
**Description:**
I have a Graph that works well but if I wait for a sufficient amount of time, nodes start disappearing with this error:
`THREE.BufferGeometry.ComputeBoundingSphere: Computed radius is NaN. The "position" attribute is likely to have NaN values.`

**To Reproduce:**
Leave graph open for awhile. (>5 mins). 

**Expected behavior:**
Nodes don't disappear.

**Screenshots**
![image](https://github.com/vasturiano/3d-force-graph/assets/52805376/8ce8f8de-84e3-4bee-8402-c5d1a7d59cea)

**Desktop:**
 - OS: Windows
 - Browser Chrome
 - Version 115.0.5790.110

Any help would be appreciated. 
[localhost-1690818495756.log](https://github.com/vasturiano/3d-force-graph/files/12216930/localhost-1690818495756.log)

**Comment by vasturiano** [comment]
@NabeelUppel thanks for reaching out.

I'm unable to reproduce your issue. Could you make a simple reproducible example on https://codesandbox.io/ where this issue consistently happens?

**Comment by NabeelUppel** [comment]
Very late reply but i managed to solve the issue, can't be sure what exactly cause it but now it's work. 
Thank you and great work!
