### ISSUE TITLE
link arrow size become adjustable

### ISSUE THREAD

**Issue by DanielChuDC** [vasturiano/3d-force-graph#648]
**Is your feature request related to a problem? Please describe.**
Hi @vasturiano , would like to ask if it is possible to make arrow size become adjustable? Thanks in advanced!

**Describe the solution you'd like**
Let the link arrow size to be adjustable.

**Describe alternatives you've considered**
Based on current API, can we have one more function called ==> linkDirectionalArrowSIze([num]) 

linkDirectionalArrowLength([num, str or fn]) 
linkDirectionalArrowColor([str or fn]
linkDirectionalArrowRelPos([num, str or fn]) 
linkDirectionalArrowResolution([num])

**Comment by vasturiano** [comment]
@DanielChuDC the arrow size is determined the length set in `linkDirectionalArrowLength`. So you can just use that to specify the size.
