### ISSUE TITLE
How can I manipulate the length of the links?

### ISSUE THREAD

**Issue by frostbytedata** [vasturiano/3d-force-graph#65]
I am using text for the nodes, and I'd like to make the links much longer so my nodes are more naturally spread apart. This looks better with long line as node text. Thanks for all your hard work on these 3D libraries. You are a beast.

**Comment by artyomtrityak** [comment]
If you're using D3, not ngraph you can use d3 methods for this:

```js
// this.graph = ForceGraph3D()(this.chartRef) ....
// ...
this.graph.d3Force('link').distance((d) => {
      if (d.source.type === "my-long-type") {
        return 70;
      }
      return 30;
    }).strength(1);
```

**Comment by frostbytedata** [comment]
Very cool. Thank you!
