### ISSUE TITLE
Screenshot to the graph does not work

### ISSUE THREAD

**Issue by EmmaU25** [vasturiano/3d-force-graph#68]
I'm using Angularjs to create the application, and I'm trying to make a screenshoot function

I used HTML2CANVAS and Angular screenshoot but in both cases when I try to recover the graphic image it returns a blank image

![screenshot](https://user-images.githubusercontent.com/19750665/39635493-f9c1bbdc-4fbd-11e8-88ea-8898b7ee612a.png)

Why.?

**Comment by vasturiano** [comment]
I'm not sure, but it could be a timing issue. Are you sure that the snapshot is taken **after** the graph has rendered?

**Comment by EmmaU25** [comment]
Yes, I do it after the graph has already been painted on the canvas, that is after the Graph function. in fact I see the graphic but it always goes blank, I already used html2canvas and angularscreenshot but it always happens the same in both

**Comment by artyomtrityak** [comment]
@EmmaU25  it's actually not HTML - graph is THREE.js scene. So you need to find a way to export 3D scene to canvas and make screenshot.

For example this one https://stackoverflow.com/questions/15558418/how-do-you-save-an-image-from-a-three-js-canvas/15563621

**Comment by EmmaU25** [comment]
@artyomtrityak  but i use 3D-graph Data for create the Graph and i don't know how to do for use the solutions

**Comment by EmmaU25** [comment]
```
$scope.screenshoot = function(){
    html2canvas(document.getElementById("3d-graph")).then(function(canvas) {
      return Canvas2Image.saveAsJPEG(document.getElementById("3d-graph"));
    });
  };

```
this is my code but i dont know how to do that 
`var context = canvas.getContext("experimental-webgl", {preserveDrawingBuffer: true});`

**Comment by viktor853** [comment]
I had the same problem and found a working solution (not tested in all browsers). You need to request an 'Animation Frame'-callback and take the screenshot inside that callback.

```JavaScript
function export (canvas) {
   var image = undefined;
   window.requestAnimationFrame (timestamp => {   // Get an animation frame
      image = canvas.toDataURL();   // Google how to get your preffered data format
   });//end Lambda
}//end Fct
```

Here is my long version with resizing and downloading. The difference is that 'requestAnimationFrame' is called a second time for the resizing effect.

```JavaScript
function export (canvas, format, size) {
   var origsize = [canvas.height, canvas.width];
   var image = undefined;

   switch (format) {
      case "PNG": {
         try {
            if (size) resize (size[0], size[1]);   //TODO implement 'resize' of graph

            requestAnimationFrame ( () => {
               requestAnimationFrame (timestamp => {   // A second frame for the resizing thing
                  image = canvas.toBlob (blob => {
                     var anchor = document.createElement ('a');
                     anchor.download = "graph_" + (new Date ().toISOString () ) + ".png";
                     anchor.href = (window.webkitURL || window.URL).createObjectURL (blob);
                     anchor.dataset.downloadurl = ["image/png", anchor.download, anchor.href].join (':');
                     anchor.innerHTML = "hello world";
                     document.body.appendChild (anchor);
                     anchor.click ();   // Create a link and click on it; delete it afterwards
                     document.body.removeChild (anchor);
                  }, "image/png");

                  resize (origsize[0], origsize[1]);
               });//end Lambda 2
            });//end Lambda 1
         } catch (e) {
            resize (origsize[0], origsize[1]);
         }//end catch
      } break;
   };//end switch

   return image;
}//end Fct

function resize (height, width) {   // Example implementation
   if (height >= 0) graph.height(height);
   if (width >= 0) graph.width(width);
}//end Fct
```

**Comment by nupurbiswas** [comment]
@viktor853 How are you calling the export function? I tried following but did not work 
   `$('#savebutton').click(function(){    
       var a1 = export('#3d-graph','PNG','100');
     });`

**Comment by ankazen** [comment]
This work for me.

==========
let c = this.graph.renderer().domElement; #get canvas

window.requestAnimationFrame(timestamp => { // Get an animation frame

     let image = c.toDataURL("image/png"); // Google how to get your preffered data format

     console.log(image); #done

 });

**Comment by DOrsulak-SOLIEL** [comment]
Kept on getting black screen, didnt think I was gonna get there, but this worked for me (angular 14):

```
import {saveAs} from 'file-saver';

      let ctx = this.threeDGraph.renderer().getContext();
      window.requestAnimationFrame(timestamp => {  
        const dataURL = ctx.canvas.toDataURL('image/png');
        saveAs(dataURL, 'image.png');
      });
```
