### ISSUE TITLE
ReferenceError: ForceGraph3D is not defined

### ISSUE THREAD

**Issue by saraershadi** [vasturiano/3d-force-graph#69]
Hi, 

I want to use your provided example in text-nodes folder but it reaches to the following error.
Loading failed for the <script> with source “file:///three”.
index.html:4
Loading failed for the <script> with source “file:///3d-force-graph”.
index.html:5
ReferenceError: ForceGraph3D is not defined

Do you know the source of this error and how can I fix it ?

Thank you
Sarah

**Comment by vasturiano** [comment]
@saraershadi make sure you serve the `index.html` using a local webserver. Opening the `html` file directly in the browser will cause it to malfunction.

You can also load it directly from GH: https://vasturiano.github.io/3d-force-graph/example/basic/index.html
