### ISSUE TITLE
How to dynamic change nodes style

### ISSUE THREAD

**Issue by lslzl3000** [vasturiano/3d-force-graph#71]
E.g. click on one node, highlight this node, 
or 
show all linked nodes, make all others' opacity to 0.1 or change to another color

**Comment by vasturiano** [comment]
@lslzl3000 this is an example on how to do nodes/links highlighting and style changes dynamically, from a different library (2d `force-graph`), but `3d-force-graph` follows a very similar interface: 
[example](https://vasturiano.github.io/force-graph/example/highlight/) / [source](https://github.com/vasturiano/force-graph/blob/master/example/highlight/index.html)

Hopefully that helps to clarify it.
