### ISSUE TITLE
trackball control bugs?

### ISSUE THREAD

**Issue by lslzl3000** [vasturiano/3d-force-graph#73]
I found some control problems, hope some help

when dragging/control the camera[not dragging nodes]
1. it triggers nodes hover event, which I think should not
2. when mouse released, if the mouse was hover on one of the nodes, it will trigger a click event on that node
3. I also noticed that it works weird on mobile touch devices, e.g. need touch twice to trigger click, zoom/pitch gesture hard to control

**Comment by vasturiano** [comment]
Thanks for the report @lslzl3000. I'm able to reproduce those issues, I'll issue a fix when I have a little time.

**Comment by troymolsberry** [comment]
I made an attempt at fixing this here: https://github.com/vasturiano/three-render-objects/pull/2

**Comment by vasturiano** [comment]
@lslzl3000, just published a new version (`1.32.5`) which should fix the hover/click issues. Thanks to @troymolsberry for the assistance! 🎉 🎉
