### ISSUE TITLE
How to replace nodes with images

### ISSUE THREAD

**Issue by Ssanmifoguang** [vasturiano/3d-force-graph#75]

**Comment by vasturiano** [comment]
@Ssanmifoguang using `.nodeThreeObject()` ([example](https://vasturiano.github.io/3d-force-graph/example/custom-node-geometry/)) you can set custom objects as your nodes.

You can use three.js [TextureLoader](https://threejs.org/docs/#api/loaders/TextureLoader) to load images and then apply them as the material of the 3d objects, or as [Sprites](https://threejs.org/docs/#api/objects/Sprite) for a 2d representation.

**Comment by scottbyrns** [comment]
`
var loader = new THREE.TextureLoader();

// load a resource
loader.load(
	"/my/image.jpg",
	// Did load texture
	function (texture) {
    const Graph = ForceGraph3D()
		(document.getElementById('3d-graph'))
        .nodeThreeObject((node) =>  new THREE.Mesh(
			new THREE.BoxGeometry( 5, 5, 5 ),
			new THREE.MeshBasicMaterial( { map: node.texture } )
		)
		.graphData(nodes)
	},
	// Did Update Progress
	function (xhr) {},
	// Did Suffer Error
	function (xhr) {}
)
`
