### ISSUE TITLE
Suggestions for improving performance on big (50k+ nodes, 100k + edge) graph?

### ISSUE THREAD

**Issue by tjrileywisc** [vasturiano/3d-force-graph#81]
My graph data really taxes my browser tab when I load it. It's a pretty big graph- is there any way to improve performance? I set the opacity for links and nodes to 1 to disable transparency, but is there anything else I might try?

**Comment by rkalidhindi-tanium** [comment]
I am also facing this challenge! Have you tried `enablePointerInteraction (false)` yet?

**Comment by tjrileywisc** [comment]
@rkalidhindi-tanium 
Thanks, that helped a little bit once the graph was generated. I think I'm going to have to prune links that aren't important to me though.

**Comment by vasturiano** [comment]
@tjrileywisc another strategy that helps with a high volume of nodes/links is to not iteratively render the build-in part of the graph while the force engine is still running, but first let the force engine cooldown and then render the final version statically. This separates the load into two phases: physics calculations > WebGl rendering. You won't see the graph build-in animation, but with such a high number of graphs that is bound to be quite janky anyway.

This can be controlled by doing:
```
Graph
  .warmupTicks(200) // Adjust number of iterations to taste
  .cooldownTicks(0)
```

Here's an example of that method in action: https://bl.ocks.org/vasturiano/34e0ac2ad391e33ad5dde43ec7ce3d40

That example has `~6k` nodes and `~68k` links. How large is your graph data?

**Comment by nupurbiswas** [comment]
@vasturiano Thanks for this nice work. However, I still have the problem of slow loading of the graph. The browser is taking quite a long time and cache memory is also increasing for graphs of nodes ~6k and links ~80k. I checked all old issues of github but could not improve much. Moreover, the link shared by you 

[https://bl.ocks.org/vasturiano/34e0ac2ad391e33ad5dde43ec7ce3d40](https://bl.ocks.org/vasturiano/34e0ac2ad391e33ad5dde43ec7ce3d40)

is not loading the graph. index.js is also not in the HTML. How can I load the graph faster? I prefer to work in 3D.

**Comment by vasturiano** [comment]
@nupurbiswas the example is now fixed, thanks for pointing it out.
You can see the `index.js` here:
https://bl.ocks.org/vasturiano/raw/34e0ac2ad391e33ad5dde43ec7ce3d40/a3348a959d1ce4fd71c735ba55a51875d39cb0ed/index.js

Have you tried the above suggestion of setting `cooldownTicks` to 0, and did that help the performance?

**Comment by nupurbiswas** [comment]
@vasturiano Thank you for sharing the index.js file and also for fixing the stress test page. The stress test example took 30 sec to appear with cooldownTicks(0). For my data it is taking >1min. Is it possible to make it faster? Also, if I left click on it, the graph continues animation for more than a minute. Is it possible to provide a 'Pause' button to freeze the graph instantly?

**Comment by vasturiano** [comment]
@nupurbiswas you can try with reducing the `warmupTicks` to say `30`. That will limit the number of iterations prior to the render, so you'll see the result earlier, but the layout may not be as optimal as when you have more iterations.
As for freezing the layout engine after the first render, you can set `warmupTicks(0)` at that point. The layout engine won't run any iterations when you perform updates to it.
