### ISSUE TITLE
New lines in Labels

### ISSUE THREAD

**Issue by rkalidhindi-tanium** [vasturiano/3d-force-graph#82]
Hi @vasturiano,
I was wondering if you had any advice on making the newlines show up in labels. My label contains newline characters, but the label always ends up printed as one long line (unless the node is near the right edge of the screen, which makes line breaks at other locations).

Thank you!

**Comment by vasturiano** [comment]
@rkalidhindi-tanium you can use HTML to stile the labels, like so:
```
chart.nodeLabel(d => '<div>First line</div><div>Second line</div>');
```

**Comment by rkalidhindi-tanium** [comment]
I didn't realize I could return those sorts of insturctions. I ended up doing:
`chart.nodeLabel(d => '<span style="white-space: pre-line;">${d.label}</span>'`
for more flexibility.
Thank you Vasturiano!
