### ISSUE TITLE
Disable User Camera Control while Autorotating

### ISSUE THREAD

**Issue by rkalidhindi-tanium** [vasturiano/3d-force-graph#83]
Hi @vasturiano,

I really liked your autorotate example and I wanted to do something similar. But I noticed that weird things happen when the mouse controls are used and autorotate is on (zooming and panning makes it return to it's original position in jerks, and changing the angle with left-click throws the autorotate off the normal access). 
Since none of these effects are particularly desirable, I was wondering if there was a way to turn off mouse control of the camera (left-click, scroll, right-click).

Thank you for the wonderful library and quick responses!!

**Comment by vasturiano** [comment]
@rkalidhindi-tanium good point. I added a new method (`enableNavigationControls(<bool>)`) that lets you disable the trackball controls. I think this will work for your case.

Also updated the [auto-orbiting example](https://vasturiano.github.io/3d-force-graph/example/camera-auto-orbit/) to disable those interactions.
