### ISSUE TITLE
Links not generating for node 0

### ISSUE THREAD

**Issue by MedievalMatt** [vasturiano/3d-force-graph#84]
Hopefully this makes sense or someone can tell me what I did wrong.

If I add any link functions to my graph I get a weird layout where the links appear to extend to infinity. If I zoom in or out all the way it resolves itself, but my central node disappears.  I'm not trying to do anything particularly fancy with my links, just the following:

Graph.linkOpacity(0.9)
          .linkWidth(1)
          .linkResolution(25);

If I take away any sort of link styling functions then the links appear just fine as simple lines. I can provide the node code if that will help, but I thought I'd check and see if anyone has run into anything similar.
 
<img width="2032" alt="screen shot 2018-06-22 at 11 44 35 pm" src="https://user-images.githubusercontent.com/5084295/41805346-953f226e-7676-11e8-8f3e-99dacedbee4a.png">
<img width="2032" alt="screen shot 2018-06-22 at 11 44 42 pm" src="https://user-images.githubusercontent.com/5084295/41805345-951b23c8-7676-11e8-8dba-31a621f96d7a.png">
<img width="2032" alt="screen shot 2018-06-22 at 11 44 56 pm" src="https://user-images.githubusercontent.com/5084295/41805344-950b2702-7676-11e8-8427-635a7949a725.png">
<img width="2032" alt="screen shot 2018-06-22 at 11 45 54 pm" src="https://user-images.githubusercontent.com/5084295/41805343-94fc0984-7676-11e8-8acc-1cf8aed0b2c5.png">

**Comment by mys** [comment]
I have same issue drawing custom `nodeThreeObject` with _any_ of changed `link` size properties (width/directional particles etc.)

**Comment by rkalidhindi-tanium** [comment]
@MedievalMatt 

I use ```
Graph.linkOpacity(0.5)
.linkDirectionalParticleWidth(2.5)
.linkDirectionalParticleColor(() => '#d4d4d4')
``` without any trouble.

Could you elaborate more on what your issue is and possibly explain what's happening in each pic? I can't really tell from the pictures. Is the first one the one with the faulty links and the rest are ok?
