### ISSUE TITLE
Examples fail to load

### ISSUE THREAD

**Issue by nascif** [vasturiano/3d-force-graph#85]
Appears to be an issue with the latest version deployment at unpkg.com.
Console error messages when trying to open https://vasturiano.github.io/3d-force-graph/example/large-graph/

unpkg.com/3d-force-graph@1.35.3:1 Failed to load resource: the server responded with a status of 404 ()
(index):1 Refused to execute script from 'https://unpkg.com/3d-force-graph@1.35.3' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
(index):15 Uncaught ReferenceError: ForceGraph3D is not defined
    at (index):15
autosave.js:10 autosave.js loads into https://vasturiano.github.io/3d-force-graph/example/large-graph/
autosave.js:210 autosave.js loading takes: 2.764892578125ms
autosave.js:211 autosave.js is loaded at 2018-06-27T20:08:53.447Z

404 was for unpkg.com/3d-force-graph@1.35.3:1. Clicking on the link results in:
Cannot find module "dist/3d-force-graph.min.js" in package 3d-force-graph@1.35.3

**Comment by vasturiano** [comment]
Thanks for the heads up @nascif1 There seemed to be some kind of caching error in `unpkg` for this particular version. I published a new patch version (`1.35.4`) and things are back to normal:
https://unpkg.com/3d-force-graph
