### ISSUE TITLE
custom tooltips: enhance nodeLabel to accept either a string or a function

### ISSUE THREAD

**Issue by micahstubbs** [vasturiano/3d-force-graph#88]
enhance nodeLabel to accept either a string or a function.

had this idea that it would be nice to have a custom tooltip.

in this example https://github.com/micahstubbs/3d-force-graph-examples/blob/master/click-to-focus/02/vis.js

I can specify `.nodeLabel('description')`

but what I really want to do is something like this 

```javascript
.nodeLabel(node => `${node.description} from ${node.user}`)
```

here's what the d3 blocks citation graph looks like, which just the  `.nodeLabel('description')` tooltips:
![screen shot 2018-06-29 at 12 18 05 pm](https://user-images.githubusercontent.com/2119400/42110581-831a2e92-7b96-11e8-9bb0-aec151471981.png)
(nice enough that it's got me inspired to do more 😄 )

**Comment by vasturiano** [comment]
Hey @micahstubbs , thanks for the request. I'm happy to say it does already support that. :)

`.nodeLabel()`, as most of the other component methods, is already an accessor function hybrid, which can receive a simple property accessor (`string`) or a callback function which includes the node to extract the label for, supporting the syntax you mentioned.
Plus, it also accepts HTML or plain text, so you could do something like:
```
graph.nodeLabel(node => `<b>${node.title}</b>: ${node.value}`)
```

**Comment by micahstubbs** [comment]
indeed it does 🎉 

![screen shot 2018-06-30 at 5 11 37 pm](https://user-images.githubusercontent.com/2119400/42129950-bbd078e8-7c88-11e8-9f86-44bef751948e.png)
