### ISSUE TITLE
Node with Fixed Position

### ISSUE THREAD

**Issue by rkalidhindi-tanium** [vasturiano/3d-force-graph#90]
Hi @vasturiano,

I have a node that is meant to be the focal point of my graph, and I was wondering if there was a good way to fix it to position (0, 0, 0). I am currently thinking of repeatedly setting it's (x, y, z) in graphData using SetInterval, but I was hoping there was a more solid method of assuring this.

Thank you!

**Comment by vasturiano** [comment]
@rkalidhindi-tanium in the node that you wish to fix, you can simply add three attributes (`fx`,`fy` and `fz`) representing the fixed position. That will make sure that node remains fixed!

**Comment by rkalidhindi-tanium** [comment]
I tried to add a node like so:
`{id: "center node", fx: 0, fy: 0, fz: 0}`
but I don't think it fixed it. 
When I look at the node's _threeObj.position, it is not at (0,0,0). I'm not sure if I'm looking at the wrong thing.

**Comment by vasturiano** [comment]
@rkalidhindi-tanium yes, the `__threeObj.position` attribute should follow the the fixed coordinates, at the least after one render cycle. The node's `x`, `y`, `z` should reflect it too.

Could you check that feeding the following data fixes the first node to pos(0, 0, 0) while the other remain free:
```
myGraph.graphData({
  nodes: [
    { id: 0, fx: 0, fy: 0, fz: 0 },
    { id: 1 },
    { id: 2 }
  ],
  links: []
});
```

**Comment by rkalidhindi-tanium** [comment]
I assume this is not what I should be seeing?
![screen shot 2018-07-05 at 4 37 12 pm](https://user-images.githubusercontent.com/39538634/42352837-c82ccf82-8071-11e8-907c-ac80733a9f5e.png)

**Comment by rkalidhindi-tanium** [comment]
I am using ngraph, if that makes any difference.

**Comment by vasturiano** [comment]
@rkalidhindi-tanium yes, that's the reason. Fixing nodes only works with the D3 engine. I should've mentioned that earlier.

**Comment by rkalidhindi-tanium** [comment]
Would it be possible to get access to the ngraph 'graph' or 'layout' objects? I know ngraph has equivalent functionality with it's pinNode function. There is a significant difference in how to two force engines place the nodes in my use case, and I'd like to continue using ngraph if possible.

**Comment by vasturiano** [comment]
@rkalidhindi-tanium there is no current way to access the ngraph inner engine object. I've been pondering whether it's actually useful to maintain both engines in the lib. Can you tell me what part of ngraph you find useful that you cannot achieve with the `d3` engine?

**Comment by rkalidhindi-tanium** [comment]
ngraph is just more visually appealing for my use case out of the box. I have a lot of loops coming out of a center node. With ngraph the loops are visually distinct and separated, while d3 causes them to be tangled together and ends up looking like a ball of yarn/cocoon. 

I saw your comment on an earlier issue about changes to the d3 force engine that would make it look, similar, but I haven't succeeded in getting it quite to the same level. 
I tried:
`Graph.d3VelocityDecay(0.2)
          .d3Force('charge', d3.forceManyBody().strength(-100))`
But that second line keeps erroring out.

**Comment by rkalidhindi-tanium** [comment]
@vasturiano 
I was using an older version of d3 for other things, and that was what caused my original error. 
I got the new version installed and reran it with the above parameters, and it immediately caused my chrome browser to start leaking memory and crash. Adding `graph.forceEngine('ngraph')` back immediately stopped that issue.

**Comment by vasturiano** [comment]
@rkalidhindi-tanium could you post an example where the memory leak is happening?

**Comment by rkalidhindi-tanium** [comment]
I will try to replicate the issue.

**Comment by vasturiano** [comment]
@rkalidhindi-tanium thanks for setting up the example. There's a few things here.
* The 'charge' force is already declared in the system. By doing `.d3Force('charge', /* force definition */ )` you're actually adding an additional force to the system, with the same name. This can only be problematic and may be one of the things contributing to a possible mem leak. If you wish to add a new force to the system, you should use a different name than charge. On the other hand if you wish to modify the settings of an existing force, you can do so by first retrieving the force (`.d3Force('charge')`) and then calling any of its settings methods. In your case you're modifying the `strength`, so something like:
```
Graph.d3Force('charge').strength(-100);
``` 

* The internal `forceManyBody` (charge) force is actually from the [d3-force-3d](https://github.com/vasturiano/d3-force-3d) engine, a fork of `d3-force` that uses the 3rd dimension. In your case you're adding the `d3.forceManyBody` imported from `d3`. This is the 2 dimensional version of the engine. That's why you see a 2D layout in a 3D space. If you want the layout to use the 3rd dimension, you should import the additional forces from `d3-force-3d` instead.

Let me know if this solves it for your case.

**Comment by rkalidhindi-tanium** [comment]
@vasturiano That is much, much better, thanks!

I really like the way the graph spreads out and becomes easier to digest when I hold the center node and let it reheat for a few seconds. Do you have any advice on how I could make that happen programmatically? I am trying `d3AlphaDecay(.0001)`,  (and even smaller!) which does help spread the loops out a bit, but not to the extent that manually reheating it does.

**Comment by vasturiano** [comment]
Well, you can make the `alphaDecay` 0. :) That's what happens while a node is being dragged. You could make that programmatically by setting it initially to 0 and eventually increasing after some time.

Another way is to increase the strength of the repulsion (charge) force. It's that intensity that gets attenuated over time by the alpha. Yet another is to adjust the strength of the attraction force in the links ([forceLink](https://github.com/d3/d3-force#forceLink)).

Another useful parameter is the `d3VelocityDecay`, this determines the resistance of the medium, like a inertia force if you will.

All of these params can be used together to calibrate the force engine to your specific case, so it's a matter of fine-tuning. :)

**Comment by rkalidhindi-tanium** [comment]
Thank you for the advice, I was having a hard time understanding how all the parameters affected the graph (not much of a physics person unfortunately!).

I will try `alphaDecay` at 0 and go from there. :)
