### ISSUE TITLE
Color for Link Directional Particles and Arrows Not Working?

### ISSUE THREAD

**Issue by rkalidhindi-tanium** [vasturiano/3d-force-graph#91]
Hi @vasturiano,

I'd like to change the color for the link directional particles to make them more visible on a white background. 

I tried: 
`Graph.linkDirectionalParticleColor('black')
.linkDirectionalArrowColor('black')`
but nothing seems to have changed. 

I can't tell if something is actually wrong or if I am just using the methods wrong. Any help would be appreciated.

Thank you!

**Comment by vasturiano** [comment]
@rkalidhindi-tanium you're on the right track, the only difference is that those methods should take a function, not a plain color string, so:
```
Graph.linkDirectionalParticleColor(() => 'black')
```
should do it!

**Comment by mys** [comment]
Maybe the Readme.md documentation should be corrected? If it can't take simply 'color' string?

>linkDirectionalParticleColor([str or fn])

**Comment by vasturiano** [comment]
@mys it can take a string but that represents the attribute name of the link object to extract the value from, not the actual value. So, something like:
```
Graph.linkDirectionalParticleColor('particleColor')
```
When the link object looks like:
```
links: [{
  source: ...,
  target: ...,
  particleColor: 'black'
}, ...]
```

**Comment by rkalidhindi-tanium** [comment]
That makes a lot of sense, thank you both!

**Comment by netanyahuyasser** [comment]
What about random color?
