### ISSUE TITLE
glittering and flashing

### ISSUE THREAD

**Issue by Virgozss** [vasturiano/3d-force-graph#92]
How to let the node have the effect of glittering and flashing？

**Comment by artyomtrityak** [comment]
@Virgozss you an do this if you put inside node object another THREE.js object with transparency and opacity. If this new object radius will be more - it will be rendered as glowing object on top.

**Comment by artyomtrityak** [comment]
This is code from my project. `this.__threeNodes` contains list of rendered 3d objects. You can get this objects in `nodeThreeObject` method

```js
      const node = this.state.data.nodes.find(n => n.id === selectedNodeId);
      const object = this.__threeNodes[node.id];
      const color = getObjectColor(node.type);
      const glowSize = 150;
      const geometry = new THREE.SphereBufferGeometry(glowSize);
      const material = new THREE.MeshBasicMaterial({
        color,
        transparent: true,
        opacity: 0.2
      });
      const glowEffect = new THREE.Mesh(geometry, material);
      glowEffect.name = "glow";
      object.add(glowEffect);
```
