### ISSUE TITLE
Angle in cameraPosition

### ISSUE THREAD

**Issue by rkalidhindi-tanium** [vasturiano/3d-force-graph#94]
Hi @vasturiano,

I am trying to implement a feature that lets you turn autorotate on and off. In order to make turning it back on easier, I recenter the camera before I make it rotate. I took inspiration from your 'click to focus on node' example, and got this far:
`Graph.cameraPosition({
              x: 0,
              y: 0,
              z: distance,
            }, { x: 0, y: 0, z: 0 }, 3000);` 
The first parameter does correctly move it to (0,0,distance), and the second does make it face (0,0,0). I was wondering why the autorotate was still off, and I realized that --though the camera was in the right place and pointed in the right direction-- the angle was off (like the viewport was in the place, just rotated 90 degrees). Is there any way to manipulate that parameter as well? To not move or turn the camera, but just rotate it?

Thank you for your help! (I'm really sorry if my explanation was unclear or confusing, let me know if there is anything I can clarify.)

**Comment by vasturiano** [comment]
@rkalidhindi-tanium I see.  Yeah, the `cameraPosition` does not support setting the camera rotation.
The easiest way to set that would be to access the camera object directly (via `.camera()`) and then apply the desired rotation, using a [quaternion](https://threejs.org/docs/#api/core/Object3D.applyQuaternion) for example.

**Comment by rkalidhindi-tanium** [comment]
I think that could work, thanks! On a related note, is there any way to switch to orbit controls instead of trackball?

**Comment by rkalidhindi-tanium** [comment]
Orbit controls would be helpful. I have a central node with an image that I am trying to orient. It would also be nice to have access to it's native autoRotate and reset view functions. I have made my own, so it's not absolutely needed, but it seems smart to use the native ones if available.

**Comment by catherineomega** [comment]
Orbit controls would definitely be helpful for my use case: I have users who get dizzy and stop using my graph because trackball controls are confusing to them.

From what I understand, the way this is usually done in Three.js is be to instantiate a new camera and assign orbit controls to it, but I'm a little unclear why that's not working in my case. Should I just fork `3d-force-graph.js` and add `orbitControls` alongside `tbControls`?

**Comment by catherineomega** [comment]
Okay, I totally spoke too soon. I got it working with tooltips and click-to-focus on nodes and it doesn't require messing about with the core `3d-force-graph.js` script at all.

@vasturiano, I realize I've gotten this a bit off topic, but do you have any interest in me submitting a pull request with my method wrapped up as an example?

**Comment by vasturiano** [comment]
@rkalidhindi-tanium @catherineomega I've just added support for configuring different camera controls. It now supports `orbit`, `fly` and the already existing `trackball`. This can be done using an initialization config option, like so:
```
myGraph = ForceGraph3D({ controlType: 'fly' })
  (<domElement>)
``` 

Here's a few examples for [fly](https://vasturiano.github.io/3d-force-graph/example/controls-fly/) and [orbit](https://vasturiano.github.io/3d-force-graph/example/controls-orbit/).

Let me know if this works fine for your use cases.
