### ISSUE TITLE
Remove selected node

### ISSUE THREAD

**Issue by lucacinelli** [vasturiano/3d-force-graph#95]
Is it possibile to remove a selected node?

**Comment by artyomtrityak** [comment]
How do you select node?

**Comment by mys** [comment]
Just delete element in `graphData().nodes[]` array, eg.:

`graphData().nodes.splice(i, 1)`
http://bl.ocks.org/tgk/6068367

or

`graphData().nodes.pop()`
https://bl.ocks.org/mbostock/1095795

**Comment by lucacinelli** [comment]
>@artyomtrityak
 How do you select node?

In a simple way i select a node like that
`		.onNodeClick(node => {
			if (node){
				if (selectedNodes.indexOf(node) === -1)
					selectedNodes.push(node);
			}}`

___________________________________________________________

> @mys

> Just delete element in graphData().nodes[] array, eg.:

Ok, it works, and it's useful 👍 
Thanks

**Comment by vasturiano** [comment]
@lucacinelli in case it helps, there is also an example that removes nodes on click:
https://vasturiano.github.io/3d-force-graph/example/dynamic/

One important detail is that you should first remove all the links associated with the node, and only remove the node when it's unreferenced by any link. Something like this:
https://github.com/vasturiano/3d-force-graph/blob/adc43652252a3c8349955caff5e15c31ad4ec825/example/dynamic/index.html#L38

**Comment by lucacinelli** [comment]
@vasturiano I had already thought that I should first delete all the links associated with the node.
Anyway You were very clear. 
Thank you very much 👍
