### ISSUE TITLE
disabling Pointer Interaction leaves labels up

### ISSUE THREAD

**Issue by rkalidhindi-tanium** [vasturiano/3d-force-graph#98]
Hi @vasturiano ,

If `Graph.enablePointerInteraction(false)` gets called while the pointer is hovering over a node, the label never goes away. 

Would it be possible to have `Graph.enablePointerInteraction(false)` do a quick clean up (to remove any currently visible labels) before turning off its event handlers and becoming inactive?

Thank you!

**Comment by vasturiano** [comment]
@rkalidhindi-tanium thanks for the report! I've issued a fix so you shouldn't see that any more in the latest version (`1.36.1`).
